### ISSUE TITLE
Auto AssistEdit or Best Practice Warning

### ISSUE THREAD

**Issue by jimmymcp** [microsoft/AL#4190] opened 2018-11-13 09:34 UTC
In the olden days we used to be able to rely on the fact that adding code to the AssistEdit trigger would automatically show the AssistEdit button on the page control. It doesn't any more. One of a couple of things would help prevent me getting caught out by this (again):

1. Automatically show AssistEdit for a control that has code in an AssistEdit trigger
2. Show a best practice analyser warning when there is code in the trigger but the property hasn't been set

Cheers :-)

**Comment by fvet** [comment] 2019-03-15 07:52
This seems more like a bug than an enhancement, #4477

**Comment by atoader** [comment] 2019-08-07 11:03
This is a bug and it appears to have been fixed in the latest developer preview. Please read Freddy's blog post to learn how you can get the latest image https://freddysblog.com/2019/07/31/preview-of-dynamics-365-business-central-2019-release-wave-2/

**Comment by atoader** [comment] 2019-08-07 11:04
I will close this issue as it is a duplicate of #4477

**Closed by atoader** 2019-08-07 11:04 UTC
Labels: enhancement
