### ISSUE TITLE
[extensibility-enhancement] Make it possible to set UsageCategory in PageExt

### ISSUE THREAD

**Issue by guidorobben** [microsoft/AL#6406] opened 2021-01-08 14:18 UTC
I have my base extension (1) on MS and we have a extension (2) that has the base (1) as a dependency. 

We have a page that is needed in extension 2 but the page is included in base extension (1). The reason for this that that there will be more than 1 extension that will add fields and actions to that page.

When we only have the base App installed, the page should not show up in the search results. It is useless because it is basically an empty page. But when we install App 2, the page should be searchable. 

For this reason it should be possible to set the UsageCategory in the PageExtension. This way I can leave blank in the Base App and fill it in Extension 2.

I hope this makes sense. If you need more info, let me know.

**Comment by dtkb** [comment] 2021-01-13 10:55
dupe of https://github.com/microsoft/AL/issues/1573

**Comment by dtkb** [comment] 2021-01-20 17:04
Please upvote the Idea: https://experience.dynamics.com/ideas/idea/?ideaid=cdc99444-4b97-e911-80e7-0003ff68d318

**Comment by atoader** [comment] 2021-01-20 17:10
Please upvote the BCIdea. We will close this issue

**Closed by atoader** 2021-01-20 17:10 UTC
