### ISSUE TITLE
Error when publishing the App with build 12.2.22932. 

### ISSUE THREAD

**Issue by srkkoneti** [Microsoft/AL#2886] opened 2018-07-13 10:37 UTC
We have updated with build 12.2.22932, this below error keeps happening during the publish.

![published error](https://user-images.githubusercontent.com/39953344/42687305-1b93ecb0-86b6-11e8-9825-855ece438295.png)

**Comment by thpeder** [comment] 2018-07-13 10:49
Duplicate of #2867

**Closed by thpeder** 2018-07-13 10:49 UTC
Labels: duplicate
