### ISSUE TITLE
Enum.FromInteger not working on enum variables

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#6003] opened 2020-07-03 05:57 UTC
**Describe the bug**
`Enum.FromInteger` is not available for enum variables.

**To Reproduce**
Working:
`MyEnumVar := Enum::"My Enum Object Name".FromInteger(5);`

Not working:
`MyEnumVar := MyEnumVar.FromInteger(5);`

Compiler error message:

> Member 'FromInteger(Integer)' cannot be accessed with an instance reference; qualify it with 'EnumType' insteadAL(AL0311)

**Expected behavior**
`MyEnum := MyEnumVar.FromInteger(5);` should be accepted. It is even used as an example in the documentation:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/enum/enum-frominteger-method#example

**Versions:**
 - AL Language: 5.0.288712

**Comment by qutreson** [comment] 2020-07-03 10:17
Hi @NKarolak, can you provide a small project reproducing the issue? Is this not working at compile time, when publishing or at runtime?

I could not reproduce it on the extension version you mentioned.

![image](https://user-images.githubusercontent.com/31541422/86459441-10b6a180-bd27-11ea-8581-676715f6745a.png)

**Comment by qutreson** [comment] 2020-07-03 10:19
For reference, this looks similar to #5811

**Comment by NKarolak** [comment] 2020-07-03 10:23
You have reproduced the "working" example, but omitted the "not working" example.

Just add the following line to your project, and the compiler will raise an error that it does not recognize FromInteger:
`MyEnumVar := MyEnumVar.FromInteger(0);`

**Comment by atoader** [comment] 2020-07-03 10:35
FromInteger is a static method on the enum type, not a member method. The non-working case is by design.

**Comment by dtkb** [comment] 2020-07-03 10:36
Fix the docs then? Or make (appropriate) static methods available on instances, as they are in many other languages.

**Comment by atoader** [comment] 2020-07-03 10:40
I'll transfer it to the doc repository. In many languages, static methods are not available on instances. We have chosen this model and we do not plan to change it.

**Comment by EmilDamsbo** [comment] 2023-10-19 08:28
This should have been closed when it was fixed in the docs repo, as it is still by design but the docs should have been clarified.

**Closed by EmilDamsbo** 2023-10-19 08:28 UTC
Labels: bug, al-docs
