### ISSUE TITLE
Extended table error when base table Primary Key gets changed

### ISSUE THREAD

**Issue by JayDashti** [Microsoft/AL#3984] opened 2018-10-08 21:39 UTC
Hello,

We had created an extended table for "Lot No. Information" table. In recent release of BC, the primary key field "Lot No." has been increased from 20 to 50. Now we cannot re-install our app. We are getting this error:

"Deployment failed. Errors: App ID: <guid> Message: { TableExtension SIK-LotNoInformatoin:: Unsupported field change. Field:Lot No: Change:LengthChanged 

I cannot create another extended table and copy data over by upgrade codeunit because of existing extended table! I have no option to delete existing extended table either because of backward compatibility. There is no Obsolete property for extended table.  Could you show me how I can resolve this error?

Do I have to recreate my app with new App ID and Version?

**Comment by pzentner** [comment] 2018-10-08 22:29
are you using this field (primary key field) somewhere in a key definition in your table extension? just wondering, if this is actually a platform issue or something that you can fix.

in general, you are correct, once a table or table extension is there, it cannot be deleted or fields deleted. However, field length increases were always possible so far. 

are you testing this in a tenant specific app in a real tenant or in a docker image? with docker, I would first make sure that you are using the latest version and also the latest al compiler. 

I am not at a computer right now, but I can test that put later maybe to see, if I am getting any errors or how to get around it.

**Comment by JayDashti** [comment] 2018-10-08 22:43
Thank you. This is happening in LIVE tenant and I am in trouble because I cannot re-install the app and client is waiting on this!

I am not using "Lot No." field in that extended table nor making any changes to KEY fields. I have just extended the table and added few more text fields to the Lot No. Information table. But now that the base table has the PK field changed my extended table gives me that error. I tried whatever I could but I cannot pass this error. 

I was able to recreate this in my local container and saw the issue. After I change the Lot No field length in the "Lot No. Information" table the extended table in SSMS is still showing the old length. I can reinstall the app if I use synchronization mode=Recreate but that's not an option for me in LIVE since I would lose client data!

**Comment by JayDashti** [comment] 2018-10-09 19:57
Could someone help me on this please?

**Comment by pzentner** [comment] 2018-10-09 20:11
I was trying to recreate this last night, but my docker environment started acting up, so I have not been able to do that yet.

When you create a new version of the app (basically for the new field length in the PK) and give it a new version number, do you get this error message? not sure, if that's what you did in the first place.

you could, otherwise, export the data via configuration package (including stock and extension data), delete the records, republish your extension, and then the import the data. not good, but at least an option

**Comment by pzentner** [comment] 2018-10-09 20:36
Recreating with a new app id definitely would work, but it doesnt make sense. It is probably the fastest way to get to your result, but you need to have different object ids and need to export the data via config package and then reimport it.

@StanislawStempin is that something by design? it technically should not matter if a stock tables pk changes

**Comment by JayDashti** [comment] 2018-10-09 21:55
I was informed that this issue that has arisen will need a platform upgrade:

"Unfortunately, rebuilding a platform takes multiple hours and testing. This means that the earliest we can deploy a solution is tomorrow. We are doing everything we can to ensure this is completed as fast as possible."

**Comment by StanislawStempin** [comment] 2018-10-10 20:27
Closing, as this seems to be handled through support.

Any issues affecting live tenants should be handled through support as GitHub provides no SLAs on resolution or response times.

**Closed by StanislawStempin** 2018-10-10 20:27 UTC
