### ISSUE TITLE
[AA0137] Return variable is described as "unused"

### ISSUE THREAD

**Issue by guidorobben** [microsoft/AL#6454] opened 2021-02-05 14:53 UTC
**Title**
Return variable is described as "unused".

**Description**
Return variable is described as "unused". But the Name itself isn't used, the variable is used. Sometimes it is used as an EXIT. 

**Reason for the rule**
It is working incorrectly

``` Example of bad code ```
_Variable 'Result' is unused in 'HasJobProgress'._

local procedure HasJobProgress() **Result: Boolean**
var
    JobProgressHeader: Record "Job Progress Header";
begin
    //A343
    JobProgressHeader.SetRange("Job No.", "No.");
    **exit(JobProgressHeader.FindFirst);**
end;

**Good code sample**
It should nog generate a Warning. As you can see it is used.

``` Example of good code ```

**Good and bad practices for fixing the rule**

Dont check the return value for it being used. 

**Remarks**
​

**Comment by dtkb** [comment] 2021-02-05 15:22
dupe of https://github.com/microsoft/AL/issues/6252

> the fact that an explicit return parameter is part of a function but not assigned in the function is indeed an unused variable. Yes of course the function will still return the value whether or not the variable is used but the point is, if the variable is not used, then why have it there in the first place and removing it will have absolutely no impact on the code. That is in the spirit of the rule and it is working correctly

- https://github.com/microsoft/AL/issues/6252#issuecomment-756140371

**Closed** 2021-02-08 06:43 UTC
Labels: CodeCop, duplicate, static-code-analysis
