### ISSUE TITLE
can the length of field which is part of Primary key increased

### ISSUE THREAD

**Issue by tejabalusu** [microsoft/AL#5544] opened 2019-12-11 10:18 UTC
Hi,

We have increased the length of field from 10 to 20 which is part of primary key. Then trying to publish the same. But we are facing the below issue.

** Unsupported field change.   Field: MyTestField ; Change :LengthChanged**

Can we increase the length of field which is part of Primary key.

**Comment by AskeHolst** [comment] 2019-12-13 13:41
See #4620 
The only option at the moment is replacing the table.

**Comment by atoader** [comment] 2019-12-14 17:05
I will close this as a duplicate of #4620

**Closed by atoader** 2019-12-14 17:05 UTC
Labels: question
