### ISSUE TITLE
Incorrect syntax highlighting for fields with word 'end'

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL#7213] opened 2022-10-13 06:23 UTC
Word 'end' is highlighted within the field name
```
                field(LastBillingPeriodEndDate; Rec."Last Billing Period End Date")
                {
                    ApplicationArea = all;
                }
```
![image](https://user-images.githubusercontent.com/16342128/195517762-ce43650b-fd94-4333-99cb-0a7417b4f0dc.png)

![image](https://user-images.githubusercontent.com/16342128/195517851-7c026880-dbd0-4bdd-adf7-38bed5b44f72.png)

**Comment by thloke** [comment] 2022-10-13 08:43
Duplicate of #7041

**Closed by thloke** 2022-10-13 08:43 UTC
