### ISSUE TITLE
XLIFFs from txt2AL: Some Trans-unit-IDs differ in the generated files 

### ISSUE THREAD

**Issue by Kowa63** [Microsoft/AL#3026] opened 2018-07-25 13:37 UTC
I comparing 3 XLIFFs:
2 were generated by txt2AL (en-US, de-DE) using a container with NAV Version: 13.0.23255.0-DE
The third is the generic one which is generated by the AL compiler in the translations folder for the objects in question which were created by txt2AL in the same run.

Strange phenomenon: While many trans-unit-IDs exist in both files, some do not. Only en-US and the generic one coincide completely in that respect.
Since you can't compare the other XLIFFs direcly, I created a PowerShell script to write missing trans-unit-IDs ( i.e. existing in xlf 1, but not in xlf 2) to a diff file, which can then be compared to file 1.

The script is available here, with GUI, so it's easy to use:
http://www.msdynamics.de/viewtopic.php?f=17&t=35092

When I compare the en-US to the generic file, there are no missing trans-unit-IDs. That is the behaviour I would expect. The en-US has an additional 
`<target state="translated">` 
line for every trans-unit, and all is well.
 
But when I compare the de-DE to the generic, there are hundreds of missing trans-unit-IDs, and the same diff result comes up when I compare en-US to de-DE.
Apparently some trans-unit-IDs are changed in the de-DE file, but why?

If I had a "pure" AL project (i.e. not started from C/AL), the generic file would form the basis of all translations, and all corresponding trans-unit-IDs in all files would be identical. Why does txt2AL deviate from this logic?

**Comment by thpeder** [comment] 2018-07-25 14:10
Hi @Kowa63,
Thanks for reporting the issues.
It would make it much easier for us to investigate the problem if you could provide an example which showcases it.

**Comment by Kowa63** [comment] 2018-07-25 14:42
I have attached all 3 XLIFFs in the XLIFF.zip 
If you compare the XYZApp.g.xlf to XYZApp.en-US.xlf, is is straightforward job, but you compare the XYZApp.g.xlf to XYZApp.de-DE.xlf or XYZApp.en-US.xlf to XYZApp.de-DE.xlf, it is total mess in many places due the changed IDs. 
Also attached is a XLIFF diff file created by my script, comparing the de-DE to the generic file. If you compare that to the de-DE file you will see lots of missing trans-units, and those are the ones which have a different trans-unit-ID in the generic file. 
[XLIFF.zip](https://github.com/Microsoft/AL/files/2228239/XLIFF.zip)
[XYZApp.de-DE_MissingTransUnitsDEvsGeneric.xlf.zip](https://github.com/Microsoft/AL/files/2228264/XYZApp.de-DE_MissingTransUnitsDEvsGeneric.xlf.zip)

**Comment by Kowa63** [comment] 2018-07-26 10:44
After some further digging 
If you use files generated **in the same run** of txt2AL, the trans-unit-ids from en-US and de-DE match.
The trans-unit-ids of translated files seem to messed up when these files are part of a AL project.
To get the whole GUI translated, currently the only way seems to be to write a script which compares 3 XLIFFs, takes the trans-unit-ids of file 1, looks for the english text in file 2, takes that trans-unit-id to look for the first matching translation in file 3 and create a fourth file, with trans-unit-Ids of file1 and translations of file 3. Apart from all the additional work this requires, there is always the possibility of ambiguous word pairs, so when we finally have usable file we have to look through the whole GUI to spot senseless translations, even though the whole app is properly translated in terms of traditional ML properties.

**Comment by Kowa63** [comment] 2018-07-27 13:40
As a workaround I managed to write a PowerShell script to clean up this mess. It goes through the generic file and looks for the source text in the generated file from txt2AL and picks the target translation and inserts that into the new file. Within the limits of the mentioned ambiguities, that works satisfactorily and we finally have a translated GUI for our App.

**Comment by thpeder** [comment] 2018-07-27 14:29
Thanks for sending the .xlf files but it would be much more helpful if you would send some .txt files that reproduces the problem.
The Ids generated by Txt2Al should be deterministic so if you can get different results on the same input then it sounds like a bug.

**Comment by Kowa63** [comment] 2018-07-27 14:47
What .txt files do you mean? In this whole process, none were used. The transation.txt which I could export from C/SIDE has no problems whatsoever.
We have a fully translated app in C/AL as the starting point, then Convert-ModifiedObjectsToAL is executed and we end up with lots of .al files and 2 .xlfs for 'en-US' and 'de-DE' which together form the new project in VS Code. This is then compiled there, which produces the additional generic xlf.

**Comment by thpeder** [comment] 2018-07-30 08:38
You started out the issue with writing in the description that the de-De version had some missing Ids which you then said was fixed by generating the files in **in the same run**.
I don't get what you mean by "the same run", since running the conversion gives you both translated files (for you en-US and de-DE) so why was multiple runs necessary? and if you gave it the same input in both runs with the same version of txt2Al then it should produce the same output, and if that is not the case then I would very much appreciate if you could provide repro steps so we can get that fixed.

Is the problem you have today that the translated files doesn't have the same Ids as the generated file, or why do you need the Powershell script?

We are aware of the fact that as you change your code to introduce new labels or remove old ones then the translated files doesn't get updated with the Id changes, but that sounds like a different problem then what you have.

**Comment by Kowa63** [comment] 2018-08-04 12:38
After reading about #2964 I repeated the process twice to compare the results, but we always ended up with DE GUI that was only partly translated. The en-US and de-DE looked different each time, but we never got to the stage that we had a usable de-DE file **after** this had become part of the AL project, even though we did **not** change any labels, controls or their positions before compiling. 
The script was urgently needed to produce a proper de-DE file with correct trans-unit-IDs throughout.

Apart from this, we also have noticed that the translated files are not updated accordingly when controls are moved to new position, but that is another issue.

**Comment by thpeder** [comment] 2018-08-21 09:48
Hi @Kowa63,
Thanks a lot for your feedback but I need some txt files with some objects that reproduces the problem in order to investigate the problem.

**Comment by Kowa63** [comment] 2018-08-22 08:19
I'm afraid those files contain confidential code, in the meantime the app is already in preview in AppSource, but that wouldn't have been possible without the above mentioned script.  
https://appsource.microsoft.com/en-us/product/project-madeira/PUBID.gbedv_gmbh|AID.opplus365-v0|PAPPID.88cf5d4c-8afc-4a98-9cb7-212196c51d74-preview?flightCodes=opplus365preview&pub_source=email&pub_status=success
We are planning the release some smaller apps with a dependency on this one in future, I will try to isolate some files there when the problem reoccurs.

**Closed** 2018-10-10 21:37 UTC
Labels: input-needed, investigate
