### ISSUE TITLE
Missing type symbol

### ISSUE THREAD

**Issue by Abdhamoud** [microsoft/AL#7654] opened 2024-01-27 07:58 UTC
iam facing a problem in business central al extensions on version bc14 
 when iam creating a function or an publisher in extension and subscribing it on other extension an error is appearing on the parameter _missing_type_symbols i have contacted microsoft support which they suggested to upgrade to the latest cumulative update which i tried and didnt worked knowning that this code was working from long time ago till december. Moreover i have tried my code with a demo database and it worked .
![IMG-20240126-WA0028](https://github.com/microsoft/AL/assets/157876677/bd4d9fb6-7e0c-4567-8e79-d79eaf505b1f)

**Comment by jmadrigalTCN** [comment] 2024-01-28 09:59
I have been facing the very same problem, I till today I have not been able to solve it.
If I work with Al Languaje extension v 11.7.863928 the _missing_type_symbols do not appear, but with the most recent versions of AL Language I have the problem

**Comment by pri-kise** [comment] 2024-01-29 08:35
I thinks this is a duplicate of https://github.com/microsoft/AL/issues/7529

And since BC14 is out of support it seems that microsoft won't fix this issue. I'm not happy with this either, but I cannot change it.

**Comment by kalberes** [comment] 2024-02-01 09:13
14.x is out of support. Can you repro this issue with a server providing symbols that is still in support?

**Closed** 2024-02-16 10:56 UTC
Labels: input-needed
