### ISSUE TITLE
Unable to compile BC14 CU0 extension with dependencies

### ISSUE THREAD

**Issue by mtaanquist** [microsoft/AL#7188] opened 2022-10-04 10:00 UTC
**1. Describe the bug**
When attempting to compile an extension targeting BC 14 using 10.0.687650 with at least one dependency to a Microsoft extension, the compiler fails with an error that it cannot find a Test package. This worked without issue in the previous version 9.5.674382.

**2. To Reproduce**
1. Set up a BC14.0 container, or install BC14.0. I've used a container with the following script:
```ps
New-BcContainer -accept_eula -artifactUrl (Get-BCGet-BCArtifactUrl -type OnPrem -country DK -version 14.0) -licenseFile "C:\Path\To\DevLicense.flf" -auth NavUserPassword -updateHosts
```
2. Create a new AL project using AL Go! in VS Code
3. Add the following dependency to the project:
```json
    {
      "appId": "ac762be1-e90f-4a72-b519-612a5e3ddc2e",
      "name": "OIOUBL",
      "publisher": "Microsoft",
      "version": "1.0.0.0"
    }
```
4. Download symbols from your container or installation of BC14.
5. Attempt to compile. The compilation fails.

**3. Expected behavior**
The extension should compile as it did in the previous version.

**4. Actual behavior**
The compilation fails with the following message:
```
Compilation started for project 'ALProject4' containing '1' files at '12:00:15.692'.

error AL1022: A package with publisher 'Microsoft', name 'Test', and a version compatible with '11.0.0.0' could not be found in the package cache folder 'c:\Users\mt\Documents\AL\ALProject4\.alpackages'

Compilation ended at '12:00:15.734'.

Error: The package could not be created.
```

**5. Versions:**

- AL Language: 10.0.687650
- Visual Studio Code: 1.71.2
- Business Central: 14.0.29537.0 (dk)
- List of Visual Studio Code extensions that you have installed:
AL Language
Docker
PowerShell

### Final Checklist
* [x] Search the issue repository to ensure you are reporting a new issue
* [x] Reproduce the issue after disabling all extensions except the AL Language extension
* [x] Simplify your code around the issue to better isolate the problem

**Notes**
It seems this is not an issue with every version of BC14, as we have customers on newer cumulative updates where we can still compile our extensions. It may be an issue with the old OIOUBL (and other Microsoft) extension, but this issue was still not prevalent in the previous AL compiler version, and if we downgrade it in VS Code, it still compiles without issues.

**Comment by Inrego** [comment] 2023-01-05 07:39
We are experiencing the same issue, except we're not using `OIOUBL` in our project. We are however using `Payment and Reconciliation Formats (DK)`

**Comment by qutreson** [comment] 2023-01-20 15:54
@Inrego @mtaanquist - Does the app.json of your extension contain the "test" property? This property is used to take a dependency on the test framework in BC 14 (in BC 15, this is replaced by a set of AL extensions). If this dependency isn't needed by your app, you can remove it from your app.json. 

In your docker image, can you also run the following command: Get-NavAppInfo -SymbolsOnly - does it return an entry for the "test" package?

**Comment by Inrego** [comment] 2023-02-16 11:24
@qutreson Thank you for your answer. It led me to find a solution. Sorry for the slow response, I've been on paternity leave.

So to answer your questions: No, the app.json does not contain a "test" property.
`Get_NavAppInfo -SymbolsOnly` did return an entry for the "test" package.

So, my solution was to add a "test" property to my app.json, with the same version number as the package returned by aforementioned command. Now the project compiles and uploads again without issue.

As a side note, we had declared a .NET variable called "Process". After updating the VSCode extension, we received an error about duplicate assignment of that name when we uploaded our AL extension. That was solved by renaming our Process variable to something else.

**Comment by qutreson** [comment] 2023-02-17 10:44
@Inrego - Thank you for the update, and happy to hear that you could find a way to solve the problem on your side. 

In future release of Business Central, this type of issue shouldn't exist since the Test project has been deprecated in favor of actual AL extensions containing the test framework objects.

Can we close this issue?

**Comment by Inrego** [comment] 2023-02-17 11:47
The issue is still relevant for people working on BC instances that aren't kept up to date with newest version (for companies with a lot of custom code, it's not a simple thing to update).
This undocumented workaround is required to develop AL apps against these instances, so I think a reasonable solution would be to document it.

Also, I'm not the OP of this issue, and therefore I shouldn't be the one to decide whether it can be closed.

**Comment by qutreson** [comment] 2023-02-17 15:20
@mtaanquist - Is this issue still blocking on your side?

**Comment by thloke** [comment] 2023-03-27 04:20
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Closed by thloke** 2023-03-27 04:20 UTC
Labels: input-needed
