### ISSUE TITLE
No. of references

### ISSUE THREAD

**Issue by RafaelKoch** [Microsoft/AL#129] opened 2017-04-07 12:35 UTC
The number of references shown in the Code is not always correct. For example if I have a field on a table and have this field on some page it is not shown as a reference. 

Also in some cases (no clear repro, sorry...) showing the reference works just fine and sometimes it shows blank.

**Comment by esbenk** [comment] 2017-04-07 13:13
The number of references are updated async. That can be situations were there is a delay before count is updated. We are very interested in repros for incorrect counting. 

In general, if hover over a references shows information of a symbol it will be counted. We recently found that fields included in keys didn't get counted.

**Comment by RafaelKoch** [comment] 2017-04-07 13:22
I will try to repro on our current project as much as I can. Anyway, Your explanation made me thnk this might be related to the issue with performance. Maybe the update You mention is slower and slower until I think it does not work. Might also explain why my colleague who brought this up said he felt it works sometimes and sometimes not without an apparent logic.

**Comment by RafaelKoch** [comment] 2017-04-18 14:44
I think this issue can be closed. No more repro and I still think it might be connected to the issue with Performance.

**Comment by StanislawStempin** [comment] 2017-04-19 12:39
Closing under the assumption that issue #135 is the root cause.

**Closed by StanislawStempin** 2017-04-19 12:39 UTC
Labels: bug, duplicate
