### ISSUE TITLE
Microsoft/AL: Business Central: Button New in page Service Zones cannot be used

### ISSUE THREAD

**Issue by EelcoWijr** [Microsoft/AL#2624] opened 2018-06-18 11:30 UTC
We want to create a new **Service Zone** in the page Service Zones. This page is now empty, but if we choose the button new, then nothing happens. 

We have set the option user experience in the company info to Premium. When we then open the screen Service Zones, the this page is empty. Then we choose the button **new**. 
We see that nothing happens.
![image](https://user-images.githubusercontent.com/40356789/41533576-97273d88-72fb-11e8-82af-7465bab0c4c3.png)

**Comment by salgiza** [comment] 2018-06-19 12:00
FWIW: I was curious about this bug and checked on our BC sandbox, and I could add a new Service Zone without problems (notice the extra actions):

![image](https://user-images.githubusercontent.com/6630306/41594727-acef4f6a-73c4-11e8-8cb7-22ba4c821572.png)

I went to the Company Info card, though, and I noticed that the User Experience field was empty (I didn't know this was possible with BC?).

**After changing to a Company that has the "Premium" UX, I got the same results as you.**

**Comment by EelcoWijr** [comment] 2018-06-20 08:05
One of the first things I dit in BC was setting the User Experience in the company information on Premium

**Comment by salgiza** [comment] 2018-06-20 08:59
Sorry, my comment might have been a bit confusing: I was just confirming that I could also reproduce the bug, and that it happened after setting the User Experience setting to "Premium".

Looking at the fields in the page (with the classic development environment), they have "Advanced" set as the "Application Area":
https://docs.microsoft.com/en-us/dynamics365/business-central/across-faq#why-are-some-ui-elements-that-i-used-in-dynamics-nav-not-visible-in-

Advanced is supposed to be assigned to fields that are not commonly used, or that they have not yet been optimised for the web client.

I'm not sure what's the reason for the fields in the zone table to be excluded from BC, but it certainly is very strange to be able to access the page, but then being unable to add any records to it (either the page should be hidden, or the fields should be visible), that's why **I think this should be considered a bug.**

While waiting to see what Microsoft says regarding this ticket, there's actually a documented way to make this fields available (and everything else marked as Advanced, though):
https://docs.microsoft.com/en-gb/dynamics365/business-central/dev-itpro/developer/devenv-extending-application-areas#adding-advanced-application-area-to-the-essentials-and-premium-experiences-using-an-extension

**Comment by grobyns** [comment] 2018-06-22 11:38
@salgiza : you are right that you should not be able to have a blank user experience in BC. AFAIK this was due to a bug in 'copy company' where the experience was not copied to the new company. This should be fixed in a next update.

@EelcoWijr : there is inconsistency in the tagging here and that is a bug. I need to confirm with our PM to see whether page 6020 and all links to it should be tagged with #Advanced or #Service. Once confirmed, it will be fixed.

thanks,
Gert

**Comment by grobyns** [comment] 2018-07-04 07:48
The tags have been updated and will be available in the next update.

br/Gert

**Closed by grobyns** 2018-07-04 07:48 UTC
Labels: cross-team-investigate
