### ISSUE TITLE
Unable to download APP with backslash in name

### ISSUE THREAD

**Issue by gunnargestsson** [Microsoft/AL#2364] opened 2018-05-26 14:54 UTC
Downloading Symbols in my Test App

[2018-05-26 14:52:24.70] Error: Could not find a part of the path 'c:\AdvaniaGIT\Workspace\GIT\GitHub\businesscentral\ALTests\.alpackages\Objects4NAV_G\L Source Names_2.0.1.2.app'.

[2018-05-26 14:52:28.66] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.

Filename is: c:\AdvaniaGIT\Workspace\GIT\GitHub\businesscentral\ALTests\.alpackages\Objects4NAV_GL Source Names_2.0.1.2.app

**Comment by qutreson** [comment] 2018-05-28 12:56
Hi @gunnargestsson, which version of the AL extension are you running? I tried to reproduce it and it seems to be fixed on our latest version.

**Comment by gunnargestsson** [comment] 2018-05-28 13:27
using current bcsandbox container.

**Comment by gunnargestsson** [comment] 2018-05-28 13:33
Does the app your are downloading include the / character in the name

**Comment by qutreson** [comment] 2018-06-19 13:01
I was able to reproduce the error when downloading symbols of a package with a forward slash in its name with the AL extension version: 0.15.18771 and the server version: W1 12.0 (21812), but not on our latest master. This has been fixed in the meanwhile. Updating to a newer version should fix your issue.

**Closed** 2018-08-03 14:19 UTC
Labels: bug, shipped
