### ISSUE TITLE
Page Extension: allow to modify ApplicationArea of source page

### ISSUE THREAD

**Issue by ti-jalopez** [microsoft/AL#6131] opened 2020-09-09 11:00 UTC
Hi,
I need to extend cost functionality, and I'll create a new app area MYCOST, that uses standard extended cost objects. The problem is that I can't modify ApplicationArea from source page to add my app area, to show it in web client if I enabled my new app area and I disable the standard app area.
Nowadays, a can modify ApplicationArea at field level, but not a page level.

Sample code:
```

pageextension 50000 "MYCostTypeList" extends "Cost Type List"
{
    //TODO:  allow to modify ApplicationArea of source page
    ApplicationArea = CostAccounting, MYCOST;

    layout
    {
        // Add changes to page layout here
        modify("No.")
        {
            ApplicationArea = CostAccounting, MYCOST;
        }

    }
```
Best regards,

**Comment by qutreson** [comment] 2020-09-09 12:46
Closing as duplicate of #5271

This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Closed by qutreson** 2020-09-09 12:46 UTC
