### ISSUE TITLE
AL language debug don't work on this version of Code [1.18]

### ISSUE THREAD

**Issue by lorenzosoncini** [microsoft/AL#7392] opened 2023-05-06 10:31 UTC
Type: <b>Bug</b>

With visual studio code 1.78 the debugger of AL languange don't work.

We have downgraded to 1.77.3

LSo
Lorenzo Soncini
Italy

Extension version: 11.0.787898
VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.20348
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|31.65GB (24.65GB free)|
|Process Argv|--crash-reporter-id 4aa2835a-233e-46a4-9e56-2a63ce4dbcd5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
vscrpc:30673769
pythonsymbol12:30671437
showlangstatbar:30730054
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
fixshowwlkth:30730052
showsbindicator:30730056
pythongtdpathcf:30731979

```

</details>

**Comment by pri-kise** [comment] 2023-05-08 05:32
Duplicate of https://github.com/microsoft/AL/issues/7388

**Comment by thloke** [comment] 2023-05-09 06:40
As mentioned, this is a duplicate.

**Closed by thloke** 2023-05-09 06:40 UTC
