### ISSUE TITLE
 Personalization issue

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#1536] opened 2018-01-31 14:47 UTC
are there any known issues that using  Personalization crashing the client?

there is no container log also..

**Comment by esbenk** [comment] 2018-02-01 07:24
Not to my knowledge.

**Comment by NKarolak** [comment] 2018-02-01 07:46
If you mean NAV 2018 CU1 (which is the incorrect scope actually), there is a known issue that will be fixed in CU2.

**Comment by pmohanakrishna** [comment] 2018-02-01 10:21
this is docker build 20258.
we are using page of type worksheet
adding/removing fields from subpage 

![image](https://user-images.githubusercontent.com/23735402/35673295-22e7a552-0767-11e8-9d2b-6bd8b8a77f1b.png)

**Comment by StanislawStempin** [comment] 2018-04-16 11:17
Could you please try to reproduce the issue on the latest Developer Preview release? Otherwise it's out of scope of this repository and you'd need to ask Support for help.

**Comment by pmohanakrishna** [comment] 2018-04-17 10:06
I tested in 20901 build and still issue exists
it is happening on few pages only.
where can I see details about these kind of issues?

![image](https://user-images.githubusercontent.com/23735402/38863346-fba75d2e-4254-11e8-8499-02bca14104f2.png)

**Comment by thpeder** [comment] 2018-05-18 08:44
Hi @pmohanakrishna,
Could you please provide a small sample extension or point out an existing page where the issue can be reproduced in.

Thanks,
Thomas

**Comment by thpeder** [comment] 2018-05-30 12:42
Closing the issue since we haven't heard from you in some time. Feel free to reopen if the issue still persists.

**Closed** 2018-05-30 12:41 UTC
Labels: input-needed, investigate

**Comment by pmohanakrishna** [comment] 2018-06-07 09:08
We have a big solution and not sure whether I can create a sample script to reproduce it. Is it possible to check with screen sharing?
