### ISSUE TITLE
Pages not available on search 

### ISSUE THREAD

**Issue by zuhadmahmood** [Microsoft/AL#2514] opened 2018-06-08 08:02 UTC
Hi,
I am facing an issue that the page i have created is not visible on search bar.i have checked and referred to previous solutions but it didn't work for me. i have also published the sample package "GetAddressService" and the issue is same for it.This my code so far for this. 

![issue](https://user-images.githubusercontent.com/15164880/41145838-c74ff330-6b1a-11e8-8079-bc17d2db1964.png)

![issue 2](https://user-images.githubusercontent.com/15164880/41146189-00ab03bc-6b1c-11e8-9123-47f17600d013.png)

Please help me regarding this ASAP.

Thanks.

**Comment by atoader** [comment] 2018-06-08 08:04
Hi! Are you using the latest CU or the latest docker image?

**Comment by zuhadmahmood** [comment] 2018-06-08 09:29
Hi,
I am using cloud sandbox.

Thanks.

**Comment by atoader** [comment] 2018-06-08 10:52
Did you publish from VSCode or from the command line?

**Comment by atoader** [comment] 2018-06-08 12:26
We are investigating a bug that might be related to this, but it is difficult to say if it is the exact same problem.

**Comment by StanislawStempin** [comment] 2018-08-03 14:59
The issue is fixed in version 12.2 and newer. Please make sure that your online sandbox is on that version by checking System Information page. If it's on a lower version you can Reset the sanbox

**Closed by StanislawStempin** 2018-08-03 14:59 UTC
Labels: investigate
