### ISSUE TITLE
Increase maximum length of object names

### ISSUE THREAD

**Issue by KonnosPB** [microsoft/AL#4644] opened 2019-02-22 09:22 UTC
Is it possible to increase the maximum length of the object names?
The restriction to 30 characters is no longer up to date, especially since we should use prefixes/suffixes.

**Comment by atoader** [comment] 2019-08-02 09:58
Hi @KonnosPB! Thank you for your suggestion. We have considered this, but as Johan mentions in #4488 , it would require a major refactoring of our system. As an alternative, we are investigating support for namespaces in AL.
I will close the issue as it is a duplicate of #4488

**Closed by atoader** 2019-08-02 09:58 UTC
Labels: suggestion
