### ISSUE TITLE
Wrong Warning AA0240: The Label '...' must not contain email addresses or phone numbers.

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#6337] opened 2020-12-02 13:23 UTC
**Describe the bug**
With the next major docker image we get the warning for a guid.

> ##[warning]c:\Run\DevOps\MainApp\src\NotificationMgt.Codeunit.al(4,43): warning AA0240: The Label 'NotificationGuidTxt' must not contain email addresses or phone numbers.

**To Reproduce**
``` 
codeunit 50000 "Notification Mgt."
{
    var
        NotificationGuidTxt: Label '307d78af-ae6b-4c9d-a8ba-12482323c5ea', Locked = true;
[..]
 ```

**Expected behavior**
No warning for guids.

**Comment by PaulIvan** [comment] 2021-01-06 11:18
Hi @DanielGoehler I cannot reproduce in the latest version of the compiler. 
Please check the [latest developer preview](https://github.com/microsoft/AL#al-developer-preview-builds) it should be fixed.

![image](https://user-images.githubusercontent.com/617029/103762886-537c6d80-5019-11eb-8bcd-a2fc9f68c457.png)

![image](https://user-images.githubusercontent.com/617029/103762633-ecf74f80-5018-11eb-8851-b9b87afc2299.png)

**Comment by DanielGoehler** [comment] 2021-01-06 11:51
Currently the warning doesn't occur anymore in the production version (6.1.381323). It seems the hole phone numbers recognition was removed.

**Closed** 2021-01-06 11:51 UTC
Labels: CodeCop, bug, in-progress
