### ISSUE TITLE
Error when publishing app to Docker

### ISSUE THREAD

**Issue by hermannsson** [Microsoft/AL#1729] opened 2018-03-05 10:11 UTC
I am developing a NAV extension and using Docker to build and run.

Suddenly the following error occured:
![image](https://user-images.githubusercontent.com/20382388/36969391-3fba9ac2-205d-11e8-8690-1b4c47e9dee3.png)

As you can see the error doesn't specify a problem and I am kinda lost as to what might be causing it..
I tried setting up a brand new Docker container but received the same error.

Any ideas what could cause this?

**Comment by kalberes** [comment] 2018-03-05 11:57
Is there anything in the eventlog for the server?

**Comment by hermannsson** [comment] 2018-03-06 10:06
This seems to be a problem with a codeunit I created that inserts test data with the OnOpenCompany trigger. This is only for early development, we are still using SchemaUpgrade = Recreate for the app.
After removing this codeunit the error has not occured..
I still haven't found out what was the cause of the problem.

**Comment by atoader** [comment] 2018-04-17 12:24
Hi @hermannsson ! Do you have any more information around the cause of the problem? Can you create a minimal extension that reproduces the error?

**Comment by DominikDitoIvosevic** [comment] 2018-04-26 09:56
@hermannsson ! Do you have any more information around the cause of the problem? Can you create a minimal extension that reproduces the error?

**Comment by hermannsson** [comment] 2018-04-26 10:59
Hi

I'm sorry, I totally forgot about this open issue.
I was not able to reproduce it and unfortunately have no other information regarding this.
Development on the extension has been put off for the time being.

If needed I can try to reproduce it, it seemed to me the OnOpenCompany trigger was causing it.

**Comment by StanislawStempin** [comment] 2018-05-02 12:52
Closing the issue due to no repro. Please open a new issue if you encounter it again.

**Closed by StanislawStempin** 2018-05-02 12:52 UTC
Labels: input-needed, investigate
