### ISSUE TITLE
Go to Definition for Codeunit that implements Interface for Enum value does not work

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/AL#5972] opened 2020-06-18 07:04 UTC
**Describe the bug**
Have an enum that implements an interface, with a value that implements the interface with a codeunit:
![WSB_Example](https://user-images.githubusercontent.com/7383241/84987931-6133d980-b141-11ea-97b1-a9eab6737f84.png)
Or, an example in the Base Application (enum 7004 Price Asset Type):
![MS_Example](https://user-images.githubusercontent.com/7383241/84988088-a7893880-b141-11ea-9f0b-e888b7471c1a.png)
If you use `Go to Definition` on the Codeunit then you'll get the notification "`No definition found for <codeunit>`".

**To Reproduce**
1. Open an enum that implements an interface (e.g., enum 7004 Price Asset Type in the Base Application, or your own enum in a sample app).
2. Put your cursor on a codeunit used in the `Implementation` property of one of the enum values.
3. Use `Go to Definition`
4. "Go to Definition" does not work ☹️ 

**Expected behavior**
"Go to definition" opens the codeunit that implements the interface for the enum value

**Screenshots**
![gotodef_implementation](https://user-images.githubusercontent.com/7383241/84988503-66455880-b142-11ea-92e4-a82fa6199451.png)
![MS_Example](https://user-images.githubusercontent.com/7383241/84988088-a7893880-b141-11ea-9f0b-e888b7471c1a.png)

**5. Versions:**
 - AL Language: 5.0.288712

**Comment by AndreyKorepanov** [comment] 2020-06-18 22:00
Hi @rvanbekkum, thank you for reporting the issue. I tried to reproduce it on the the master branch (Base App, enum 7004 Price Asset Type as you suggested), and "Go to definition" (or F12) works fine there. Apparently the issue was fixed since 5.0.288712. Please try to reproduce it with the latest daily build. 
I am going to close the issue now, as this repository is only for issues related to the AL compiler in latest developer preview environment. If you need further help we suggest you to open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.. Thank you!

**Closed by AndreyKorepanov** 2020-06-18 22:00 UTC
