### ISSUE TITLE
Spring release fails with "Call Back" error when calling DotNet functions

### ISSUE THREAD

**Issue by peikba** [microsoft/AL#4930] opened 2019-04-25 21:06 UTC
The following line in the AL code works fine in Dynamics 365 BC CU6 but fails in Spring Release:

_Attempted to issue a client callback while a write transaction started, this can impact performance: CodeUnit 6185472 VM Installation GetClientPath._

The line is 

  PathTxt:=Path.GetDirectoryName(Assembly.GetExecutingAssembly().GetName().CodeBase);

The application also fails with the same message using other commands:

  IF NOT CONFIRM(DeleteWarningTxt) THEN
    EXIT;

**Comment by PooyaKharamesh** [comment] 2019-04-30 11:59
Hi 

Please provide us all the information mentioned in the template, including server runtime and AL language extension version. please also send us a full package that repros the issue.

/Pooya

**Comment by ThomasBrodkorb** [comment] 2019-05-01 15:51
Hello Pooya,
this is not related to any AL version or so, but is an issue in the transaction management already.
Whenever you call a DotNet function after a MODIFY/INSERT/DELETE/RENAME, without having a COMMIT in between, will cause this error.
Easy to find, I enclose a small page in this form to see what I mean:

`
OBJECT Page 50000 Test
{
  OBJECT-PROPERTIES
  {
    Date=01.05.19;
    Time=17:49:00;
    Modified=Yes;
    Version List=;
  }
  PROPERTIES
  {
  }
  CONTROLS
  {
    { 1   ;    ;Container ;
                ContainerType=ContentArea }

    { 2   ;1   ;Group     ;
                CaptionML=ENU=General;
                GroupType=Group }

    { 5   ;2   ;Field     ;
                Name=PingPong;
                ControlAddIn=[Microsoft.Dynamics.Nav.Client.PingPong;PublicKeyToken=31bf3856ad364e35] }

  }
  CODE
  {

    EVENT PingPong@-5::AddInReady@2();
    BEGIN
      CurrPage.PingPong.Ping(100);
    END;

    EVENT PingPong@-5::Pong@3();
    VAR
      Customer@1000 : Record 18;
    BEGIN
      Customer.FINDFIRST;
      Customer.MODIFY;
      CurrPage.PingPong.Stop();
      MESSAGE('Pong');
    END;

    BEGIN
    END.
  }
}
`

Running this page will cause the error to pop up.
Even though the result of the (ClientSide) call will return immediately and must be part of the transaction, the error raises.

**Comment by AndreyKorepanov** [comment] 2019-05-03 13:41
We assigned it to the appropriate team and we will come back once we get more information.

This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. In the future, for similar issues please contact the support team for a more efficient response.

**Comment by vhn** [comment] 2019-05-03 15:18
Based on yammer posts, apparently BC14 introduced an NST setting "AllowSessionCallSuspendWhenWriteTransactionStarted" that has default value false.

Since it's undocumented, I can only guess that the intention is to remind developers that they are holding an active database transaction while venturing into "unknown latency" territory by touching files, webservices or control addins (the client) at the same time, which is a bad design pattern for database performance.

If you switch it to true, I'm guessing the NST will behave just like earlier versions of BC/NAV, but it would be nice with some clarification from MS.
Since the default value is false, I can only assume that the cloud version of BC will enforce this new limitation for performance reasons.

**Comment by ThomasBrodkorb** [comment] 2019-05-03 15:23
If that assumption is true, then it is very confusing that this issue exists in CRONUS as well.
See issue #4942

**Comment by ThomasBrodkorb** [comment] 2019-05-03 19:02
If that assumption is true, then it is very weird that this issue exists in CRONUS as well.
See issue #4942

This means that Microsoft releases untested functionality.

**Comment by jglathe** [comment] 2019-05-03 19:06
> This means that Microsoft releases untested functionality.
Who would have thought.

**Comment by kfuglsang** [comment] 2019-05-15 10:41
Can confirm this issue on the spring release.
The AllowSessionCallSuspendWhenWriteTransactionStarted setting does not change anything for me.

**Comment by jbakach** [comment] 2019-05-30 12:53
Thanks so much @kfuglsang with this corrects the problem.

**Comment by eque2al** [comment] 2020-05-06 09:19
> Can confirm this issue on the spring release.
> Changing the AllowSessionCallSuspendWhenWriteTransactionStarted setting fixes the issue.

Maybe for On Prem but with MS pushing for everyone in the SaaS model this can't be set.  I'm having problems all over the place with Dimensions which can easily be solved (locally) with this property set to true but that won't work in Sandbox/Production databases!

And it seems the solution is to add a Commit() statement which really goes against the grain .. as a Navision trained developer I remember Hynek Muhlbacher (and other Gurus at that time) saying to absolutely avoid them if at all possible!!

**Comment by leachxpe** [comment] 2020-06-02 09:32
Any news on fix for this ?

**Comment by charlespockert** [comment] 2020-11-18 18:51
> > Can confirm this issue on the spring release.
> > Changing the AllowSessionCallSuspendWhenWriteTransactionStarted setting fixes the issue.
> 
> Maybe for On Prem but with MS pushing for everyone in the SaaS model this can't be set. I'm having problems all over the place with Dimensions which can easily be solved (locally) with this property set to true but that won't work in the cloud ie. Sandbox/Production databases!
> 
> And it seems the solution is to add a Commit() statement which really goes against the grain .. I can still (just about) remember some 24 years ago in Navision on a training course with Hynek Muhlbacher who was saying to absolutely avoid them if at all possible!!

@eque2al I'd be curious to see what your code looks like and what your issues with dimensions are; are you talking about a problem with issuing calls to .NET assemblies during your dimension handling code or just any client callback (like CONFIRM etc)?

The reason I'm confused is that you say that it would also be a problem on SaaS, however, you can't run .NET code on SaaS that isn't part of the base application (i.e. marked as safe by MS).

That means you won't be referencing any arbitrary .NET assemblies in the first place...so that problem isn't relevant to this github issue.

@peikba are you saying that during write transactions you expect `CONFIRM` to work? It shouldn't and that's by design.

Client callbacks block executing code until the client responds - you can't start a write transaction (which inevitably will take a lock on a table) and then just block the transaction until the user finally gets round to clicking on the "Yes/No" button on a popup. Users sometimes walk away from their machines. Locking the entire GL Entry table because Susan went to get a cup of tea is bad news.

This error exists explicitly to prevent situations like that.

I agree, the fact it's throwing on abitrary .NET code such as `Path.GetDirectoryName()` is an issue, but it should **always** throw on `CONFIRM` calls, because these issue client callbacks which block execution.

**Comment by atoader** [comment] 2020-11-22 17:13
Thank you all for the productive discussion! As there is a mitigation that can be applied when using .NET interoperability on-prem and as the issue is outside of the scope of this repository, I will be closing this thread.

It appears that the default behavior is by-design, but I would encourage you to open a support case or file a bug in Collaborate if you disagree.

**Comment by awarnica** [comment] 2020-12-03 19:37
> > > Can confirm this issue on the spring release.
> > > Changing the AllowSessionCallSuspendWhenWriteTransactionStarted setting fixes the issue.
> > 
> > 
> > Maybe for On Prem but with MS pushing for everyone in the SaaS model this can't be set. I'm having problems all over the place with Dimensions which can easily be solved (locally) with this property set to true but that won't work in the cloud ie. Sandbox/Production databases!
> > And it seems the solution is to add a Commit() statement which really goes against the grain .. I can still (just about) remember some 24 years ago in Navision on a training course with Hynek Muhlbacher who was saying to absolutely avoid them if at all possible!!
> 
> @eque2al I'd be curious to see what your code looks like and what your issues with dimensions are; are you talking about a problem with issuing calls to .NET assemblies during your dimension handling code or just any client callback (like CONFIRM etc)?
> 
> The reason I'm confused is that you say that it would also be a problem on SaaS, however, you can't run .NET code on SaaS that isn't part of the base application (i.e. marked as safe by MS).
> 
> That means you won't be referencing any arbitrary .NET assemblies in the first place...so that problem isn't relevant to this github issue.
> 
> @peikba are you saying that during write transactions you expect `CONFIRM` to work? It shouldn't and that's by design.
> 
> Client callbacks block executing code until the client responds - you can't start a write transaction (which inevitably will take a lock on a table) and then just block the transaction until the user finally gets round to clicking on the "Yes/No" button on a popup. Users sometimes walk away from their machines. Locking the entire GL Entry table because Susan went to get a cup of tea is bad news.
> 
> This error exists explicitly to prevent situations like that.
> 
> I agree, the fact it's throwing on abitrary .NET code such as `Path.GetDirectoryName()` is an issue, but it should **always** throw on `CONFIRM` calls, because these issue client callbacks which block execution.

Hi Charles,

We are seeing the issue under a very simple scenario in BC14, on prem. 

Cronus DB
Create a PO with a vendor who has a purchaser attached.
Add a GL line item
In the header - change the purchaser code

**Client callback error**

The error is because the default NAV code wants to ask the user if they want to update the lines with the new dimension - with a CONFIRM dialog.

This is base nav code without customizations. 

What should we do here? Go through the whole database and add IF GUIALLOWED to every base NAV object that uses a confirm? I do not see the 'AllowSessionCallSuspendWhenWriteTransactionStarted ' setting on the NAV service administration tool as an option to check or uncheck - I certainly would if I could. On which tab is this located?

I am a little confused by your comment that the code should be restructured - this is base NAV code that we don't want to change.

Thanks for any help you can provide.

**Comment by charlespockert** [comment] 2020-12-04 13:39
> > > > Can confirm this issue on the spring release.
> > > > Changing the AllowSessionCallSuspendWhenWriteTransactionStarted setting fixes the issue.
> > > 
> > > 
> > > Maybe for On Prem but with MS pushing for everyone in the SaaS model this can't be set. I'm having problems all over the place with Dimensions which can easily be solved (locally) with this property set to true but that won't work in the cloud ie. Sandbox/Production databases!
> > > And it seems the solution is to add a Commit() statement which really goes against the grain .. I can still (just about) remember some 24 years ago in Navision on a training course with Hynek Muhlbacher who was saying to absolutely avoid them if at all possible!!
> > 
> > 
> > @eque2al I'd be curious to see what your code looks like and what your issues with dimensions are; are you talking about a problem with issuing calls to .NET assemblies during your dimension handling code or just any client callback (like CONFIRM etc)?
> > The reason I'm confused is that you say that it would also be a problem on SaaS, however, you can't run .NET code on SaaS that isn't part of the base application (i.e. marked as safe by MS).
> > That means you won't be referencing any arbitrary .NET assemblies in the first place...so that problem isn't relevant to this github issue.
> > @peikba are you saying that during write transactions you expect `CONFIRM` to work? It shouldn't and that's by design.
> > Client callbacks block executing code until the client responds - you can't start a write transaction (which inevitably will take a lock on a table) and then just block the transaction until the user finally gets round to clicking on the "Yes/No" button on a popup. Users sometimes walk away from their machines. Locking the entire GL Entry table because Susan went to get a cup of tea is bad news.
> > This error exists explicitly to prevent situations like that.
> > I agree, the fact it's throwing on abitrary .NET code such as `Path.GetDirectoryName()` is an issue, but it should **always** throw on `CONFIRM` calls, because these issue client callbacks which block execution.
> 
> Hi Charles,
> 
> We are seeing the issue under a very simple scenario in BC14, on prem.
> 
> Cronus DB
> Create a PO with a vendor who has a purchaser attached.
> Add a GL line item
> In the header - change the purchaser code
> 
> **Client callback error**
> 
> The error is because the default NAV code wants to ask the user if they want to update the lines with the new dimension - with a CONFIRM dialog.
> 
> This is base nav code without customizations.
> 
> What should we do here? Go through the whole database and add IF GUIALLOWED to every base NAV object that uses a confirm? I do not see the 'AllowSessionCallSuspendWhenWriteTransactionStarted ' setting on the NAV service administration tool as an option to check or uncheck - I certainly would if I could. On which tab is this located?
> 
> I am a little confused by your comment that the code should be restructured - this is base NAV code that we don't want to change.
> 
> Thanks for any help you can provide.

Sounds like a bug to me - there should be a hotfix/CU for that.

Interestingly it is actually possible even in V17.1 to hold a lock if you show a confirmation dialog during a write transaction.

I'm pretty sure this wasn't allowed before (it's certainly not allowed in other places like `Form.RunModal` and `Codeunit.Run`), but maybe MS are trying to work around it; there are new codeunits for handling `Confirm` dialogs in the spring 2019 releases which do all the checks you should do. In my opinion it shouldn't be allowed as it can lead to some bad situations if you aren't careful about how you implement.

For example, I did some writes here (I locked the customer table by modifying a few records in a loop on a page action):

![image](https://user-images.githubusercontent.com/9073518/101169518-fa45a680-3634-11eb-87d0-e8cdbc5f3989.png)

I haven't yet responded to the confirm popup, so in another session, as expected I get lock timeouts trying to edit the records:

![image](https://user-images.githubusercontent.com/9073518/101169571-0fbad080-3635-11eb-8668-0444abfd4136.png)

Also, sure enough, I closed the browser window that was locking the customer table and the lock was held. That means I have to wait 30 minutes before I can write to this table (user sessions auto-timeout after 30 minutes on SaaS).

It really is a bad idea to popup confirmation boxes during write transactions as it can leave the target tables locked for up to 30 minutes.

**Comment by qutreson** [comment] 2021-11-30 10:58
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Closed by qutreson** 2021-11-30 10:58 UTC
Labels: cross-team-investigate
