### ISSUE TITLE
Event Subscriber Bug

### ISSUE THREAD

**Issue by aidasberesinevicius** [microsoft/AL#5463] opened 2019-11-15 13:11 UTC
**To Reproduce**
E.g.

There is publisher in Customer table:
![image](https://user-images.githubusercontent.com/31065713/68945627-76b2e080-07b9-11ea-9ba7-234c6b17b20e.png)

I created subscriber for this publisher but changed record from Customer to Currency:
![image](https://user-images.githubusercontent.com/31065713/68945693-a235cb00-07b9-11ea-9c20-15e98dc482b9.png)

Published extension and triggered that publisher and got result like this:
![image](https://user-images.githubusercontent.com/31065713/68945733-bf6a9980-07b9-11ea-8d0e-5904f7b1d3aa.png)

**Expected behavior**
Get error in Visual studio code that record does not match

**Versions:**
 - AL Language: 4.0.194000
 - Business Central: 15.1.37793.0

**Comment by atoader** [comment] 2019-11-16 10:21
Thank you for the repro! This seems to be a duplicate of #5464 . We will fix the issue in the next CU.

**Closed** 2019-11-16 10:21 UTC
Labels: duplicate
