### ISSUE TITLE
VM Landing Page not working

### ISSUE THREAD

**Issue by reiniroosh** [Microsoft/AL#741] opened 2017-10-07 21:55 UTC
The landing page in the VM has an error:
Server Error in '/' Application.

Everything does seem to be set up correctly... I can open the NAV client and developer environment.
But I can't figure out how to set up the launch.json, since the landing page supposedly will tell me how to configure it, so I can't get started with AL.

I tried restarting the VM, same result.
I deleted and re-deployed a new VM image, same results.

**Comment by peterz84** [comment] 2017-10-08 00:14
Same problem here.

Try the following in Launch.json:

{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "al",
			"request": "publish",
			"name": "Local server",
			"server": "https://--put your vm-name here--.westeurope.cloudapp.azure.com/",
			"serverInstance": "NAV",
			"tenant": "",
			"authentication": "UserPassword",
			"startupObjectId": 22
		}
	]
}

**Comment by reiniroosh** [comment] 2017-10-08 23:31
Thank you peterz84, that helped.

After changing the server to the https, I got the error about ssl being actively refused.
I needed to install the certificate, but that's also supposed on the landing page.
Maybe there's a better way... but... I copy the pfx from "Nav Container Helper" and then install it.

Then it gives me an error that I'm not authorized, which makes sense because I was still putting in `authentication: "Windows"` after putting in the UserPassword it downloaded symbols successfully!

So that is good. Now I'm trying to publish the extension and it errors with:
```
Success: The package is created.
Error: Chosen debug configuration has an unsupported attribute value `request`: 'publish'.
```

**Comment by yrest** [comment] 2017-10-09 07:02
Please see [https://github.com/Microsoft/AL/issues/738](https://github.com/Microsoft/AL/issues/738)

**Comment by reiniroosh** [comment] 2017-10-09 17:18
Thank you, it worked.

**Comment by freddydk** [comment] 2017-10-10 06:50
It should work now - I think this is caused by the country.txt file in the c:\demo folder ending up empty due to an error in the navcontainerhelper.
The error should be fixed (and in the next version, the landing page will ignore an error like that), but if you add US to country.txt today, you should be fine.

In the upcoming october preview,. the landing page has been moved to the VM instead of being inside the container, this means that the landing page will work even if the container is stopped.
The idea is to be able to extend the landing page with information on which containers are running and their health - and potentially do more cool stuff there.

**Comment by peterz84** [comment] 2017-10-10 07:28
Adding US to the country.txt indeed works for the landing page.

**Closed** 2017-10-18 10:49 UTC
Labels: question
