### ISSUE TITLE
[Question] ATT Code Coverage for Extension

### ISSUE THREAD

**Issue by OleTeichmann** [Microsoft/AL#3576] opened 2018-09-05 13:55 UTC
I want to see how much code our automated tests for our extension covers. But if i start the "Code Coverage" and filter on our object range i get following Error: "Index was outside the bounds of the array.".
Also if i do not filter the "Code Coverage" my whole client crashes if i scroll down the list.
Does anybody have an idea how to fix that?

**Comment by StanislawStempin** [comment] 2018-10-15 13:21
Code Coverage is not yet supported for AL. It is on our backlog, currently planned to be implemented within the next 6-9 months.

**Comment by OleTeichmann** [comment] 2018-10-18 06:36
@StanislawStempin that means we can not check if our extension meets the required code coverage for release in the store?

**Comment by jwikman** [comment] 2018-10-18 06:41
@OleTeichmann  it would also mean that Microsoft can't check that...

**Comment by StanislawStempin** [comment] 2018-11-05 14:13
Closing as duplicate of https://github.com/Microsoft/AL/issues/1827

**Closed by StanislawStempin** 2018-11-05 14:13 UTC
Labels: duplicate, suggestion
