### ISSUE TITLE
Database::xxx is not supported in Const expressions of properties (RunPageLink, ...)

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#6229] opened 2020-10-19 07:58 UTC
**Describe the bug**
We would like to avoid hardcoded usage of table id's (e.g. CONST(18)) as much as possible and enforce the use of Database::xxx instead (e.g. DATABASE::Customer). However, seems like this is still not supported in the latest AL versions, neither have we found a decent workaround.

**To Reproduce**

```
pageextension 50100 CustomerListExt extends "Customer List"
{
    actions
    {
        addfirst(Dimensions)
        {
            action(MyDimensionsSingle)
            {
                ApplicationArea = Dimensions;
                Caption = 'Dimensions-Single';
                Image = Dimensions;
                Promoted = true;
                PromotedCategory = Category7;
                RunObject = Page "Default Dimensions";
                RunPageLink = "Table ID" = CONST(18),        // This is the default code
                                      "No." = FIELD("No.");
                ShortCutKey = 'Alt+D';
            }
            action(MyDimensionsSingle2)
            {
                ApplicationArea = Dimensions;
                Caption = 'Dimensions-Single';
                Image = Dimensions;
                Promoted = true;
                PromotedCategory = Category7;
                RunObject = Page "Default Dimensions";
                RunPageLink = "Table ID" = CONST(Database::Customer),   // This is how we would like to include Database::xxx support
                                      "No." = FIELD("No.");
                ShortCutKey = 'Alt+D';
            }
            action(MyDimensionsSingle3)
            {
                ApplicationArea = Dimensions;
                Caption = 'Dimensions-Single';
                Image = Dimensions;
                Promoted = true;
                PromotedCategory = Category7;
                RunObject = Page "Default Dimensions";
                                RunPageLink = "Table ID" = filter(Database::Customer),  // This is how we would like to include Database::xxx support - option 2
                                      "No." = FIELD("No.");
                ShortCutKey = 'Alt+D';
            }
        }
    }
}
```

**Expected behavior**

Please provide support for **Database::xxx** in Const expressions of page properties (RunPageLink, ...)

**5. Versions:**

 - AL Language: 

![image](https://user-images.githubusercontent.com/25268332/96417204-52455c80-11f1-11eb-9d0e-94caad1b09b7.png)

**Comment by dtkb** [comment] 2020-10-19 08:33
dupe of #6163 which just got punted to BCIdeas

**Comment by fvet** [comment] 2020-10-19 08:34
https://experience.dynamics.com/ideas/idea/?ideaid=3c20fb10-3802-eb11-b5d9-0003ff68e671

**Closed** 2020-10-19 08:34 UTC
