### ISSUE TITLE
CodeCop Rule: AL0424 "The Multilanguage syntax is being deprecated. Please update to the new syntax"

### ISSUE THREAD

**Issue by RoieSantos** [microsoft/AL#5789] opened 2020-04-08 10:36 UTC
**Describe the bug**
Encounter this warning upon updating our extensions to BC16.

**To Reproduce**

1. Make sure you are using the updated AL Language extension (5.0.254558)
2. Create a page / pageextension having a property of "PromotedActionCategoriesML"

**Screenshot**
![image](https://user-images.githubusercontent.com/63336107/78774713-66093e00-79d8-11ea-914c-61ce8989fedd.png)

Can we ask what is the best action needed to eliminate the warning. Thank you.

**Versions:**

AL Language: 5.0.254558
Business Central: 16.0.11209.0 (Preview)

**Comment by nicolassaleron** [comment] 2020-04-09 11:09
Hi,
This is not a bug but is related to the fact that ML properties should be used anymore.

Please have a look here : https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files

In your case, you should use PromotedActionCategories property and translate it in a XLIFF file.

**Comment by qutreson** [comment] 2020-04-13 14:58
Closing this issue as a good answer and some links to the documentation were provided.

**Closed by qutreson** 2020-04-13 14:58 UTC

**Comment by RoieSantos** [comment] 2020-04-16 10:15
Hi qutreson, 

Sorry for my late reply on this, We have try the above solution you sent and still not able to achieve the multi language functionality via translation files. Here are screenshot of our testing

1. In our app.json we put the features : "TranslationFile" , "GenerateCaptions" and ExcludeGeneratedTranslations

![image](https://user-images.githubusercontent.com/63336107/79444084-09340600-801e-11ea-993a-b077308ef2a6.png)

2. We also did copy the auto generated .xlf file to create a new en-AU.xlf file to support EN-AU language
![image](https://user-images.githubusercontent.com/63336107/79444241-4a2c1a80-801e-11ea-9edf-e8d180eec27c.png)

3. In the newly created .xlf file we change the target-language to "en-AU"
![image](https://user-images.githubusercontent.com/63336107/79444344-66c85280-801e-11ea-84ed-36bb448e7ffc.png)

4. In our Pageextension we only put Caption in the properties .. since the CaptionML or PromotedCategoryML is being deprecated.
![image](https://user-images.githubusercontent.com/63336107/79444436-82335d80-801e-11ea-8da0-98759feea8fc.png)

5. We did double check if the translation file has the caption properties of the said pageextension
![image](https://user-images.githubusercontent.com/63336107/79444519-9c6d3b80-801e-11ea-8a5f-5afde71a9c34.png)

Below are the result of the testing.
![image](https://user-images.githubusercontent.com/63336107/79444563-aabb5780-801e-11ea-9471-589c980b5669.png)
![image](https://user-images.githubusercontent.com/63336107/79444576-ae4ede80-801e-11ea-8689-f56e75b2af45.png)

As per our testing only the language English(United States) "en-US" achieved the caption properties. 

Please advise If we miss on some setup of we are lacking of something? Appreciate you reply 

Thank You

**Comment by qutreson** [comment] 2020-04-16 11:21
As per our online documentation (see [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files#the-xliff-file)), you have to add a `<target>` element for each entry under the `<source>`. If you don't specify the target, then the entry is not considered.

**Comment by RoieSantos** [comment] 2020-04-17 01:09
Hi qutreson,

Thanks for the info, It is all working now
![image](https://user-images.githubusercontent.com/63336107/79521100-ad0fc700-809b-11ea-909a-84f10e267ab5.png)

Appreciated your help 

Thank you
