### ISSUE TITLE
The TestPage is not open

### ISSUE THREAD

**Issue by FSchneiderYav** [microsoft/AL#6344] opened 2020-12-07 10:35 UTC
**Describe the bug**
I created a testfunction with invoke an action.
```
lpgMasterDataComments.Trap();
lpgInspPlanCard.ActComments.Invoke();
lpgMasterDataComments.Comment.SetValue(lpgInspPlanCard."No.".Value);
```
The problem is, that behinde the action a RunObjekt is and not a trigger:
```
action(ActComments)
{
    ApplicationArea = QA;
    Caption = '&Comments';
    Image = ViewComments;
    RunObject = page "QA Master Data Comments";
    RunPageLink = Table = const("Inspection Plan Header"),
                    "Code / No." = field("No."),
                    "Code / No. 2" = field("Version Code");
}
```
The testfunction now says, that The TestPage is not open, for
`lpgMasterDataComments.Comment.SetValue(lpgInspPlanCard."No.".Value);`

**5. Versions:**
 - AL Language:  v6.1.362735
Version: DE Business Central 16.3 (Platform 16.0.14073.14195 + Application 16.3.14085.14238)
Azure AD tenant: common, Environment: Sandbox (Sandbox)

**Comment by NKarolak** [comment] 2020-12-07 12:07
```
lpgMasterDataComments.Trap();
lpgInspPlanCard.ActComments.Invoke();
lpgMasterDataComments.Comment.SetValue(lpgInspPlanCard."No.".Value);
```

Your code is missing an Open method prior to Action.Invoke(), e.g.
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/testpage/testpage-openview-method

**Comment by FSchneiderYav** [comment] 2020-12-07 12:25
Thats right, this is only an cut out. The Page lpgInspPlanCard is open and has also lines usw.

**Comment by thpeder** [comment] 2020-12-08 09:25
If the comment from NKarolak fixed your issue, then just close it. If that is not the case then could you wrap up your code into a small project, to make it easier for us to reproduce.
Thanks

**Comment by atoader** [comment] 2021-04-13 17:24
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Closed by atoader** 2021-04-13 17:24 UTC
Labels: input-needed
