### ISSUE TITLE
Evaluate doesn't work for biginteger

### ISSUE THREAD

**Issue by ppvandermark** [microsoft/AL#4999] opened 2019-05-24 07:28 UTC
During testing we noticed a somewhat small issue with Biginteger.
This happens when you want to evaluate an string into a Biginteger.

**To Reproduce**
Steps and to reproduce the behavior:
```   procedure TestOn_Text2BigInteger_ConversionFunctions();
    var
        bigintegerText: Text;
        bigintegerText2: Text;
        bigintegerValue1: BigInteger;
        bigintegerValue2: BigInteger;
        bigintegerValue3: BigInteger;
    begin
        bigintegerText := '1999999998‬';
        bigintegerText2 := '999999998‬';
        bigintegerValue1 := 999999999;
        bigintegerValue1 += 999999999;  //has 1999999998‬ as value
        Evaluate(bigintegerValue2, bigintegerText2); //error expected 999999998‬ to be put inside the biginteger
        Evaluate(bigintegerValue3, bigintegerText); //error expected 1999999998‬ to be put inside the biginteger
```

![image](https://user-images.githubusercontent.com/50981177/58309976-e2695180-7e05-11e9-84cc-dcef6872258f.png)

**Versions:**
![image](https://user-images.githubusercontent.com/50981177/58310120-24929300-7e06-11e9-8980-1df7ebbcc41c.png)

**Comment by JohanStenberg100** [comment] 2019-09-03 12:33
Hi @ppvandermark! I tried this from our master branch and I couldn't reproduce it. Please try again with the latest extension version available and latest server available and get back to us if this doesn't work.

Also, I found that when copying your _code_ in markdown, there was some invisible unicode characters with number "8236" which sneaked in. So try and re-write your quoted strings in your example as well to be sure to get rid of those.

**Comment by JohanStenberg100** [comment] 2019-09-03 12:39
Can you try on the latest developer preview? And let us know if it doesn't work? I will close this issue in the meanwhile.

**Comment by ppvandermark** [comment] 2019-09-30 09:16
Hello @JohanStenberg100,

I finally had some time to check out what is happening.
First of all i will let you know i am working on the daily build so version 15.
![image](https://user-images.githubusercontent.com/50981177/65864180-b9d40400-e371-11e9-96e1-ddcacf6d431b.png)

But try to run this code and it looks like the compiler is not handling the Biginteger correctly.
The code is basically the same just one small difference 
![image](https://user-images.githubusercontent.com/50981177/65864489-3ebf1d80-e372-11e9-9028-621682f62e75.png)

`

    [Test]
    procedure TestOn_Text2BigIntegerBroken();
    var
        ConversionFunctions: Codeunit "e-Con Conversion Functions";
        bigintegerText: Text;
        bigintegerValueCorrect: BigInteger;
        bigValue: BigInteger;
    begin
        bigintegerText := '4294967294‬';
        bigintegerValueCorrect := 2147483647;
        bigintegerValueCorrect += bigintegerValueCorrect;
        Evaluate(bigValue, bigintegerText);
        // Test can not be executed due to an error in standard bc
        if not (ConversionFunctions.Text2BigInteger(bigintegerText) = bigintegerValueCorrect) then
                Error(StrSubstNo('The Text to BigInteger was expecting an %1 as value got %2', bigintegerValueCorrect, bigValue));
    end;

    [Test]
    procedure TestOn_Text2BigIntegerWorks();
    var
        ConversionFunctions: Codeunit "e-Con Conversion Functions";
        bigintegerText: Text;
        bigintegerValueCorrect: BigInteger;
        bigValue: BigInteger;
    begin
        bigintegerText := '4294967294';
        bigintegerValueCorrect := 4294967294L;
        Evaluate(bigValue, bigintegerText);
        // Test works
        if not (ConversionFunctions.Text2BigInteger(bigintegerText) = bigintegerValueCorrect) then
            Error(StrSubstNo('The Text to BigInteger was expecting an %1 as value got %2', bigintegerValueCorrect, bigValue));
    end;

    `

![image](https://user-images.githubusercontent.com/50981177/65865213-619e0180-e373-11e9-97e2-066c5ee08d03.png)

As you can see one has an error the other one is fine i see this as a rather big issue since we evaluate alot but atleast i now have a workaround that feels weird to us!

Kind regards,

**Comment by JohanStenberg100** [comment] 2019-09-30 13:43
Hi @ppvandermark, thanks for these good repro-steps. I will take a closer look when I have the capacity.

**Comment by JohanStenberg100** [comment] 2019-10-02 05:49
Hi @ppvandermark, you have the same issue in your example as before, there's a hidden unicode character in the first test procedure.

![image](https://user-images.githubusercontent.com/43748198/66020906-08f07500-e4e9-11e9-8ca7-fa9b36d63f88.png)

After the last character '4', there's another character. This can't be parsed and that's why the conversion fails. If I remove this character, both tests passes. I will close this issue now, thanks.

**Closed by JohanStenberg100** 2019-10-02 05:49 UTC
Labels: investigate
