### ISSUE TITLE
Possible to use globals from page in pageextension

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#586] opened 2017-09-02 12:55 UTC
We are extending the native sales statistics pages and the sales subpages (like Sales Cr. Memo Subform). We are adding fields that use globals in the native page (like TotalSalesLine and TotalSalesHeader). These symbols are not recognized by the AL compiler (but they work fine in extensions v1).
Example:
      field("Amount Paid (LCY)";"Amount Paid (LCY)")
      {
        ApplicationArea=Basic,Suite;
        AutoFormatExpression=TotalSalesHeader."Currency Code";
        CaptionML=ENU='Total Payment Amount';
      }

TotalSalesHeader is not found. It would be great to be able to use globals from the page. Will this be a possibility? In the above example, we can fairly easily work around it, but there are others that are not so easy (like the Statistics pages).

**Comment by DominikDitoIvosevic** [comment] 2017-10-05 08:30
Right now you can expose the global variables through getter/setter procedures. We are thinking about this scenario

**Comment by RonKoppelaar** [comment] 2018-05-11 09:17
Any progress or new information regarding access to global variables inside page extensions?

**Comment by frivadulla** [comment] 2018-11-22 09:39
Dealing with this problem just now, any new regarding this issue?

**Comment by StanislawStempin** [comment] 2018-11-23 11:54
We don't have any updates yet. This is still on the backlog but we hope to start working on it within the next 6 months.  I will close this issue as duplicate of #593 and let's continue the discussion there.

**Closed by StanislawStempin** 2018-11-23 11:54 UTC
Labels: suggestion
