### ISSUE TITLE
Report Extensions - UnprocessableEntity. Reason: Input string was not in a correct format.

### ISSUE THREAD

**Issue by waldo1001** [microsoft/AL#6523] opened 2021-03-10 08:40 UTC
When I create this simple report extension:
```al
reportextension 50105 "Customer Top 10 Ext" extends "Customer - Top 10 List"
{
    RDLCLayout = './Src/Report Extension Examples/Customer Top 10/CustomerTop10List.rdlc';

    dataset
    {
        add(Integer)
        {
            column(SomeNewField; SomeNewField) { }
        }
        modify(Integer)
        {
            trigger OnAfterGetRecord()
            begin
                SomeNewField := 'waldo';
            end;
        }
    }
    var
        SomeNewField: Text;
}
```

It does compile, but it results in an error:
```
[2021-03-10 09:17:55.99] Sending request to http://bcdaily:7049/BC/dev/apps?tenant=default&SchemaUpdateMode=synchronize&DependencyPublishingOption=default
[2021-03-10 09:17:56.50] The request for path /BC/dev/apps?tenant=default&SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: Input string was not in a correct format.
```

**Comment by thloke** [comment] 2021-03-10 22:29
I've found the cause for this. It's a bug which happens if an add change does not specify a field from the dataset. It should work if you add another column that uses a table field. We'll fix this.

**Comment by thloke** [comment] 2021-03-11 01:44
It also looks like adding triggers to existing dataitems doesn't work as expected, so in this case the new `OnAfterGetRecord` will not be executed.

**Comment by waldo1001** [comment] 2021-03-11 08:53
That I noticed :-).
Also the intellisense for triggers doesn't work .. would be great to be able to use within VSCode..

**Comment by JesperSchulz** [comment] 2021-03-12 08:50
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 23190 and VS Code Extension Version 7.0.430011. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Closed by JesperSchulz** 2021-03-12 08:50 UTC
Labels: bug, in-progress, ships-in-future-update
