### ISSUE TITLE
Rapid Application Publish broken when changing AL code in Report

### ISSUE THREAD

**Issue by Aephyon** [microsoft/AL#5498] opened 2019-11-28 10:56 UTC
- AL Extension Version: 4.00.199169
[ReportSample.zip](https://github.com/microsoft/AL/files/3901222/ReportSample.zip)

- Server Version: Version: W1 15.1 (Platform 15.0.37898.0 + Application 14.0.29530.0)

Hi,

It appears the Rapid Application Publish functionality does not work anymore after an AL code change is done in an existing published Report.

See example in the attachments: when the report is initially published it works fine after clicking the "Preview" button (don't mind the runtime error though...). When the "// Message('Hello')" code line is uncommented and a RAD is performed, the infamous "Something went wrong" screen appears.

**Comment by PooyaKharamesh** [comment] 2019-11-29 09:54
do you also have any changes in the RDLC file with RAD publishing?

**Comment by Aephyon** [comment] 2019-11-29 11:00
> do you also have any changes in the RDLC file with RAD publishing?

No, only AL code changes

**Comment by AndreyKorepanov** [comment] 2020-06-22 13:38
Hi @Aephyon, is it still actual? I tried the code you attached on the master branch and could not get repro. It seems the issue has been fixed since the version you mentioned. I am going to close it now, please re-open if it is still reproducible on the latest daily build. Thank you.

**Closed by AndreyKorepanov** 2020-06-22 13:38 UTC
Labels: input-needed
