### ISSUE TITLE
CodeCop warning AA0237 is not correct

### ISSUE THREAD

**Issue by mhenricus** [microsoft/AL#6073] opened 2020-08-06 14:32 UTC
**Describe the bug**
CodeCop warning AA0237 is given if the record variable starts with 'Temp' and the record var is not defined temporary:
https://docs.microsoft.com/nl-be/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0237-nontemporaryvariablesmustnotbeprefixedtemp
But I have a record variable based on a table that starts with the name 'Template'

**To Reproduce**
Steps and to reproduce the behavior:

                    trigger OnAction()
                    var
                        TemplateHeader: Record "IGO Template Header";

**Expected behavior**
No Warning at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/69308907/89544115-042fd800-d802-11ea-9061-34ae1d07e281.png)

**5. Versions:**

 - AL Language: v6.0.313479

 - Business Central: NL Business Central 17.0 (Platform 17.0.15306.0 + Application 17.0.15311.0)

**Comment by PaulIvan** [comment] 2020-10-01 12:07
I am closing this issue because it appears that it has been resolved, check the [latest developer preview](https://github.com/microsoft/AL#al-developer-preview-builds) . Please open a new issue if you believe this has not been resolved and reference the current issue.

**Closed by PaulIvan** 2020-10-01 12:07 UTC
Labels: CodeCop, bug, in-progress, static-code-analysis

**Comment by dennisroczek** [comment] 2021-02-04 01:04
either it is not resolved with v6.1.397164 or it still not released or it is a regression. :-(

**Comment by dtkb** [comment] 2021-02-04 09:24
The issue is probably related to the prefix, `IGO` in the original post. The warning is **not** raised if a table is called `Template Name Test` and a variable `TemplateNameTest`. It **is** raised if the table name is prefixed like `MYCO Template Name Test` but the variable is not.

**Comment by dennisroczek** [comment] 2021-02-06 12:14
> The issue is probably related to the prefix, `IGO` in the original post. The warning is **not** raised if a table is called `Template Name Test` and a variable `TemplateNameTest`. It **is** raised if the table name is prefixed like `MYCO Template Name Test` but the variable is not.


Doesn't matter. If you try to move records from 
`  TemplateIGOTemplateHeader: Record "IGO Template Header";`
to
`  IGOTemplateHeader: Record "IGO Template Header";`
you get the same warning for the first record, although it is a good description of the record/the task you wanted to do.

**Comment by mhenricus** [comment] 2021-02-15 16:18
It doesn't seem to be fixed.
And the affix doesn't seem to be the problem either. 
The codecop does seem to assume that any variable starting with 'Temp' should be a temporary variable.

![image](https://user-images.githubusercontent.com/69308907/107970656-b1558b00-6fb1-11eb-86d6-338d1b80a228.png)

![image](https://user-images.githubusercontent.com/69308907/107970753-d34f0d80-6fb1-11eb-9f8a-98dc5686ebde.png)

**Comment by NKarolak** [comment] 2021-02-16 06:59
> check the latest developer preview . 

This means it is supposed to be fixed in the next main version of the AL Language, in this case: **7**.x - have you tested that version?

**Comment by mhenricus** [comment] 2021-02-16 16:07
Ah, just tested with 7.0.415152 and it seems to work fine now!
😊
