### ISSUE TITLE
Consecutive InstructionalText groups not visible

### ISSUE THREAD

**Issue by gunnargestsson** [Microsoft/AL#1579] opened 2018-02-08 14:03 UTC
Code like 

      group(Group20)
      {
        Visible=FirstStepVisible;
        group("Welcome to G/L Source Name Setup")
        {
          Caption='Welcome to G/L Source Name Setup';
          group(Group18)
          {
            ShowCaption=false;
            InstructionalText='To be able to use Source Names on G/L Entries, users must have required permissions.';
          }
          group(Group19)
          {
            ShowCaption=false;
            InstructionalText='Users that can update master tables, like; Customer, Vendor, Bank Account and Fixed Asset, must be able to update the G/L Source Name lookup table.';
          }
        }

only shows the first InstructionalText in AL.  Both visible in C/AL.

Screenshots attached from both versions.

![assistedsetup](https://user-images.githubusercontent.com/23558797/35976559-7011bbda-0cd8-11e8-89b3-08a707704c51.PNG)
![assistedsetupv2](https://user-images.githubusercontent.com/23558797/35976702-db897218-0cd8-11e8-856f-411122d645f8.PNG)

**Comment by dennisfrostlander** [comment] 2018-02-09 14:24
Cannot completely reproduce without a full page code, but could you please try quoting the instruction text in group 19?
```
      group(Group19)
      {
        ShowCaption=false;
        InstructionalText='"Users that can update master tables, like; Customer, Vendor, Bank Account and Fixed Asset, must be able to update the G/L Source Name lookup table."';
      }
```
This is because the text contains a semicolon, which in the old ML syntax used to separate the languages (ENU=xxx;).

**Comment by gunnargestsson** [comment] 2018-02-09 15:29
Yes the doubble quotes work magic :)
![glsoursenamesetup](https://user-images.githubusercontent.com/23558797/36035160-068b33ae-0dae-11e8-941d-14b9741a7a77.PNG)

**Comment by StanislawStempin** [comment] 2018-04-09 12:33
This issue should be fixed on March 2018 Update, i.e. you should no longer require double quotes. Please comment or log a new issue if you are still running into this problem.

**Closed** 2018-04-09 12:33 UTC
Labels: bug, shipped
