### ISSUE TITLE
BC21 Error when running Import Classification Data from Excel

### ISSUE THREAD

**Issue by srkkoneti** [microsoft/AL#7178] opened 2022-09-27 15:20 UTC
**Platform 21.0.45803.0 + Application 21.0.45833.0**
Data Classification Worksheet
Set Up Data Classifications
Import Classification Data from Excel
Choose Excel file and hit next *** NOTE it does not matter what excel file you attach, the issue happens when the system tries to open the file, the data inside does NOT matter
![image](https://user-images.githubusercontent.com/39953344/192566425-07999c7a-c40e-4cef-a97c-8de8df41869c.png)

**Comment by dnpb** [comment] 2022-09-27 16:24
As that's not a bug in the AL language or compiler, it's off-topic here.

Since [Data Classification seems to be a System Module](https://github.com/microsoft/ALAppExtensions/tree/main/Modules/System/Data%20Classification), you should be able to [report the issue on AlAppExtensions](https://github.com/microsoft/ALAppExtensions/issues) instead. You should probably give them an example Excel file though...!

**Comment by thloke** [comment] 2022-09-29 08:41
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

**Closed by thloke** 2022-09-29 08:41 UTC
