### ISSUE TITLE
Breakpoints in debug mode get disabled on Case statements

### ISSUE THREAD

**Issue by robertosb** [microsoft/AL#6084] opened 2020-08-16 20:18 UTC
**Describe the bug**
When adding breakpoints in one of my projects it all looks fine (red dots are added in VS Code).
However when I hit publish with debugging, the red dots become dark circles and if I try to add other breakpoints  it shows me an error (it also shows it when the BC session starts for each breakpoint added)
"Unverified breakpoint"
"Error: It is not possible to add a breakpoint at line number x in application object type CodeUnit, ID y"

The code also doesn't stop on these breakpoints

**To Reproduce**
please see above
[edit]: please add the breakpoints on a Case statement or within the Case code, perhaps try even on a Case option.

``` AL Code to reproduce the issue ```

**Expected behavior**
I would expect the code to stop on my breakpoints.

**Screenshots**
![image](https://user-images.githubusercontent.com/39469150/90343106-ad2bcd80-e061-11ea-9be7-8085c181ebd0.png)
![image](https://user-images.githubusercontent.com/39469150/90343125-c16fca80-e061-11ea-9f68-4fb10ce1fa99.png)

**5. Versions:**

 - AL Language: 5.0.312966

 - Business Central: docker container as per below
Version: NZ Business Central 16.3 (Platform 16.0.14073.15236 + Application 16.3.14085.15266)
Azure AD tenant: common, Environment: Sandbox (Sandbox)

**Comment by robertosb** [comment] 2020-08-17 02:35
It seems the problem is when adding breakpoints on or inside case statements and I am not the only one who had this.
A colleague told me even when it works, it doesn't stop on the line you add the breakpoint, so it's a known issue.
I placed a breakpoint outside and it worked, let me know if you can release a fix in AL or if it is a VS Code issue?

Cheers,
Robert

**Comment by atoader** [comment] 2020-08-17 05:24
Hi! Can you provide a project to reproduce this and a video/screenshot with the breakpoints placed?

**Comment by robertosb** [comment] 2020-08-18 20:58
![image](https://user-images.githubusercontent.com/39469150/90564573-b354b200-e1f9-11ea-9e08-794af08da4a4.png)
![image](https://user-images.githubusercontent.com/39469150/90564628-cc5d6300-e1f9-11ea-959b-71dc0f2e084b.png)
![image](https://user-images.githubusercontent.com/39469150/90564745-f7e04d80-e1f9-11ea-93b0-511f9d89fc09.png)
Hi Alexandru,

   Please find the screendumps of a sample hello world created with AL:GO with a simple Case function.
   You will see that if you place a breakpoint on the Case instruction it won't stop there.

Cheers,
Robert

**Comment by atoader** [comment] 2020-08-20 03:54
Thank you!

**Comment by kalberes** [comment] 2020-08-26 12:19
I think this has been fixed. But as I know it required a server fix, so I do not know if it will be available on 17.X only or whether it has been backported to 16.X

**Comment by robertosb** [comment] 2020-08-26 20:50
> been fixed. But as far as I know it requ

That's great news, is this mentioned anywhere by Microsoft?
Would be great to see if it's backported or when it is planned for release? I suppose 2020 Wave2, but if it's backported, then maybe earlier?

Cheers,
Robert

**Comment by qutreson** [comment] 2020-09-16 06:09
@robertosb, can you give it a try in our latest developer preview? This issue has been fixed and was backported to 16.x too. #5597 provides more information about it, as they seem to be reporting the same issue.

**Comment by qutreson** [comment] 2020-09-29 11:47
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Closed by qutreson** 2020-09-29 11:47 UTC
Labels: bug, debugger, input-needed
