### ISSUE TITLE
Issue when deploying apps

### ISSUE THREAD

**Issue by MikeGlue** [Microsoft/AL#691] opened 2017-09-15 15:58 UTC
I've been dealing with a weird issue where if I do any of the following it will result in an "internal error" in VS Code when I try to deploy the app package.

1. Deploy a package, rename the connection name in launch.json and do another deploy
2. Deploy a package, add new connection config in launch.json and do another deploy
3. Deploy a package in app1, switch to another app and deploy the package to a connection name that is different than what was in the first app

Long and short, there seems to be an issue when switching between deployment connections if they have different names. I've tried clearing the credential cache when this happens but it does not seem to help. All that results in is the following:

![image](https://user-images.githubusercontent.com/5204734/30491983-0236ad66-9a0d-11e7-93cb-b43a0b9c7de5.png)

Strangely enough the only way I can get this resolved is to use the AL: Go command to create a brand new project and then deploy to the address that I was initially trying to deploy to. After that I can go back to my original app and do the deployment without error.

I'm using the 0.9.12794 extension in VS Code and I'm deploying against 2 different dev preview machines using the latest September updates.

**Comment by StanislawStempin** [comment] 2017-09-18 09:14
Thanks for reporting and narrowing down the problem. We will look into it.

**Comment by dennisfrostlander** [comment] 2017-09-22 09:04
Hi @MikeGlue,

Could you please clarify a few things?
1. When you say "rename the connection", I guess you mean changing the "name" attribute in the launch.json configuration object, right?
2. How do you do a deploy? F5, Ctrl+F5, or pressing the green "play" button in the VSCode UI?
3. In step (Deploy a package in app1...) how do you switch to another app? In the same VScode window or another VSCode window?
4. What is the version of your VSCode?

**Comment by MikeGlue** [comment] 2017-09-22 15:44
Here you go:

1. yes that is correct
2. I press F5. 
3. In the same VS Code window. With the old project folder open, I go to the file menu and open the new folder.
4. I typically keep it up to date whenever a new version is released. Currently I'm using version 1.16.1. Oh, it's also the 64-bit one.

**Comment by esbenk** [comment] 2017-09-23 06:35
There seems to be some problems with VsCode 1.16.1. We saw that at the workshop at Directions and is still investigating if we can change something or it is a VsCode issue.

Can you try to download and install the July version ([1.15](https://code.visualstudio.com/updates/v1_15)) of VsCode?

**Comment by MikeGlue** [comment] 2017-09-25 15:13
Unfortunately even with using 1.15 I still get the same issue.

**Comment by dennisfrostlander** [comment] 2017-09-28 09:14
Hmm, when following the repro, the only error I sometimes get is this:
![image](https://user-images.githubusercontent.com/16953692/30958233-c38b77a6-a43c-11e7-90e3-89a9988a7256.png)

As you can see I have renamed my configuration in launch.json but VSCode still tries to launch the previous one on F5. This specific problem is probably a small VSCode bug. The next time I press F5 it finds the new configuration.

However, I never get the following error:
![image](https://user-images.githubusercontent.com/5204734/30491983-0236ad66-9a0d-11e7-93cb-b43a0b9c7de5.png)

Or was this error the result of clearing the credentials cache?

One thing we added in the new release is automatic saving of launch.json when you press F5. If you change the server name in the launch.json, do *not* save the file and press F5, we might get stale information from VSCode. This will be improved.
By the way, were you saving the launch.json before pressing F5 in your tests?

Regarding multiple configurations in launch.json, when you press F5 we use the default one. It can be set in the Debugging tab in VSCode:
![image](https://user-images.githubusercontent.com/16953692/30958579-e605e360-a43d-11e7-939d-df72e71fbf4c.png)

**Comment by MikeGlue** [comment] 2017-10-03 17:45
I did some more testing and I now think that this relates to the clearing of the credential cache. If I avoid clearing the cache, I can switch between deployment configurations using the dropdown on the debug tab. I can use Ctrl+F5 and F5 and the "play" button all without issue. 

As soon as I clear the cache though, all of the methods stop working, all with the same internal error. That's when I have to use the Go! command and create a new project and publish it to the environment I want.

**Comment by dennisfrostlander** [comment] 2017-10-10 09:01
Just wanted to mention that I still can't reproduce the reported behavior. Using exactly the same setup, on the latest dev preview VM, same VSCode version. It's a real puzzle.

A recording of some of my attempts is below. 

![f5](https://user-images.githubusercontent.com/16953692/31377844-ada039ce-ada9-11e7-9b74-e0e7cecf252d.gif)

**Comment by StanislawStempin** [comment] 2018-01-03 14:25
Closing based on lack of repro. Please log a new issue if it still occurs on latest builds.

**Closed by StanislawStempin** 2018-01-03 14:25 UTC
