### ISSUE TITLE
False detection of AS0018 "A procedure belonging to a public API must not be removed"

### ISSUE THREAD

**Issue by jwikman** [microsoft/AL#5868] opened 2020-05-11 20:30 UTC
**Describe the bug**
When we delete a codeunit that has been marked with ObsoleteState = Pending; we get the AS0018 error. 

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a codeunit with a couple of procedures
2. Set ObsoleteState = Pending; in the codeunit
3. Compile to get an app file
4. Copy the app file to the .alpackages folder
5. Configure appsourcecop.json for that version
6. Increase version in app.json
7.  delete codeunit (or just comment out a procedure) and compile

Now AS0018 will appear.

v1.0.0.0:
```
codeunit 50100 "MyCodeunit"
{
    ObsoleteState = Pending;
    ObsoleteReason = 'Will be removed..';
    ObsoleteTag = '15.0';


    procedure MyProcedure()
    begin
        Message('repro');
    end;

    procedure MyProcedure2()
    begin
        Message('now');
    end;
}
```
v1.1.0.0:
```
codeunit 50100 "MyCodeunit"
{
    ObsoleteState = Pending;
    ObsoleteReason = 'Will be removed..';
    ObsoleteTag = '15.0';


    procedure MyProcedure()
    begin
        Message('repro');
    end;

}
```

**Expected behavior**
Since the object was obsolete pending, no issues should appear...
Both a procedure, all procedures or the whole codeunit should be able to be deleted - since the object has ObsoleteState= Pending.

**Screenshots**
N/A
**5. Versions:**

 - AL Language: 5.0.270354

 - Business Central: N/A

**Comment by jwikman** [comment] 2020-05-12 09:22
@qutreson this issue still exists in 5.0.271898

**Comment by jwikman** [comment] 2020-05-12 09:34
@qutreson One "funny thing" I noticed when testing this is that I can change an object with  ObsoleteState = Pending to Access=Internal, but I cannot change the scope of a procedure to Internal. The change in the API is still the same...

Deleting a whole objekt that has ObsoleteState = Pending should be possible, don't you think?

**Comment by qutreson** [comment] 2020-05-12 10:19
@jwikman the original issue seems to me like a duplicate of #5869. We can keep the discussion about breaking changes on procedures in obsolete objects in the related issue.

The following scenarios should not raise any diagnostics:
- Turning an obsolete object/procedure to internal and not obsolete
1. Version 1: codeunit is public and obsolete
2. Version 2: codeunit is internal and **not** obsolete
- Removing an obsolete object
1. Version 1: codeunit is obsolete
2. Version 2: codeunit is removed

When removing the obsolete attribute in the base line, we are considering that the obsoleted object has been removed and a brand new one, which is not part of the public interface from the base line, is introduced. If the object or the procedure remains obsolete in the current version of the extension it will still be validated for breaking changes as it is still part of the public interface defined by the base line.

**Comment by jwikman** [comment] 2020-05-12 11:38
It might be considered a duplicate, they sure are related anyway. But it _is_ different rules...

I'll continue the discussion in #5869, since they are all related.

**Comment by qutreson** [comment] 2020-05-12 16:05
Closing this one as a duplicate then, to make sure to keep it one place.

**Closed by qutreson** 2020-05-12 16:05 UTC
Labels: AppSourceCop, static-code-analysis
