### ISSUE TITLE
AS0003 is broken with AL Extension v8.1.540594

### ISSUE THREAD

**Issue by alexlang24** [microsoft/AL#6826] opened 2021-11-10 09:14 UTC
- AL Extension Version: v8.1.540594

- Error is displayed although the package cache folder includes the app. This doesn't come up with the previous AL Extension Version v8.1.525271.

The version 'App Version' of the extension with publisher 'Publisher' and name 'App Name' could not be found in the baseline package cache folder. If you do not want to validate breaking changes, remove the property 'version' from the AppSourceCop.json.

**Comment by kalberes** [comment] 2021-11-10 23:12
Can you please specify some more details? What is your repro step, what is your AppSourceCop.json?

**Comment by alexlang24** [comment] 2021-11-11 11:17
I have an existing repository of an app which is listed in AppSource. Also another app repository is concerned.

My AppSourceCop.json is this:
{
    "mandatoryAffixes": ["CCS", "CCS "],
    "supportedCountries": ["US", "DE", "AT", "CH", "HU"],
    "version": "3.1.71135.0"
}

On my computer the latest AL Language extension has been installed which then occurred this error.

Then I've installed the previous AL Language extension and no error occurs:
![image](https://user-images.githubusercontent.com/31060488/141288418-acfe47bf-fb11-4c70-960c-d848340df0fc.png)

If I update AL Extension then I again get this error.

Same behaviour with this repository had one of my colleagues. If helpful I can share my repository or show it via teams.

**Comment by qutreson** [comment] 2021-11-11 13:41
We cannot reproduce the issue for now on a simple AL project. Can you share your settings? Are you using a single app or a workspace with multiple apps?

Can you also try to specify this `"baselinePackageCachePath": "<path-to-your-package-cache-path>"` in your AppSourceCop.json (ex: `"baselinePackageCachePath": "./.alpackages"`)? Does that help?

**Comment by alexlang24** [comment] 2021-11-11 15:18
I use a workspace with multiple apps. It consists a Test App and also a Library App.

Yesterday I've checked all settings regarding al:package cache path
User, Workspace and Folders has the same:
![image](https://user-images.githubusercontent.com/31060488/141322757-8227bf99-6710-439f-8bd0-cbd435fb50af.png)

But good news is that parameter "baselinePackageCachePath" helps!

**Comment by alexlang24** [comment] 2021-11-11 15:28
I should have read the docs article 
[https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0003#setting-up-appsourcecop-to-detect-breaking-changes](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0003#setting-up-appsourcecop-to-detect-breaking-changes)

But strange why this is now necessary. Any changes must have been done in the AL extension I guess.

**Comment by kalberes** [comment] 2021-11-11 19:09
Yes there were some refactoring done to increase the speed of loading projects with project references and reduce loading of app symbol references

**Comment by JesperSchulz** [comment] 2021-11-26 18:52
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 33063 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Closed by JesperSchulz** 2021-11-26 18:52 UTC
Labels: bug, in-progress, ships-in-future-update, static-code-analysis, AppSourceCop
