### ISSUE TITLE
Glitch in VSCode when looking at corresponding case/end begin/end

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/AL#6065] opened 2020-08-03 09:14 UTC
**Describe the bug**
In the VSCode editor, begin/end seems to be always associated even if "end" can also be used with "case". So when you have a "case" in a procedure, begin/end are not highlighted correctly.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a new codeunit like below:

```
codeunit 50000 MyCodeunit
{
    trigger OnRun()
    begin
        case true of
            true:
                Message('True');
            false:
                Message('False');
        end;
    end;
    
}
```

2. Select _begin_ after OnRun: it is associated with the end of the case.

**Expected behavior**
End of the case should be associated with the case, and the last end should be associated with the begin of the trigger.

**Screenshots**
![image](https://user-images.githubusercontent.com/44807684/89166239-07189780-d57a-11ea-9c3d-77a0884dee0f.png)

**5. Versions:**
 - AL Language: 6.0.302409

**Comment by dtkb** [comment] 2020-08-03 14:03
dupe of https://github.com/microsoft/AL/issues/5828

see also https://github.com/microsoft/AL/issues/5828 et al.

**Comment by dtkb** [comment] 2021-01-27 12:26
This appears to be fixed, as per the linked duplicate.

**Closed** 2021-01-27 13:03 UTC
Labels: bug
