### ISSUE TITLE
IncludeCaption has no effect on WORD layouts

### ISSUE THREAD

**Issue by srenders** [microsoft/AL#5687] opened 2020-02-24 13:13 UTC
**Describe the bug**
When creating a report dataset, in AL, and using IncldeCaption on fields, no captions (labels) are created in the WORD layout. Is that normal?
When using a Label it gets created, when using IncludeCaption it does not.

**To Reproduce**
Steps and to reproduce the behavior:
Create the following Report:
```
report 50106 CustomerListReport
{
    UsageCategory = ReportsAndAnalysis;
    ApplicationArea = All;
    AdditionalSearchTerms = 'Customer List Report';
    RDLCLayout = 'CustomerListReport.rdl';
    WordLayout = 'CustomerListReport.docx';
    DefaultLayout = RDLC;

    dataset
    {
        dataitem(Customer; Customer)
        {
            column(CustomerNo; "No.")
            {
                IncludeCaption = true;
            }
            column(CustomerName; Name)
            {
                IncludeCaption = true;
            }
            column(City; City)
            {
                IncludeCaption = true;
            }
            column(BalanceLCY; "Balance (LCY)")
            {
                IncludeCaption = true;
            }
        }
    }
    labels
    {
        LabelName = 'Label Text', Comment = 'Foo', MaxLength = 999, Locked = true;
    }
}
```

Generate the layout using Ctrl+Shft+B

**Expected behavior**
Labels should becreated in the layouts.

**Screenshots**
![includecaption-word](https://user-images.githubusercontent.com/17511254/75155014-5c20c980-570f-11ea-8c57-016d3c3381be.png)
![includecaption-rdlc](https://user-images.githubusercontent.com/17511254/75155032-65aa3180-570f-11ea-927d-3081c9e2c224.png)

**5. Versions:**
 - AL Language: 
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 4.0.229715
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

 - Business Central:
Version: US Business Central 15.2 (Platform 15.0.39461.40778 + Application 15.2.39060.0)

**Comment by srenders** [comment] 2020-03-09 11:40
**Any update on this?**

It seems like a bug and I don't know of any other way to make a report multi-language, unless you want people to start using FIELDCAPTION() and adding a lot of fields in the dataset, which imho is not so good for performance...

(IncludeCaption is used to generate captions in the language of the user running the report and FIELDCAPTION() should only be used to generate reports in the language of the recipient, for example for document reports.)

**Comment by srenders** [comment] 2020-04-29 12:01
Any update or ETA of a fix?

**Comment by srenders** [comment] 2020-05-26 12:28
Any update or ETA of a fix?

**Comment by rsgilbert** [comment] 2020-10-06 12:32
Any update?

**Comment by rsgilbert** [comment] 2020-10-06 12:47
According to this page https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-includecaption-property, it seems like that's the intended behavior

**Comment by dtkb** [comment] 2020-10-06 14:34
Yeah, but it shouldn't be... BC has no problem putting things from the `labels` section of the report code into the Word layout, so why can't it also put things with `IncludeCaption=true` there too, just like it does for RDLC layouts? I doubt there's a technical barrier, just a bug or a lack of implementing the feature.

**Comment by rsgilbert** [comment] 2020-10-07 10:07
I am guessing its not the recommended approach, perhaps most people use rdlc to design reports. WordLayouts look better but they seem to have less capabilities. Just today I could not creating a nested repeating group in my WordLayout. Either it cant be done or the people who know how to do it dont blog or document how its done.

**Comment by lvanvugt** [comment] 2020-11-11 06:54
Today I picked up working with WORD layout again after a log time. Now on BC17 for first time and running into the same issue. And I am **flabbergasted** that it is still not fixed.

If you cannot get captions added to the Labels in dataset xml (definition) WORD layout is totally useless.

BTW: the funny thing (and tedious workaround) is that if I export the WORD layout through the Report Layout Selection (Custom Reports Layouts) the captions do reside in the xml dataset structure and I can get things working.

**Comment by dtacconi** [comment] 2020-11-13 13:57
This request has been sent now through the the CSS channel and escalated to development team. 
When the item will be processed, I will updated this thread with the outcome. 
FYI this feature limitation is there since ages (tested from 14.x onwards).

**Comment by nhsejth** [comment] 2020-11-18 15:05
The problem has been identified and a fix is on its way to the repository. The issue was caused by the code that generated the empty template from the report design, it inserted the normal labels, but did not generate new labels for the columns with include caption.

**Comment by lvanvugt** [comment] 2020-11-18 15:25
Hooray. Great. But I am somewhat disappointed that a support escalation was needed to get things moving (again?).

**Comment by atoader** [comment] 2020-11-18 15:38
We try our best to fix issues reported through GitHub, but we will not be able to address all of them. If anything is very important, please raise it through support.

**Comment by lvanvugt** [comment] 2020-11-18 15:43
> 
> 
> We try our best to fix issues reported through GitHub, but we will not be able to address all of them. If anything is very important, please raise it through support.

I know. I was a MSFTE, and yes, true for raising anything very important through support, but that shouldn't have been the case here, as this is clearly a major issue by the shear fact that we get the advice to use WORD over RDLC from MS.
Read the **Important** notice here https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-howto-rdl-report-layout

**Comment by atoader** [comment] 2020-11-22 17:23
I will close this issue as the fix has been checked in and will be available in a future CU for Business Central.

**Closed by atoader** 2020-11-22 17:23 UTC
Labels: bug
