### ISSUE TITLE
System.OutOfMemoryException when trying to build & publish app

### ISSUE THREAD

**Issue by ptijsma** [microsoft/AL#5969] opened 2020-06-16 09:50 UTC
**Describe the bug**
We're in the process with the whole development team to split up our solution into multiple apps, but things are going really slowly because of this error occuring time and time again.

When trying to build & publish our app for the second time during a VS Code session (because of ongoing development) a System.OutOfMemoryException occurs

**To Reproduce**
Steps and to reproduce the behavior:
1. Open VS Code
2. Open a workspace with the app (in our case +/- 4300 source files)
3. Press F5 to build & publish
4. Check some functionality
5. Back to VS Code and stop debugger
6. Make some changes to the code
7. Press F5 again to build & publish
8. Error occurs

**Update: This only occurs if the "features" property in the app.json file is set to "TranslationFile"**
But of course this is only a workaround

**Expected behavior**
Even after disabling a lot of VS extensions en changing settings in VS Code to boost performance, it presents this issue.
We need to be able to trust AL en VS Code to work smooth and properly without out-of-memory exceptions.

**Screenshots**
![image](https://user-images.githubusercontent.com/18245218/84759442-04acaf00-afc7-11ea-8c8a-30f1a82948fd.png)

**5. Versions:**

 - AL Language: 5.0.280447

 - Business Central: 16.0.13440.13772 (OnPrem)

**Comment by AndreyKorepanov** [comment] 2020-06-18 20:10
Hi @ptijsma, thank you for reporting the issue. Could you please provide a project which demonstrates the issue, may be it is possible to localize the problem. It would significantly help us to reproduce the issue. What kind of changes do you make at i.6, does the translation file has any changes between ii.3 and 7? Thank you.

**Comment by ptijsma** [comment] 2020-06-19 08:38
Hi @AndreyKorepanov,
Provide a project.. Ehhm.. I could provide you our App in a private message somehow, however, it's in total 249 MB and contains 4452 files.
Regarding the translation files:
We have these translation files in the directory:
![image](https://user-images.githubusercontent.com/18245218/85113925-5f891500-b218-11ea-84da-dd368e505e04.png)

The BaseApp.g.xlf would normally be bigger, but beacuse the property "TranslationFile" has been disabled, this isn't rebuild currently

re/ Changes at i.6: Can be any change as simple as adding a MESSAGE somewhere. Nothing fancy
re/ Translation file changes: We haven't made any changes to the en, nl, de translation files between i.3 and i.7. The only change (When the property "TranslationFile" has been enabled) is that the BaseApp.g.xlf is being rebuild on F5. 
To my understanding it's exactly the rebuild of BaseApp.g.xlf that causes the crash.

Hope this helps,
Thanks,
Peter

**Comment by AndreyKorepanov** [comment] 2020-06-19 09:25
Hi @ptijsma, thank you for reply. I'll try to get a repro on the Base app, In my case Base app translation file is around 50K.

**Comment by ptijsma** [comment] 2020-06-19 09:30
Hi @AndreyKorepanov ,
Just to be sure: BaseApp in our case, is our BaseApp which has of course a dependancy on the Microsoft BaseApp.
![image](https://user-images.githubusercontent.com/18245218/85118207-50a66080-b220-11ea-93be-e9a221359b37.png)

**Comment by ptijsma** [comment] 2020-06-22 13:14
Hi @AndreyKorepanov ,

Just another screen shot with a different Out of memory exception. Same app. Not sure if this helps though.

![image](https://user-images.githubusercontent.com/18245218/85290028-9cfbd580-b498-11ea-8012-754dfc5ebbac.png)

**Comment by ptijsma** [comment] 2020-06-29 13:27
Hi @AndreyKorepanov,

Just found out one more thing.
Seems our generated Xlf files are also kind of corrupted... It seems there are quite some entries with duplicate id's:

![image](https://user-images.githubusercontent.com/18245218/86011455-fa55d080-ba1c-11ea-8ed1-97d98a208632.png)

I'm guessing this could also be some kind of reason for out of memory exceptions..

**Comment by AndreyKorepanov** [comment] 2020-06-29 21:01
Hi @ptijsma, it seems the former is related to the #5866. Thanks.

**Comment by ShivamG0217** [comment] 2021-08-19 12:01
@atoader @AndreyKorepanov  
 Do we have any resolution for this issue??

**Comment by suryanshsangwan** [comment] 2021-11-26 11:18
Use 64 bit compiler.
It will be much faster and does not give out of memory exceptions

**Comment by suryanshsangwan** [comment] 2021-11-26 11:20
This error usually comes while building large applications/extensions.

When the memory used for this process exceeds 4GB it throws out of memory.

**Comment by iTomate** [comment] 2022-02-18 12:54
@suryanshsangwan 
Is there a 64 bit compiler for AL available? If so, where would i find it?

**Comment by suryanshsangwan** [comment] 2022-02-18 12:57
@iTomate AL vscode extension is the compiler. When you extract it, you will find a win32 folder that contains the 64bit compiler and its dependencies.

**Comment by rcverbeek** [comment] 2022-03-31 10:06
We ran into simular problems when changing the BC18 baseapp. We are unable to compile the app: System.OutOfMemoryException

When deleting the xlf files from the Translations folder, compilation finishes succesfully.

**Comment by suryanshsangwan** [comment] 2022-03-31 10:13
![PXL_20220331_154150151.MP~2.jpg](https://user-images.githubusercontent.com/32640058/161032199-73ea60b6-5632-4ae7-9b58-c095e811c240.jpg)

**Comment by suryanshsangwan** [comment] 2022-03-31 10:13
Use this path

**Comment by rcverbeek** [comment] 2022-03-31 10:29
Thats seems to be working quite well! Thanks a lot Suryansh

**Comment by BazookaMusic** [comment] 2024-03-17 22:06
The 64 bit executable is shipped nowadays, so I'll close this

**Closed by BazookaMusic** 2024-03-17 22:06 UTC
Labels: bug
