### ISSUE TITLE
Addafter(anchor) does not see correct references.

### ISSUE THREAD

**Issue by Update-Mark** [Microsoft/AL#4920] opened 2019-04-23 09:50 UTC
**Describe the bug**
In the OnPremise version of BC - Spring Update, I am seeing an inconstancy between some controls. For example, the Prepayment anchor is listed in VS Code as the control number (Control1900201301) when using the AddAfter, AddBefore, AddFirst, and AddLast tags.

For Example:
![image](https://user-images.githubusercontent.com/35524409/56570600-8b305100-65bb-11e9-9bfc-ca418092e8ec.png)

Works fine.

![image](https://user-images.githubusercontent.com/35524409/56570709-b7e46880-65bb-11e9-81bc-6b47d1154720.png)

![image](https://user-images.githubusercontent.com/35524409/56570802-e5c9ad00-65bb-11e9-915e-ba8d9d68fe0b.png)

Does not allow for compile, however using the corresponding control number:

![image](https://user-images.githubusercontent.com/35524409/56570948-33deb080-65bc-11e9-9b08-6cd769840224.png)

Allows the extension to be compiled, but causes an error on publishing:
![image](https://user-images.githubusercontent.com/35524409/56571024-61c3f500-65bc-11e9-94be-1eaf5ae54887.png)

This has happened to me on two, separate databases, that have both been upgraded from BC13 to BC14, granted, in different extensions and can be resolved in most cases, by using a addbefore the next valid anchor control.  In both cases, these were recreated extensions that worked in BC13.

--Things attempted to resolve the issue.--
1. Recompiled all objects.
2. Generated Symbols.
3. Uninstalled and reinstalled the al VS extension from the .vsix.
4. Restarted services and the Docker container.

Has anyone else come across this and can tell me what stupid thing I have done? 

**Expected behavior**
The correct control name is either generated or used.

**Versions:**
On Premise - 3.0.106655 (installed from .vsix)

 - Business Central:
 Version: Platform 14.0.29530.0 + Application 29537

**Comment by rvanbekkum** [comment] 2019-04-23 12:29
I think this is the same issue as #4893. I received a reply on Yammer from @atoader that this is a known issue and that it will be resolved in CU01.

**Comment by Update-Mark** [comment] 2019-04-23 12:36
Well that is exactly my problem!  My search skills have failed me!

**Comment by qutreson** [comment] 2019-04-24 07:31
Closing this issue as a duplicate of #4893

**Closed by qutreson** 2019-04-24 07:31 UTC
