### ISSUE TITLE
Error: The request failed with code 422, reason:  The following SQL error was unexpected: Incorrect syntax near ')'.

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#458] opened 2017-08-03 12:03 UTC
If you create a new table extension that contains only FlowFields, that is, no real fields, then the following error occurs. This occurs, however, only when the extension is deployed, not in the development phase.

**_Error: The request failed with code 422, reason:
The following SQL error was unexpected:
Incorrect syntax near ')'._**

The problem appears to be in the generated SQL Query. However, this only applies to table extensions with FlowFields.

In the event viewer the whole thing looks like this:

```
Server instance: Navision_main
Tenant ID: <ii>default</ii>
<ii>Session type: UnknownClient
Session ID: 7
User: NAVDEVTOOLS07\VMADMIN
Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavSqlException
ErrorNumber: 102
SuppressMessage: False
DiagnosticsSuppress: False
SuppressExceptionCreatedEvent: False
FatalityScope: None
Message:
  <ii>The following SQL error was unexpected:
  Incorrect syntax near ')'.
  SQL statement:
  CREATE TABLE dbo."CRONUS International Ltd_$Finance Cue$36739467-0e90-4c70-ab92-caddb2e093e6" (CONSTRAINT "CRONUS International Ltd_$Finance Cue$36739467-0e90-4c70-ab92-caddb2e093e6$0" PRIMARY KEY CLUSTERED ("Primary Key"))
  StackTrace:
     at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
     at System.Environment.get_StackTrace()
     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.ThrowNavSqlException(SqlExceptionAdapter exceptionAdapter, String commandText, Boolean isLastExceptionARollbackCause, Boolean logExceptions)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.<>c__DisplayClass106_0`1.<ExecuteFunction>b__0()
     at Microsoft.Dynamics.Nav.Types.NavThread.RunExternalAction[T](Func`1 action)
     at Microsoft.Dynamics.Nav.Diagnostic.NavDiagnostics.SendTraceTagOnThreshold[T](String tag, Category category, Verbosity verbosity, Int32 threshold, Func`1 action, String message, Object[] parameters)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.ExecuteFunctionWithTrace[T](EventTask task, Func`1 function, String commandText)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlCommand.ExecuteNonQueryImp()
     at Microsoft.Dynamics.Nav.Runtime.NavSqlBatchedCommand.ExecuteNonQuery()
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDdlCommands.PrepareNewTable(NavDatabase database, NavSqlTableAndChange tableAndChange, Int32 companyToken, SyncMode syncMode)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseSync.SyncAllTables(IEnumerable`1 tableChanges, RebuildAction rebuildAction, Int32[] companyTokens, SyncMode syncMode, Int32 syncStepNo, Int32 totalSteps, NavAppSyncOptions appSyncOptions, Boolean perTable)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseSync.SynchronizeTableChanges(NavSession session, IEnumerable`1 tableChanges, Int32[] companyTokens, SyncMode syncMode, Boolean isUpgradeTableSynchronization, Boolean perTable)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseSync.PerformAppSync(NavSession session, IEnumerable`1 tableChangesToSynchronize, Int32[] companyTokens)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseSync.SynchronizeTenantDatabaseForAppSyncInternal(NavSession session)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseSync.<>c__DisplayClass104_0.<SynchronizeTenantDatabaseForAppSync>b__0(NavTenant tenant, NavSession systemSession)
     at Microsoft.Dynamics.Nav.Runtime.NavTenant.Microsoft.Dynamics.Nav.Runtime.ITenantSessionHandler.RunTenantActionInSystemSession(Action`2 action, Boolean throwExceptions, Boolean useCurrentCulture, Boolean allowAppsDisabledMode)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseSync.SynchronizeTenantDatabaseForAppSync(AppSyncContext appSyncContext)
     at Microsoft.Dynamics.Nav.Runtime.NavAppSyncManagementTasks.SyncNavApp(SyncNavAppArguments args)
     at Microsoft.Dynamics.Nav.Service.NSAdminService.<>c__DisplayClass116_0.<Microsoft.Dynamics.Nav.Types.ITenantDatabaseManagementService.SyncNavApp>b__0()
     at Microsoft.Dynamics.Nav.Runtime.NavSqlTransientErrorHelper.<>c__DisplayClass2_0`1.<RetryOperationWithTransientError>b__0()
     at Microsoft.Dynamics.Nav.Runtime.NavSqlTransientErrorHelper.InternalRetryOperationWithTransientError[T](Action operation, Int32 maxRetryCount, Int32 retryIntervalInSeconds, String callerName, String additionaInfo, Boolean expectedType)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlTransientErrorHelper.RetryOperationWithTransientError[T](Func`1 operation, Int32 maxRetryCount, Int32 retryIntervalInSeconds, String caller, String additionalContext)
     at Microsoft.Dynamics.Nav.Service.NSAdminService.Microsoft.Dynamics.Nav.Types.ITenantDatabaseManagementService.SyncNavApp(SyncNavAppArguments syncNavAppArguments)
     at Microsoft.Dynamics.Nav.Service.Dev.DevService.SyncNavApp(NavAppManifest manifest, String tenantId)
     at Microsoft.Dynamics.Nav.Service.Dev.DevService.<>c__DisplayClass4_1.<PublishAndInstallExtension>b__0()
     at Microsoft.Dynamics.Nav.Service.Dev.DevService.PublishAndInstallExtension(NavSession session, Stream packageStream, PerformanceLog performanceLog)
     at Microsoft.Dynamics.Nav.Service.Dev.Web.Controllers.AppsController.<PublishAndInstall>d__0.MoveNext()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at Microsoft.Dynamics.Nav.Runtime.NavSynchronizationContext.<>c__DisplayClass1_0.<ClearThreadLocalStorageDelegate>b__0(Object state)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
     at System.Threading.ThreadPoolWorkQueue.Dispatch()</ii>
HResult: -2146233088
----------------------------------
Type: System.Data.SqlClient.SqlException
ClientConnectionId: 6301059f-f36b-4b1f-8101-e02ba8cf91ae
Class: 15
LineNumber: 1
Number: 102
Server: LOCALHOST\NAVDEMO
State: 1
Source: .Net SqlClient Data Provider
ErrorCode: -2146232060
Message: <ii>Incorrect syntax near ')'.</ii>
StackTrace:
     at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
     at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
     at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
     at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
     at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
     at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.<>c__DisplayClass106_0`1.<ExecuteFunction>b__0()
HResult: -2146232060
</ii>
```

**Comment by kalberes** [comment] 2017-08-14 11:32
This looks a duplicate of #311

**Closed** 2017-09-11 15:30 UTC
Labels: duplicate
