### ISSUE TITLE
Different symbols for tests compilation between VSCode & NavContainerHelper, usage of CodeUnit "Assert" and AL0265: Reference to object Assert is ambiguous.

### ISSUE THREAD

**Issue by megel** [Microsoft/AL#4658] opened 2019-02-27 10:57 UTC
Version: `13.3.27233.0-de` and docker Image: `mcr.microsoft.com/businesscentral/onprem:de-ltsc2016`

I have figured out, my VSCode downloading different Symbols from container than the **NavContainerHelper**. When I start with app.json & launch.json:

![image](https://user-images.githubusercontent.com/15800069/53483948-f3165f80-3a82-11e9-840e-6ee33dc6caf7.png)
![image](https://user-images.githubusercontent.com/15800069/53484143-67510300-3a83-11e9-9b34-b5b481d97944.png)

```
[2019-02-27 11:25:03.10] Using reference symbols cache path: c:\vsts-agent-MME\_work\6\s\TestApp\./.alpackages
[2019-02-27 11:25:03.11] Sending request to http://172.19.120.197:7049/nav/dev/packages?publisher=Microsoft&appName=Application&versionText=13.0.0.0&tenant=default
[2019-02-27 11:25:03.11] Sending request to http://172.19.120.197:7049/nav/dev/packages?publisher=Microsoft&appName=System&versionText=13.0.0.0&tenant=default
[2019-02-27 11:25:03.11] Sending request to http://172.19.120.197:7049/nav/dev/packages?publisher=COSMO CONSULT&appName=Customer02&versionText=0.0.0.1&tenant=default
[2019-02-27 11:25:17.52] All reference symbols have been downloaded.
```
The downloaded symbols from container:
![image](https://user-images.githubusercontent.com/15800069/53483871-cc582900-3a82-11e9-8f6d-5d5dda434b67.png)

With VSCode, I'm able to publish my testapp to the container. This works well.
In Azure DevOps I use NavContainerHelper and run this command to compile the test application. This fails, because a newer version of application symbols is downloaded (Microsoft_Application_13.**3**.27233.0.app) and there is a problem with the **Assert** CodeUnit:
```PowerShell
Using Symbols Folder: C:\vsts-agent-MME\_work\6\s\TestApp\.alpackages
Downloading symbols: Microsoft_Application_13.3.27233.0.app
Url : http://Cust-02-bld:7049/NAV/dev/packages?publisher=Microsoft&appName=Application&versionText=13.3.27233.0&tenant=default
Downloading symbols: Microsoft_System_13.0.12929.0.app
Url : http://Cust-02-bld:7049/NAV/dev/packages?publisher=Microsoft&appName=System&versionText=13.0.12929.0&tenant=default
Downloading symbols: COSMO CONSULT_Customer02_0.0.0.1.app
Url : http://Cust-02-bld:7049/NAV/dev/packages?publisher=COSMO%20CONSULT&appName=Customer02&versionText=0.0.0.1&tenant=default
Compiling...
Microsoft (R) AL Compiler version 2.1.1.13845
Copyright (C) Microsoft Corporation. All rights reserved

Compilation started for project 'Customer-02-Tests' containing '2' files at '11:24:26.882'.

C:\vsts-agent-MME\_work\6\s\TestApp\src\Codeunit_-_CC-Tests.al(7,17): error AL0185: Codeunit 'Assert' is missing

Compilation ended at '11:24:33.137'.

Compile-AppInNavContainer : App generation failed
At line:1 char:1
+ Compile-AppInNavContainer Cust-02-bld -appProjectFolder "C:\vsts-agen ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Compile-AppInNavContainer

PS C:\vsts-agent-MME\_work\6\s\TestApp>
```

Well, I can fix this by changing the **app.json**:
![image](https://user-images.githubusercontent.com/15800069/53484744-c6634780-3a84-11e9-9305-25edec2e8190.png)
Symbols are downloaded correct and app compiles:
![image](https://user-images.githubusercontent.com/15800069/53484803-f579b900-3a84-11e9-8385-705c34b1c06a.png)

Same in Azrue DevOps:
```powershell
PS C:\vsts-agent-MME\_work\6\s\TestApp> Compile-AppInNavContainer Cust-02-bld -appProjectFolder "C:\vsts-agent-MME\_work\6\s\TestApp" -appOutputFolder "C:\vsts-agent-MME\_work\6\s\TestApp" -appSymbolsFolder "C:\vsts-agent-MME\_work\6\s\TestApp\.alpackages" -cr
edential ([PSCredential]::new("username", (ConvertTo-SecureString -String "Pa$$$$word" -AsPlainText -Force))) -UpdateSymbols
Using Symbols Folder: C:\vsts-agent-MME\_work\6\s\TestApp\.alpackages
Downloading symbols: Microsoft_Application_13.3.27233.0.app
Url : http://Cust-02-bld:7049/NAV/dev/packages?publisher=Microsoft&appName=Application&versionText=13.3.27233.0&tenant=default
Downloading symbols: Microsoft_System_13.0.12929.0.app
Url : http://Cust-02-bld:7049/NAV/dev/packages?publisher=Microsoft&appName=System&versionText=13.0.12929.0&tenant=default
Downloading symbols: Microsoft_Test_13.3.27233.0.app
Url : http://Cust-02-bld:7049/NAV/dev/packages?publisher=Microsoft&appName=Test&versionText=13.3.27233.0&tenant=default
Downloading symbols: COSMO CONSULT_Customer02_0.0.0.1.app
Url : http://Cust-02-bld:7049/NAV/dev/packages?publisher=COSMO%20CONSULT&appName=Customer02&versionText=0.0.0.1&tenant=default
Compiling...
Microsoft (R) AL Compiler version 2.1.1.13845
Copyright (C) Microsoft Corporation. All rights reserved

Compilation started for project 'Customer-02-Tests' containing '2' files at '11:16:28.857'.


Compilation ended at '11:16:38.138'.
```
But now I can not publish the TestApp to the container because "AL0265: Reference to object Assert is ambiguous.":
```powershell 
C:\vsts-agent-MME\_work\6\s\TestApp\COSMO CONSULT_Customer-02-Tests_0.0.0.1.app successfully created in 27 seconds
C:\vsts-agent-MME\_work\6\s\TestApp\COSMO CONSULT_Customer-02-Tests_0.0.0.1.app
PS C:\vsts-agent-MME\_work\6\s\TestApp> Publish-NavContainerApp Cust-02-bld -appFile '.\COSMO CONSULT_Customer-02-Tests_0.0.0.1.app' -skipVerification -install
Copy .\COSMO CONSULT_Customer-02-Tests_0.0.0.1.app to container Cust-02-bld (c:\run\COSMO CONSULT_Customer-02-Tests_0.0.0.1.app)
Publishing c:\run\COSMO CONSULT_Customer-02-Tests_0.0.0.1.app
Installing Customer-02-Tests on tenant default
Extension compilation failed
src/Codeunit_-_CC-Tests.al(7,17): error AL0265: Reference to object Assert is ambiguous. Make sure you are not referencing packages containing objects with the same names.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.5.0.3\ContainerHandling\Invoke-ScriptInNavContainer.ps1:30 char:9
+         Invoke-Command -Session $session -ScriptBlock $scriptblock -A ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$NAV/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp
    + PSComputerName        : 0809ea71e97568648620fcafb09fe0e2a4a5f4f97d30cf35b3bdc3f462a707ed

PS C:\vsts-agent-MME\_work\6\s\TestApp>
```

My Test-Project (App + C/Side + TestApp):

[CUST-02.ZIP](https://github.com/Microsoft/AL/files/2909925/CUST-02.ZIP)

**Comment by freddydk** [comment] 2019-02-27 11:12
If you are using EnableSymbolLoading - you should unpublish the symbols:
Unpublish-NavContainerApp <container> -appname Application - publisher microsoft
(same with system and test)

**Comment by freddydk** [comment] 2019-02-27 11:14
Looks to be the same as this: https://github.com/Microsoft/navcontainerhelper/issues/325
The root cause is that the localized database has a wrong appversion in the database - that is being fixed as we speak.

**Comment by megel** [comment] 2019-02-27 12:17
@freddydk, whats happen with CAL changes in my build process, when I run `Unpublish-NavContainerApp -appname Application - publisher Microsoft` before compiling the Test?

**Comment by freddydk** [comment] 2019-03-04 18:52
unpublishing the application symbols will remove confusion about which symbols you get - and you will always get the symbols generated.'
The root cause of this problem is, that the version number of the application is wrong when using enablesymbolloading - meaning that you will have two sets of symbols in the database and the newest set is the wrong set.

**Comment by qutreson** [comment] 2019-03-12 14:18
Hi @megeal, I am closing this issue as it seems to be already tracked by Microsoft/navcontainerhelper#325 and as a solution was proposed by @freddydk. Please open a new issue in case you are still facing this problem.

**Closed** 2019-03-12 14:18 UTC
