### ISSUE TITLE
15.21.1 breaks AL extension for Dynamics NAV 2018

### ISSUE THREAD

**Issue by r2-4u** [microsoft/AL#6384] opened 2020-12-17 15:50 UTC
Issue Type: <b>Bug</b>

"Couldn't find a debug adapter descriptor for debug type 'al' (extension might have failed to activate).

This extension is still heavily used, and not updated, so this needs to be fixed.

Extension version: 0.13.195601
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (16.25GB free)|
|Process Argv|--crash-reporter-id 6d8ed3dc-71f4-4ad6-b356-c0da196dc945|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440cf:30237828
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773cf:30236630

```

</details>

**Comment by epernst** [comment] 2020-12-19 19:41
That's a known issue: #6368 
You need to downgrade to 1.51

**Comment by atoader** [comment] 2020-12-28 15:00
Closing as duplicate of #6368

**Closed by atoader** 2020-12-28 15:00 UTC
Labels: duplicate
