### ISSUE TITLE
enableCodeActions performance drops

### ISSUE THREAD

**Issue by f4n0** [microsoft/AL#6196] opened 2020-10-05 12:57 UTC
**Describe the bug**
If I enable the al.enableCodeActions, the whole project performances drop to a level that is mostly unusable.
The IntelliSense takes 15/20 sec. to display the hints, errors take ages to update. even thou the checked file is small (around 200 lines)

**To Reproduce**
Steps and to reproduce the behavior:
1. Go to settings.json
2. set  `  "al.enableCodeActions": true,`

``` AL Code to reproduce the issue ```

**Expected behavior**
The performance cannot degrade like that

**Screenshots**

**5. Versions:**

 - Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 6.0.344420
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

 - Business Central: 16.4

**Comment by kalberes** [comment] 2020-10-06 16:15
Are you using the al.incrementalBuild: true setting? and hopefully the al.useLegacyRuntime is set to false.

**Comment by stefanoPrimo** [comment] 2020-10-07 07:09
legacy runtime is not specified (so I think that the default is false) and also incrementalBuild is not specified (not sure which value is the default one).
Now I added that to the settings, I give it a try!

**Comment by stefanoPrimo** [comment] 2020-10-07 09:28
Well, it is a bit better, but still pretty slow.

**Comment by kalberes** [comment] 2020-10-07 16:40
How big is your workspace and how many WITH statement warnings do you get?

**Comment by stefanoPrimo** [comment] 2020-10-08 07:35
The fun fact is that: I've Already solved all the with statement warnings. The workspace is nor small or big, it is like 100 files/objects.
and usually, my CPU is at 30% and Memory 50%, there is still plenty of resources to use

**Comment by kalberes** [comment] 2020-10-09 16:09
We may need a workspace with repro.  Else it will be hard to do anything. I will mark it as  a bug for now, but without a repro it has a chance to be ignored or closed.

**Comment by mjmatthiesen** [comment] 2021-04-19 20:58
I have the same issue. I would actually prefer to turn off intellisense/linter/formatter/etc now. Even the errors are often stuck because some process has crashed. I end up having to reload vscode to clear the bad state and have it re-analyze the changes.

I'm not sure how the ms devs are handling it, because if I open something like sales header posting, I experience the same performance degradation.

**Comment by NKarolak** [comment] 2021-06-28 07:03
@kalberes I'm affected by this as well, when using F2 to rename a variable. It takes 10 seconds.
To reproduce, you need all three following settings

```
"al.enableCodeActions": true,
"al.enableCodeAnalysis": true,
"al.backgroundCodeAnalysis": true,
```

However, only one specific repository of mine is really badly affected. I can share it with you, but not publicly over GitHub.

**Comment by kalberes** [comment] 2021-07-01 20:09
"al.enableCodeActions": true, "al.enableCodeAnalysis": true, are on our agenda (every time every half year) to refactor them not to consume all the memory in the world.  You can maybe take a process dump of the *Host.exe, and share that one.

**Comment by qutreson** [comment] 2023-11-28 13:39
@f4n0 @NKarolak - Are you still experiencing performance issues when enabling code actions with the latest AL extensions from the marketplace? There have been some investments done in the last releases to improve the code analysis framework which should have addressed performance issues.

**Comment by NKarolak** [comment] 2023-11-28 14:05
@qutreson No issue on my side.

**Comment by qutreson** [comment] 2023-11-28 14:48
Closing then this issue. If you are still experiencing issues, please log a new issue with new repro steps and additional context.

**Closed by qutreson** 2023-11-28 14:48 UTC
Labels: input-needed, language-server-integration, workspaces
