### ISSUE TITLE
'al/previewDocument' failed with error: 'Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by pranav4186** [Microsoft/AL#3405] opened 2018-08-20 18:53 UTC
I am getting below error in AL when I am trying to see definition of any objects.
![image](https://user-images.githubusercontent.com/35543761/44360269-34440c00-a46f-11e8-9cb0-40138ce7ba28.png)

I am trying to connect to the Daily build of Business central which is installed on docker. I could download the symbols and publish the app but get this error when trying to see definition of an object.

Thanks

**Comment by thpeder** [comment] 2018-08-20 21:40
Hi @pranav4186,

What version of the extension and the server are you running?
Does it happen for every object you try or are there some specific objects it only fails on?

**Comment by pranav4186** [comment] 2018-08-21 18:06
Hello,

I am running it on docker for the daily build of BC (us version). 
It is happening on for all the objects.
I am building my own extension so the version is 1.0.0.0.
The platform and application version is set to 12.00.0.0 in app.jason

Thanks

**Comment by atoader** [comment] 2018-11-02 11:56
Hi @pranav4186 ! Are you still encountering this issue?

**Comment by StanislawStempin** [comment] 2018-11-07 12:32
Closing due to lack of information to reproduce the issue. Please make sure you're using the latest AL Language version and that you deleted symbols that might have been downloaded from older versions of Business Central.

**Closed by StanislawStempin** 2018-11-07 12:32 UTC
Labels: input-needed, investigate
