### ISSUE TITLE
Pages, queries and SourceTableTemporary 

### ISSUE THREAD

**Issue by superjma** [Microsoft/AL#2729] opened 2018-06-26 11:52 UTC
Hi I have a problems with getting SourceTableTemporary to work.

I have a page with SourceTableTemporary 

If i create a page lige the following.
```
page 50008 "Merged Job Entries"
{
    Editable = false;
    PageType = List;
    SourceTable = "Job Journal Line";
    SourceTableTemporary = true;
....
    trigger OnOpenPage()
    begin
        FillTempTable();
    end;
....
    local procedure FillTempTable();
    var
        JobJnlLines : Query "Job Jnl Lines";
        JobLedgEntries : Query "Job Ledg Entries";
    begin
        if not IsTemporary then
            Error('Error not temp');
       ....
    end
}
```

But the function FillTempTable insert the record in the database instead of keeping it temporary.

**Comment by qutreson** [comment] 2018-07-04 08:48
Hi @superjma, I just tried your code on our latest master and I couldn't reproduce the issue as the source table is temporary as expected for me (it did not trigger then error message). Which version of the AL extension and of the server are you using?

**Comment by superjma** [comment] 2018-07-04 10:29
Hi

Al-version: 0.12.15355.
Nav-server: 11.0.20348.0

**Comment by qutreson** [comment] 2018-07-04 11:06
Thank you for reporting the issue. It seems to be fixed in our latest builds. As you are running on NAV 2018 and this potentially requires deeper investigation, please log a support case for your problem (see [FAQ - I found an issue on NAV 2018, what do I do?](https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#nav-2018-issues)) if you want this to be backported.

**Closed** 2018-07-19 16:09 UTC
Labels: customer-support
