### ISSUE TITLE
[Local Azure Function] Task was canceled

### ISSUE THREAD

**Issue by JulienDecottignies** [Microsoft/AL#2316] opened 2018-05-23 13:59 UTC
Hi,

I just tried to deploy a very little Azure function, and invoke it in my AL Code.

My AL Code looks like this:
```
codeunit 50101 CallAzure
{
    trigger OnRun();
    begin
    end;
    
local procedure GetName(Name: Text): Text
var
    Client: HttpClient;
    Content: HttpContent;
    Response: HttpResponseMessage;
    Url: Text;
    Result: Text;
begin
    Content.WriteFrom(Name);
    Url := 'https://test.azurewebsites.net/api/TriggerName?name='+Name;
    //Url := 'http://localhost:7071/api/TriggerName?name='+Name;
    Client.Get(Url, Response);    
    Response.Content.ReadAs(Result);
    exit(Result);
end;

//App runs on page 22
[EventSubscriber(ObjectType::Page, 22, 'OnOpenPageEvent', '', false, false)]
local procedure NameTheName()
var
    Julien: Text;
    Bill: Text;
begin
    Julien := 'Julien';
    Bill := 'Bill';
    
    Message('Premier prenom = %1 ', GetName(Julien));
    Message('Deuxieme prenom = %1', GetName(Bill));
end;

}

```
I tried to do that by two different ways: localy and by the url given by the azure portal. I have exactly the same code, the only difference resides in the url called.

When i call my azurewebsite.net/api url, it works fine.
When I call my localhost url (running in a separated terminal) it makes a very long time to show me:
`Error: A task was canceled`
(when i try this url in my browser, it works fine)

If I call my azurewebsite.net/api url, just after I have this error message:
`The request for path /NAV/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Cannot install extension TestAzureFunction because another service is currently modifying the state of extensions on tenant default.`

And have to wait for about 5minutes to be able to deploy again my extension.

I think it'sprobably a port problem, and if it's really that, could someone explain how to configure that ..?

Tried on the latest Docker image (bcsandbox:12.0.21865.0-fr)

**Comment by atoader** [comment] 2018-06-13 11:55
Hi @JulienDecottignies ! Are you still blocked by this?

**Comment by JulienDecottignies** [comment] 2018-06-13 12:05
Hi,
I didn't try to call my azure function locally since the day I posted the last message. 
I call my azure function by the URL provided by azurewebsite.

Also, I found another way to do what I wanted to do with azure functions, by using controladdin. So I'm not able to try again to run azure function locally in my actual project for now.

**Comment by atoader** [comment] 2018-06-13 13:01
Ok. Thanks for letting me know! In any case, it seems that the problem is related to the local Azure setup and not to the NAV runtime or compiler. I will close the issue.

**Closed by atoader** 2018-06-13 13:01 UTC
Labels: investigate
