### ISSUE TITLE
Global Variable on Page to set StyleExpr gives error

### ISSUE THREAD

**Issue by johndcollins** [Microsoft/AL#671] opened 2017-09-12 23:08 UTC
I'm trying to add a Global Variable to control the styleexpr of a column on my list page, but I get the following error on the page:
"The identifier 'ScheduleStatusStyle' could not be found."

On my page I have the following field:
        field("Schedule Status";"Schedule Status")
        {
          StyleExpr=ScheduleStatusStyle;
          ApplicationArea=All;
        }

At the end of the page I have this:
  trigger OnAfterGetRecord();
  begin
    ScheduleStatusStyle := GetScheduleStatusStyle("Schedule Status");
  end;

  var
    ScheduleStatusStyle : Text;
}

The page compiles ok.
This was converted from a working application, so I know the functionality works..

**Comment by StanislawStempin** [comment] 2017-09-13 09:12
It looks like we're missing automatic inclusion of that variable in the dataset.  For now you could try adding [InDataSet] attribute to ShceduleStatusStyle and we will look into the issue on our side.

**Comment by qutreson** [comment] 2017-09-15 12:47
Duplicate of #538

**Closed** 2017-09-15 12:48 UTC
Labels: duplicate
