### ISSUE TITLE
Caption deprecated with no documented replacement

### ISSUE THREAD

**Issue by drizztdourden08** [microsoft/AL#6917] opened 2022-02-02 17:49 UTC
Please include the following with each issue:

**1. Describe the bug**
I am trying very hard to to do this the right but this is very hard when documentation is so sparse and unclear.

I'm on the translation bit of an extension of a report and I'm reusing some of the code from previous work from another developer but since then, it is clear that the codebase has evolve and no longer "support" some of the code.

I'm using the new and "proper" way with .xlf file to translate but I want to translate the Caption for the column (Their respective "Label") but it seems that the "Caption" property isn't supported anymore and I get this:
`'Caption' is being deprecated in the versions: '1.0' or greater. This property does not have any effect on report columns. This warning will become an error in a future release.`

Alright, fine. I can replace this with the newer one. Problem is there is no way to find anything on how to do this in a "newer" way anywhere online. Every example I see uses this and the official documentation doesn't say it isn't suposed to be used or what to use instead.

How are we suposed to try and do it correctly when the documentation isn't updated along with the codebase itself?

**2. To Reproduce**
N/A

**3. Expected behavior**
N\A

**4. Actual behavior**
N\A
**5. Versions:**

- AL Language: 8.3
- Visual Studio Code:
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

- Business Central: 2021 release wave 2 update 1
- List of Visual Studio Code extensions that you have installed: AL and AL object designer

**Comment by thloke** [comment] 2022-02-03 06:37
The reason why it's deprecated is because it never worked at all. You have a few options for captions on columns:

1. Use `IncludeCaption = true;` to inherit the caption from the underlying table column. This will generate a new parameter in your layout that you can use. To translate this, you will need the translation key for the underlying table column.
2. Use a report label instead (`labels` section), and then that can be used in your layout. If you use the `TranslationFile` feature in your app.json, then the .xlf file will be created with the correct entry for the label.

Which approach is best depends on whether you want to just inherit the underlying table field's translations, or provide your own custom one.

**Comment by drizztdourden08** [comment] 2022-02-04 20:18
There is still something that doesn't work in this system.

I have used your recommendation and everything in "labels" isn't translated at all.

However, if it's a variable, it does get translated just fine. why  would it need to be a variable for this to happen? 

In the RDL report, I'm using the labels in the "parameters" section, why list all the labels I have. They're all appearing the the translation file just fine but can't get the translation to apply on them.

Labels code:

    labels
    {
        // Header
        lInvoice = 'INVOICE', Locked = false;
        lInvoiceNo = 'Invoice No.';

        //Bill Details
        lBillableTo = 'BILLABLE TO';
        lPayableTo = 'PAYABLE TO';
        lBillableToName = 'Payables Account';
        lPayableToName = 'Receivable Account';
        lAttentionTo = 'Attention To';


        //Bill Info
        lDocumentDate = 'Document Date';
        lPeriod = 'Period';
        lPO = 'PO';
        lMasterAgreement = 'Master Agreement';
        lPaymentMethod = 'Payment Method';

        //Lines Labels
        lConsultantName = 'Consultant Name';
        lConsultantRole = 'Role';
        lProjectName = 'Project Name';
        lProjectNumber = 'Project #';
        lCustomerPO = 'Customer PO';
        lHours = 'Hours';
        lTotalHours = 'Total Hours';
        lrate = 'Rate';
        lAmount = 'Amount';
        lDescription = 'Description';
        lQuantity = 'Quantity';
    }

I have this in the `OnAfterGetRecord()` trigger:

                //Set report language
                CurrReport.Language := Language.GetLanguageID(CustomerInfo."Language Code");

Debugging says the language is "FRA", which is my target here. I have a file generated with Nab AL Tool named "BCTest.g.fr-CA.xlf" and that contains the following (Part of it only:

      [...]
      <file datatype="xml" source-language="en-US" target-language="fr-CA" original="BCTest.g.xlf">
        <body>
          <group id="body">
            <trans-unit id="Report 2763558668 - Property 2879900210" size-unit="char" translate="yes" xml:space="preserve">
              <source>Sales - Invoice FX</source>
              <target>Ventes - Facture FX</target>
              <note from="Developer" annotates="general" priority="2"></note>
              <note from="NAB AL Tool Refresh Xlf" annotates="general" priority="3">New translation.</note>
              <note from="Xliff Generator" annotates="general" priority="3">Report DevInvoiceFX - Property Caption</note>
            </trans-unit>
            <trans-unit id="Report 2763558668 - NamedType 2491107794" size-unit="char" translate="yes" xml:space="preserve">
              <source>You must specify one or more filters to avoid accidently printing all documents.</source>
              <target>[NAB: SUGGESTION]Vous devez spécifier un ou plusieurs filtres pour éviter d'imprimer accidentellement tous les documents.</target>
              <note from="Developer" annotates="general" priority="2"></note>
              <note from="NAB AL Tool Refresh Xlf" annotates="general" priority="3">Suggested translation inserted.</note>
              <note from="Xliff Generator" annotates="general" priority="3">Report DevInvoiceFX - NamedType NoFilterSetErr</note>
            </trans-unit>
            [...]
            <trans-unit id="Report 2763558668 - ReportLabel 3025740591" size-unit="char" translate="yes" xml:space="preserve">
              <source>INVOICE</source>
              <target>FACTURE</target>
              <note from="Developer" annotates="general" priority="2"></note>
              <note from="NAB AL Tool Refresh Xlf" annotates="general" priority="3">Suggested translation inserted.</note>
              <note from="Xliff Generator" annotates="general" priority="3">Report DevInvoiceFX - ReportLabel lInvoice</note>
            </trans-unit>

original .g file:

          [...]
          <file datatype="xml" source-language="en-US" target-language="en-US" original="BCTest">
            <body>
              <group id="body">
                <trans-unit id="Report 2763558668 - Property 2879900210" size-unit="char" translate="yes" xml:space="preserve">
                  <source>Sales - Invoice FX</source>
                  <note from="Developer" annotates="general" priority="2"></note>
                  <note from="Xliff Generator" annotates="general" priority="3">Report DevInvoiceFX - Property Caption</note>
                </trans-unit>
                <trans-unit id="Report 2763558668 - NamedType 2491107794" size-unit="char" translate="yes" xml:space="preserve">
                  <source>You must specify one or more filters to avoid accidently printing all documents.</source>
                  <note from="Developer" annotates="general" priority="2"></note>
                  <note from="Xliff Generator" annotates="general" priority="3">Report DevInvoiceFX - NamedType NoFilterSetErr</note>
                </trans-unit>
                [...]
              <trans-unit id="Report 2763558668 - ReportLabel 3025740591" size-unit="char" translate="yes" xml:space="preserve">
                <source>INVOICE</source>
                <note from="Developer" annotates="general" priority="2"></note>
                <note from="Xliff Generator" annotates="general" priority="3">Report DevInvoiceFX - ReportLabel lInvoice</note>
              </trans-unit>


And part of the actual result (to make the above make sense) when I run the report, which is a custom invoice:

The first window doesn't show the report title translated:
![image](https://user-images.githubusercontent.com/36481532/152596780-9ab146e2-c2d7-468f-ad35-b85d9b32bb25.png)

The Report (invoice) itself is behaving as I described it. I added a few debugging field to ensure that the language set was the right one. My interface is set in English (Canadian one) and the customer is in fact set to French Canadian.

- The Title is not translated (Which reside in labels as shown above)
- The test variable Label is translated correctly ( I just used an error message I already had)
![image](https://user-images.githubusercontent.com/36481532/152596854-fcf57c5f-83da-47ca-a992-958c777c023c.png)

and for good measure, I checked that the language code I got was in fact the one for fr-CA (like my xlf file says)
![image](https://user-images.githubusercontent.com/36481532/152597440-9b53f047-8d14-4704-9554-32cd08f660d1.png)

Big issue (well imo) is that the second method requires every single label to have a column associated with it, and hence need to be part of the dataset. So when used in the RDL report, it is used with "First" keyword. That method doesn't make any sense to me.


What am I doing wrong here or is that by design? What's going on in the background?

**Comment by thloke** [comment] 2022-02-08 03:47
You're completely right, we're not taking into account the Report.Language when getting translations for the labels. This is a bug. What you're doing should work. I'm re-opening and accepting this with the scope of fixing the usage of Report.Language with labels.

**Comment by thloke** [comment] 2022-02-08 03:48
To set expectations, this bug is technically out of scope for this repo. I'll be passing it on to the owning team but there's a chance that they will decide to down prioritize this and not accept the bug so I can't make any promises if/when it will be fixed.

**Comment by drizztdourden08** [comment] 2022-02-08 03:51
Where should this have been? Is it part of BC itself then?

**Comment by thloke** [comment] 2022-02-08 03:57
The original issue was correctly raised here since that's about how properties of built-in objects are to be used. For the updated issue the best channel would have been through customer support or collaborate.

The rule of thumb that we use is this repo (and our team) is concerned with writing and compiling AL code, but the actual running of AL code belongs to a different team. So once it's published, it's out of our hands (usually). Of course, dev tools like debugging also fall under our umbrella.

Sometimes the lines are blurry, like in this case since translation files are generated by the compiler but actually parsed and resolved by the server and a localization bug could be either that we generated the wrong stuff, or the server is doing the wrong thing.

**Comment by drizztdourden08** [comment] 2022-02-08 04:21
Should I open a ticket with support as well to get this going? I am the Admin here and I can do that.

**Comment by thloke** [comment] 2022-02-08 04:23
I've passed the internal ticket to the owning team already, so we can go with that.

It depends on the urgency, if this is something that has to be fixed in the short term (next three months) then a ticket would be the way to go. If not, then letting it go through our usual prioritization process is better.

**Comment by thloke** [comment] 2022-03-09 09:25
I've heard back from the team that owns this, and it's not something we can support easily today and is by design. The problem is that report parameters (Labels) are localized once when the report is run. They are not considered to be per-row data. Because the setting of the language is happening on the `OnAfterGetCurrRecord` trigger, this means that this happens **after** the label has been localized and has no subsequent effect on it.

Put another way, we do not regenerate the labels per-row which we would have to do if we wanted to support this. Labels are not considered to be per-row data.

So the order of events is:

1. Report is run
2. Labels are localized
3. `OnAfterGetCurrRecord` trigger fires and sets the report language

There are some talks about making the localization of parameters more dynamic, but that is on the distant horizon and nothing immediate.

**Closed by thloke** 2022-03-09 09:25 UTC
Labels: in-progress

**Comment by drizztdourden08** [comment] 2022-03-09 12:40
What’s the point of labels if they can’t be translated? I’m not sure what people are supposed to use them for.

This is going to be a very small percentage of business that don’t have more than one language.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nhsejth** [comment] 2022-04-07 11:56
Labels are only localized per report invocation and not included in the data set that is being generated. This means that the label has the language that is effective then the report starts and not when the data item iterator runs over the records in the dataset. Normal strings calculated from tables can be used per row and are included in the data set.
To set the language before the report runs, do something like (ReportLocalLanguage is a report instance):

 ReportLocalLanguage.Language := 1031;
 ReportLocalLanguage.RunModal();

This will set the local language to DE-de and the report output will contain DE labels if they exist.
If localized text strings are to be used, it can be necessary to add a calculated column to the dataset and add the localized values from code.
