### ISSUE TITLE
isseu with VS Code 1.52.0

### ISSUE THREAD

**Issue by aalund** [microsoft/AL#6369] opened 2020-12-14 08:51 UTC
**Describe the bug**
After updateting to VS Code ver. 1.52.0 you are getting the following error:
"Couldn't find a debug adapter descriptor for debug type 'al' (extension might have failed to activate)

**To Reproduce**
update VS Code to 1.52.0 try to debug your app and you will get the error.
**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/16407224/102059570-5c4e9a80-3df1-11eb-86df-338fdedfdc1e.png)

**5. Versions:**
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18363

 - AL Language: 
3.0.299784
 - Business Central:
BC14

**Comment by dannoe** [comment] 2020-12-14 09:29
Duplicate of #6368

**Comment by pborring** [comment] 2020-12-17 11:39
Please see #6368 for update and cause. Closing this entry as a dup.

**Closed by pborring** 2020-12-17 11:39 UTC
