### ISSUE TITLE
AL0755 misleading

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#7358] opened 2023-04-04 08:32 UTC
Originally placed on [Yammer](https://www.yammer.com/dynamicsnavdev/threads/2192718532968448).

**1. Describe the bug**

> [AL0755](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/diagnostics/diagnostic-al755): The 'CustomTableName' already defines a method called 'GetRecord'. This warning will become an error in a future release.

is thrown on declaring a page function called `GetRecord`. The warning message appears even twice, once you point to the page code line. 

Other than the message says, there is no second table function with the same name. However, RecordIDs declare such a function.

Edit: I was mislead by the table vs. page name. The warning was actually meaning this method: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/page/page-getrecord-method.

**2. To Reproduce**
On an arbitrary page object, declare a public function called `GetRecord`.

**3. Expected behavior**
It would be nice if the warning could be clearer, like: 

> The 'xxx' **page** already defines an **in-built** method called 'yyyy'. This warning will become an error in a future release.

**4. Actual behavior**
See 1.

**5. Versions:**

- AL Language: 11.0.779295
- Visual Studio Code: 1.77.0

**Comment by NKarolak** [comment] 2023-04-04 11:34
The very same issue appears when you declare a page function called `Update()` (it wasn't me 😁).

`AL0755: The 'CustomPageName' already defines a method called 'Update'. This warning will become an error in a future release.`

**Comment by bjarkihall** [comment] 2023-04-07 00:12
`DataCaptionExpression` sometimes pointed to a procedure called `Caption` on our pages.
Don't know if it was intended as overloads (old code), but I think this warning is generally a good catch.
Still, I wonder how this will play out in the future - can we expect sudden errors if we have `procedure Foo` declared on a page object and MS adds a new page method called `Page.Foo`?

**Comment by JesperSchulz** [comment] 2023-04-26 08:59
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 23.0.10536.0 and VS Code Extension Version 12.0.788495. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Closed by JesperSchulz** 2023-04-26 08:59 UTC
Labels: ships-in-future-update, accepted

**Comment by blrobl** [comment] 2023-04-26 09:11
Please also note that this warning has been relaxed in the latest release, as not all built-in AL methods could lead to runtime errors when shadowing them. So in this case defining a procedure with the name GetRecord, Update or Caption will no longer throw an error.
