### ISSUE TITLE
Global Variable Issues in PageExtension

### ISSUE THREAD

**Issue by rjimenezgactive** [Microsoft/AL#2588] opened 2018-06-14 06:45 UTC
This seems bug. I want to use the global variable InvoiceDiscountPct but still throws below error.

![image](https://user-images.githubusercontent.com/40259602/41395907-9a3fc3ae-6faf-11e8-9980-f9d6be9a2995.png)

![image](https://user-images.githubusercontent.com/40259602/41395918-a5c9d8cc-6faf-11e8-82a4-32dd054ace80.png)

**Comment by atoader** [comment] 2018-06-14 07:14
Hi @rjimenezgactive ! Please search the repo for existing issues before posting a new one: https://github.com/Microsoft/AL/search?q=Global+variable&type=Issues . We've discussed this in a number of issues: #593 is more or less a duplicate of this.

**Closed** 2018-08-03 15:25 UTC
Labels: duplicate, question
