### ISSUE TITLE
Debugger only allows for one step and then stops responding

### ISSUE THREAD

**Issue by erikrijn** [microsoft/AL#7404] opened 2023-05-11 12:43 UTC
- Visual Studio Code Version: 1.78.1
- AL Extension Version:  v11.0.787898
- Server Version: 22.0.56380.0

Since a couple of days my debugger has been broken. Whenever a breakpoint is triggered, VS code allows one continue (or F5), step over (or F10) or one step into (or F11) action. After the first step, the F-keys and debugger buttons are unresponsive and the debugger freezes at that point.

Multiple colleagues have the same issue since the latest VS Code update.
It happens in all AL workspaces that are completely unrelated.

**Comment by jsc-dsacharow** [comment] 2023-05-11 14:05
Hi,
we can confirm the same issue in our Company.
We tried reinstalling VS Code, all Extensions - we even tried using the AL Language Extension Pre-Release Channel.

Debugging is not possible right now which is a huge issue!

**Comment by jorispoppe** [comment] 2023-05-11 14:23
#7388

**Comment by RichardJ70** [comment] 2023-05-11 14:37
Same here with AL Extension version v12.0.779795. Both launch and attach have the same issue.

**Comment by thloke** [comment] 2023-05-12 02:39
This is a duplicate of #7388 

The problem is on the VSCode side, so our current recommended workaround is to downgrade your version of VSCode to 1.77.

For more details on when the fix will be in the normal build of VSCode, follow this thread: https://github.com/microsoft/vscode/issues/181485

**Closed** 2023-05-12 02:39 UTC
