### ISSUE TITLE
[ControlAddin] Unable to display control dynamically

### ISSUE THREAD

**Issue by JulienDecottignies** [microsoft/AL#5130] opened 2019-07-11 13:41 UTC
Hi,

I'm trying to display a controladdin in a group of a page dynamically by setting the group Visible property with a global boolean.

The boolean is updated to true when user hits an action on the page

On both Firefox, Chrome and Edge browsers, when the action is fired, I've this error:

![image](https://user-images.githubusercontent.com/29598240/61053643-3b10a000-a3ee-11e9-94b7-cac74144d311.png)

In the logs of my containers, I have this message:
![image](https://user-images.githubusercontent.com/29598240/61053789-83c85900-a3ee-11e9-8e74-2dfe3d8ef756.png)

in the framework.js at line **4503:6036** there is :
![image](https://user-images.githubusercontent.com/29598240/61053972-e4579600-a3ee-11e9-83e6-5ea24d2735e7.png)

For this example, I just have a StartupScript that fire a controladdin trigger that does nothing:
![image](https://user-images.githubusercontent.com/29598240/61054137-254faa80-a3ef-11e9-976e-12223b92a64d.png)

Here is my usercontrol in the group of my page: 
![image](https://user-images.githubusercontent.com/29598240/61054225-50d29500-a3ef-11e9-9086-58903a915270.png)

Here is the action that updates the Visible property of my group:
![image](https://user-images.githubusercontent.com/29598240/61055651-4a91e800-a3f2-11e9-917a-52360619e24c.png)

I've also tested in private/incognito browser mode.

Thanks for any help ! 

- AL Extension Version: 3.0.145991
- Server Version: 14.1.33107.0-W1

**UPDATE**

The error occurs when my page is in this configuration:

```
group(someFields)
{
    field(FirstField; FirstField)
    {
        
    }
}

group(somePart)
{
    part(MyPart; MyPartName)
    {}
}

group(addingroup)
{
    Visible = MyBool;

    usercontrol(MyAddin; MyAddin)
    {
        ApplicationArea = All;
    }
}
```

If I put my addinGroup between someField group and somePart group, I don't have the error.

What's happenning ?

**Comment by hoovercj** [comment] 2019-08-28 11:48
@JulienDecottignies I am not able to reproduce this in our latest version. If this still reproduces for you, could you create a minimal example that repros and share the full zip with us (with minimal control add-in code, manifest, app.json, etc.)?

This is the main snippet that I tried, with some variations, but everything worked fine, so I'm hoping this was an issue that we have fixed since you first reported the bug:

```
page 50130 Bug5130Page
{
    layout
    {
        area(Content)
        {
            group(someFields)
            {
                field(FirstField; 'Some Name')
                {
                    Caption = 'Field 1';
                }
            }

            group(somePart)
            {
                part(MyPart; "Trial Balance")
                {
                }
            }

            group(addingroup)
            {
                Visible = MyBool;

                usercontrol(MyAddin; "Microsoft.Dynamics.Nav.Client.BusinessChart")
                {
                    ApplicationArea = All;
                }
            }
        }
    }

    actions
    {
        area(processing)
        {
            action(ToggleChartVisibility)
            {
                Caption = 'Toggle Chart Visibility';
                Image = "8ball";
                trigger OnAction()
                begin
                    MyBool := not MyBool;
                end;
            }
        }
    }

    var
        MyBool: Boolean;
}
```

**Comment by atoader** [comment] 2019-09-05 13:55
Closing this as no-repro

**Closed by atoader** 2019-09-05 13:55 UTC
Labels: cross-team-investigate
