### ISSUE TITLE
Cannot Publish App to Docker

### ISSUE THREAD

**Issue by JulianTillmann** [Microsoft/AL#4373] opened 2018-12-18 07:24 UTC
When I try to publish my Extension to a local docker Image (BCOnPrem), I get "Could not publish the package to the Server. See Visual Studio Code debug console for more Details" 

The debug console is empty. I found a related GitHub issued and changed to Runtime 2.0, but I still get the same error. 

Then I tried the EventLog of the docker Image, here Is the error: 

Index              : 859
EntryType          : Error
InstanceId         : 701
Message            : Server instance: NAV
                     Category: Development
                     ClientSessionId: 00000000-0000-0000-0000-000000000000
                     ClientActivityId: 2fb5bdbc-2492-4109-b9b4-7f31f3df51b9
                     ServerSessionUniqueId: cf9d74a9-9166-4a89-ad1a-456dae741181
                     ServerActivityId: 32c9699d-e5c5-403d-a415-ecdb152f661a
                     EventTime: 12/18/2018 15:45:11
                     Message Failed request -- Method:POST;
                     Url:http://bc:7049/nav/dev/apps?SchemaUpdateMode=synchronize; StatusCode:422;
                     ReasonPhrase:Unprocessable Entity; Token:
                     ProcessId: 1840
                     Tag: 00006NR
                     ThreadId: 27
                     CounterInformation:
Category           : (33)
CategoryNumber     : 33
ReplacementStrings : {Server instance: NAV
                     Category: Development
                     ClientSessionId: 00000000-0000-0000-0000-000000000000
                     ClientActivityId: 2fb5bdbc-2492-4109-b9b4-7f31f3df51b9
                     ServerSessionUniqueId: cf9d74a9-9166-4a89-ad1a-456dae741181
                     ServerActivityId: 32c9699d-e5c5-403d-a415-ecdb152f661a
                     EventTime: 12/18/2018 15:45:11
                     Message Failed request -- Method:POST;
                     Url:http://bc:7049/nav/dev/apps?SchemaUpdateMode=synchronize; StatusCode:422;
                     ReasonPhrase:Unprocessable Entity; Token:
                     ProcessId: 1840
                     Tag: 00006NR
                     ThreadId: 27
                     CounterInformation: }
Source             : MicrosoftDynamicsNavServer$NAV
TimeGenerated      : 18.12.2018 16:45:11
TimeWritten        : 18.12.2018 16:45:11
UserName           :

**Comment by JulianTillmann** [comment] 2018-12-18 09:00
It seems to be, that an already published app cannot be updated from VSCode. If I go to Docker PowerShell and Uninstall & Unpublish the app, the next time it works again. 

But why can't VSCode update the app automatically?

**Comment by thpeder** [comment] 2018-12-18 09:21
Hi @JulianTillmann,
There was a bug in the previous version of VScode (1.29.x) which had the effect that you didn't saw the errors when publishing. Update VSCode to version 1.30.x.

**Comment by JulianTillmann** [comment] 2018-12-18 09:25
I'm using 1.30

**Comment by thpeder** [comment] 2018-12-18 09:40
Then you should see the error in the Debug console.
For why you are seeing the problem is hard to say but having some good steps to reproduce the issue would help us tremendously.

**Comment by JulianTillmann** [comment] 2018-12-18 09:54
I'm still not getting any info in my debug console


I posted an update, Maybe that would help with the Repro? 
>           It seems to be, that an already published app cannot be updated from VSCode. If I go to Docker PowerShell and Uninstall & Unpublish the app, the next time it works again.
> But why can't VSCode update the app automatically?

Right now I'm experimenting with Extension dependencies, Maybe I cannont update an Extension, when a dependant Extension is already installed?

**Comment by atoader** [comment] 2018-12-19 06:46
Hi @JulianTillmann ! This seems related to #4256 . Could you try the following flow?
1. Publish version 1.0.0.0 of an extension from the command line.
2. Install the extension from the command line.
3. Try to publish version 1.0.0.0 from VScode. This will fail.
4. Increase the version to 1.0.0.1 from VSCode and try to publish again. This time it should work.

**Comment by larswestman** [comment] 2018-12-19 10:12
> I'm still not getting any info in my debug console
> 
> I posted an update, Maybe that would help with the Repro?
> 
> > ```
> >       It seems to be, that an already published app cannot be updated from VSCode. If I go to Docker PowerShell and Uninstall & Unpublish the app, the next time it works again.
> > ```
> > But why can't VSCode update the app automatically?
> 
> Right now I'm experimenting with Extension dependencies, Maybe I cannont update an Extension, when a dependant Extension is already installed?

Yes. You must uninstall the dependent extension first. Also F6 gives you more info in the debug output than what F5/ctrl+F5 currently does

**Comment by JulianTillmann** [comment] 2018-12-19 13:55
@larswestman that seems to be the solution. What does F6 mean?

**Comment by larswestman** [comment] 2018-12-19 13:57
You run the in-client designer with F6. For some reason the error messages when publishing with F5/ctrl+F5 no longer shows as they have done in the debug output. errors when publishing with F6 still does though.

So use F5 och ctrl+F5 but if you get an error press F6 to see the error message

**Comment by atoader** [comment] 2018-12-19 16:58
There is a new feature in VSCode that pops up multiple Debug windows and hides the output of the latest publish with F5. We have another bug tracking this problem and we hope to get it resolved soon. @JulianTillmann can I close this issue?

**Comment by JulianTillmann** [comment] 2018-12-20 06:08
Thanks for the info, that's good to know. 

I think this Case can be closed, but I'm not sure if that was the only Problem. The whole VSCode-AL-Docker-Thing seems still a bit beta-testy ;-)

**Comment by atoader** [comment] 2018-12-20 15:31
Like all software, it can be improved, and we are working hard on doing so :)

**Closed by atoader** 2018-12-20 15:31 UTC
Labels: input-needed
