### ISSUE TITLE
Incorrectly referenced AS0011 from AppSourceCop

### ISSUE THREAD

**Issue by rdebath** [microsoft/AL#4610] opened 2019-02-14 13:59 UTC
**Describe the bug**

Location of error is incorrect; pointing at a file that does _not_ contain MS/AL code.
(This appears to be the default location as noted in #4588)
Error message itself is not correct (AIUI).

Fields are not part of the extension, this is moving existing fields.

**To Reproduce**

    $ grep CreditTransferRegEntries */*                                                                                                                                                                        
    src/Modification-Payment_Journal_Page_256.al:        moveafter(TransmitPayments;CreditTransferRegEntries)

    $ grep Purch..FA */*                                                                                                                                                                                        
    src/Modification-General_Posting_Setup_Page_314.al:        moveafter("Direct Cost Applied Account";"Purch. FA Disc. Account")                                                                             
    src/Modification-General_Posting_Setup_Page_314.al:        moveafter("Purch. FA Disc. Account";"Purchase Variance Account")

    $ grep Purchase.Variance  */*                                                                                                                                                                               
    src/Modification-General_Posting_Setup_Page_314.al:        moveafter("Purch. FA Disc. Account";"Purchase Variance Account")

**Expected behavior**
A clear and concise description of the error and it's location (if any). 

**Screenshots**
![image](https://user-images.githubusercontent.com/5853223/52790540-bb5cf000-305e-11e9-90b6-62bdd0b4af46.png)

**Versions:**
Name: AL Language
Id: microsoft.al
Description: AL development tools for Dynamics 365 Business Central
Version: 2.1.86206
Publisher: Microsoft

**Comment by JohanStenberg100** [comment] 2019-02-18 10:34
Hi @rdebath, thanks for reporting this issue.

I can't reproduce this however, here's the example I use:

```
pageextension 50100 MyExtension extends "Payment Journal"
{
    layout
    {
    }

    actions
    {
        moveafter(TransmitPayments; CreditTransferRegEntries)
    }
}
```

Can you please post a small AL sample? I have activated `CodeCop` and `AppSourceCop`.

Thanks,

Johan

**Comment by rdebath** [comment] 2019-02-18 13:12
Small repo with all the binaries uploaded to https://github.com/rdebath/ALHelloWorld


Name: AL Language
Id: microsoft.al
Description: AL development tools for Dynamics 365 Business Central
Version: **2.1.91153**
Publisher: Microsoft

**Comment by qutreson** [comment] 2019-06-05 19:27
Hi @rdebath, this issue can still be reproduced with the latest extension from our marketplace but has been fixed in our master branch.

**Closed by qutreson** 2019-06-05 19:27 UTC
Labels: input-needed
