### ISSUE TITLE
Target not respected when using runtime package built for 17.2 running on 17.3

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#6451] opened 2021-02-04 09:10 UTC
**Describe the bug**
I found a bug with Continia Document Capture, and they believe it is caused by a runtime package built against BC 17.2 being run on BC 17.3, as it seems not to occur on BC 17.2. Thus, I am posting here in case this is a general and unknown issue with runtime app use.

I haven't retested personally but trust Continia probably know what they're talking about!

**To Reproduce**
Opening the Document Capture Setup card and clicking the action Related > About brings up an Error() window with the following text:

> You cannot make this call on table ID 2000000040 from a RecordRef data type when you are using a compilation target other than OnPrem."

The stack trace from "View the last known error" is:
```none
"CSC Onprem Licn. Mgt."(CodeUnit 6192854).GetLicenseeInfo line 12 - Continia Core by Continia Software
"CSC Core Mgt."(CodeUnit 6192832).GetLicenseeInfo line 12 - Continia Core by Continia Software
"CSC Core"(CodeUnit 6192833).GetLicenseeInfo line 5 - Continia Core by Continia Software
"CDC License Mgt. Subscr."(CodeUnit 6085861).OnGetLicenseeInfo line 4 - Continia Document Capture 365 by Continia Software
"CDC Continia License Mgt."(CodeUnit 6192771).OnGetLicenseeInfo line 2 - Continia Document Capture 365 by Continia Software
"CDC Continia License Mgt."(CodeUnit 6192771).LicenseeInfo line 2 - Continia Document Capture 365 by Continia Software
"CDC About Document Capture"(Page 6085605).OnOpenPage(Trigger) line 2 - Continia Document Capture 365 by Continia Software
```

I have also seen errors in the Event Viewer, during normal usage, not reported via GUI:

> Message Cloud -> OnPremise call security violation. Caller App=Continia Document Capture 365 by Continia Software 6.5.2.0 Func=OnRun, Callee App=Base Application by Microsoft 17.3.20469.20605 Func=OnAfterSalesHeaderDelete

> Message Cloud -> OnPremise call security violation. Caller App=Continia Document Capture 365 by Continia Software 6.5.2.0 Func=OnRun, Callee App=Base Application by Microsoft 17.3.20469.20605 Func=SetCRMSalesOrderIdOnSalesHeaderDeletion

> Message Cloud -> OnPremise call security violation. Caller App=Continia Document Capture 365 by Continia Software 6.5.2.0 Func=OnRun, Callee App=Base Application by Microsoft 17.3.20469.20605 Func=RemoveCouplingToCRMSalesOrderOnSalesHeaderDelete

a Continia developer said:
> I have just tested in my own environment and there seems to be an issue when using runtime packages. 
> DC 6.50.2 has been build for BC17.2, but if you install the app on a BC 17.3 then the target is not respected and then you get the error.

**Expected behavior**
No error / no difference in behaviour whether the runtime package is run on 17.2 or 17.3

**5. Versions:**
 - AL Language: n/a
 - Business Central: GB Business Central 17.3 (Platform 17.0.20458.20517 + Application 17.3.20469.20605)

**Comment by sdelikostov** [comment] 2021-02-10 13:33
I have same problem when trying to change a Customer record using RecordRef. When I am changing the customer manual, I don't have problems.
The error is:
Cloud -> OnPremise call security violation. Caller App=XXX by ZZZ 17.0.0.1 Func=CreateTableRecord, Callee App=Base Application by Microsoft 17.3.20469.20605 Func=RunWorkflowOnCustomerChanged

Application 17.3.20469.20605

**Comment by kalberes** [comment] 2021-02-13 11:21
The event viewer issue is just noise for now and will be removed in the 17.5 release. The runtime package issue needs to be investigated. I guess it was compiled OnPrem and then it is a bug. Else it is not.

**Comment by sdelikostov** [comment] 2021-02-14 13:09
Hello again,

I think, I found my problem - service was 17.2, but the database is 17.3.
I upgraded the service to 17.3 and now I don't have this issue.

**Comment by kalberes** [comment] 2021-02-16 09:13
Ok then I close the issue.

**Closed by kalberes** 2021-02-16 09:13 UTC

**Comment by dtkb** [comment] 2021-02-16 09:14
Closing my issue based on a report from someone else, which I don't think applies to my situation and I haven't verified yet in any case... seems wrong to me.

**Comment by kalberes** [comment] 2021-02-16 13:43
I have not seen any bugs. Runtime packages have to follow the runtime. By design.
