### ISSUE TITLE
Publish unsigned code

### ISSUE THREAD

**Issue by IvoMol** [Microsoft/AL#92] opened 2017-02-03 13:59 UTC
Write own code and successfully create package "Job Team". But publish code (F5) freezes.
If I try publish this package manually, there is error: 
Publish-NAVApp : You cannot publish an extension that has not been code signed. To overrule this check and publish the unsigned extension, set the –SkipVerification parameter.
If I add this parameter, package is published and can be installed.

![publish](https://cloud.githubusercontent.com/assets/17826638/22593692/bc84d3a6-ea17-11e6-94c1-296d16cd130b.JPG)

**Comment by StanislawStempin** [comment] 2017-02-08 09:33
This is an issue between VS Code 1.9.0 and the AL extension. Please try installing the VS Code 1.8.1 version:
https://vscode-update.azurewebsites.net/1.8.1/win32/stable

The issue is fixed with the coming February Update.

**Comment by IvoMol** [comment] 2017-02-08 09:46
I can confirm that with VS Code version 1.8.1 publishing (F5) works OK.
Thank you!

**Closed** 2017-02-08 09:47 UTC
Labels: bug, ships-in-next-update

**Comment by waldo1001** [comment] 2017-02-08 10:46
Me too ...
