### ISSUE TITLE
report extension RequestFilterFields compile/deploy but are not used

### ISSUE THREAD

**Issue by db-bc** [microsoft/AL#6704] opened 2021-07-13 13:57 UTC
This code adding/changing `RequestFilterFields`:

```al
reportextension 66666 SVP extends "Suggest Vendor Payments"
{
    dataset
    {
        modify(Vendor)
        {
            RequestFilterFields = "No.", Name, "Name 2", "Search Name", "Payment Method Code", "Payment Terms Code";
        }
    }
}
```

used to not deploy (to BC 18.2 iirc) with an error that the feature was not supported.

Now it *does* deploy without complaints, **but** the property is ignored; the standard filters are shown...

![image](https://user-images.githubusercontent.com/63455896/125464345-5fdf2143-55de-4fe5-af74-1c9625b52fb5.png)

Please fix the property so that we can actually amend what filters are offered by default. Ta!

* AL: 7.3.486497
* BC: GB Business Central 18.3 (Platform 18.0.27224.27770 + Application 18.3.27240.27859)

**Comment by thloke** [comment] 2021-07-13 23:51
This (along with CalcFields) is supported in BC 19.0 onwards, so the next major release. I'll mark this as a bug, but only to restrict its usage when targeting 18.x releases.

**Comment by thloke** [comment] 2021-07-22 02:17
Walking back my previous comment, I'm backporting support for this to 18.x. Since it requires an update on the server, this will only work on the next 18.x CU.

**Comment by db-bc** [comment] 2021-07-26 14:59
Thanks. Is that only `RequestFilterFields`, or also `CalcFields` as you additionally mentioned?

**Comment by thloke** [comment] 2021-07-26 23:57
Both `RequestFilterFields` and `CalcFields` will have modify support in the upcoming CU. Both of these will work additively (i.e. in addition to any specified on the base DataItem, as opposed to overwriting).

**Comment by db-bc** [comment] 2021-07-27 09:12
Brilliant, thanks! I had meant to ask whether they were additive too, presumed they would be, but appreciate the confirmation!

**Comment by thloke** [comment] 2021-08-05 07:57
I can confirm that support for this is going into the 18.4 release. Closing the issue.

**Closed by thloke** 2021-08-05 07:57 UTC
Labels: bug, in-progress
