### ISSUE TITLE
AA0181 rule warning for Codeunit.Find method

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/AL#7731] opened 2024-04-25 12:36 UTC
There is a codeunit with `Find(var RecordVariable: Record SomeRecord): Boolean` method defined in my code.
When I use it like
```al
if CodeunitVariable.Find(RecordVariable) then;
```
or
```al
CodeunitVariable.Find(RecordVariable)
```
I am getting _warning AA0181: The FindSet() or Find() method on the record 'SomeRecord' must be used only in connection with the Next() method_.

**Note:** If the call is repeated on multiple lines, the warning appears only on the last line of code.

Maybe there is a relation to #7459.

**Versions:**

- AL Language: v13.0.971907
- Visual Studio Code: 1.88.1

Internal work item: [AB#534244](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534244)

**Comment by EmilDamsbo** [comment] 2024-04-26 09:20
I think the issue is lacking come context for what is the issue. According to [the public documentation about this analyzer rule](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0181#reason-for-the-rule), the scenario sounds like it is by design. Can you provide further details on 
1. What behaviour your were not expecting
2. What you _were_ expecting,
3. A code snippet with proper context

**Comment by NKarolak** [comment] 2024-04-26 09:27
@EmilDamsbo
I was mistaken on first read as well, but: The rule should warn for `Record.Find` only. But it also gives false positives on `Codeunit.Find`, whereas `Find` in the latter case is a custom procedure, not the AL method.

**Comment by EmilDamsbo** [comment] 2024-05-01 11:30
Thanks both, I misread the original issue. Seems this has been correctly tagged now

**Comment by sergiusignacius** [comment] 2024-05-07 07:55
It does seem like we're incorrectly emitting AA0181 on signatures that resemble the `.Find` method on records.  

Here's a repro:

```
codeunit 50109 MyCodeunitA
{
    procedure Find(rec: Record Customer): Boolean
    begin
        exit(true);
    end;
}


codeunit 50110 MyCodeunitB
{

    procedure Test(cu: Codeunit MyCodeunitA; r: Record Customer)
    begin
        if cu.Find(r) then
            Message('Found');
    end;
}
```

AA0181 is emitted on `cu.Find(r)`. Approving the bug. Thank you for reporting it!

**Comment by JesperSchulz** [comment] 2024-06-07 09:59
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 25.0.20197.0 and VS Code Extension Version 14.0.1032641. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Closed by JesperSchulz** 2024-06-07 09:59 UTC
Labels: ships-in-future-update, CodeCop, accepted
