### ISSUE TITLE
Debugger stops at first breakpoint and wont move on in VSCode 1.78

### ISSUE THREAD

**Issue by cosmo-skol** [microsoft/AL#7388] opened 2023-05-04 08:09 UTC
1. Describe the bug

Debugger stops at the first breakpoint, but does not allow further navigation within the code. 
The debugger does not accept any commands to move on:
- Step over next line (F10)
- Go to next line (F11)
- Go to next breakpoint (F5) 

2. To Reproduce

- Update to VSCode version 1.78
- Set breakpoint in AL code. 
- Start debugging to breakpoint. 
- Try to move the debugger to another line of code

3. Expected behavior

Should be able to debug further. In VSCode version 1.77.3 this was still possible, a downgrade fixes this behavior.

4. Actual behavior

Debugger stops at breakpoint and wont move on

5. Versions:

AL Language: 11.0.787898
Visual Studio Code: 1.78.

**Comment by nndobrev** [comment] 2023-05-04 11:59
Hi, thanks for logging the issue. We also discovered it internally and we are already looking at it and what we should do from our end. Note there is also an issue opened on the vscode side: https://github.com/microsoft/vscode/issues/181485

**Comment by nzcraig** [comment] 2023-05-05 03:57
Also have same issue.
VS Code 1.78

**Comment by smorv** [comment] 2023-05-08 06:10
I have the same issue. 
VS Code 1.78

**Comment by tmajvdlaan** [comment] 2023-05-08 06:31
I'm experiencing the same!

**Comment by stefaanMLB** [comment] 2023-05-08 12:02
Same here

**Comment by christianbraeunlich** [comment] 2023-05-08 13:08
+1

**Comment by RodionLobuzov** [comment] 2023-05-08 13:14
+1

**Comment by minaskats** [comment] 2023-05-08 13:51
+1

**Comment by DanielGoehler** [comment] 2023-05-09 06:46
+1

**Comment by JellebBE** [comment] 2023-05-09 06:55
Same issue

**Comment by JurgenVh** [comment] 2023-05-09 07:05
Same issue

**Comment by GhOnBc** [comment] 2023-05-09 09:25
same issue

**Comment by jwikman** [comment] 2023-05-09 09:45
Hey all, 

You can stop reporting +1 on this issue :)

The root cause seems to have been identified and will be fixed in VSCode. See https://github.com/microsoft/vscode/issues/181485 for details.

Workaround for now is to use v1.77.3. Just remember to disable the auto-update of VSCode by adding this to your settings: `"update.mode": "manual"`

**Closed** 2023-05-10 07:55 UTC
Labels: ships-in-future-update, debugger, accepted

**Comment by fartwhif** [comment] 2023-07-17 17:18
> Hey all,
> 
> You can stop reporting +1 on this issue :)
> 
> The root cause seems to have been identified and will be fixed in VSCode. See [microsoft/vscode#181485](https://github.com/microsoft/vscode/issues/181485) for details.
> 
> Workaround for now is to use v1.77.3. Just remember to disable the auto-update of VSCode by adding this to your settings: `"update.mode": "manual"`

in [microsoft/vscode#181485] Neoster is talking about 1.78.2,  debugging remains broken with that version, for me.  the only permutation that worked for me was installing v1.77.3 and getting the latest stable AL extension.

**Comment by NKarolak** [comment] 2023-07-18 06:12
@fartwhif Closed issues are no longer tracked by Microsoft. Regarding your break point issue, please create a new issue.

**Comment by fartwhif** [comment] 2023-07-18 19:32
I scoured the open issues and didn't find it, but found this one, I didn't realize it was closed.  It shouldn't be closed.  Since it's wrongfully closed and there are new recent replacements that aren't closed you can be reassured that spamming the issue won't help.  I wish you and the rest of the AL dev pioneers the best.

**Comment by atulljoshi** [comment] 2025-05-13 16:04
I am facing the similar issue. I am using VSCode under codespaces. I am writing some RISC-V assembly code which i am debugging using gdb integrated with vscode. . I am able to put breakpoint at the first instruction, but it never stops there. When i set "stopAtConnect":true, it does stop at entry but when i try to step in, debugger go haywire. If i tru to debug using standalone gdb, i don't observe this issue.

VSCode version being used in codesapces is 1.100.0
