### ISSUE TITLE
Code Analyzer bug due comment: The 'end' keyword should always start a line

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#2826] opened 2018-07-09 09:34 UTC
Hi,

The default Code Analyzer contains a bug when we add comment after the latest code line within a function

![image](https://user-images.githubusercontent.com/28626283/42442576-52c8be2a-836b-11e8-9609-a9a5e2ebb965.png)

```
codeunit 11239107 "Test Codeunit"
{
    trigger OnRun()
    begin
    end;

    local procedure Function1()
    var
    begin
        Message('a'); // Test
    end;

    local procedure Function2()
    var
    begin
        Message('a');
    end;
}
```

**Comment by qutreson** [comment] 2018-07-09 11:48
Closing as duplicate of #1901. The bug is fixed in newer versions of the extension.

**Closed by qutreson** 2018-07-09 11:48 UTC
