### ISSUE TITLE
Import NAVxData

### ISSUE THREAD

**Issue by stefanoPrimo** [microsoft/AL#5439] opened 2019-11-11 12:04 UTC
**Describe the bug**
Before adding a few fields (without any breaking changes), the import of my navxdata was fine.
Now after I add these two boolean fields the Install codeunit does not work anymore, I even cannot install the extension. It returns always this error:
```[2019-11-11` 12:55:14.79] The request for path /np_BC140/dev/apps?SchemaUpdateMode=recreate&DependencyPublishingOption=default failed with code 422. Reason: Could not install the extension Transport Costs on tenant default due to the following error: Unable to read beyond the end of the stream.```

If I comment all the install codeunit it will works as usual, but with no data in it. 

**To Reproduce**

**Expected behavior**
I've added 2 boolean fields with the default value, they are not in the PK, it has to work

**Screenshots**

**5. Versions:**

 - AL Language: 
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 4.0.198182
Publisher: Microsoft

 - Business Central:
Business Central 140: Version 14.0.35916.0

**Comment by atoader** [comment] 2019-11-11 12:09
Hi @stefanoPrimo ! Does this issue reproduce on the 2019 Wave 2 release?
If it does, could you please provide a sample extension that reproduces this issue and the exact steps to reproduce the problem? If it doesn't, you will have to go through our standard support channel to get the issue fixed on 14.

**Comment by stefanoPrimo** [comment] 2019-11-11 13:31
Hi @atoader  !
I've tried with BC 2019 Wave 2.
Originally the app works only with BC14 so I had to delete some codeunit in order to have a compilable app. 
Unfortunately, also in BC15 the publish failed, now with this error:

`[2019-11-11 14:28:06.76] The request for path /BC150IT/dev/apps?SchemaUpdateMode=recreate&DependencyPublishingOption=default failed with code 422. Reason: Could not install the extension Transport Costs on tenant default due to the following error: Decimal byte array constructor requires an array of length four containing valid decimal bytes.`

Any Ideas ?

**Comment by atoader** [comment] 2019-11-11 14:05
It appears your install code is running and it is encountering an exception. ```Decimal byte array constructor requires an array of length four containing valid decimal byte``` this part of the error message is coming from your code. I don't think this issue is coming from the platform, but if you can post a sample that reproduces it, we can investigate it some more.

**Comment by atoader** [comment] 2019-11-24 18:50
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Closed by atoader** 2019-11-24 18:50 UTC
Labels: input-needed
