### ISSUE TITLE
Analysis rule AW0006 should not give warning in case UsageCategory is set to None

### ISSUE THREAD

**Issue by daansaveyn** [microsoft/AL#4677] opened 2019-03-04 16:35 UTC
I believe this warning not give a warning in case the UsageCategory property is set to None.

**Comment by fvet** [comment] 2019-03-05 08:07
In case we set UsageCategory to 'None', we explicitly tell the page should not be listed in the search results. This makes the AW00006 rule (to set the ApplicationArea) no longer applicable for this scenario.
`
Page 2060202 "NVT Alert User Group Members"
{
    Caption = 'User Group Members';
    DelayedInsert = true;
    PageType = List;
    PopulateAllFields = true;
    SourceTable = "Alert User Groups Members";
    UsageCategory = None;
`

**Comment by GreatScott000** [comment] 2020-04-22 09:33
Any word on if/when this will be corrected?

**Comment by atoader** [comment] 2020-05-06 05:29
Hi! It is on our backlog, but I cannot provide an ETA. Once the issue is picked up, it will be marked as in-progress and a milestone will be attributed.

**Comment by dtkb** [comment] 2021-01-20 17:13
Isn't this done already?

**Comment by atoader** [comment] 2021-01-20 17:25
Thanks @dtkb ! Looking at the code, it appears that this was fixed. I'll close the issue

**Closed by atoader** 2021-01-20 17:25 UTC
Labels: UICop, bug, static-code-analysis
