### ISSUE TITLE
MS Dynamics NAV Extensions TableRelation property issue

### ISSUE THREAD

**Issue by linasostreika** [Microsoft/AL#2267] opened 2018-05-16 11:23 UTC
Hello,

I have got an issue with TableRelation property. I am using CU05 AL Language extensions and NAV 2018 CU05W1.  I have created new table and field has relation to another table.
<img width="335" alt="ext_bug" src="https://user-images.githubusercontent.com/39334704/40113959-ce43d9fe-5913-11e8-8702-3c574579e954.PNG">
Relation works until WHERE, when I lookup field it returns me all units (does not matter if building true or false). Building field type - boolean. Another interesting thing that, when i click  ctrl+space  inside the brackets after WHERE system offers me options to choose form the table i am creating not from the related table. Does anyone have similar problems and can help?

**Comment by thpeder** [comment] 2018-05-16 13:29
Hi @linasostreika,
The intellisense was fixed in #1981 and the other part of it is also fixed in the latest developer preview.
Please contact support for getting it backported.

**Comment by linasostreika** [comment] 2018-05-17 04:59
Hi @thpeder 
Which developer preview? The latest is for March right? And I can not find anything related to this issue there.

**Comment by thpeder** [comment] 2018-05-17 07:49
Sorry @linasostreika I got the dates mixed up, but it will be there in the next developer preview.

**Comment by linasostreika** [comment] 2018-05-17 11:27
Thanks @thpeder  I look forward to it.

**Comment by linasostreika** [comment] 2018-05-30 04:35
Hi @thpeder , new developer preview is already released, but i can not find this problem solution in there?

**Comment by thpeder** [comment] 2018-05-30 13:15
Could you provide a small example of the bug since I can't reproduce it.

**Comment by linasostreika** [comment] 2018-05-30 13:42
@thpeder what do you mean small example? You need object files or anything else?

**Comment by thpeder** [comment] 2018-05-30 14:08
I mean I don't want your entire app, but if you could distill it down to the essential part so it is easy for me to reproduce it.

**Comment by linasostreika** [comment] 2018-05-31 06:19
Hi @thpeder, can you drop me your personal contact? I will send you my sandbox files.

**Comment by thpeder** [comment] 2018-05-31 08:33
What is the version of the server are you running?
The fix is released for the developer preview but it might not have been backported to any CU to Nav2018.

**Comment by linasostreika** [comment] 2018-06-01 05:01
I am using NAV2018 CU05.

**Comment by thpeder** [comment] 2018-06-01 09:09
I have just tried to repro your bug on CU5 with success and then I tried on our branch for the next CU and it was working as expected.
So the bug has been fixed and is coming in the next CU.

**Comment by linasostreika** [comment] 2018-06-01 09:16
@thpeder  Thanks

**Closed** 2018-06-01 09:27 UTC
Labels: customer-support
