### ISSUE TITLE
Worksheets opened from Departments should open in a new window

### ISSUE THREAD

**Issue by larswestman** [microsoft/AL#4067] opened 2018-10-17 12:26 UTC
A page with PageType = Worksheet should open in a new window when opened from the departments menu. That's how the same page built in c/side behave. The AL-version looks quite strange until you klick on the refresh button to the right in the address bar. Then suddenly it opens up in a new window and looks fine.

"platform": "13.0.0.0",
"application": "13.0.24623.0",
AL Extension: 2.0.48254

This is the wrong layout:
![wrong layout](https://user-images.githubusercontent.com/43792551/47151795-00ecf480-d2db-11e8-9487-a90541bcf1ae.jpg)

Here's how it looks when opened in a new window:
![correct layout](https://user-images.githubusercontent.com/43792551/47151796-00ecf480-d2db-11e8-8079-e77a367e3696.jpg)

And here's the code involved:
![code](https://user-images.githubusercontent.com/43792551/47151981-a30cdc80-d2db-11e8-8257-af3dd9046c8c.jpg)

It seems as it's the control StatusFilter that's causing the problem.

**Comment by atoader** [comment] 2021-04-13 16:59
I am closing this issue because it is no longer within the scope of this repository.  If additional action is needed, please open a support case.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Closed by atoader** 2021-04-13 16:59 UTC
Labels: al-core-compiler, bug
