### ISSUE TITLE
Code 422: Sorry, we have just updated this page. Reopen it and try again.

### ISSUE THREAD

**Issue by jpagessummar** [Microsoft/AL#3875] opened 2018-09-27 07:28 UTC
[2018-09-27 09:03:55.85] The request for path /v1.0/sandbox/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: No se pudo instalar la extensión SUMMAR para el suscriptor msweua3554t53488933 debido al error siguiente: Lo siento, acabamos de actualizar esta página. Vuélvala a abrir e inténtelo de nuevo. (Translated) The SUMMAR extension for the subscriber msweua3554t53488933 could not be installed due to the following error: Sorry, we have just updated this page. Reopen it and try again.

This happens in CU type Install, when you use Transferfields or record.Copy

- AL Extension Version: 0.16.19969
- Server Version: ES Dynamics NAV 12.3 (23918)

**Comment by jpagessummar** [comment] 2018-10-03 10:20
This also happen in anywhere you use the Transferfields or record.Copy

AL Extension Version: 2.0.48254
Server Version: ES Dynamics NAV 12.3 (23918) - Sandbox

![image](https://user-images.githubusercontent.com/42030465/46404731-54b9e400-c706-11e8-9adb-46c0057d9810.png)

**Comment by zuhadmahmood** [comment] 2018-11-20 10:00
Hi I am facing the similar issue  **Sorry, we just updated this page. Reopen it, and try again.**   while running preview post on sales or purchase invoices from my AL extension .

-System Version US Dynamics NAV 13.0 (25432) - Sandbox 

Thanks.

**Comment by jehelles** [comment] 2018-11-22 15:19
Hi @jpagessummar,

I am trying to fix the issue, but I cannot reproduce it here. You say that using TransferFields or record.copy anywhere triggers the issue, could you provide a minimal example extension that exhibits the problem? Just paste the .al file(s) here.

**Comment by jpagessummar** [comment] 2018-11-23 11:07
The error I'am receiving right now is:
    "Visual Studio Code: Could not publish the package to the server. See Visual Studio Code debug console for more details."

And the debug console says 
    "The package has been published to the server."

codeunit 70116815 "SMR InstallExtension"
{
    Subtype = Install;
    trigger OnInstallAppPerCompany();
    var
        GLaccH: Record "G/L Account";
        GLacc: Record "G/L Account";
        AccNo: Label '4750001'; //Put here an account that doesn't exist but do exist its head
    begin
        if not GLacc.Get(AccNo) then begin
            if not GLaccH.get(copystr(AccNo, 1, 5)) then
                if not GLaccH.get(copystr(AccNo, 1, 4)) then
                    if not GLaccH.get(copystr(AccNo, 1, 3)) then
                        error('The heading account for %1 does not exist.', AccNo);
            GLacc.TransferFields(GLaccH);
            GLacc."No." := AccNo;
            GLacc.insert(true); // without true it also fails
        end;
    end;
}

Thanks

**Comment by jpagessummar** [comment] 2018-11-23 11:14
The same error ocurrs if you use GLacc.Copy(GLaccH) instead of GLacc.TransferFields(GLaccH)

**Comment by zuhadmahmood** [comment] 2018-12-10 13:05
not sure if this can help you to identify the issue but today i got the same error while changing global dimensions using the standard process. 

![image](https://user-images.githubusercontent.com/15164880/49734385-e9603580-fca5-11e8-8dc0-98f0b1e11188.png)

**Comment by jehelles** [comment] 2019-01-04 14:44
First some background on this error message: You will get this message if you have stale Record reference. For example, if you do the following:

```
GLAcc1.get('xyz')
GLAcc2.get('xyz')
GLAcc2."Description" := 'Desc 2';
GLAcc2.modify;
GLAcc1."Description" := 'Desc 1';
GLAcc1.modify;
```
When the last modify is attempted, the platform will detect that you are trying to modify a record that someone else (in this case the "someone else" is actually our self using another record reference to the same row in the database) modifying while you where working on it, and give you the error you encountered. This is to avoid the modifications on GLAcc1 accidentally overwriting the changes done on GLAcc2.

This means that many different kinds of errors can give you the same error message, and therefore I don't think your issue @zuhadmahmood is related to the issue in this ticket. You can also see this error in cases where it is not related to programming errors, for example if two users are opening the same customer and editing it at the same time.

Back to the issue in the ticket: I have tried to create an extension that only has the code you include, but I cannot reproduce it here. I have account 3120, so I used account 3120001, and it created the new account without issues.

My guess is that you have a trigger somewhere, either in your extension, another extension or in the base application that does something on insert of G/L accounts. You can try to get to the root cause by trying without any other extensions, and only the code you included in this issue. If that stills fails, you can try first to remove the TransferFields completely, and try to remove the Insert.

If all these fails to uncover the root cause, I will suggest you contact support, then they can help gather all the information we need to solve this.

**Comment by jpagessummar** [comment] 2019-01-07 09:53
Hello
I've tested exactly the same code I sent on 23 Nov 2018 and now is working fine.
Thanks

AL Extension Version: 2.1.69331
Server Version: ES Dynamics NAV 13.1 (26678)

**Comment by NKarolak** [comment] 2019-01-11 10:34
Just in case you are struggling to find the wrong code; in addition to jehelles's snippet you should also watch out for something like this (simplified):

```
...
YourRec1.INSERT;
YourRec1.TRANSFERFIELDS(YourRec2); // YourRec2 has the same PK as Rec1
YourRec1.MODIFY; // <-- ERROR
```

Solution:

```
...
YourRec1.INSERT;
YourRec2 := YourRec1;
YourRec1.TRANSFERFIELDS(YourRec2,FALSE);
YourRec1.MODIFY;
```

**Comment by jehelles** [comment] 2019-01-11 10:37
Thanks for additional input @NKarolak!

Since everything is working now, I will close this issue.

**Closed by jehelles** 2019-01-11 10:37 UTC
Labels: cross-team-investigate
