### ISSUE TITLE
The RDLC reports printout is blank in version Microsoft_Application_13.0.24234.0 and Microsoft_System_13.0.12929.0

### ISSUE THREAD

**Issue by navlarste** [Microsoft/AL#3534] opened 2018-08-31 16:44 UTC
Reports in an Extension 

All my report s worked fine in version Microsoft_Application_12.2.23097.0 and Microsoft_System_12.0.12928.0

After upgrade to version Microsoft_Application_13.0.24234.0 and Microsoft_System_13.0.12929.0 all my reports is blank nothing is printed (looks the same as you don’t have any RDLC)

**Comment by dennisfrostlander** [comment] 2018-09-03 12:50
The issue has been fixed in starting from the image bcinsider.azurecr.io/bcsandbox-master:13.0.24239.0

Please remember to update the AL extension to version al-2.0.41872.vsix, since the root cause was in the .app packaging code.

**Closed** 2018-10-15 11:49 UTC
Labels: bug, shipped
