### ISSUE TITLE
"Older" Demand from Production Forecast being left behind 

### ISSUE THREAD

**Issue by CarlMachamer** [Microsoft/AL#1745] opened 2018-03-06 17:21 UTC
Scenario:

1. Enter Production Forecast entries for an item on 01/18/19 and 01/24/19 for 100 PCS each day
2. Run the planning worksheets "Calc. Regenerative Plan"
3. Set the start date to 01/25/19
4. Set ignore Forecasts Before to 01/01/19
5. Use forecast is set to 2019

Codeunit 99000854, CheckForecastExist function uses ExcludeForecastBefore variable which would include the forecast entry dated 01/18/19 but then it does a Find('+') which will result in it always finding the last one closest to the "Start Date", in this case the 01/24/19 entry.  Any other entries from the last entry before the start date are also left behind.  The code never resets the filters on Forecast Entry or a findfirst back up where it sets ForecasetExist := CheckForecasetExist() and before it starts repeating through.  It doesn't seem like the intention is to leave that demand behind since it's finding past demand closest to the start date.  Can you verify?  If it shouldn't be, clearing the forecastentry.forecast date with a findfirst right after ForecastExist := CheckForecastExist(ForecastEntry,OrderDate,ToDate); seems to resolve it.

**Comment by JesperSchulz** [comment] 2018-03-15 12:21
Thank you very much for reporting this issue! I forwarded your issue to one of our program managers, to shed some light on the expected behavior. Below is the reply. Please reply if this explains the behavior you have noticed.

---------PM REPLY---------

Result/Expected result is missing.

The forecast doesn't contain type of period. Type of period is used for data entry only.
This allows to have different period type in one forecast (user can enter forecasted values monthly, but before Christmas user can enter forecasted values daily).
There is no "ending date" for period, so system calculates periods:
Find first record. This record represents beginning of period and forecasted qty.
Find next record - (don't remember, but it probably does -1D) this is end of period.
Continue to the end.
For the last record - end of period will be "31129999"

In provided scenario user wants to plan demand for 01/25/19 till (let's say 01/31/19).
System tries to find all forecast periods that affects the requested period.
One of steps is to find forecasted periods that started before starting date and didn't finish. That's why is uses FIND(+), which finds record on 01/24/2019. 
This record considered as "demand of 100 pcs in period from 01/24/19..12/31/9999".

The records 01/18/19 till 01/23/19 are ignored, as they represent passed periods and we don't care if demand happened that time or not, as soon as they don't affect requested period (01/25/19..??)
The "Ignore Forecast Before" excludes forecasts records that started before specified date and didn't finish. So if you had forecast line on 010118 with 100000000 pcs and nothing after (means - nothing entered on step 1 of scenario) this 100000000 will be used for planning, unless user Set ignore Forecasts Before to 01/01/19.

**Comment by CarlMachamer** [comment] 2018-03-16 14:34
Hi, thanks for the reply!

The ending date isn't the issue here, it's what the system calculates as the starting date.

"Find first record. This record represents beginning of period and forecasted qty." Yes, and findfirst should be reused again before it repeats through the forecast entries and then it will pickup past entries.

"One of steps is to find forecasted periods that started before starting date and didn't finish. That's why is uses FIND(+), which finds record on 01/24/2019."  It left out the demand on the 18th but picked up some past demand by including the 24th.

"The records 01/18/19 till 01/23/19 are ignored, as they represent passed periods and we don't care if demand happened that time or not, as soon as they don't affect requested period (01/25/19..??)"  Why did we care about the demand on the 24th as that is passed demand as well?  Is the intent to only go back 1 forecast entry and grab that demand?

True the forecast records themselves don't contain type of period but if you input forecast "monthly", it still records it as the 1st of the month.  If you record it as monthly, then enter a daily forecast, say for the 10th, then run your plan with a starting date of the 15th, the entry on the 1st will not be picked up but the entry on the 10th will; in this case again "some" past demand is picked up.

Would it make more sense to go back and pickup all past demand as far back as the date in the "Ignore Forecasts Before" field?

Thanks!

**Comment by JesperSchulz** [comment] 2018-03-20 11:14
I've got  a few more replies for you from our program manager :-) As this issue isn't related to an al development issue, I would kindly refer you to our other support channels with this issue, where you will have a more direct connection to the people who can answer your questions / fix your problems. If possible, we would like to reserve this repo for App Extensibility issues, to keep issues separated. But before closing this issue, here are the replies from our PM:

The ending date isn't the issue here, it's what the system calculates as the starting date.
**PM: ending date is exactly the issue – you’ll see below.**
"Find first record. This record represents beginning of period and forecasted qty." Yes, and findfirst should be reused again before it repeats through the forecast entries and then it will pickup past entries.
**PM: No. it Should not, as other entries are “closed” (guess why it is consider as closed)**
"One of steps is to find forecasted periods that started before starting date and didn't finish. That's why is uses FIND(+), which finds record on 01/24/2019." It left out the demand on the 18th but picked up some past demand by including the 24th.
**PM: demand on before 24th is “closed”.** 
"The records 01/18/19 till 01/23/19 are ignored, as they represent passed periods and we don't care if demand happened that time or not, as soon as they don't affect requested period (01/25/19..??)" Why did we care about the demand on the 24th as that is passed demand as well? Is the intent to only go back 1 forecast entry and grab that demand?
**PM: Because this is the only demand that is “open” ” (guess why it is consider as open)**
True the forecast records themselves don't contain type of period but if you input forecast "monthly", it still records it as the 1st of the month. If you record it as monthly, then enter a daily forecast, say for the 10th, then run your plan with a starting date of the 15th, the entry on the 1st will not be picked up but the entry on the 10th will; in this case again "some" past demand is picked up.
**PM: Try to answer the question: you see the record with date 01/01/2018 –what is period: day/month/quarter or year?** 
**PM: (Answer – it depends on date of next record. If there is _no_ next record that period is “indefinite”)**
Would it make more sense to go back and pickup all past demand as far back as the date in the "Ignore Forecasts Before" field?
**PM: No. It’s two “different” concepts. In your example the value in “Ignore Forecast Before” has no impact on result.**

I hope that this somehow answers your questions a little. If you still believe we have a product bug, I'd like to ask you to create a collaboration request through CSS, which will allow us to pick the issue up for previously released products by a team who knows more about this. Thank you for bringing your issue forward!

**Closed by JesperSchulz** 2018-03-20 11:14 UTC
Labels: application, enhancement
