### ISSUE TITLE
Unable to sync updates - MetaTable Error

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/AL#4234] opened 2018-11-19 15:22 UTC
**Describe the bug**
When trying to install an app update the sync step (through powershell as well as the Extension Management page) I get the error: 

There was an error deserializing the object of type Microsoft.Dynamics.Nav.Types.Metadata.MetaTable. The maximum string content length quota (8192) has been exceeded 
while reading XML data. This quota may be increased by changing the MaxStringContentLength property on the XmlDictionaryReaderQuotas object used when creating the XML 
reader. Line 1, position 333.

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. Install common library
2. Install app
3. Update app and rebuild
4. Uninstall, Unpublish old
5. Publish New
6. Attempt to sync new, get error. At this time nothing can be synced anymore, even brand new apps cause the error

I'm trying to determine a better repro but I am not sure what to look at. Any idea what the metatable xml error could possibly be related to? That would help me narrow it down in to a test project for the repro. 

This is a new issue, we did not run in to this when working on the app now released in appsource. The only changes made were adding more translation files and adding action images to the role center extension which I would not expect to be related to the metadata table. 

**Expected behavior**
Can sync app updates

**Versions:**
Using the azure VM from Daily_Builds_-_Maintaining_an_app_in_AppSource 

 - AL Langauge: al-2.0.48254

 - Business Central: CA Dynamics NAV 13.1 (25341)

--

**Comment by kalberes** [comment] 2018-11-20 11:39
Does the event viewer have more info?

**Comment by strophanthus** [comment] 2018-11-20 13:36
Same error but there is a stack trace


Message App Sync Exception -- System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type Microsoft.Dynamics.Nav.Types.Metadata.MetaTable. The maximum string content length quota (8192) has been exceeded while reading XML data. This quota may be increased by changing the MaxStringContentLength property on the XmlDictionaryReaderQuotas object used when creating the XML reader. Line 1, position 333. ---> System.Xml.XmlException: The maximum string content length quota (8192) has been exceeded while reading XML data. This quota may be increased by changing the MaxStringContentLength property on the XmlDictionaryReaderQuotas object used when creating the XML reader. Line 1, position 333.
   at System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, String res, String arg1, String arg2, String arg3)
   at System.Xml.XmlDictionaryReader.ReadContentAsString(Int32 maxStringContentLength)
   at System.Xml.XmlBaseReader.ReadElementContentAsString()
   at ReadMetaFieldFromXml(XmlReaderDelegator , XmlObjectSerializerReadContext , XmlDictionaryString[] , XmlDictionaryString[] )
   at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at ReadArrayOfMetaFieldFromXml(XmlReaderDelegator , XmlObjectSerializerReadContext , XmlDictionaryString , XmlDictionaryString , CollectionDataContract )
   at System.Runtime.Serialization.CollectionDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at ReadMetaTableFromXml(XmlReaderDelegator , XmlObjectSerializerReadContext , XmlDictionaryString[] , XmlDictionaryString[] )
   at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   --- End of inner exception stack trace ---
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.DataContractSerializer.ReadObject(XmlDictionaryReader reader, Boolean verifyObjectName)
   at Microsoft.Dynamics.Nav.Runtime.Apps.DatabaseAppSyncSnapshotRepository.DeserializeMetaTable(XmlElement root)
   at Microsoft.Dynamics.Nav.Runtime.Apps.DatabaseAppSyncSnapshotRepository.ReadAndDeserializeMetaTable(NavSqlCommand command, Int32 ordinal)
   at Microsoft.Dynamics.Nav.Runtime.Apps.DatabaseAppSyncSnapshotRepository.GetAllForApp(AppId appId)
   at Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseSync.SynchronizeTenantDatabaseForAppSyncInternal(NavSession session)
ProcessId: 6724
Tag: 00001X1
ThreadId: 17

**Comment by strophanthus** [comment] 2018-11-20 14:04
Okay I tried removing all the translation files, and the error has gone away. 

I added the same number of translation files to a smaller project and that one works fine. 

I think it seems likely to be a combination of translations and table count or size.

**Comment by strophanthus** [comment] 2018-11-21 11:47
Can someone look at this please?

**Comment by cmrudolph-msft** [comment] 2018-11-21 16:30
@strophanthus - The only way I have been able to reproduce this so far is by creating a CaptionML property where a single language string is greater than the 8192 characters mentioned in the error. It has not mattered how many fields OR how many distinct languages I create. **The error occurs when one string gets too long.**

Can you see if one or more of your translation strings goes beyond this length? I am looking into ways to raise this quota in the deserialization code, but want to make sure we are looking at exactly the same issue first.

**Comment by cmrudolph-msft** [comment] 2018-11-21 17:04
Serializer quotas have been upped all around. This will work fine in future updates.

**Comment by strophanthus** [comment] 2018-11-21 17:30
Sorry missed your additional comment there. Any idea how soon it will be available in the daily previews? In case there's something else going on, because our cases aren't matching up, I'd like to check if it's still happening and figure out whether I should keep trying to pin it down.

**Comment by cmrudolph-msft** [comment] 2018-11-21 17:34
Interesting. A string that long seemed unlikely. That said, my repro did produce the exact same symptoms (and the issue is pretty clear from the error). With the deserialization quotas effectively removed, all these cases **should** disappear.

The platform change is going through the build now and should therefore be available in the the daily preview within a couple days (depending on exactly what build the Docker image gets based on).

If you're willing to share your package privately I'm happy to test it out immediately assuming it's easy to just publish + sync it against a vanilla base. You can get it to me via mail using chrudolp at microsoft or through whatever medium you prefer.

**Comment by strophanthus** [comment] 2018-11-21 17:41
I would be willing, but this is only mildly urgent so waiting for the build is okay with me. 

Thanks!

**Comment by qutreson** [comment] 2019-04-17 12:52
Closing this issue as it was fixed back in November. If you are still facing this issue, please log a new issue.

**Closed by qutreson** 2019-04-17 12:52 UTC
Labels: bug, in-progress
