### ISSUE TITLE
Use of CurrReport.skip in Report Extension object

### ISSUE THREAD

**Issue by jensthomsenEV** [microsoft/AL#6949] opened 2022-02-23 08:09 UTC
When using CurrReport.skip in report extension trigger OnBeforeAfterGetRecord(), it only skips the extension trigger, but execution continues to the OnAfterGetreord() on the report. I would expect it to skip the whole dataitem:
![image](https://user-images.githubusercontent.com/36921101/155281574-806da6b6-7e7f-4c57-a5a6-684c7df3b8f4.png)

**Comment by dnpb** [comment] 2022-02-23 09:55
Do you have a self-contained, minimal `reportextension` object that shows the problem? A censored screenshot is unlikely to give MS much way to get started quickly.

**Comment by nndobrev** [comment] 2022-02-24 10:26
@jensthomsenEV Is this visible on the latest AL Language extension version? Can you please provide more info and follow the bug logging template: https://github.com/microsoft/AL/blob/master/ISSUE_TEMPLATE

**Comment by dnpb** [comment] 2022-05-12 08:34
https://github.com/microsoft/AL/issues/7039 has more info so I guess this one should be closed.

**Comment by thloke** [comment] 2022-05-17 08:55
Closing as a dupe of #7039

**Closed by thloke** 2022-05-17 08:55 UTC
Labels: input-needed

**Comment by TMEKUMA** [comment] 2023-02-28 13:48
Do you have any new information on this?
