### ISSUE TITLE
PromotedActionCategories in Page Extensions...

### ISSUE THREAD

**Issue by NeilHalliday** [microsoft/AL#6543] opened 2021-03-19 08:27 UTC
Hi,

When changing the PromotedActionCategories in a page extension the standard property does not work, however the PromotedActionCategoriesML does work. The multi-language element generates a warning however and will be an error at some point in the future.

Here is an example of what I mean...

I'm extending the warehouse shipment page, and have the following property change in it.

![image](https://user-images.githubusercontent.com/17927660/111751780-cb260e80-888c-11eb-8fd8-a81d900f7655.png)

When using just the PromotedActionCategories property, the result is as follows...

![image](https://user-images.githubusercontent.com/17927660/111751628-a29e1480-888c-11eb-9695-93aa43467ec2.png)

If you then change it to the PromotedActionCategoriesML the result is as follows...

![image](https://user-images.githubusercontent.com/17927660/111751659-aaf64f80-888c-11eb-8d72-85677d1d8de0.png)

For the moment we can carry on using the multi-language property, but will be unable to when that is deprecated.

**Comment by dtkb** [comment] 2021-03-19 09:10
seems like a dupe of https://github.com/microsoft/AL/issues/1398 or others

**Comment by neverbeam** [comment] 2021-03-23 09:15
We had a similar issue as well, only for us the translation stayed in english. What ended up fixing it for us was that in the XLF file the property "Original" was not set correctly. In our case this settings was incorrect in the app (baseapp) that our app had a dependency on. So the problem was not even in the app that defined th PromtedActionCategories.
This caused the PromotedActionCategories to fail for the translated language. 

I am referrring to:
  <file datatype="xml" source-language="en-US" target-language="nl-NL" **original="YourAppName"**>

Perhaps this is also the issue in your case?

**Comment by dtkb** [comment] 2021-03-25 14:21
How could the base app be relevant to `PromotedActionCategories`?

I just saw this again, and the correct caption was shown when viewing in English (US) language, but it reverted to Category9 when changed to English (UK).

**Comment by cet0bs** [comment] 2022-01-11 10:02
We have the same issue , that in the source language the caption for the Promoted Action Category in the Page Extension works, but as soon as we use another Language (de-DE for example) it shows Category9.

**Comment by neverbeam** [comment] 2022-03-15 11:01
Perhaps this can help you a bit:
https://community.dynamics.com/business/f/dynamics-365-business-central-forum/418979/working-with-xliff-things-to-know

The issue for me was always that the original tag in the translation xlf file was not correct.

**Comment by KristofKlein** [comment] 2022-03-15 15:11
ok that link was indeed helpful. So to see if I got this right: I use a NZ version of BC. That leads to a NZ xlif in the base app. now my extension comes around without any xlif but with an extended PromotedActionCategories. As the Servicetier is not able to "combine" xlifs for that "inputstring" it takes what it has: Base App xlif. And this does not know of my Categories (of course) so it just runs along with this "translation"....as I (user) said: please show me in NZ .... so I have to have a translation from english to english, just to make sure that the "outmost" xliff wins the question on: which String should we use for NZ PromotedActionCategories ... yeah that is no good :D I can get my situation work, but ....well, no good :)

**Comment by EmilDamsbo** [comment] 2022-11-02 13:19
Hello, this issue is an older issue and since our last update we have implemented a new syntax for promoting actions. Please review the updated documentation here:
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-promoted-actions

**Closed by EmilDamsbo** 2022-11-02 13:19 UTC
