### ISSUE TITLE
Go to Definition with more configurations in launch.json

### ISSUE THREAD

**Issue by IvoMol** [microsoft/AL#4203] opened 2018-11-14 17:59 UTC
**Describe the bug**
We are not able show base application objects (.dal) when launch.json contains more than one configuration. 

**To Reproduce**
1. There is only one configuration in launch.json.
2. Define variable Item: record Item; and Go to Definition (F12) -> works OK.
3. Add Configuration in launch.json (clone the same or create different one)
4. Go to Definition (F12) -> empty definition shown

**Expected behavior**
Standard object definition downloaded and shown from configuration used in Debug.

**Versions:**
 - AL Langauge: 2.0.48254
 - Business Central: On-premises 13.0.24623

**Comment by JohanStenberg100** [comment] 2018-11-15 08:12
Hi @IvoMol, thanks for opening this issue. I can't reproduce this issue on AL language version 2.0.48254. Can you provide your VS Code version and which OS you are using?

**Comment by bennyvanlyssebettens** [comment] 2018-11-21 20:17
AL Language: 2.0.43900
BC: BE Dynamics NAV 13.0 (24630)

`{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "BC130",
            "server": "http://localhost",
            "serverInstance": "BC130",
            "port": 7149,
            "authentication": "Windows",
            "startupObjectType": "Page",
            "startupObjectId": 99000,
            "breakOnError": true,
            //"schemaUpdateMode": "Recreate"
        },
        {
            "type": "al",
            "request": "launch",
            "name": "BC130BE",
            "server": "http://localhost",
            "serverInstance": "BC130BE",
            "port": 7179,
            "authentication": "Windows",
            "startupObjectType": "Page",
            "startupObjectId": 99000,
            "breakOnError": true,
            //"schemaUpdateMode": "Recreate"
        }
    ]
}
`
Works fine

**Comment by IvoMol** [comment] 2018-11-25 19:19
Retested on newer BC on-premises version (CU01):
Microsoft (R) AL Compiler version 2.0.56865
Microsoft_Application_13.0.25924.0

** Tested AL code, Customer List -> Go to Definition: **
pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    begin
        Message('App published: Hello world');
    end;
}

** Original launch.json **
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "http://localhost",
            "serverInstance": "DynamicsNAV130",
            "authentication": "Windows",
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true
        }
    ]
}

** Correct Customer%20List.dal with full code **
OnInit()
  SetCustomerNoVisibilityOnFactBoxes;
  
  CaptionTxt := CurrPage.CAPTION;
  SetCaption(CaptionTxt);
  CurrPage.CAPTION(CaptionTxt);
  PowerBIVisible := FALSE;
  CurrPage."Power BI Report FactBox".PAGE.InitFactBox(CurrPage.OBJECTID(FALSE),CurrPage.CAPTION,PowerBIVisible);
 
OnOpenPage()
  CRMIntegrationEnabled := CRMIntegrationManagement.IsCRMIntegrationEnabled;
  
  SetWorkflowManagementEnabledState;
  SETFILTER("Date Filter",'..%1',WORKDATE);
 
OnAfterGetCurrRecord()
  SetSocialListeningFactboxVisibility;
  
  CRMIsCoupledToRecord :=
    CRMCouplingManagement.IsRecordCoupledToCRM(RECORDID) AND CRMIntegrationEnabled;
  OpenApprovalEntriesExist := ApprovalsMgmt.HasOpenApprovalEntries(RECORDID);
  
  CanCancelApprovalForRecord := ApprovalsMgmt.CanCancelApprovalForRecord(RECORDID);
  
  WorkflowWebhookManagement.GetCanRequestAndCanCancel(RECORDID,CanRequestApprovalForFlow,CanCancelApprovalForFlow);
etc.

** Doubled launch.json **
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "http://localhost",
            "serverInstance": "DynamicsNAV130",
            "authentication": "Windows",
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true
        },
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server 2",
            "server": "http://localhost",
            "serverInstance": "DynamicsNAV130",
            "authentication": "Windows",
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true
        }
    ]
}

** Wrong Customer%20List.dal, only with skeleton and global variables**
page 22 "Customer List"
{
  layout
  {
    area(Content)
    {
      repeater(Control1)
      {
        field("No.";"No.")
        {
        }
        field("Registered Name";"Registered Name")
        {
        }
etc.

**Comment by kalberes** [comment] 2018-11-26 13:06
Hi,

You are right. Having multiple configuration definitions is not supported with the go to definition feature.  This is by design for now.  The reason being that we have no implementation in our language server code base on how to choose the default configuration. Which is fully supported when debugging.

**Comment by kalberes** [comment] 2018-11-26 15:23
Even though it is by design, it should be made working. Marking it as a bug.

**Comment by ralf-escher** [comment] 2019-10-11 13:19
We have just experienced this bug with our AL environment (official BC15), 😞 
additionally the "Run In Web Client" also only works with one configuration in launch.json. 
Any chance this issue will be solved in time?

**Comment by qutreson** [comment] 2020-06-30 06:17
Closing this issue as it has been fixed for AL extensions with version higher than 5.0.235548

**Closed by qutreson** 2020-06-30 06:17 UTC
Labels: bug, in-progress, workspaces
