### ISSUE TITLE
Download reference symbols fails in test app when dependency app name contains a slash

### ISSUE THREAD

**Issue by sheldonUSL** [Microsoft/AL#3799] opened 2018-09-20 19:10 UTC
AL Version 0.16.26913
September BC release

When trying to develop a Test app for our extension that we registered with a '/' character in its name, the test app compile fails when referencing it.
We modified the sample Rewards Extension app and test app to demonstrate the issue.
We renamed the app "Rewards Extension" to "G/L Rewards Extension", which compiles with the '/' character in the name and publishes correctly.
Then we reference it in the Test app, in the Dependencies section, and it fails by trying to add the name to a path (for some reason??).
We noticed that it silently switched the forward slash in the name to a backslash in the error below.

{
  "id": "26c672bd-b5aa-44d0-95ef-6eb3cfa1fafd",
  "name": "Rewards Extension Tests",
  "publisher": "Default publisher",
  "brief": "",
  "description": "",
  "version": "1.0.0.0",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "capabilities": [],
  
  "dependencies": [ 
    {
    "appId": "623836d1-e834-409d-a889-a115a8b07855", 
    "name": "G/L Rewards Extension", 
    "publisher": "Default publisher", 
    "version": "1.0.0.0"}
  ],
  "screenshots": [],
  "showMyCode": true,
  "platform": "12.0.0.0",
  "application": "12.0.0.0",
  
 
  
  "idRange": {
    "from": 50100,
    "to": 50149
  }
}

The app "G/L Rewards Extension" is installed successfully.

When I run ^F5 , I get this error:

[2018-09-20 14:30:11.45] Using reference symbols cache path: c:\Users\vmadmin\Documents\AL\Rewards Extension Tests\./.alpackages
[2018-09-20 14:30:11.45] Sending request to https://xxxxxxx.eastus.cloudapp.azure.com:7049/nav/dev/packages?publisher=Microsoft&appName=Application&versionText=12.0.0.0
[2018-09-20 14:30:11.46] Sending request to https://xxxxxxx.eastus.cloudapp.azure.com:7049/nav/dev/packages?publisher=Microsoft&appName=System&versionText=12.0.0.0
[2018-09-20 14:30:11.46] Sending request to https://xxxxxxx.eastus.cloudapp.azure.com:7049/nav/dev/packages?publisher=Default publisher&appName=G%2FL Rewards Extension&versionText=1.0.0.0
[2018-09-20 14:30:11.66] Error: Could not find a part of the path **'c:\Users\vmadmin\Documents\AL\Rewards Extension Tests\.alpackages\Default publisher_G\L Rewards Extension_1.0.0.0.app'.**

[2018-09-20 14:30:18.19] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.

We are dead in the water for submitting our app until we can create our Test app.

**Comment by qutreson** [comment] 2018-09-20 20:30
Hi @sheldonUSL, this looks like a duplicate of #2364, I believe this should be fixed with the July update.

**Comment by qutreson** [comment] 2018-09-20 20:31
Can you try verifying it with the AL extension from August (version 0.17.32492) ?

**Closed** 2018-09-20 20:35 UTC
Labels: duplicate

**Comment by sheldonUSL** [comment] 2018-09-20 21:18
qutreson: I am confused. Here we are in September, and I am running the latest version of AL **0.16.26913**. Tried to update AL again within Visual Studio Code and no new version is available. Where is this July release, or when will this "July" release be actually released?
The Microsoft AL webpage: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
references a July release, but the version number stated there is: 0.16.19969 which is way lower than what I reported the error with. 
Please advise and clear my confusion.
Thanks
