### ISSUE TITLE
No Values on Page Inspector for pages with Temaporary Source Tables

### ISSUE THREAD

**Issue by megel** [microsoft/AL#4720] opened 2019-03-13 11:11 UTC
Version: Platform 14.0.28496.0 + Application

When I use the Page Inspector on pages with temporary source tables, no field values are shown:
![image](https://user-images.githubusercontent.com/15800069/54274583-b8372000-4588-11e9-8be5-ed993d7e9693.png)

**Comment by alantipo** [comment] 2019-03-20 18:22
This is currently by design. We are planning to add values of fields from temporary tables into Page Inspector in the future.

**Comment by qutreson** [comment] 2021-11-30 10:55
Closing this issue as it was marked as by-design and is beyond the scope of the AL language and development tools. 
You can post this anyway to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Closed by qutreson** 2021-11-30 10:55 UTC
Labels: cross-team-investigate
