### ISSUE TITLE
Inserting the UserId method from intellisense is missing parenthesis

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#6908] opened 2022-01-31 06:35 UTC
Reactivating closed case #6356

**Describe the bug**
Unlike system methods in general, the `UserId` method chosen from intellisense does not automatically insert the method parenthesis.

**To Reproduce**
Enter `User` and choose entry `UserId` from intellisense:
![image](https://user-images.githubusercontent.com/34504100/151748976-f86b8697-8c1e-4a6e-900b-7a0a0f771a7a.png)
The inserted value will be `UserId`

Repeat search and insert `UpperCase`: 
the inserted value will be
`UpperCase()`

**Expected behavior**
Insert UserId() instead of UserId

**Versions:**
AL Language: 8.3.570094

**Comment by dannoe** [comment] 2022-01-31 08:55
I think this is intended:

The docs page for [UserId ](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/database/database-userid-method) states:

This method can be invoked using property access syntax.

The sames goes for [Record.IsEmpty](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-isempty-method).

And for some reason the compiler defaults to the property syntax, if it is available.

**Comment by thloke** [comment] 2022-02-03 06:30
I think this is what we intend actually. We have some methods which behave more like properties, and so we default to property access syntax for these. Other examples from Record are `Count` `CountApprox` `TableName`... there's a whole bunch of these. It might be nice to have a setting for the AL Extension so you can specify which behaviour is preferred. That would be an enhancement though, so it will have to go to BCIdeas.

I'm closing this issue as "By Design".

**Closed by thloke** 2022-02-03 06:30 UTC
