### ISSUE TITLE
Problem: Page Action is not Displayed, when RunObject is used and the page refere to a special table

### ISSUE THREAD

**Issue by megel** [Microsoft/AL#1290] opened 2017-12-22 12:26 UTC
NAV Version:
![grafik](https://user-images.githubusercontent.com/15800069/34297505-d1240544-e718-11e7-9e26-462a74cf6017.png)

app.json (`"target": "Internal"`)

In my page I have defined 3 actions, but only 2 are visible.

```javascript
area(Processing)
{ 
        // This action is visible & can be executed
	action("Table Information")
	{
		ApplicationArea = All;
		Image = Info;
		trigger OnAction();
		var p : Page "My Table Information";
		begin
			p.Run;
		end;
	}

        // This action is not shown (same page is used)
	Action("Table Information 2")
	{
		ApplicationArea = All;
		RunObject = Page "My Table Information";
		RunPageMode = View;
		Image = Info;
	}

        // This action is shown - but uninterestion for the Issue
	Action(Setup)
	{
		ApplicationArea = All;
		RunObject = Page "My Setup";
		Image = Setup;
	}
}
```

The page / actions in the WebClient (RTC is the same result): 
![grafik](https://user-images.githubusercontent.com/15800069/34297359-fe6d35c6-e717-11e7-8428-4f98b5afe2b9.png)

My page uses the SourceTable `Table Information`:
```javascript
page 51007 "Table Information OETT"
{
    PageType        = List;
    SourceTable     = "Table Information";
    // ...
}
```

When I change the SourceTable e.g. to:
`SourceTable     = "Table Permission Buffer";`

Than the action is shown correct:
![grafik](https://user-images.githubusercontent.com/15800069/34297925-44e4199a-e71b-11e7-9082-ae3edea76d23.png)

**Comment by DominikDitoIvosevic** [comment] 2018-02-13 07:39
Hi @megel . Could you please verify you are still experiencing this issue?
I tried reproing it but it doesn't repro, I can see the action.
One thing which happens is when you don't specify that the action does anything (no run object or trigger) then the action is not displayed.
We should indeed report at least a warning in that case.

**Comment by megel** [comment] 2018-02-13 16:24
@DominikDitoIvosevic which build should I try?

**Comment by DominikDitoIvosevic** [comment] 2018-02-14 07:08
Please try with a version after 11.0.20221.0. Could you maybe upload a small sample zip of the extension causing issues so that we have a repro?

**Comment by megel** [comment] 2018-02-16 10:27
@DominikDitoIvosevic , sorry this Issue still exists:
WebClient:
![grafik](https://user-images.githubusercontent.com/15800069/36303211-a10c53ec-130b-11e8-9241-b44d837a53a3.png)
RTC:
![grafik](https://user-images.githubusercontent.com/15800069/36303371-3f760fdc-130c-11e8-8146-d30492574c5d.png)

Here is a sample project:
[Microsoft AL [ActionTest].zip](https://github.com/Microsoft/AL/files/1730928/Microsoft.AL.ActionTest.zip)

My Version:
![grafik](https://user-images.githubusercontent.com/15800069/36303271-d31b3c54-130b-11e8-83b1-d450116805e0.png)
![grafik](https://user-images.githubusercontent.com/15800069/36303297-ecfa7450-130b-11e8-9b8a-3612923cd2a9.png)
![grafik](https://user-images.githubusercontent.com/15800069/36303393-52165a48-130c-11e8-832e-2d558fbce478.png)

**Comment by DominikDitoIvosevic** [comment] 2018-02-19 13:33
@megel thank you for the repro. Very peculiar indeed. I will investigate further

**Comment by thpeder** [comment] 2018-03-20 10:15
The Page Action not being displayed is intentional because the table is not included in the license.

**Comment by megel** [comment] 2018-04-09 06:13
@thpeder if the license is the root cause, what is the difference between:

```
var p : Page "My Table Information";
begin
	p.Run;
end;
```
and
```
RunObject = Page "My Table Information";
RunPageMode = View;
```

**Comment by RobAnderson42** [comment] 2018-04-09 16:31
The difference is how the action is declared. 

In the latter case, the RunObject property adds metadata to the action telling us what table is being accessed. Because Table Information isn't part of the license, we remove the action from the ribbon when the page is opened.

In the former case everything is done in code so the action doesn't have that metadata.

**Comment by DominikDitoIvosevic** [comment] 2018-04-26 09:49
We are closing this for "by design"

**Closed by DominikDitoIvosevic** 2018-04-26 09:49 UTC
Labels: bydesign
