### ISSUE TITLE
Cannot debug any (Yes/No) Codeunits

### ISSUE THREAD

**Issue by ewaldventer** [microsoft/AL#6999] opened 2022-04-13 13:40 UTC
- AL Extension Version: 9.0.605172

- Server Version: 19.3

Trying to debug any of the codeunits with a (Yes/No) in the name results in a **No content available** message. It does look like the culprit is the forward slash as the name on the tab displays as **No).dal**

![image](https://user-images.githubusercontent.com/8598877/163188400-bca77bca-9da5-4790-ab3c-40bb911697fc.png)

**Comment by dnpb** [comment] 2022-04-13 13:57
dupe of https://github.com/microsoft/AL/issues/6972

**Comment by kalberes** [comment] 2022-04-14 08:50
It is a duplicate. Hopefully the next vsix release will have a fix for it.

**Closed by kalberes** 2022-04-14 08:50 UTC
