### ISSUE TITLE
Codecop-analyzer keeps crashing 

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/AL#5726] opened 2020-03-15 05:55 UTC
{
	"resource": "/c:/Users/app.json",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "AD0001",
	"severity": 4,
	"message": "Analyzer 'Microsoft.Dynamics.Nav.CodeCop.Localizability.Rule218TooltipMustBeFilledOnPageForFieldsAndActions' threw an exception of type 'System.NullReferenceException' with message 'System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Microsoft.Dynamics.Nav.CodeCop.Localizability.Rule218TooltipMustBeFilledOnPageForFieldsAndActions.ExtractCountOfOptionsFromGlobalVar(ISymbol symbol) in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeCop\\Localizability\\Rule218TooltipMustBeFilledOnPageForFieldsAndActions.cs:line 287\r\n   at Microsoft.Dynamics.Nav.CodeCop.Localizability.Rule218TooltipMustBeFilledOnPageForFieldsAndActions.AnalyzeCaptions(SymbolAnalysisContext symbolAnalysisContext, SyntaxNode node, IdentifierNameSyntax identifierName, ISymbol symbol) in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeCop\\Localizability\\Rule218TooltipMustBeFilledOnPageForFieldsAndActions.cs:line 265\r\n   at Microsoft.Dynamics.Nav.CodeCop.Localizability.Rule218TooltipMustBeFilledOnPageForFieldsAndActions.AnalyzeModifiedControlsAndActions(SymbolAnalysisContext symbolAnalysisContext, SyntaxNode node, ISymbol symbol) in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeCop\\Localizability\\Rule218TooltipMustBeFilledOnPageForFieldsAndActions.cs:line 123\r\n   at Microsoft.Dynamics.Nav.CodeCop.Localizability.Rule218TooltipMustBeFilledOnPageForFieldsAndActions.AnalyzePageModifyFields(SymbolAnalysisContext symbolAnalysisContext, ImmutableArray`1 changeSymbols) in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeCop\\Localizability\\Rule218TooltipMustBeFilledOnPageForFieldsAndActions.cs:line 88\r\n   at Microsoft.Dynamics.Nav.CodeCop.Localizability.Rule218TooltipMustBeFilledOnPageForFieldsAndActions.AnalyzePage(SymbolAnalysisContext symbolAnalysisContext) in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeCop\\Localizability\\Rule218TooltipMustBeFilledOnPageForFieldsAndActions.cs:line 61\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass49_2.<ExecuteSymbolActionsCore>b__0() in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 655\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 1099'",
	"source": "AL",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}

**Comment by nicolassaleron** [comment] 2020-03-16 07:26
Same here, it seems to happen for me when rule "AA0218" is disabled.

**Comment by MarcHansenMicrosoft** [comment] 2020-03-16 09:30
Hi 

Could you provide some info on the repro that makes it crash?

/Marc

**Comment by nicolassaleron** [comment] 2020-03-16 19:17
From my side it's complicate to reproduce. It occurs on all my apps. But when I create a new app with only one page without a tooltip, the error does not occur.

**Comment by salgiza** [comment] 2020-03-18 10:28
The analyzer kept crashing with this error with one of our apps, and I've managed to reproduce it (it requires a Spanish version of BC16).

```
pageextension 50000 "Test Purchase Order" extends "Purchase Order"
{
    layout
    {
        modify("Special Scheme Code")
        {
            Visible = false;
        }
    }
}
```

For whatever reason (because I don't see anything particular about those fields) the analyzer crashes as soon as we try to modify one of the fields added by the Spanish localization for SII (reporting taxes to the Spanish tax agency).

**Comment by miljance** [comment] 2020-03-19 13:36
Same here, it happens for me when rule "AA0218" is disabled.

**Comment by MarcHansenMicrosoft** [comment] 2020-03-23 16:09
Thanks for the added info.

**Comment by tinfister** [comment] 2020-04-20 12:28
It seems it's the problem with modifying Option fields.
No analyzer problem with modifying Text field
![image](https://user-images.githubusercontent.com/29481795/79751578-1a795d00-8313-11ea-8827-61e90e91bd00.png)
Problem with modifying Option field
![image](https://user-images.githubusercontent.com/29481795/79751610-282ee280-8313-11ea-90b5-688e1330f957.png)

AL Language extensiton 5.0.254558

**Comment by atoader** [comment] 2020-05-06 05:44
@MarcHansenMicrosoft can you take a look?

**Comment by Djordje-Arsic** [comment] 2020-06-09 11:18
Hello,

I had the same issue appearing like this, but the cause and the solution were different. 

I'm playing with interfaces and enums, so I had an enum extension in my app, extending native Enum "Price Asset Type" that is implementing "Price Asset". In this case since it's interface, the strong contract demands that my value in enum extension also implements, and I was missing property Implementation. **But instead of having compile error, I had this warning that is not very intuitive and it had nothing to do with tooltip missing.**

**Comment by waldo1001** [comment] 2020-06-15 09:05
This issue is now failing my build pipeline:
![image](https://user-images.githubusercontent.com/12088142/84638973-fe9bcd00-aef7-11ea-997c-3b5292d27f96.png)

**Comment by MarcHansenMicrosoft** [comment] 2020-06-15 09:49
We have just gotten the latest platform into Nav repo.

This would mean that if you get the latest development docker that will be coming.
Then this issue should be fixed.

**Closed by MarcHansenMicrosoft** 2020-06-15 09:49 UTC
Labels: CodeCop, bug, in-progress, static-code-analysis
