### ISSUE TITLE
Enums with whitespace

### ISSUE THREAD

**Issue by vlkov** [Microsoft/AL#3795] opened 2018-09-20 14:35 UTC
- AL Extension Version: 0.17.23984

- Server Version: 13.0.24267

Can't use enum values which names consist whitespace.  

enum 50130 "My Enum"
{
    Extensible = true;
    value(0; first)
    {
        Caption = 'first';
    }
    value(1; "Two words")
    {
        Caption = 'Two words';
    }

}
table 50130 TestTable
{
    DataClassification = ToBeClassified;

    fields
    {
        field(1; MyType; Enum "My Enum")
        {
            DataClassification = ToBeClassified;

        }
    }

    var
        myInt: Integer;

    trigger OnInsert()
    var
        My: Enum "My Enum";
    begin
        MyType := MyType::first;
        My := MyType::"Two words";
    end;

    trigger OnModify()
    begin
        case MyType of
            MyType::"Two words":
                Message(Format(MyType));
            MyType::first:
                Message('Test');
        end;
    end;

**Comment by qutreson** [comment] 2018-09-20 20:34
Hi @vlkov, this is a duplicate of #3566.

**Closed** 2018-09-20 20:34 UTC
Labels: duplicate
