### ISSUE TITLE
Error while publishing Cannot read properties of undefined (reading 'getWorkspaceSettings')

### ISSUE THREAD

**Issue by jjsalvomateos** [microsoft/AL#7711] opened 2024-04-10 13:14 UTC
hello, I have a problem with the AL extension in version v12.7.964847, when I to press the F5 button to publish I get the following error:

[Error - 14:00:10] Sending notification workspace/didChangeConfiguration failed
TypeError: Cannot read properties of undefined (reading 'getWorkspaceSettings')
    at didChangeConfiguration (c:\Users\user\.vscode\extensions\ms-dynamics-smb.al-12.7.964847\dist\webpack:\al\src\services\editorService.ts:103:17)
    at t.SyncConfigurationFeature.unregister [as onDidChangeConfiguration] (c:\Users\user\.vscode\extensions\ms-dynamics-smb.al-12.7.964847\dist\webpack:\al\node_modules\vscode-languageclient\lib\common\configuration.js:165:32)
    at t.SyncConfigurationFeature.register (c:\Users\user\.vscode\extensions\ms-dynamics-smb.al-12.7.964847\dist\webpack:\al\node_modules\vscode-languageclient\lib\common\configuration.js:128:5)
    at t.SyncConfigurationFeature.async [as initialize] (c:\Users\user\.vscode\extensions\ms-dynamics-smb.al-12.7.964847\dist\webpack:\al\node_modules\vscode-languageclient\lib\common\configuration.js:119:5)
    at S.initializationFailedHandler [as initializeFeatures] (c:\Users\user\.vscode\extensions\ms-dynamics-smb.al-12.7.964847\dist\webpack:\al\node_modules\vscode-languageclient\lib\common\client.js:1289:5)
    at StartFailed [as doInitialize] (c:\Users\user\.vscode\extensions\ms-dynamics-smb.al-12.7.964847\dist\webpack:\al\node_modules\vscode-languageclient\lib\common\client.js:827:37)
    at S.start (c:\Users\user\.vscode\extensions\ms-dynamics-smb.al-12.7.964847\dist\webpack:\al\node_modules\vscode-languageclient\lib\common\client.js:709:39)

In older versions I have no problems to publish, but it returns me error the environment for being in an old version.

Can anyone help me?

**Comment by thloke** [comment] 2024-04-11 02:58
Duplicate of https://github.com/microsoft/AL/issues/7664

**Closed** 2024-04-11 03:06 UTC
Labels: customer-support
