### ISSUE TITLE
CodeCop Rule AA0150  is displayed incorrectly when a text variable is used like an array.

### ISSUE THREAD

**Issue by jthoerner-tso** [microsoft/AL#6421] opened 2021-01-16 17:26 UTC
**Describe the bug**
A CodeCop Rule AA0150 warning is displayed when a text variable submitted by reference is only assigned values per position. 

By per position, I mean something like 
Text[Pos] := Value;

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a new code unit object and copy the following programme code

``` 
trigger OnRun()
    var
        Text1: Text;
        Text2: Text;
    begin
        MyProcedure(Text1);
        Message(Text1);

        MyProcedure2(Text2);
        Message('%1', Text2[1] + Text2[2] + Text2[3]);
    end;


    local procedure MyProcedure(var Text1: Text)
    begin
        Text1 := 'a' + 'b' + 'c';
    end;

    local procedure MyProcedure2(var Text2: Text)
    begin
        Text2[1] := 'a';
        Text2[2] := 'b';
        Text2[3] := 'c';
    end;
 ```

**Expected behavior**
That this warning is not displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/63199461/104818235-a11d8500-5826-11eb-915c-209236371b8e.png)

**5. Versions:**

 - AL Language: v6.1.397164

 - Business Central: BC17.2

**Comment by dtkb** [comment] 2021-01-18 10:11
dupe of https://github.com/microsoft/AL/issues/6179 (but your title is better!)

**Comment by atoader** [comment] 2021-01-20 17:39
Thanks for the good repro! I'll keep this issue and close the other one as a duplicate.

**Comment by NKarolak** [comment] 2021-06-28 09:13
@atoader any news?

**Comment by atoader** [comment] 2021-07-05 18:29
I accepted the bug and I will send it to @PaulIvan :)

**Comment by mazhelez** [comment] 2022-06-24 11:02
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.

For this case consider using [Pragma Warning Directive](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/directives/devenv-directive-pragma-warning).

**Closed by mazhelez** 2022-06-24 11:02 UTC
Labels: bug, in-progress, static-code-analysis, CodeCop
