### ISSUE TITLE
Dictionary GET function sets last known error when not necessary

### ISSUE THREAD

**Issue by LNitzsche** [microsoft/AL#5935] opened 2020-06-02 10:01 UTC
When trying to GET() an entry from a dictionary with an invalid key an exception is thrown. This is expected behaviour.
When avoiding the exception with "if GET(key, var)" or any other method to evaluate the return value, in case of invalid key the return value is false and no error is thrown. This is also expected and documented.
My problem is, that nevertheless the error code  "KeyNotFound" is set in the "last known error".
The expected behaviour would be not to set any error code in this case.
This would also be consistent to the behaviour of the RECORD.GET() function which sets the DB:RecordNotFound error code only if the boolean result of GET() is not evaluated.

Because I am using Dictionary.GET() many times, there are often false alarms in the "last known error" variable possibly overwriting some more important "real" errors.

**Comment by kalberes** [comment] 2020-06-02 11:07
Makes sense.

**Comment by mjmatthiesen** [comment] 2020-06-05 01:59
Logging that error seems correct to me. If you want to avoid it, you should likely use ContainsKey before the Get.

**Comment by dtkb** [comment] 2020-06-05 09:22
It should behave how other built-in try-functions like `Get()`/`Find*()`/etc do. We've seen that `Record.Get()` does not set an error code if the returned Boolean is consumed. Presumably nor do others? Confirmation would be welcome. Then this should act like those. If they don't set the error code when consumed, nor should it.

**Comment by kalberes** [comment] 2020-06-06 17:05
Agree that things should be consistent. This is why I have accepted as a bug that we investigate and adjust if needed. You are right and the LastErrorCode is not set if the return value is consumed.
For your info the LastErrorCode is coupled to the last "known" exception thrown within and NSt session. When you call if (customer.Get(...))) that gets translated to a trappabble get call that will not throw if the record is not found. Thus in this case there is no last exception.
And Dictionary.Get works the same way as i could see. 
So this is not a bug :)

**Comment by db-bc** [comment] 2021-08-06 10:28
Any idea when this might be fixed?

Probably not the best example, but one I've hit several times, is when sending reports via Custom Layout Reporting, the codeunit sees the 'wrong' `LastErrorText` and displays an error (list) - so we have to write longer/less obvious code to work around the fact that a checked `Get()` still sets the last error. There are likely better examples, but that already shows it causing hassle in practice.

As a minimal reproducible sample, this code:
```al
pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var
        Dict: Dictionary of [Integer, Integer];
        i: Integer;
    begin
        if Dict.Get(42, i) then;
        Message(GetLastErrorText());
    end;
}
```

still produces this error:
![image](https://user-images.githubusercontent.com/63455896/128496806-f91f793f-746f-4a81-b2e5-a6dfb72dc51a.png)

as of _GB Business Central 18.3 (Platform 18.0.27224.28697 + Application 18.3.27240.28715)_ and
```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 7.4.496506
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

...but it shouldn't, because we consumed the result of `Get(Integer; var Integer)`, meaning we didn't want an error to get thrown.

**Comment by LNitzsche** [comment] 2021-11-25 13:09
A similar failure is in the function 
procedure SelectToken(Path: Text, var Result: JsonToken): Boolean

If you want to use this function to decide, if Path references a valid token then "Last Known Error" is also set if the result is false.
But this should not happen, if the boolean return value is evaluated by the caller.

Internal this may be the same cause for a JsonObject is nothing else than a Dictionary of [Text, JsonToken].

Are there any plans to fix this issue?

**Comment by dnpb** [comment] 2021-11-25 13:10
I guess you closed it by mistake ;-)

**Comment by LNitzsche** [comment] 2021-11-25 13:16
Yes, this was a mistake, have reopened again.

**Comment by kalberes** [comment] 2021-12-03 12:59
Runtime issue. For faster resolution the best process is:
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Closed by kalberes** 2021-12-03 12:59 UTC
Labels: bug, runtime
