### ISSUE TITLE
Unnecessary RDLC Dataset modification when compiling

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/AL#5845] opened 2020-04-28 20:39 UTC
**Describe the bug**
This problem is not a really a bug but causes unnecessary modifications in RDLC files:
* When you compile (AL: Package), the section <DataSets> of RDLC files are placed at the end of the file
* When you open the RDLC file with Visual Studio Report Designer and save the file, the <DataSets> section is moved at the beginning of the file

This problem causes tracking changes in RDLC file more difficult than it is already :)

**To Reproduce**
Steps and to reproduce the behavior:
1. Open a RDLC file with Visual Studio Report Designer
2. Change something and save the file
3. Commit your changes against the current branch
4. Call AL: Package action
    You can notice now that the RDLC file has been changed.

**Expected behavior**
It would be expected that the <DataSets> section should be left at the same position by replacing the node where it is by the new one; and not deleting it+adding at the end.

**Screenshots**
./.

**5. Versions:**
 - AL Language: 5.0.254558

**Comment by boych83** [comment] 2020-04-29 06:51
True. It is annoying.
We partially switched to word layout and I'm noticing similar behaviour with word layout.
Without any changed on a report and after running build some of them (not all) are marked as changed. We did't figure out yet why that is happening.

BR,
Bojan

**Comment by TeusV** [comment] 2021-03-16 14:19
Now happens with Word layouts...

**Comment by yurim108** [comment] 2024-02-27 11:27
4 years later... The problem is still there. 
My colleagues design multiple reports for BC 23. 
I merge master branch into my feature branch and compile the app: most of rdl files are changed now an I have to undo the changes manually. That's annoying. 

Some setup in VS Code like "Use Visual Studio Report Designer format" would be appreciated.

**Comment by thloke** [comment] 2024-03-26 09:55
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern.

**Closed by thloke** 2024-03-26 09:55 UTC
Labels: bug, requires-triage, al-core-compiler, reporting

**Comment by hbunjes** [comment] 2025-01-27 14:53
I'd be happy if you reconsider this decision. If you have many reports it makes commiting changes sometimes difficult as you likely select a wrong report and do not want to commit all reports every time...
