### ISSUE TITLE
Getting Error when sending get request with content.

### ISSUE THREAD

**Issue by RavinderKumarGitHub** [microsoft/AL#7085] opened 2022-06-20 11:30 UTC
trigger OnAction()
                var
                    httpclients: HttpClient;
                    httpcontents: HttpContent;
                    httpheader: HttpHeaders;
                    httprequest: HttpRequestMessage;
                    httpresponse: HttpResponseMessage;
                    reponsetxt: Text;
                begin
                    httpcontents.clear;
                    httpcontents.WriteFrom('{"SiteIDs":[4438],"StartDate":"2022-06-15T12:47:04.030757+01:00","EndDate":"2022-06-15T12:47:04.030757+01:00"}');
                    httpcontents.GetHeaders(httpHeader);

                    httpheader.Clear();
                    httpheader.Add('Content-Type', 'application/json');
                    httpheader.Add('GUID', string1);
                    httpheader.Add('DevID', string2);
                    httpheader.Add('CompanyId', string3);

                    httprequest.GetHeaders(httpheader);
                    httprequest.Content := httpcontents;

                    httprequest.Method('GET');
                    httprequest.SetRequestUri(Url);

                    httpclients.Clear();

                    httpclients.Send(httprequest, httpresponse);

                    if httpresponse.Content().ReadAs(reponsetxt) then
                        Message('%1\%2', reponsetxt, httpresponse.HttpStatusCode);
                end;

**_Error:_**

System.Net.ProtocolViolationException: Cannot send a content-body with this verb-type.
at System.Net.HttpWebRequest.CheckProtocol(Boolean onRequestStream)
at System.Net.HttpWebRequest.BeginGetRequestStream(AsyncCallback callback, Object state)
at System.Net.Http.HttpClientHandler.StartGettingRequestStream(RequestState state)
at System.Net.Http.HttpClientHandler.PrepareAndStartContentUpload(RequestState state)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Dynamics.Nav.Runtime.NavHttpClient.<>c__DisplayClass48_0.b__0(CancellationToken ct)
at Microsoft.Dynamics.Nav.Types.NavCancellationToken.RunActionWithCancellationToken[T](Func2 func) at Microsoft.Dynamics.Nav.Runtime.NavHttpClient.SendWithTelemetry(HttpRequestMessage requestMessage, String endpoint) at Microsoft.Dynamics.Nav.Runtime.NavHttpClient.<>c__DisplayClass47_0.<Send>b__1() at Microsoft.Dynamics.Nav.Types.NavThread.<>c__DisplayClass44_0.<RunExternalAction>b__0() at Microsoft.Dynamics.Nav.Types.NavThread.RunExternalAction[T](Func1 action)
at Microsoft.Dynamics.Nav.Runtime.TrappableHttpOperationExecutor.<>c__DisplayClass0_0.b__0()
at Microsoft.Dynamics.Nav.Runtime.TrappableOperationExecutor.Execute(DataError errorLevel, Func1 operation, Action2 processNativeException)

**Comment by dnpb** [comment] 2022-06-20 11:44
Seems a duplicate of https://github.com/microsoft/AL/issues/5961

**Comment by nndobrev** [comment] 2022-06-21 13:56
Sending a GET request with body is a controversial topic, as @dnpb linked correctly https://github.com/microsoft/AL/issues/5961 you can see we are using just a wrapper and we can't do much about it the failure.

**Closed by nndobrev** 2022-06-21 13:56 UTC
