### ISSUE TITLE
Wrong variable name makes it pass by value not reference in subscriber

### ISSUE THREAD

**Issue by laviniaavram** [microsoft/AL#7493] opened 2023-09-05 12:41 UTC
**1. Describe the bug**
Item Tracking Management codeunit event publisher has a parameter named 'varQtyToHandleOnSourceDocLine' which makes it be passed by value not by reference as it was probably intended

**2. To Reproduce**

1. Go to codeunit 6500 "Item Tracking Management"
2. Search for OnRegisterNewItemTrackingLinesOnBeforeCannotMatchItemTrackingErr procedure definition
3. Its parameters are     
(var empTrackingSpecification: Record "Tracking Specification" temporary; var tyToHandleToNewRegister: Decimal; var QtyToHandleInItemTrackin: Decimal; **varQtyToHandleOnSourceDocLine**: Decimal; var IsHandled: Boolean)

**3. Expected behavior**
'varQtyToHandleOnSourceDocLine' should be 'var QtyToHandleOnSourceDocLine' so it can be modified in a custom codeunit by subscribing to the OnRegisterNewItemTrackingLinesOnBeforeCannotMatchItemTrackingErr  event

**4. Actual behavior**
Value of varQtyToHandleOnSourceDocLine can't be modified

**5. Versions:**

- AL Language: 11.5.834620
- Visual Studio Code: 1.81.1
- Business Central: BE Business Central 22.4 (Platform 22.0.60193.0 + Application 22.4.59114.59220)
- List of Visual Studio Code extensions that you have installed:
365businessdevelopment.bdev-al-xml-doc
andrzejzwierzchowski.al-code-outline
BartPermentier.al-toolbox
chunsen.bracket-select
davidfeldhoff.al-codeactions
donjayamanne.githistory
GitHub.copilot
Gruntfuggly.todo-tree
humao.rest-client
jamespearson.al-test-runner
martonsagi.al-object-designer
ms-azuretools.vscode-azurefunctions
ms-azuretools.vscode-azureresourcegroups
ms-azuretools.vscode-azurestorage
ms-azuretools.vscode-docker
ms-dynamics-smb.al
ms-vscode.azure-account
ms-vscode.powershell
nabsolutions.nab-al-tools
nwallace.createGUID
rasmus.al-var-helper
rvanbekkum.xliff-sync
ryu1kn.partial-diff
stefanmaron.businesscentral-lintercop
vjeko.vjeko-al-objid
vscode-icons-team.vscode-icons
waldo.al-extension-pack
waldo.crs-al-language-extension
wayou.vscode-todo-highlight
wbrakowski.al-navigator
yzhang.markdown-all-in-one

**Comment by dannoe** [comment] 2023-09-05 16:02
This is an issue that belongs to this repository: https://github.com/microsoft/ALAppExtensions/issues
Duplicate of https://github.com/microsoft/ALAppExtensions/issues/23481

**Comment by BazookaMusic** [comment] 2023-09-06 14:55
> This is an issue that belongs to this repository: https://github.com/microsoft/ALAppExtensions/issues Duplicate of [microsoft/ALAppExtensions#23481](https://github.com/microsoft/ALAppExtensions/issues/23481)

Thanks for the help! Closing this issue as indeed it belongs to the other repository.

**Closed by BazookaMusic** 2023-09-06 14:55 UTC
