### ISSUE TITLE
 The request for path /v1.0/sandbox/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: The extension was unable to be deployed due to a dependency between extensions.

### ISSUE THREAD

**Issue by adityasalwan** [Microsoft/AL#3964] opened 2018-10-05 18:46 UTC
I am trying to add field to sales order page and getting this error

// Table Extension Code

tableextension 50131 salesOrderTableElement extends "Sales Header"
{
    fields
    {
        field(50131; MEMO; Code[250])
        {
            DataClassification = ToBeClassified;
            Caption = 'MEMO';
        }
    }
}

// Page Extension Table

pageextension 50132 SalesOrderExtension extends "Sales Order"
{
    layout
    {
        addlast(General)
        {
            field(MEMO; MEMO)
            {
                ApplicationArea = "All";
            }
        }
    }

**Comment by pzentner** [comment] 2018-10-05 19:41
I have noticed that only when I have a tenant specific extension installed that extends another extension and then trying to update the underlying extension. Do you have any other extensions installed that maybe extend the Sales Header table or do you have another tenant specific extension installed and maybe are overlapping object ids?

I am just trying to determine where the issue is coming from, since there are probably a few different options to look at.

**Comment by adityasalwan** [comment] 2018-10-05 19:58
> I have noticed that only when I have a tenant specific extension installed that extends another extension and then trying to update the underlying extension. Do you have any other extensions installed that maybe extend the Sales Header table or do you have another tenant specific extension installed and maybe are overlapping object ids?
> 
> I am just trying to determine where the issue is coming from, since there are probably a few different options to look at.

No, There's Nothing like that.. This issue of mine is solved 
But now i have another issue and that is the field i have created for "Sales Order" Page is Coming in designer Mode and not directly on page and also when i try to place that field it shows error and says It doesn't work

If you could help me this case.

**Comment by pzentner** [comment] 2018-10-05 20:37
You will have to update your ApplicationArea. It should be

`
ApplicationArea = All;
`

So, no quotes around the "All".

**Comment by adityasalwan** [comment] 2018-10-05 20:51
> You will have to update your ApplicationArea. It should be
> 
> `ApplicationArea = All;`
> 
> So, no quotes around the "All".

Thanks sir
I am Learning 365
I am working on this and My Motive is to make This Field mandatory in such a way that untill this field is not filled Sales order can not be posted and also this field to appear on posted sales invoice page
I hope if you can help me

**Comment by pzentner** [comment] 2018-10-05 20:58
You will have to add this field to the posted header(s), for instance, if you want to store this on the invoice and shipment. Then you will have to determine where in the process you want to check for a value in this field. You can use the event recorder to determine the events that are called during this process and then determine the correct event to subscribe to. Then you only have to subscribe to the event and throw an error, if the field is empty.

You will have to select the proper event, ideally, before any posting is started so that you don't start processing transactions and then have the system have to roll back the transaction or - even worse - some of the transaction is already committed to the database and then only rolls back a partial transaction.

I personally would actually validate empty fields during the release process rather than posting, since the release is always called before the posting, even if the user did not release the document separately.

**Comment by adityasalwan** [comment] 2018-10-05 21:15
> You will have to add this field to the posted header(s), for instance, if you want to store this on the invoice and shipment. Then you will have to determine where in the process you want to check for a value in this field. You can use the event recorder to determine the events that are called during this process and then determine the correct event to subscribe to. Then you only have to subscribe to the event and throw an error, if the field is empty.
> 
> You will have to select the proper event, ideally, before any posting is started so that you don't start processing transactions and then have the system have to roll back the transaction or - even worse - some of the transaction is already committed to the database and then only rolls back a partial transaction.
> 
> I personally would actually validate empty fields during the release process rather than posting, since the release is always called before the posting, even if the user did not release the document separately.

Sir,
Can you please help me in this. I am just the beginner 
can you help me what logic we have to place to get desired output 
i only want this filed to be mandatory and when we hit the post button and we open posted sales invoice.. I want this field to appear there 
THANK YOU

**Comment by pzentner** [comment] 2018-10-05 21:20
I'm sorry, but this forum is not really the right place to teach AL development in business central or the application itself. There is a lot of training material out there and i would suggest to maybe take a class in AL development.

We are here to answer specific technical questions or look into possible AL bugs and are more than happy to help with that.

**Comment by StanislawStempin** [comment] 2018-10-10 20:14
Thank you @pzentner for helping answer this one.

**Closed by StanislawStempin** 2018-10-10 20:14 UTC
Labels: question
