### ISSUE TITLE
Suggestion: Improvment for "Renaming" of objects, that includes whitespaces in the object name

### ISSUE THREAD

**Issue by megel** [Microsoft/AL#1291] opened 2017-12-22 12:43 UTC
When I select the **tail** of the obejct name e.g.:
![grafik](https://user-images.githubusercontent.com/15800069/34298241-1a20f8de-e71d-11e7-880c-d711199c8250.png)

The rename functionality provides only the part, where the cursor is located for renaming input:
![grafik](https://user-images.githubusercontent.com/15800069/34298192-cac77f4c-e71c-11e7-9048-9be6d1adf5f7.png)

IMHO, the correct behavior would be the full "Object Name", which happens, when you select the first part of the name:
![grafik](https://user-images.githubusercontent.com/15800069/34298324-81bf202e-e71d-11e7-95cf-f5f14eb50b1f.png)
![grafik](https://user-images.githubusercontent.com/15800069/34298338-99740270-e71d-11e7-95ae-1aa59b46c4fb.png)

**Comment by DominikDitoIvosevic** [comment] 2017-12-27 10:01
Unfortunately, this is a limitation of Visual Studio Code which we have not been able to go around. We are looking into how to fix this.

**Comment by qutreson** [comment] 2018-02-13 12:00
Duplicate of #498

**Closed** 2018-02-13 12:01 UTC
Labels: duplicate
