### ISSUE TITLE
JsonObject.Replace(Text, JsonToken) Method is not doing what is says in the documentation.

### ISSUE THREAD

**Issue by PPExperlogix** [microsoft/AL#7221] opened 2022-10-21 13:15 UTC
Please include the following with each issue:

**1. Describe the bug**
The documentation saids that jsonObject.Replace replaces the value of the given key.
![image](https://user-images.githubusercontent.com/116359562/197198877-af2c3039-f619-4c3a-b10d-ec5b8382709a.png)

In reality it's removing the entire key and adding it back to the end of the object.
![image](https://user-images.githubusercontent.com/116359562/197198404-41e5ee51-bb1d-4969-b833-6686c6b5523a.png)
This is the object we send.

And this is the object we get returned
![image](https://user-images.githubusercontent.com/116359562/197198629-9eefe00b-4ff2-4aa2-9dcb-48237165ea56.png)

**2. To Reproduce**

``` AL
local procedure ReplaceValue()
    var
        jObject: JsonObject;
    begin
               jObject.ReadFrom('{"1": "B","2": "B",}');
               jObject.Replace(Format(1), 'A');
    end;
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
That the replace function does not disrupt the overal structure of the jsonobject.

**4. Actual behavior**
Remove key and places it on the bottom of the json object.

**5. Versions:**

- AL Language:
-
![image](https://user-images.githubusercontent.com/116359562/197200213-e5c284b5-1691-4afd-8bd7-af2e169a7742.png)

- Visual Studio Code:
Latest version
- Business Central:
![image](https://user-images.githubusercontent.com/116359562/197199995-b899e9e2-cb93-4628-a6f6-0f57015c4115.png)

- List of Visual Studio Code extensions that you have installed:
![image](https://user-images.githubusercontent.com/116359562/197200344-7e0c40db-606c-420b-a59e-32ee1d51f662.png)

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by mjmatthiesen** [comment] 2022-10-21 20:06
Can I ask what the issue is with the key being moved to the bottom?

**Comment by PPExperlogix** [comment] 2022-10-24 07:28
We start with a certain structure in the documents because they can become extreemly big.
When we are debugging our application we can check these documents for wrong data.
And it can become really messy when values are moving back and fort all the time.

And like stated before the documentation is stating something different.
It telling me it changing the value of the property and not removing and adding a new key.

Most implementations like newtonsoft have a function to just change the value without destroying the structure.

**Comment by thloke** [comment] 2022-11-01 07:36
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

The reason why this is out of scope is because it relates to the runtime behaviour of BC, so it needs to go to the team who handles the runtime.

**Closed by thloke** 2022-11-01 07:36 UTC
