### ISSUE TITLE
Cannot reference Internal objects within permissionset

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL#6765] opened 2021-09-16 07:36 UTC
**Description**
When referencing Internal object within permissionset, we receive the following error:

_error AL0161: 'System Initialization Impl.' is inaccessible due to its protection level_

**Way to Reproduce**
use the following code 
```
permissionset 50000 testpermissionset
{
    Assignable = true;
    Permissions =
        CodeUnit "System Initialization Impl." = X;
}
```

**Expected behavior**
We should be able to reference any type of objects within the permissionset object. When permissions were stored as data, it was possible to add internal objects to our permission sets. 

**5. Versions:**
- AL Language: v7.4.502459
- Visual Studio Code: 1.60.1
- Business Central: Version: W1 18.2 (Platform 18.0.26213.26464 + Application 18.2.26217.26490)
- List of Visual Studio Code extensions that you have installed: not relevant

**Comment by dnpb** [comment] 2021-09-16 08:22
You won't be able to call that codeunit from your app, so I don't see why your app should need or be able to grant permissions for it. What/why is the exact requirement?

**Comment by nicolassaleron** [comment] 2021-09-16 08:49
I have logged a similair issue here #6693 

Maybe Microsoft could give us some guidance here but from my point of view, permissionset is not the same thing as regular object that reference object to run something.
If your app is doing something that indirectly calls an internal or Scope(OnPrem) object, then, to make your app running out of the box you have to provide a permissionset that sets permissions on this object.

**Comment by gintuoklis** [comment] 2021-09-16 09:14
We are not using any of the standard MS permissions, since they are gives way too much access. For e.g.  D365 BASIC gives access to all reports,pages,codeunits...
![image](https://user-images.githubusercontent.com/16342128/133584909-99f84c17-afad-496d-8a42-cbe40cd00295.png)

Therefore, we are creating our own permission sets and handle MS objects there. We been doing it successfully when permission s were stored as data. Now, we want to transfer all our stuff to the AL objects. Here we have an issue with MS Internal objects. I cannot reference them within our permission set. I fully understand the meaning of Internal object, but I don't think the same rules should apply for the permissionset objects. We are not calling functions here, we just listing which objects user can execute.

And yes, user still needs to execute your internal objects. Without execute permission on "System Initialization Impl.", you cannot open BC. You get this error when trying to login:
![image](https://user-images.githubusercontent.com/16342128/133585440-8a91096b-7eb2-4d9c-9e96-04cd99299b9c.png)

**Comment by grobyns** [comment] 2021-09-20 08:38
Hi,

We set the access level to internal on certain objects to avoid dependencies on those objects so that we are free to change the objects without the risk of breaking anyone. If you were to include those objects in permission sets, that would be a dependency and we would not be able to freely change the object.

To solve the issue, you need to assign the permissionset "System App - Basic" to all users OR include that permissionset in one of your own permissionsets so it ends up assigned to all the users. That permissionset has all the required permissions to the run the system application and does not include permissions to anything else (so no Codeunit * = X for example).

We (MS) secure the system only on the tabledata type and allow access to all other object types. We do that by including the "BaseApp Objects - Exec" permissionset in for example "D365 BASIC". With that, users have access to all objects of all types except tabledata.

If you choose to set permissions also on codeunits, pages, reports etc then you can't use the MS provided permissionsets but you must still assign or include "System App - Basic" to be able to run the system.

I hope this helps... 

br/Gert

**Comment by gintuoklis** [comment] 2021-09-20 13:56
Hey @grobyns, 
Thank you for you reply. I followed your advice and included "System App - Basic" to our permission sets. Nevertheless, I still cannot access the system, since I have no access to _CodeUnit System Initialization Impl.: Execute._ I looked inside "System App - Basic", and there I see no permissions for any of codeunits, just tabledata permissions. Is there some other permission I should include. I am afraid, including "BaseApp Objects - Exec"  is not an option for us.

**Comment by grobyns** [comment] 2021-09-20 13:59
Hi,

I'll have to double check but if that's the case we'll need to create a permission set in the system application which grants permissions on the internal objects for you to include in your own permissionsets.

br/Gert

**Comment by gintuoklis** [comment] 2021-09-21 10:22
here's the list of internal codeunits, i needed in order to run our BC and other basic screens (like opening role centers, and item cards)

<html>
<body>


Object Type | Object ID | Object Name | Read Permission | Insert Permission | Modify Permission | Delete Permission | Execute Permission | Security Filter
-- | -- | -- | -- | -- | -- | -- | -- | --
Codeunit | 54 | Language Impl. |   |   |   |   | Yes |  
Codeunit | 55 | Caption Class Impl. |   |   |   |   | Yes |  
Codeunit | 59 | Auto Format Impl. |   |   |   |   | Yes |  
Codeunit | 151 | System Initialization Impl. |   |   |   |   | Yes |  
Codeunit | 1432 | Satisfaction Survey Impl. |   |   |   |   | Yes |  
Codeunit | 1596 | Email Installer |   |   |   |   | Yes |  
Codeunit | 1818 | Navigation Bar Sub. Impl. |   |   |   |   | Yes |  
Codeunit | 1819 | Advanced Settings Ext. Impl. |   |   |   |   | Yes |  
Codeunit | 1908 | Camera Page Impl. |   |   |   |   | Yes |  
Codeunit | 1922 | Camera Impl. |   |   |   |   | Yes |  
Codeunit | 2301 | Tenant License State Impl. |   |   |   |   | Yes |  
Codeunit | 3702 | Environment Information Impl. |   |   |   |   | Yes |  
Codeunit | 3703 | Server Setting Impl. |   |   |   |   | Yes |  
Codeunit | 3907 | Retention Policy Installer |   |   |   |   | Yes |  
Codeunit | 4032 | Client Type Mgt. Impl. |   |   |   |   | Yes |  
Codeunit | 9013 | User Login Time Tracker Impl. |   |   |   |   | Yes |  
Codeunit | 9017 | Azure AD User Mgmt. Impl. |   |   |   |   | Yes |  
Codeunit | 9018 | Azure AD Plan Impl. |   |   |   |   | Yes |  
Codeunit | 9177 | Application Area Cache |   |   |   |   | Yes |  
Codeunit | 9702 | Cues And KPIs Impl. |   |   |   |   | Yes |  
Codeunit | 9996 | Upgrade Tag Impl. |   |   |   |   | Yes |  


</body>
</html>

**Comment by grobyns** [comment] 2021-10-04 16:17
Hi,
 
this issue will be mitigated by including execute permission for all objects in the system application in ‘System App - Basic’.
 
You still won’t be able to reference internal objects as that is by design but with this update you won’t need to.
 
It will be included in an upcoming update for v19.

**Comment by gintuoklis** [comment] 2021-12-27 15:25
Hey @grobyns,

Do you know if issue been solved already?
We just bumped our extension to 19.1, and I see another codeunit missing when opening company.

`While opening company 'AutoTest', the following error occured: 'You do not have the following permissions on CodeUnit Application Area Cache: Execute
`

**Comment by thloke** [comment] 2024-04-30 06:04
Thanks for the suggestion. We've discussed this internally and have agreed that this is an improvement request that needs to be prioritized. Since this is an improvement and not a bug, you can post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Closed by thloke** 2024-04-30 06:04 UTC
Labels: bug

**Comment by grobyns** [comment] 2024-04-30 07:29
> Application Area Cache

Hi,
I can see codeunit "Application Area Cache" is included in this permissionset:
permissionset 23 "Internal BaseApp Obj. - Exec"
br/Gert

**Comment by thloke** [comment] 2024-04-30 08:12
> Thanks for the suggestion. We've discussed this internally and have agreed that this is an improvement request that needs to be prioritized. Since this is an improvement and not a bug, you can post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

To clarify on this, the Access and Scope modifiers behaviour in these cases is by design. For you to build permissionsets that contain these objects without resorting to the wildcard (*), the owning app of the object (in this case Base Application) must provide an appropriate permissionset for you to include in yours. We do our best to provide these permissionsets but we cannot predict every possible scenario. If you encounter issues like these, please post an issue on [microsoft/ALAppExtensions](https://github.com/microsoft/ALAppExtensions) with some details about which permission/permissionset you are missing.
