### ISSUE TITLE
CodeCop Rule: AA0214 The record {0} should be modified before saving to the database.

### ISSUE THREAD

**Issue by dyepri** [microsoft/AL#5787] opened 2020-04-08 07:44 UTC
**Describe the bug**
We have recently update our AL Language extension into 5.0.254558 then having ${CodeCop} declared under code analyzer it is now giving me hundreds of warnings. One of them is the CodeCop Rule: AL0214 The record {0} should be modified before saving to the database.

**To Reproduce**
Steps and to reproduce the behavior:
1. Make sure you are using the updated AL Language extension (5.0.254558)
2. Declare a record variable on your code.
3. A warning will appear stating the variable record you declared should be modified before saving to the database.

``` AL Code to reproduce the issue ```

**Expected behavior**
There should be no warnings since it is being use.

**Screenshots**
![image](https://user-images.githubusercontent.com/41933086/78757778-5f6ecc80-79c0-11ea-9626-b46e7d43ea58.png)

**5. Versions:**

 - AL Language: 5.0.254558

 - Business Central: 16.0.11209.0 (Preview)

**Comment by Jeeve65** [comment] 2020-04-08 12:03
Came here to report the same

**Comment by NCMiMa** [comment] 2020-04-08 15:54
Hi, here the same!

**Comment by nicolassaleron** [comment] 2020-04-09 11:14
Is not it a duplicate of [this issue](https://github.com/microsoft/AL/issues/5665)?

**Comment by dtkb** [comment] 2020-04-16 16:24
> Is not it a duplicate of [this issue](https://github.com/microsoft/AL/issues/5665)?

Yes, so since this one has been marked as `in-progress`, that one should be closed.

**Comment by MarcHansenMicrosoft** [comment] 2020-04-17 10:45
Just wanted to keep it if there was a variation to cover.
Thanks

**Comment by MarcHansenMicrosoft** [comment] 2020-06-30 12:10
fixed in master

**Closed by MarcHansenMicrosoft** 2020-06-30 12:10 UTC
Labels: CodeCop, bug, in-progress, static-code-analysis

**Comment by shahramab** [comment] 2020-09-05 04:35
Hi
How it is fixed?
