### ISSUE TITLE
[Txt2AL] Error with factboxes

### ISSUE THREAD

**Issue by LFlamme** [microsoft/AL#4590] opened 2019-02-11 09:33 UTC
Hi,
The Bug reported in #1618 still exists in the Txt2al Tool in BC CU2 ( Build 26556).
What Version do i need so i don´t have the Bug anymore. Bug was solved almost a year before CU2...
![image](https://user-images.githubusercontent.com/41729653/52554863-70d23e00-2de8-11e9-97f1-49c8af557b9b.png)

thanks

**Comment by thpeder** [comment] 2019-02-13 14:33
Hi @LFlamme,
It should be fixed.
How did you export the .txt files and create the delta file?

**Comment by LFlamme** [comment] 2019-02-13 14:39
I Exported the base using the Development Sehll with this command:
![image](https://user-images.githubusercontent.com/41729653/52719037-129e8a00-2fa5-11e9-9b1d-d4f1def339b2.png)
Then the modified objects:
![image](https://user-images.githubusercontent.com/41729653/52719065-23e79680-2fa5-11e9-8c7c-35e2f719f2d8.png)

Then i created the deltafiles using powershell:
`Import-module 'C:\Program Files (x86)\Microsoft Dynamics 365 Business Central\130\RoleTailored` `Client\Microsoft.Dynamics.Nav.Model.Tools.psd1'`

`$base = 'C:\VG2AL2\1Base'`
`$modified = 'C:\VG2AL2\2mod'`
`$delta = 'C:\VG2AL2\3delta'`

`Compare-NAVApplicationObject -OriginalPath $base -ModifiedPath $modified -DeltaPath $delta -ExportToNewSyntax`

**Comment by thpeder** [comment] 2019-04-11 08:30
Could you please give this a try on the latest developer preview since it seems to be fixed and if it still doesn't work could you please provide the .txt files you are using.
If you find it fixed and you need it as an update to an earlier version then please open a support case.
You can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by qutreson** [comment] 2019-10-07 11:59
@LFlamme, closing this issue as we believe it has been fixed in our latest developer previews. Please note that for verifying fixes related to the txt2al, you need to check out our latest developer previews for the version 14.x as C/SIDE is not shipped in 15.x anymore. Feel free to log a new issue if you can still reproduce it there.

**Closed by qutreson** 2019-10-07 11:59 UTC
Labels: input-needed, txt2al
