### ISSUE TITLE
Error “Property “Editable” for Quantity is invalid!” Sales Order Lines

### ISSUE THREAD

**Issue by Martin-Lavigne** [Microsoft/AL#4786] opened 2019-03-26 18:32 UTC
We are using a Custom Page to create Sales Order in Business Central. 
Our App was published and we were able to create Sales Order Correctly. 
In one of the latest version, we started to received : Property “Editable” for Quantity is invalid! 
Every time that we try to call our Sales Order Page. 
The header is created correctly but no line are inserted. 
We are calling the Custom Page using SOAP.

**Comment by Martin-Lavigne** [comment] 2019-03-26 19:24
I was able to create the Order Line by removing the line : 
Editable=NOT IsCommentLine;

**Comment by Martin-Lavigne** [comment] 2019-04-01 15:34
The problem seems to be affecting most of the Sales Order Line "Editable" property. I have seen the same issue occurred on Quantity, Unit Price and Line Discount. 
Although, I'm able to use the "Editable" property on the Sales Order header without any error.

**Comment by atoader** [comment] 2019-04-04 11:53
Hi! Could you please provide an AL snippet to reproduce this issue? What is the version of your runtime?

**Comment by PooyaKharamesh** [comment] 2019-05-03 11:58
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Closed by PooyaKharamesh** 2019-05-03 11:58 UTC
Labels: input-needed
