### ISSUE TITLE
Compile don't show any errors due a function of type [Normal]

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#2938] opened 2018-07-18 15:45 UTC
This function will break the compiler.

![image](https://user-images.githubusercontent.com/28626283/42892459-2f6465d0-8ab2-11e8-82a3-44b037a11960.png)

It's easy to create this:

1. In C/AL create a empty upgrade codeunit (Subtype = Upgrade)
2. Create a empty function and set the FunctionType on Normal (thus not <Normal> but **Normal**
3. Save the codeunit 50.000 and close the codeunit
4. Create a new report 50.000 and copy/paste the function from codeunit 50.000
5. Convert this object to AL and add this object into your project

**Comment by thpeder** [comment] 2018-07-19 07:17
Hi @bvbeek,
What do you mean by it will break the compiler?

I tried to reproduce the issue, and it simply gives an error that the Attribute Normal can only be used for codeunits with subtype test.
```
codeunit 50000 MyNormalCodeunit
{
    Subtype = Upgrade;

    [Normal]
    local Procedure EmptyProcedure()
    begin
    end;
}
```

**Comment by bvbeek** [comment] 2018-07-19 08:11
Hi @thpeder,
Please remove the line

`Subtype = Upgrade;`

In my scenario, you can see that I copy an upgrade function from an upgrade codeunit to a new clean non-upgrade codeunit.

**Comment by thpeder** [comment] 2018-07-19 08:18
I still just get the diagnostic that it is not valid.
What are you experiencing since you say it breaks it?

**Comment by bvbeek** [comment] 2018-07-19 08:19
Sorry Thomas, the destination object must be report (not a codeunit)

```
report 50000 MyReport
{
    [Normal]
    local Procedure EmptyProcedure()
    begin
    end;
}
```

**Comment by thpeder** [comment] 2018-07-19 08:22
Now the error just changed slightly to say that you can only use that attribute in a codeunit.

**Comment by thpeder** [comment] 2018-07-19 08:31
It seems to be fixed in a later version. I can reproduce it for the version you are using.

**Comment by bvbeek** [comment] 2018-07-19 09:50
Great 👍

**Closed** 2018-07-19 11:32 UTC
Labels: bug
