### ISSUE TITLE
Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by A-R-Shaji** [Microsoft/AL#2426] opened 2018-05-30 10:51 UTC
how to identify what is causing this issue?

[Error - 6:41:18 AM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'Index was outside the bounds of the array.'
StackTrace:
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportMetadataEmitter.RemoveUtf8Preamble(String content) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportMetadataEmitter.cs:line 126
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportMetadataEmitter.ConsumeLayout(XmlWriter xmlWriter, PropertyKind propertyKind, Func`2 converter, String xmlMetadataConstant, String defaultLayout) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportMetadataEmitter.cs:line 105
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportMetadataEmitter.ConsumeReportLayouts(XmlWriter xmlWriter) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportMetadataEmitter.cs:line 54
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportMetadataEmitter.<>c__DisplayClass1_0.<EmitMetadata>b__0(XmlWriter xmlWriter) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportMetadataEmitter.cs:line 47
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitter`1.EmitMetadata(Action`1 content) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\GenericObjectMetadataEmitter.cs:line 37
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.EmitMetadata(ObjectTypeSymbol containingType) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 251
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileObject(ObjectTypeSymbol containingType) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 243
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.<>c__DisplayClass16_0.<CompileObjectAsTask>b__0() in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 211
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:line 152
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.WaitForWorkers() in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 161
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethodBodies(Compilation compilation, ModuleBuilder moduleBeingBuiltOpt, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 145
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.CompileImpl(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 816
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.Compile(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 791
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.PackageTheModule(Compilation compilation, CompilerTextWriter consoleOutput, CancellationToken cancellationToken, ErrorLogger errorLogger, AnalyzerDriver analyzerDriver) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 551
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 414
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 313
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<HandleAsync>d__3.MoveNext() in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

**Comment by DominikDitoIvosevic** [comment] 2018-05-30 11:32
@A-R-Shaji . Which version of the platform and the compiler are you using?

**Comment by A-R-Shaji** [comment] 2018-05-30 13:09
AL Compiler version 0.15.18771
Version 12.0.21812

**Comment by qutreson** [comment] 2018-07-03 15:02
Hi @A-R-Shaji, are you still getting the same error when using the latest extension from the marketplace (version 0.16.16948)? The issue is related to the layout of one of your reports. If the issue still reproduce with the newer version of the extension, can you try to identify which report is failing and provide us with some repro to investigate it?

**Comment by qutreson** [comment] 2018-07-17 13:02
Closing this issue as I could not reproduce it. If you can still reproduce it with the latest AL extension, please log a new issue with some repro steps so that we can investigate it.

**Closed by qutreson** 2018-07-17 13:02 UTC
Labels: input-needed, investigate
