### ISSUE TITLE
Incorrect Tooltip when hovering column or field heading

### ISSUE THREAD

**Issue by ShadowXVII** [Microsoft/AL#4179] opened 2018-11-08 22:35 UTC
* Reproducible on bcmaster
* Affects all Business Central deployments

## Issue
When hovering columns (or fields) with the mouse you receive a tooltip to press Ctrl+F1 to "learn more".

![image](https://user-images.githubusercontent.com/446329/48231482-6166e180-e402-11e8-93ae-5c6d5a316ee0.png)

This is misleading and doesn't apply to Business Central.

## Expected Result
Instead, when you right click and click "Whats this?", you get a Learn More link, which is what should happen when hovering.

![image](https://user-images.githubusercontent.com/446329/48231537-92471680-e402-11e8-9862-3b6fed68cf80.png)

**Comment by StanislawStempin** [comment] 2018-11-21 13:43
Answer from the client team:
So this is currently by design, therefore I am closing this.
We show the shortcut on hover to make the user aware that this shortcut is available. When the user then clicks "What's this" or click a caption, we show the link directly instead.

Currently we are working on a more consistent and efficient way of showing shortcuts throughout Business Central and as part of this, we will also have a look at this specific case.

**Closed by StanislawStempin** 2018-11-21 13:43 UTC
Labels: cross-team-investigate

**Comment by ShadowXVII** [comment] 2018-11-21 20:56
I'm not sure if you've misunderstood the issue -- Ctrl+F1 doesn't work as a shortcut... Or is it a Chrome-specific bug?

**Comment by ShadowXVII** [comment] 2019-06-06 05:42
This was never resolved, and still occurs in BC 140.
