### ISSUE TITLE
Debugger crashes with a '.... is not a field on the target object which is of type...'

### ISSUE THREAD

**Issue by salgiza** [microsoft/AL#5860] opened 2020-05-07 10:27 UTC
**Describe the bug**
The debugger sometimes crashes with an error message like this (this one just happened to a coworker):

> Error: Field 'dtldCommissionEntry' defined on type 'Microsoft.Dynamics.Nav.BusinessApplication.Codeunit72116+TestEditManualDirectCommission_Scope_520575644' is not a field on the target object which is of type 'Microsoft.Dynamics.Nav.BusinessApplication.Codeunit72116+CheckEditManualDtldCommissionEntry_Scope__380509629'.

**To Reproduce**
We can't always reproduce it but we have found out that it is related to this combination:

* Two methods have a local variable with the same name. In the previous log, both procedures TestEditManualDirectCommission and CheckEditManualDtldCommissionEntry had a local record variable called DtldCommissionEntry.
* One of them calls the other.
* The variable name is added to the "Watch" panel in the VS Code debugger.

So: 
* Create two methods (say A & B) in a codeunit, each of them with some random code and two record variables pointing to the same table with the same name.
* Call procedure B from procedure A. 
* We don't know if this is required, but add some code in procedure A and B that filters and reads records from the table.
* Debug and add a watch to the variable name.
* Debug a few times (it doesn't always crash the first time).

**Expected behavior**
The debugger should not crash, I guess.

**5. Versions:**
 - AL Language: 5.0.254558
 - Business Central: Platform 16.0.11233.11434 + Application 16.0.11240.11473

**Comment by fvet** [comment] 2020-05-11 11:30
I've faced the same errors a lot, but can't find a real pattern ...

> Error: Field 'shipmentCost' defined on type 'Microsoft.Dynamics.Nav.BusinessApplication.Page2002986+PageCopy_Scope_1828964748' is not a field on the target object which is of type 'Microsoft.Dynamics.Nav.BusinessApplication.Record2002946+CopyCostsToServices_Scope_1238731984'.

One this error occurs, my 'variables' pane remains empty till I kill the debug session.

**Comment by atoader** [comment] 2020-05-11 19:26
Is there anything in the event viewer related to this?

**Comment by atoader** [comment] 2020-05-12 10:51
We've published an update to the VSIX that might solve this issue. Could you please let us know if you still encounter the problem after upgrading?

**Comment by salgiza** [comment] 2020-05-13 09:11
@atoader We just checked with the latest version of the AL extension (5.0.271898, the one published yesterday to the Marketplace) and the debugger crashed as soon as we added the variable (with the same name in both methods) to the watch panel.

**Comment by atoader** [comment] 2020-05-14 05:13
@kalberes

**Comment by charlespockert** [comment] 2020-11-11 18:43
This is still a problem for me - still crashing the debugger leaving the debug session in break mode. If I'm debugging something that's writing, it often locks the DB for 30 minutes. I have to down tools most of the time until this resolves.

**Comment by kalberes** [comment] 2020-11-12 12:01
@charlespockert 
Are your repro steps the same? Meaning that watch issue defined above? Else please open a new issue. 
If your code locks, then AL execution locks. We have a fix for 17.2 that if you close debugging from VsCode it will close the current operation, thus you should not get blocked. But that is for 17.2.

**Comment by charlespockert** [comment] 2020-11-12 18:33
> @charlespockert
> Are your repro steps the same? Meaning that watch issue defined above? Else please open a new issue.
> If your code locks, then AL execution locks. We have a fix for 17.2 that if you close debugging from VsCode it will close the current operation, thus you should not get blocked. But that is for 17.2.

Yes, I'd say based on my experience I'm pretty confident it's the same as the above.

I'm not a big user of the "watch" window, I tend to use the "hover" feature to look at values during debug, but if I don't try to look at any variables the debugger is fine.

Its **always** when I'm trying to look at a value.

Normal step-through doesn't cause an issue.

**Comment by ivanrlg** [comment] 2020-11-19 20:20
Hello, the same thing happens to me, any tip to unlock the DB quickly?

**Comment by thloke** [comment] 2022-11-15 10:02
We're working on this under #7225, closing this as duplicate of that.

**Closed by thloke** 2022-11-15 10:02 UTC
Labels: debugger, requires-triage
