### ISSUE TITLE
Debugger displays FieldRefs as RecordRefs

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#5849] opened 2020-04-30 07:46 UTC
**Describe the bug**
Using the debugger, when a FieldRef has been set, it is not possible to determine which field is set, and what the content of the field is.

**To Reproduce**
Debug the following function and hover over variable SourceFieldRef, and review the debugger "Locals" on the left: We can see the whole record, just like in the RecordRef.

```
local procedure TestFieldRef()
    var
        Item: Record Item;
        RecordRefSource: RecordRef;
        SourceFieldRef: FieldRef;
    begin
        Item.FindFirst();

        RecordRefSource.GetTable(Item);
        SourceFieldRef := RecordRefSource.FieldIndex(1);
    end;
```

**Expected behavior**
For the FieldRef, the debugger should not display the record, but only the current field and its value.

**Screenshots**
![image](https://user-images.githubusercontent.com/34504100/80685064-ec400e00-8ac6-11ea-86de-aadbd2a91429.png)

**5. Versions:**

 - AL Language: 5.0.254558

 - DE Business Central 16.0 (Platform 16.0.11233.12436 + Application 16.0.11240.12474)

**Comment by kalberes** [comment] 2020-04-30 17:19
I would not make this as a bug. This is extra information caused by legacy behaviour. I have not checked, but the old RTC has shown this the same way.

**Comment by NKarolak** [comment] 2020-04-30 19:10
Weird, I remember it differently 🤔
Even if it was true: How am I supposed to control the target and content of my FieldRef?

**Comment by kalberes** [comment] 2020-05-12 13:57
Ok this was about field refs, not record refs. Good then it is a bug.

**Comment by NKarolak** [comment] 2021-02-01 13:38
Still persistent in AL 6.1.397164, runtime 5.0.

**Comment by JesperSchulz** [comment] 2021-07-20 04:31
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 28023 and VS Code Extension Version 8.0.491888. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Closed by JesperSchulz** 2021-07-20 04:31 UTC
Labels: bug, debugger, in-progress, ships-in-future-update
