### ISSUE TITLE
Usage of the CurrReport.Skip method in report extensions

### ISSUE THREAD

**Issue by AndriiSeverin** [microsoft/AL#7039] opened 2022-05-11 18:07 UTC
**1. Describe the bug**
The usage of the [**CurrReport.Skip**](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/reportinstance-skip-method) method in the [OnBeforeAfterGetRecord](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers-auto/reportextensiondatasetmodify/devenv-onbeforeaftergetrecord-reportextensiondatasetmodify-trigger) trigger doesn't influence on the execution of the **OnAfterGetRecord** trigger of the corresponding data item.

Could you please check whether it is expected behavior (limitation for the report extensions objects) or not (it is a bug)?

**2. To Reproduce**
1. Create a new app with the following report extension:
```AL
reportextension 50100 "TEST Get Item Ledger Entries" extends "Get Item Ledger Entries"
{
    dataset
    {
        modify("Item Ledger Entry")
        {
            trigger OnBeforeAfterGetRecord()
            begin
                CurrReport.Skip();
            end;
        }
    }
}
```
2. Add the following breakpoints:
- in the first line of the **OnBeforeAfterGetRecord** trigger (in the report extension)
- in the first line of the **OnAfterGetRecord** trigger of the "**Item Ledger Entry**" data item (in the original report)
3. Publish and debug an app.
4. Run report 594 (**Get Item Ledger Entries**).

**3. Expected behavior**
The **OnAfterGetRecord** trigger of the "**Item Ledger Entry**" data item is not executed.

**4. Actual behavior**
The **OnAfterGetRecord** trigger of the "**Item Ledger Entry**" data item is executed.

**5. Versions:**
- AL Language: v9.0.615906
- Visual Studio Code: 1.67.1
- Business Central: 20.1 BE
- List of Visual Studio Code extensions that you have installed: unrelated

#6949

**Comment by TMEKUMA** [comment] 2023-02-28 13:49
Do you have any new information on this?

**Comment by thloke** [comment] 2023-03-01 04:44
This is currently out of scope for this github repository, so we're not actively looking at this. If it's urgent or blocking, I suggest contacting customer support through partner source.

**Closed by thloke** 2023-03-01 04:44 UTC
Labels: runtime - Out of Scope

**Comment by fvet** [comment] 2023-12-06 10:44
Still facing the same on BC23.0
Created incident report 2312060060002985

**Comment by fvet** [comment] 2023-12-27 16:03
Update from MS support team: 

> ... they agreed to create a bug, we created a bug (495100), which you shall track in upcoming release.

**Comment by pri-kise** [comment] 2024-08-05 12:57
@fvet do you know if this is fixed in BC24?

**Comment by thloke** [comment] 2024-08-06 01:49
I've looked up the current status of the bug internally, and it's been closed as By Design. Documentation has been updated around this.

The reason why this is By Design is that many reports bind to Integer table, and then have trigger logic in OnAfterGetRecord to advance a temporary record/query/etc.. These reports would break if the OnAfterGetRecord  was skipped. The skip does correctly make the data not be included in the final dataset even if the trigger is still called.

**Comment by duichwer** [comment] 2024-08-06 04:52
Thanks for the detailed answer.
This makes it more complicated to deal with Report Extensions, but at least it's documented now.
We have some copied reports where we don't want to print some lines in a report an therefore don't want to include those lines in the total amount.
If we were able to skip the On AfterGetRecord Code with this then we could easily move from copied reports to report extensions.
The workaround would be to substract the values from the line on the OnAfterOnAfterGetRecord.

Furthermore the value of the variable FirstValueHasBeenOutput would be wrong if the trigger is executed, but the line is ommitted in the output.

**Comment by thloke** [comment] 2024-08-06 05:26
One solution would be to introduce a `skipTriggers` param for `CurrReport.Skip()`  so it's like `CurrReport.Skip(true)` where the default value is `false`. That way the calling report(extension) can decide whether it's okay to skip triggers. That would be a new feature request, but if it's a blocker for deduplicating reports and moving customizations to extensions, then I think that's a reasonable argument.

Raise it on BCIdeas?

**Comment by pri-kise** [comment] 2024-08-06 05:38
I've created an idea.
https://experience.dynamics.com/ideas/idea/?ideaid=6552bd01-b653-ef11-b4ac-0022484d1652

I've search again in the documentation for a note on the current behaviour but I couldn't find it.

**Comment by thloke** [comment] 2024-08-06 05:43
It's been added as a note to: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/reportinstance-skip-method#remarks
