### ISSUE TITLE
Wrong SETRANGE statement can be run with strange behavior

### ISSUE THREAD

**Issue by JalmarazMartn** [microsoft/AL#6238] opened 2020-10-22 07:02 UTC
**Describe the bug**
A wrong SETRANGE statement pass compilation, and is executed with very hard to detect issues.
If I type this wrong statement:
ItemLedgerEntry.SetRange("Entry Type"::"Assembly Output");
Instead the right statement:
ItemLedgerEntry.SetRange("Entry Type","Entry Type"::"Assembly Output");
Problem panel doesn´t show anything about this. The code is executed and no filters are applied in this field. 
**To Reproduce**
Steps and to reproduce the behavior:
1. Edit an existing .al file.
2-. Declare a Record type record this way:
var
ItemLedgerEntry: record "Item Ledger Entry";
3-. Type this wrong statement
ItemLedgerEntry.SetRange("Entry Type"::"Assembly Output");

**Expected behavior**
Problem Panel must show an error explaining that a member is expected instead a value.

**Screenshots**

**5. Versions:**
 - AL Language: v6.1.352568

**Comment by dtkb** [comment] 2020-10-22 11:00
Yup, can confirm that invalid use of an option value there passes compilation without error.

**Comment by JalmarazMartn** [comment] 2020-10-22 11:40
Not only passes compilation, run without raising any error. That´s the problem, we spent many hours trying to find why my test were wrong.

**Comment by JalmarazMartn** [comment] 2022-01-31 10:17
> Hi, Many thanks for raising this issue. Unfortunately we have not been able to get to this issue as soon as we'd have liked. Since it has been a long time since this issue was last updated, it is possible that this has been fixed by a newer release of Business Central and the AL extension for Visual Studio Code. We have thus decided to close it. If the issue still affects you on the latest insider build of Business Central, please help us and open a new issue for us with the latest steps to reproduce the issue, and link back to this closed issue to track any comments or discussions.Thanks,Thaddeus

I do not agree with your answer. The bug remains and is easy to reproduce. Notice that the complaint is that the statement does not raise compilation error. Are you getting a compilation error with "ItemLedgerEntry.SetRange("Entry Type"::"Assembly Output");"? If the anwer is no, you are reproducing the issue. Because this statement is a big error under the radar of AL compilator.

**Comment by rdebath** [comment] 2022-01-31 10:32
@thloke @PooyaKharamesh
BAD Bot.

Error is trivially reproducible; did anyone bother to actually check these?
Looks like there is only about 120 of them, IMO not worth automating.

@JalmarazMartn  Note their message says to copy/paste to a new issue number.

**Comment by thloke** [comment] 2022-01-31 11:20
@rdebath, @JalmarazMartn   - I completely agree that it would have been much more ideal if we had the time to check each issue individually regardless of its age, but unfortunately we don't. We need help sorting through our backlog of really old issues to figure out which ones are still pressing issues today, and which ones are no longer relevant.

The other alternative is letting this issue sit in the pile of old issues, which reduces the likelihood of us ever getting to this.

Thanks for taking the time to confirm that it still reproduces. For this issue I can reopen it and tag it appropriately so you do not have to create a copy.

**Comment by JalmarazMartn** [comment] 2022-01-31 11:33
> @rdebath, @JalmarazMartn - I completely agree that it would have been much more ideal if we had the time to check each issue individually regardless of its age, but unfortunately we don't. We need help sorting through our backlog of really old issues to figure out which ones are still pressing issues today, and which ones are no longer relevant.
> 
> The other alternative is letting this issue sit in the pile of old issues, which reduces the likelihood of us ever getting to this.
> 
> Thanks for taking the time to confirm that it still reproduces. For this issue I can reopen it and tag it appropriately so you do not have to create a copy.

Thak you, I appreciate your attention. It is important to fix this.

**Comment by JesperSchulz** [comment] 2022-05-19 09:48
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 40800 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Closed by JesperSchulz** 2022-05-19 09:48 UTC
Labels: bug, in-progress, ships-in-future-update
