### ISSUE TITLE
Method overload return parameter

### ISSUE THREAD

**Issue by Entreri86** [microsoft/AL#6701] opened 2021-07-09 07:51 UTC
**1. Describe the bug**
When you use function overload, it does not detect that the Record type is from another record, which gives the error AL (AL0440).

**2. To Reproduce**
Create two functions with the same input parameters and different type of return record.

``` AL
Declare this function:
internal procedure ReturnGenericPrice(customerNo: Code[20]; itemNo: Code[20]; variantCode: Code[10]; baseUnitOfMeasure: Code[10]): Record "Sales Line" temporary
    var
        tempSalesHeader: Record "Sales Header" temporary;
        tempSalesLine: Record "Sales Line" temporary;
        customer: Record Customer;
        PriceCalculation: Interface "Price Calculation";
        PriceType: Enum "Price Type";
        eventSubscriberInstanceEka: Codeunit "Event Subscriber Instance Eka";
    begin
        BindSubscription(eventSubscriberInstanceEka);
        customer.Get(customerNo);
        tempSalesHeader."Document Type" := tempSalesHeader."Document Type"::Order;
        tempSalesHeader.InitRecord();
        tempSalesHeader.SetHideValidationDialog(true);
        tempSalesHeader.Validate("Sell-to Customer No.", customer."No.");
        tempSalesHeader.Insert(true);
        tempSalesLine.SetHideValidationDialog(true);
        tempSalesLine."Document Type" := tempSalesHeader."Document Type";
        tempSalesLine."Document No." := tempSalesHeader."No.";
        tempSalesLine.Type := tempSalesLine.Type::Item;
        tempSalesLine."Sell-to Customer No." := customer."No.";
        tempSalesLine."No." := itemNo;
        tempSalesLine."Unit of Measure Code" := baseUnitOfMeasure;
        tempSalesLine."Variant Code" := variantCode;
        tempSalesLine.Insert();
        tempSalesLine.GetPriceCalculationHandler(PriceType::Sale, tempSalesHeader, PriceCalculation);
        PriceCalculation.ApplyDiscount();
        tempSalesLine.ApplyPrice(tempSalesLine.FieldNo("No."), PriceCalculation);
        exit(tempSalesLine);
    end;

And then this function in the same object:
internal procedure ReturnGenericPrice(customerNo: Code[20]; itemNo: Code[20]; variantCode: Code[10]; baseUnitOfMeasure: Code[10]): Record "Purchase Line" temporary
    var
        tempSalesHeader: Record "Sales Header" temporary;
        tempSalesLine: Record "Purchase Line" temporary;
        customer: Record Customer;
        PriceCalculation: Interface "Price Calculation";
        PriceType: Enum "Price Type";
        eventSubscriberInstanceEka: Codeunit "Event Subscriber Instance Eka";
    begin
        BindSubscription(eventSubscriberInstanceEka);
        customer.Get(customerNo);
        tempSalesHeader."Document Type" := tempSalesHeader."Document Type"::Order;
        tempSalesHeader.InitRecord();
        tempSalesHeader.SetHideValidationDialog(true);
        tempSalesHeader.Validate("Sell-to Customer No.", customer."No.");
        tempSalesHeader.Insert(true);
        tempSalesLine.SetHideValidationDialog(true);
        tempSalesLine."Document Type" := tempSalesHeader."Document Type";
        tempSalesLine."Document No." := tempSalesHeader."No.";
        tempSalesLine.Type := tempSalesLine.Type::Item;
        tempSalesLine."Sell-to Customer No." := customer."No.";
        tempSalesLine."No." := itemNo;
        tempSalesLine."Unit of Measure Code" := baseUnitOfMeasure;
        tempSalesLine."Variant Code" := variantCode;
        tempSalesLine.Insert();
        tempSalesLine.GetPriceCalculationHandler(PriceType::Sale, tempSalesHeader, PriceCalculation);
        PriceCalculation.ApplyDiscount();
        tempSalesLine.ApplyPrice(tempSalesLine.FieldNo("No."), PriceCalculation);
        exit(tempSalesLine);
    end;
```

**3. Expected behavior**
Do not detect the function as duplicate, which detects that the Record subtype is different.

**4. Actual behavior**
![image](https://user-images.githubusercontent.com/15688332/125043082-df3f8700-e09a-11eb-90c0-c3ab8c529aaf.png)

**5. Versions:**

- AL Language: v7.3.486497
- Visual Studio Code: 1.58.0 (user setup)
- Business Central:
- List of Visual Studio Code extensions that you have installed:

- al v7.3.486497
-   al-code-outline v3.0.8
-   al-formatter v3.0.0
-   al-language-tools v0.0.22
-   al-navigator v0.4.6
-   al-studio v0.9.934
-   al-toolbox v2.0.12
-   azure-account v0.9.8
-   azurecli v0.5.0
-   bdev-al-xml-doc v1.1.5
-   code-settings-sync v3.4.3
-   crs-al-language-extension v1.4.9
-   csharp v1.23.12
-   docomment v0.1.20
-   github-vscode-theme v4.1.1
-   gitlens v11.5.1
-   mssql v1.10.1
-   nab-al-tools v1.4.0
-   powershell v2021.6.2
-   vsc-community-material-theme v1.4.2
-   vsc-material-theme v33.2.0
-   vsc-material-theme-icons v1.2.2
-   vscode-azurefunctions v1.4.0
-   vscode-azureresourcegroups v0.4.0
-   vscode-csharp-snippets v1.1.0
-   vscode-graphviz v0.0.6
-   vscode-highlight v1.5.0
-   vscode-language-pack-es v1.57.1
-   vscode-swaggerhub v1.0.3
-   vscode-thunder-client v1.6.1
-   vscode-todo-plus v4.18.3
-   vscode-yaml v0.21.0
-   xliff-sync v1.2.0
-   xml v2.5.1

- Windows Version: Windows_NT x64 10.0.19043
### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by db-bc** [comment] 2021-07-09 08:25
How do you call the functions? Do you expect the language to check what type of record you are trying to assign to, and then overload that way? Overloading generally doesn't consider return types in my experience; that's normal.

**Comment by db-bc** [comment] 2021-07-09 08:28
from https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-overload-method

> Overload resolution is performed by using procedure signatures to find the best match. The signature of a procedure is represented by its name and the type, order, and number of parameters. The return type of a procedure is not part of the procedure’s signature.

So this is by design and documented.

**Comment by Entreri86** [comment] 2021-07-09 08:35
Yes, I know that by design it is implemented this way, I just think it is interesting to add that functionality. I know that in C # it is not implemented that way either because in its day they did not consider it but for example in C ++ it is.

**Comment by db-bc** [comment] 2021-07-09 08:39
No, C++ does not overload on return types. And I imagine both C++ and C# did consider this and rejected it for reasons of complexity and the fact it simply cannot work in all cases (if the result is ignored, type inference is used, etc.)

**Comment by Entreri86** [comment] 2021-07-09 08:46
Yeah it does, [https://www.educba.com/function-prototype-in-c/](url)

**Comment by db-bc** [comment] 2021-07-09 08:50
That's about C and says nothing that is actually about overloading, just mentioning the word once in a vague and seemingly unrelated context. C does not have function overloading. C++ does but does not overload on return types.

**Closed** 2021-07-09 09:35 UTC
