### ISSUE TITLE
Error "The identifier xx could not be found"

### ISSUE THREAD

**Issue by rwe12345** [microsoft/AL#6548] opened 2021-03-22 15:11 UTC
If you use the properties Visible, Editable or Enabled on a pageextension you can get the error "The identifier xx could not be found" (see below).

![image](https://user-images.githubusercontent.com/44321194/112012040-24aa6980-8b29-11eb-8da8-a300cb735645.png)

I used the following code:

![image](https://user-images.githubusercontent.com/44321194/112010854-f8dab400-8b27-11eb-9fb6-cda01960d49a.png)

You only get this error when you use the Rec. In the next version we need to use this, so please fix this error.
When you build the solution, you don't get an error message.

**Comment by db0451** [comment] 2021-03-23 09:38
You need to specify what runtime and BC versions you are using. This is well known not to work in some prior ones, and IIRC that was a won't-fix, although they should definitely give compile errors if targeting a runtime in which this would otherwise be a deferred runtime error.

**Comment by db0451** [comment] 2021-03-23 09:39
dupe of https://github.com/microsoft/AL/issues/6191

**Comment by qutreson** [comment] 2021-03-23 09:50
Thank you @db0451, closing as duplicate of the issue mentioned above.

**Closed by qutreson** 2021-03-23 09:50 UTC
