### ISSUE TITLE
File link in errors/warning are cut on first space

### ISSUE THREAD

**Issue by kine** [Microsoft/AL#1879] opened 2018-03-29 06:10 UTC
In the output console, the link on file name is cut off on first space in the file name, thus unusable. E.g.:

![image](https://user-images.githubusercontent.com/110221/38072869-ad1cfc8a-3328-11e8-8dd1-c9243813a769.png)

**Comment by waldo1001** [comment] 2018-03-29 07:34
A few remarks on that.

First: yeah, it should work ;-).  But I think this is a VSCode issue...
Second: these guidelines show you how the filenaming should be: 
https://docs.microsoft.com/en-us/dynamics-nav/compliance/apptest-bestpracticesforalcode
Third: my extension can help you with that.  Latest release is going to rename all files, following these guidelines :-).  Just add the "crs-al-language-extension" in VSCode.
https://marketplace.visualstudio.com/items?itemName=waldo.crs-al-language-extension

**Comment by kine** [comment] 2018-03-29 07:47
Which version of the ext it should be? Still do not see it on marketplace. Do not kow if the output of the AL is formated or the formating is done by VSCode automatically. With the new naming convention it will be ok.

**Comment by DominikDitoIvosevic** [comment] 2018-04-03 07:58
hey guys. This is a duplicate of https://github.com/Microsoft/AL/issues/167
The bug was in vscode so I fixed the issue there and it should come with their next update or you can test it in the insider version

**Closed by DominikDitoIvosevic** 2018-04-03 07:58 UTC
