### ISSUE TITLE
txt2al: illegal character in Path

### ISSUE THREAD

**Issue by alapenas** [microsoft/AL#5309] opened 2019-09-30 10:59 UTC
After creating DELTA files with Compare-NAVApplicationObject, I got several error messages while using txt2al.exe:

`----ERROR----
Error converting file: c:\run\my\delta\PAG1.DELTA
Illegal characters in path.`

Version: 15.0.36560.0-w1 from bcsandbox-master

There is an closed issue about this, but it wasn't solved: #5192

**Comment by rdebath** [comment] 2019-10-02 09:19
It seems to be related to the (default) `{name}` and `{targetName}` plugins.
It seems to be impossible to turn off the `--rename` flag so the best I can do to workaround is to use `{type}-{id}` as the filename patterns.
As far as I can tell there is no match with the actual name of the file, it just breaks with some files.

**Comment by qutreson** [comment] 2019-10-02 09:19
@alapenas, as version 15.0 does not contain C/SIDE anymore and thus txt files cannot be exported with this version, we are now advising to use the txt2al from the 14.x previews. This is also where we will focus in future for txt2al bug fixes. We will add this to our online documentation.

**Comment by rdebath** [comment] 2019-10-02 10:52
Right, that means I have to ignore your name creation by trying to turn off `--rename` and fix the problem in a script after or roll back to a working version. As this bugfix is no longer available in a prompt manner.

Or do you have a hidden `-master` variant of a V14 docker available?

As for "previews" there are no V14 previews in "collaborate/packages" and the "Wave 2" previews (more sensibly known as V15 onprem AIUI) give "This service is unavailable" on download. Not good.

**Comment by freddydk** [comment] 2019-10-02 20:49
v15 is available publicly since yesterday - mcr.microsoft.com/businesscentral/onprem - and also as DVD's on partnersource.
for txt2al, there is a parameter called runtxt2alincontainer, which can use txt2al in another container for handling 14.x stuff - described here: https://freddysblog.com/2019/08/02/organizing-your-al-files/
Until yesterday, we created daily builds from the 14.x branch (bcinsider.azurecr.io/bcsandbox:ltsc2019 = next minor). latest build there was 14.6.36666.0-w1-ltsc2019
Found by Get-NavContainerImageTags -imageName "bcinsider.azurecr.io/bcsandbox" -registryCredential (New-Object pscredential "username", (ConvertTo-SecureString -string "password" -AsPlainText -force))).Tags

**Comment by rdebath** [comment] 2019-10-03 13:35
Thanks for that Freddy, I hadn't noticed `Get-NavContainerImageTags` and was stuck with your previous documentation.

As for spinning up a container just for `txt2al` it's actually a far better idea just to copy the Nav-client directory out of the image IMO (a 50th of the size too).

**Comment by qutreson** [comment] 2019-10-07 07:05
Hi @rdebath, after Freddy's help, are you now able to run the txt2al from 14.x with the fix for the issue reported on illegal characters in the path of the generated files?

**Comment by rdebath** [comment] 2019-10-07 11:16
Okay, I hadn't checked because I've given up on it and just script some nicer names.

It is no longer complaining about "illegal characters", but I suspect it's not doing what you want for the `{targetName}` attribute in that it's keeping spaces and fillers for all the "illegal" characters. (This is for both TableExt and PageExt).

The first argument for the `mv` command in this generated script is from `--extensionObjectFileNamePattern={type}-{id}-{targetId}-{targetName}`
```
mv 'TableExt-70000006-122-_Purch. Inv. Header_.al' TableExt_Purch.Inv.Header.al
mv 'TableExt-70000007-123-_Purch. Inv. Line_.al' TableExt_Purch.Inv.Line.al
mv 'TableExt-70000008-124-_Purch. Cr. Memo Hdr._.al' TableExt_Purch.Cr.Memo_Hdr.al
mv 'TableExt-70000009-125-_Purch. Cr. Memo Line_.al' TableExt_Purch.Cr.Memo_Line.al
mv 'TableExt-70000010-17-_G_L Entry_.al' TableExt_GL_Entry.al
mv 'TableExt-70000011-18-Customer.al' TableExt_Customer.al
mv 'TableExt-70000012-21-_Cust. Ledger Entry_.al' TableExt_Cust.Ledger_Entry.al
```

**Comment by qutreson** [comment] 2019-10-07 11:56
We have currently set the behavior to escape the illegal characters by using `_`. We chose this approach in order to minimize risks of collisions, but skipping it as you suggest is probably better. We'll fix that in our 14.x images

**Comment by ralf-escher** [comment] 2019-10-07 12:08
@qutreson: I successfully created AL files due to the hint of @freddydk.
However I got a problem with the extension name (inside the AL file), see my issue #5192.

**Comment by qutreson** [comment] 2020-06-30 06:32
Closing this issue as it appears to have been resolved. If you are still facing it, please log a new issue with some code reproducing it.

**Closed by qutreson** 2020-06-30 06:32 UTC
Labels: bug, in-progress, txt2al
