### ISSUE TITLE
Intellisense not suggesting IDs when using snippets

### ISSUE THREAD

**Issue by linonavcite** [microsoft/AL#7328] opened 2023-02-21 08:54 UTC
**1. Describe the bug**

Intellisense is not suggesting ID's when using the default snippets from the AL Extension. 

When creating a new object with a snippet (ttable, tpage, etc) intellisense is not suggesting an ID.
Same issue when creating a new field in a table extension with the tfield snippet. 

If you assign the object a name, intellisense will suggest an ID, but not without the name. 

The error is not happening when creating an extension object (tableext, tpageext etc). 

Examples:
![intellisense](https://user-images.githubusercontent.com/65947103/220300584-ca8b4411-43ac-445c-9191-450b0fd0ecb5.gif)

![intellisense_field](https://user-images.githubusercontent.com/65947103/220300601-0a4351b1-e86d-4bad-870d-dbcef84b90d5.gif)

**2. To Reproduce**

Create a new table with the ttable snippet. Remove the ID text, press CTRL + Space to open intellisense suggestion.  No ID will be suggested

Assign the table a name, go back to the empty slot between the object type definition and the object name. Press CTRL + Space to open intellisense suggestion. An id will be suggested.

AL Language version: v10.4.747197
No other extensions were enabled in recreating this issue.

**Comment by BazookaMusic** [comment] 2023-04-18 08:13
Unfortunately, after investigating this bug, it seems to be by design due to how VSCode handles templates. Here's an explanation of what's happening:

If you have a template, it looks something like this:
```
"Page of type List": {
        "prefix": "tpage",
        "body": [
            "page ${1:Id} ${2:PageName}",
            "{",
            "\tPageType = List;",
            "\tApplicationArea = ${3|All,Basic,Suite,Advanced|};",
            "\tUsageCategory = Lists;",
            "\tSourceTable = ${4:TableName};",
            "\t",
            "\tlayout",
            "\t{",
            "\t\tarea(Content)",
            "\t\t{",
            "\t\t\trepeater(${5:GroupName})",
            "\t\t\t{",
            "\t\t\t\tfield(${7:Name}; ${6:NameSource})",
            "\t\t\t\t{",
            "\t\t\t\t\tApplicationArea = ${3};",
            "\t\t\t\t\t${8}",
            "\t\t\t\t}",
            "\t\t\t}",
            "\t\t}",
            "\t\tarea(Factboxes)",
            "\t\t{",
            "\t\t\t${9}",
            "\t\t}",
            "\t}",
            "\t",
            "\tactions",
            "\t{",
            "\t\tarea(${10:Processing})",
            "\t\t{",
            "\t\t\taction(${11:ActionName})",
            "\t\t\t{",
            "\t\t\t\tApplicationArea = ${3};",
            "\t\t\t\t",
            "\t\t\t\ttrigger OnAction();",
            "\t\t\t\tbegin",
            "\t\t\t\t\t$0",
            "\t\t\t\tend;",
            "\t\t\t}",
            "\t\t}",
            "\t}",
            "}"
        ],
        "description": "Snippet: Page of type list"
    },
```
It is possible to define some auto-complete suggestions in this template like in this line:
`"\tApplicationArea = ${3|All,Basic,Suite,Advanced|};",`

When I use the template, VSCode goes into a "template autocomplete" mode, where I can use TAB to go between the different variables defined in the template and change them. If a variable has suggestions defined on it, like `ApplicationArea` here, VSCode will never contact the extension for suggestions for any part of the template while we are still in this mode. These suggestions are useful though because they auto-popup when using tab navigation and highlight the important parts of the template.

The easiest way to break out of the template autocomplete is to click on any text outside the template, then VSCode will start using the extension again. You can verify that if you try to get suggestions on the object IDs, suddenly they start appearing again.

The way this could be fixed by VSCode is that they could contact extensions when in this mode if you are explicitly asking for intellisense.

**Closed by BazookaMusic** 2023-04-18 08:13 UTC
Labels: al-core-compiler, accepted

**Comment by barandeniz** [comment] 2023-04-18 13:19
"I am struggling with this issue as well. This started happening about 1-2 months ago. Before that, everything was working perfectly, even with templates/snippets. Is there a way to disable the 'template autocomplete' feature until VSCode fixes it? (I hope they will change this behavior.) I know I can enable the correct suggestions by pressing Esc or click with mouse somewhere ekse, but then I cannot navigate to the next variable as you mentioned, @bazookaMusic."
