### ISSUE TITLE
Processing of message 'textDocument/completion' failed with error: 'Position: 1, FullSpan: (0..0)

### ISSUE THREAD

**Issue by spncrgr** [Microsoft/AL#4458] opened 2019-01-13 14:33 UTC
**Describe the bug**
An error is thrown when attempting IntelliSense/auto-completion of the AL code template `ttable`

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. Create a new AL file in Visual Studio Code named `WageSetupTable.al`
2. Rename the file to `WageScheduleTable.al` by clicking on the file in the Explorer panel and pressing F2.
3. Click the editor pane to start typing
4. Type "tt"

**Expected behavior**
Expect IntelliSense window to pop open and suggest completions.

**Workaround**
1. Close workspace
2. Close VS Code (all instances)
3. Start VS Code
4. Open workspace

IntelliSense was back to normal after I did this.

**Versions:**

 - AL Langauge: 2.1.69331 (installed into VS Code via VSIX downloaded from BC sandbox container)

 - Business Central: US Dynamics NAV 13.1 (26534)

***Full error text***
```
[Error - 9:15:31 AM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/completion' failed with error: 'Position: 1, FullSpan: (0..0)
Parameter name: position'
Details:
System.ArgumentOutOfRangeException: Position: 1, FullSpan: (0..0)
Parameter name: position
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position) in C:\a\512\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 895
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.ALCompletionService.<GetDefaultItemSpanAsync>d__4.MoveNext() in C:\a\512\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\ALCompletionService.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.<GetCompletionsAsync>d__17.MoveNext() in C:\a\512\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 157
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CompletionRequestHandler.<HandleAsync>d__4.MoveNext() in C:\a\512\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CompletionRequestHandler.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__10.MoveNext() in C:\a\512\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\a\512\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59
```

**Comment by JohanStenberg100** [comment] 2019-01-21 10:39
I can't reproduce this on our master branch. Can you please try using the latest image from [http://bcinsider.azurecr.io/bcsandbox-master](http://bcinsider.azurecr.io/bcsandbox-master)? Thanks

**Comment by spncrgr** [comment] 2019-01-21 20:50
I haven't been able to reproduce it either. I'm assuming, then, that it was just a transient error?

**Comment by JohanStenberg100** [comment] 2019-01-22 07:43
@spncrgr Perhaps, we at least need to have a consistent repro to be able to investigate it. But still, it's good that you report it, if we get multiple reports of the same issues then we'll treat it with more urgency. Now since neither of us can reproduce it, I'll go ahead and close this issue. If you manage to find a consistent repro, then please do comment here and I'll tak a look. Thanks!

**Closed by JohanStenberg100** 2019-01-22 07:43 UTC
Labels: input-needed
