### ISSUE TITLE
Non-existing report parameter when using IncludeCaption in report extension

### ISSUE THREAD

**Issue by DSaladinCH** [microsoft/AL#6601] opened 2021-04-29 06:29 UTC
**1. Describe the bug**
When adding a new column to an existing dataitem and activating IncludeCaption, it is throwing an error when running the report.
`The Value expression for the text box ‘Textbox4’ refers to a non-existing report parameter ‘SalesHeader_SellToCustomerNoCaption’`.
This is not happening when I activate IncludeCaption in a new column inside a new dataitem.

**2. To Reproduce**

1. Extend a report
2. Add a new column to an existing dataitem (in this example I create a custom report and extended this)
```
add(SalesHeader)
{
    column(SalesHeader_SellToCustomerNo; SalesHeader."Sell-to Customer No.")
    {
        IncludeCaption = true;
    }
}
```
3. Import the rdl file as custom layout and set it all up
4. Run the report

**3. Expected behavior**
Show the caption of this field, as all other field captions.

**4. Actual behavior**
![image](https://user-images.githubusercontent.com/43037258/116509997-88604900-a8c4-11eb-88d0-7812b6e5d506.png)

**5. Versions:**

- AL Language: 7.1.453917
- Visual Studio Code: 1.55.2
- Business Central: CH Business Central 18.0 (Platform 18.0.22893.23773 + Application 18.0.23013.23795)
- List of Visual Studio Code extensions that you have installed: AL Language, AL Object Helper, AL Variable Helper, Fix AL File Names

**Comment by atoader** [comment] 2021-04-29 09:11
Hi! Could you provide a project that reproduces the issue? This looks like a bug and we would like to fix it in the next CU.

**Comment by DSaladinCH** [comment] 2021-04-29 09:17
Yeah sure. I zipped the workspace (without symbols). In the workspace you got 2 projects.
The first project "Test 1" got a "Test Report" with the id 50000 and the second project "Test 2" got a report extension "Test Report Ext." with the id 50050. The report extension adds a new column to the sales header dataitem in the "Test Report".

Hope that helps you :)
[BC18Test.zip](https://github.com/microsoft/AL/files/6397490/BC18Test.zip)

**Comment by atoader** [comment] 2021-04-29 09:19
It helps a lot! Thank you very much!

**Comment by thloke** [comment] 2021-05-17 03:07
This should be fixed in the latest version. Can you try and repro with a 18.x BC version 18.0.24800.0 or later? Or the latest insider build?

If it still repros, feel free to reopen this and tag me and I'll look into it.

**Closed by thloke** 2021-05-17 03:07 UTC
Labels: bug, in-progress
