### ISSUE TITLE
Obsolete properties with TableRelation are included in Rename operations

### ISSUE THREAD

**Issue by charlespockert** [Microsoft/AL#4847] opened 2019-04-05 10:12 UTC
**Describe the bug**
When marking a table obsolete, if the `TableRelation` property points to a non-obsolete table (e.g. `"Dimension Value".Code`) - renaming a PK in the related table will cause an error:

`Table XYZ (500XX) is obsoleted, reason: "your obsolete reason here"` 

I'm not sure if this is because there is data still present in the archive since I didn't move the data in an upgrade codeunit, or if it's just because all `TableRelation` properties are checked on all tables regardless of `ObsoleteState`.

**To Reproduce**
Create a table that relates to `"Dimension Value".Code`, deploy it as an extension (with a page so you can add data). Add some data rows that look up a dimension value.

Update the extension to mark the table obsolete.

Deploy, then try and rename a dimension value code, you will get the obsolete error.
 
**Expected behavior**
Obsolete tables are not considered when checking `TableRelation` properties.

**Workaround**
A simple workaround is to remove all `TableRelation` properties from your obsolete table on your next deploy.

**Versions:**
 - AL Langauge: 3.0.115791
 - Business Central: GB Dynamics NAV 13.5 (29483)

**Comment by kalberes** [comment] 2019-04-09 16:06
Don't you get a compiler warning on the obsoleted table relation?

**Comment by thpeder** [comment] 2019-04-10 12:42
Hi @charlespockert,
Can you provide us with a small snippet of code that reproduces the issue?

**Comment by charlespockert** [comment] 2019-04-10 12:54
@kalberes the table relation is to a valid table - the obsolete object is the table that contains the table relation.

e.g. create this table

```
table 50000 "An Obsolete Table"
{
    Caption = 'Table Caption';

    fields
    {
        field(1; "Primary Key"; Code[20])
        {
        }

        field(2; "Dim. Value"; Code[20])
        {
            TableRelation = "Dimension Value".Code;
        }
        keys
        {
            key(PK; "Primary Key")
            {
                Clustered = true;
            }
        }
    }
}
```

Put some data in it, then mark it as obsolete

```
    ObsoleteReason = 'Obsolete test';
    ObsoleteState = Removed;
```

Deploy the obsolete table update

Now if you try to rename a dimension value you will receive an error that the above table is marked obsolete.

You can work-around this by removing the `TableRelation` property on the obsolete table and re-deploying.

**Comment by PooyaKharamesh** [comment] 2019-05-03 09:58
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Closed by PooyaKharamesh** 2019-05-03 09:58 UTC
Labels: input-needed

**Comment by dtkb** [comment] 2021-06-15 16:15
This can happen when inserting a Default Dimension, via whatever faff goes on below, which in BC17 (left) is ignored and presumably won't error if obsolete, but in BC15 (right, current user having this problem) will proceed if obsolete and then error in `RecordRef.Open()`. Below, `Table 50006` has a `TableRelation` to `Dimension Value`, and that causes it to get `RecordRef.Open()`ed for this check and cause the runtime error.

```none
ExceptionStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.ObsolescenceGuard.ThrowIfObsoleted(NCLMetaTable table)
   at Microsoft.Dynamics.Nav.Runtime.NavRecord..ctor(ITreeObject parent, Int32 tableId, NCLMetaTable metaTable, Boolean isTemporary, NavRecord sharedTable, String companyName, SecurityFiltering securityFiltering)
   at Microsoft.Dynamics.Nav.BusinessApplication.Record50006.__Construct(ITreeObject parent, NCLMetaTable metaTable, Boolean isTemporary, NavRecord sharedTable, String companyName, SecurityFiltering securityFiltering)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaTable.CreateObjectInstance(ITreeObject parent, Boolean isTemporary, NavRecord sharedTable, String companyName, SecurityFiltering securityFiltering)
   at Microsoft.Dynamics.Nav.Runtime.NavRecordRef.SetRecord(Int32 tableID, Boolean isTemporary, String companyName)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit408.KeyContainsOneCodeField_Scope_1193862506.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit408.KeyContainsOneCodeField(Int32 tableID)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit408.DefaultDimInsertTempObject_Scope__1107550540.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit408.DefaultDimInsertTempObject(INavRecordHandle tempAllObjWithCaption, Int32 tableID)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit408.DefaultDimObjectNoWithGlobalDimsList_Scope__1038263689.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit408.DefaultDimObjectNoWithGlobalDimsList(INavRecordHandle tempAllObjWithCaption)
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit408.DefaultDimObjectNoList(INavRecordHandle tempAllObjWithCaption)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit408.OnInvoke(Int32 memberId, Object[] args)
   at Microsoft.Dynamics.Nav.BusinessApplication.Record352.Table_ID_a45_OnValidate_Scope.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Record352.Table_ID_a45_OnValidate()
   at Microsoft.Dynamics.Nav.Runtime.NavRecord.ValidateField(FieldTriggerHandler`1 fieldEvent, NCLMetaField metaField, Boolean isUserInput, List`1 beforeHandlers, List`1 afterHandlers)
   at Microsoft.Dynamics.Nav.Runtime.NavRecord.Validate(NCLMetaField metaField, NavValue newValue, NavRecord callerRecord, Boolean isUserInput)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit408.SaveDefaultDim_Scope__376809190.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit408.SaveDefaultDim(Int32 tableID, NavCode no, Int32 fieldNumber, NavCode shortcutDimCode)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit408.OnInvoke(Int32 memberId, Object[] args)
   at Microsoft.Dynamics.Nav.BusinessApplication.Record18.ValidateShortcutDimCode_Scope__780514971.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Record18.ValidateShortcutDimCode(Int32 fieldNumber, ByRef`1 shortcutDimCode)
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Record18.Global_Dimension_1_Code_a45_OnValidate()
   at Microsoft.Dynamics.Nav.Runtime.NavRecord.ValidateField(FieldTriggerHandler`1 fieldEvent, NCLMetaField metaField, Boolean isUserInput, List`1 beforeHandlers, List`1 afterHandlers)
   at Microsoft.Dynamics.Nav.Runtime.NavRecord.Validate(NCLMetaField metaField, NavValue newValue, NavRecord callerRecord, Boolean isUserInput)
   at Microsoft.Dynamics.Nav.Service.NsDataAccess.Validate(Int32 fieldId)
   at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.<>c__DisplayClass44_0.<Validate>b__0()
   at Microsoft.Dynamics.Nav.Runtime.ApplicationObjectRootScope.AddApplicationObjectRootScope(NavApplicationObjectBase applicationObject, Action action)
   at Microsoft.Dynamics.Nav.Service.NSField.ValidateField(NavSession session)
   at Microsoft.Dynamics.Nav.Service.NSField.Validate(NavSession session)
```
