### ISSUE TITLE
Issue in Dynamics 365 Business Central

### ISSUE THREAD

**Issue by olisterrcf** [Microsoft/AL#1855] opened 2018-03-26 09:43 UTC
Hi,
I've written an extension in NAV 2018 in AL. It works perfectly fine for NAV 2018, but doesn't work in D365 BC giving error 'Error compiling dynamic control expression: '"Contract Type" = "Contract Type" :: "Rental Contract"' at index '34'. The error is: End of expression expected..'
There is no error at compile time while building or publishing the package.

**Comment by DominikDitoIvosevic** [comment] 2018-03-26 09:53
Hi @olisterrcf .
This is a duplicate of https://github.com/Microsoft/AL/issues/1800
The should be available soon and the workaround is to store the option constant from the right side into a variable

**Closed** 2018-03-26 09:53 UTC
Labels: duplicate

**Comment by olisterrcf** [comment] 2018-03-26 10:54
Thanks, I've resolved it by using a boolean variable.
