### ISSUE TITLE
ERROR : The type or method SAVEASPDF cannot be used for Extension development.

### ISSUE THREAD

**Issue by srinivasdes** [Microsoft/AL#1378] opened 2018-01-09 08:57 UTC
Facing the above issue while convert our extension from V1 to V2

**Comment by esbenk** [comment] 2018-01-09 11:22
Assuming this is on Reports we are looking into this. No ETA though.

**Comment by StanislawStempin** [comment] 2018-01-09 16:41
In the meanwhile you can export the report into a stream in the PDF format.

**Comment by StanislawStempin** [comment] 2018-11-05 10:16
Closing this as by design.
For On-Premises usage just change your app.json to Target : Internal and the function will be available.
For Cloud usage you need to withc to using Report.SaveAs function with the ReportFormat::PDF parameter and save the report to a stream.

**Closed by StanislawStempin** 2018-11-05 10:16 UTC
Labels: enhancement
