### ISSUE TITLE
[AL] Pageextension unable to use already define variables or functions from page

### ISSUE THREAD

**Issue by mpopelka** [Microsoft/AL#3829] opened 2018-09-24 19:05 UTC
When using global variables or functions defined on a page I am getting either warnings stating that they do not exist in the current context or is inaccessible due to its protection level. I have attempted this in several pageextensions and several different tenants resulting in the same warning messages. Variables and functions from objects other than pages seem to work just fine. I included an example extension using the Sales Order page where I duplicated the "Statistics" action. The OnAction() includes code that was copied from the existing "Statistics" OnAction(). 

[PAG42 Sales Order.docx](https://github.com/Microsoft/AL/files/2412453/PAG42.Sales.Order.docx)

**Comment by CanuckNav74** [comment] 2018-09-24 19:43
@mpopelka I ran into this issue today too.

There's a lengthy discussion of it here: https://github.com/Microsoft/AL/issues/593

Doesn't look like there is anything on the short-term roadmap to address this in the near future (personally, if page/table extensions were to truly adopt OOP principles, I too think that global members (functions and variables) in the base object should be accessible from the child object (i.e. the extension)

**Comment by qutreson** [comment] 2018-09-25 07:02
Closing as duplicate of #593. Feel free to contribute to the thread there if you want to add something to the discussion.

**Closed by qutreson** 2018-09-25 07:02 UTC
