### ISSUE TITLE
New Look up event feature in VS Code and function visibility

### ISSUE THREAD

**Issue by demiliani** [microsoft/AL#5810] opened 2020-04-16 14:42 UTC
**Describe the bug**
The new Shift + Alt + E shortcut in AL version 5.x permits to invoke a list of all the available events. The created event subscriber is PUBLIC as default, while it should be LOCAL as default.

**To Reproduce**
Steps and to reproduce the behavior:
1. From an AL project, open the event list by using the Shift + ALT + E shortcut
2. Select an event from the list
3. The EventSubscriber procedure is created as follows:
[EventSubscriber(...]
procedure YourEvent(...);
begin
end;

``` AL Code to reproduce the issue ```

**Expected behavior**
It should be:
[EventSubscriber(...]
local procedure YourEvent(...);
begin
end;

**Screenshots**

**5. Versions:**

 - AL Language: 5.0.254558

 - Business Central:

**Comment by dtkb** [comment] 2020-04-16 15:48
duplicate of https://github.com/microsoft/AL/issues/5802

**Comment by demiliani** [comment] 2020-04-16 21:54
Sorry missed that. Please fix 😉

**Comment by qutreson** [comment] 2020-04-17 06:50
Closing as duplicate of the issue 5802

**Closed by qutreson** 2020-04-17 06:50 UTC
Labels: duplicate
