### ISSUE TITLE
Compiler crash when using PagCust and Event Subscriber on same Page

### ISSUE THREAD

**Issue by eivindgiske** [microsoft/AL#5055] opened 2019-06-11 08:02 UTC
Bug Description:
The Compiler will crash with System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourcePageCustomizationTypeSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.PageExtensionTypeSymbol'. If the following conditions are true:
- A PagCust object references a specific page
- An Event Subscriber references the same specific page

If you remove one of the two, the project compiles

SAMPLE CODE:
codeunit 50100 "Test Event Subscriber"
{
    [EventSubscriber(ObjectType::Page, Page::"Payment Journal", 'OnAfterActionEvent', 'SuggestRemittancePayments', true, true)]
    local procedure InsertRemittanceDefaultJnlRegRepCode(var Rec: Record "Gen. Journal Line")
    begin
        message('hello');
    end;
}

pagecustomization "Payment Jnl. Rem. Helper Cust." customizes "Payment Journal"
{        
    actions
    {
        modify(SuggestVendorPayments)
        {
            Visible = false;
        }
    } 
}

TO REPRODUCE:
Run AL: Go!
Paste the above code
Add symbols for BC140
Run AL: Package
Expected result: System.InvalidCastException

**Versions:**
 - AL Language: 3.0.126610
 - Business Central: 14.0.32600

**Comment by Qww57** [comment] 2019-06-11 10:49
Similar to #5013

**Comment by qutreson** [comment] 2019-06-11 11:29
This looks like a duplicate of #5013. Closing as duplicate.

**Closed by qutreson** 2019-06-11 11:29 UTC
