### ISSUE TITLE
ModalPageHandler seems to get invalid object references passed

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/AL#2670] opened 2018-06-21 06:28 UTC
Continuing my tests and experiments using `ModalPageHandler` (see #2668). I have now rewritten my test method like so:

````
    [ModalPageHandler]
    procedure SelectTemplateHandler(var zhePage: TestPage "General Journal Template List")
    begin
        zhePage.Close();
    end;
````

I which case I get the following error when running the test:

![image](https://user-images.githubusercontent.com/8897936/41701491-f9648586-752c-11e8-9585-0328349fc119.png)

**Comment by qutreson** [comment] 2018-06-27 09:40
Hi @hemisphera, the problem is related to the `zhePage.Close()` that you are running.
The method RunModal already takes care of creating, running and closing the page as you can see here in the [docs](https://docs.microsoft.com/en-us/dynamics-nav/page-runmodal-function). As you are closing the page in the handler, the RunModal method is then failing when trying to close it again. We will try to fix the NRE and fail more gracefuly in this scenario.

For you test, I guess you can just remove the `zhePage.Close()` statement that you have in the handler and it should work as you expect it since the RunModal will close the page for you.

**Comment by hemisphera** [comment] 2018-06-28 06:12
OK, the test itself is actually not a "real" test. I was just playing around because I got trapped in something else. Then I spotted the NullReferenceException and just thought it might be a bug.

**Comment by ashik-ivor** [comment] 2018-07-03 08:53
zhePage.OK.INVOKE. Try this

**Closed** 2018-07-30 10:41 UTC
Labels: bug
