### ISSUE TITLE
AL Debugger Watch <Out of Scope>

### ISSUE THREAD

**Issue by MattiLE** [microsoft/AL#6730] opened 2021-08-09 13:21 UTC
**1. Describe the bug**
Whenever a field name contains a space, the debugger watch always displays "Out of Scope".

**2. To Reproduce**
Start the debugger and add some fields to watch

![image](https://user-images.githubusercontent.com/48024891/128712882-fd07cdfb-b555-4714-b24d-2e8d700c95e9.png)

**5. Versions:**
- AL Language: 7.4.496506
- Visual Studio Code: 1.59.0

**Comment by db-bc** [comment] 2021-08-09 13:26
From your screenshot, it looks like it results from the field needing quoted, e.g. containing a space _or_ a period as in `No.`, or etc.

**Comment by NKarolak** [comment] 2021-08-09 13:35
Compare with #5639.

**Comment by mjmatthiesen** [comment] 2021-08-19 00:40
The Add to Watch is bugged, the out of scope is a red herring.

It should add Rec."No." but instead adds just No.

**Comment by thloke** [comment] 2021-11-30 09:13
Duplicate of #5639

**Closed by thloke** 2021-11-30 09:13 UTC
Labels: debugger
