### ISSUE TITLE
You do not have permission to insert Profile records

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#2744] opened 2018-06-27 16:44 UTC
we are trying to insert new profile via code in Profiles table and while installing the app got below error

what is the process to create new profile from our app?

![image](https://user-images.githubusercontent.com/23735402/41987663-6af7c62a-7a57-11e8-8c37-3d5ef149e866.png)

**Comment by pmohanakrishna** [comment] 2018-06-27 16:45
It worked in docker installation and now we are installing in online sandbox environment (SaaS)

**Comment by thpeder** [comment] 2018-06-28 08:04
Hi @pmohanakrishna,
What do you mean by code? Do you have a snippet of what you are doing?
If you are not aware of it, then I would recommend you to have a look a the [Profile Object](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-profile-object).

**Comment by pmohanakrishna** [comment] 2018-06-28 09:18
above code is written in Install app codeunit

**Comment by HunterFeltman-MSFT** [comment] 2018-06-28 14:56
In BusinessCentral the service is setup for multi-tenancy, whereby all tenants share the same Application Database for 'common/shared' data (Such as the definition of pages/tables/etc).

Since a change to anything in this database means changes for all tenants on the system and we don't want 'bad actors' harming their neighbors, tenants in BC are mounted **without write access** to the Application DB as a security/protection measure.

The Profile table is an Application Database table that is shared across all tenants in the system and so it fall under this

**Comment by srgaggan** [comment] 2018-06-28 15:34
In order to continue allowing new Profiles, we have introduced a now object "TenantProfile" which is tenant scope. You might want to use this object instead on profiles object while adding new profiles.

**Comment by pmohanakrishna** [comment] 2018-06-28 15:47
if we add thru tenant Profile object, does it allow us to use Personalize option?

**Comment by srgaggan** [comment] 2018-06-28 15:59
Yes. Ideally users (assigned with new tenant profile) should still be able to use personalization option.  Please let us know if that doesn't work.

**Comment by pmohanakrishna** [comment] 2018-06-28 17:09
Do you mean table 2000000177 - Tenant Profile?
is it exposed for development?

![image](https://user-images.githubusercontent.com/23735402/42049577-04ae712a-7b24-11e8-9108-a996445aa579.png)

**Comment by pmohanakrishna** [comment] 2018-06-28 17:18
I tried manually adding from backend and it is same that we cannot use personalize option with Tenant Profiles. https://github.com/Microsoft/AL/issues/2688

**Comment by StanislawStempin** [comment] 2018-06-29 14:22
You should not write directly to that table but instead use the profile object as shown in the answers above.

**Comment by srgaggan** [comment] 2018-06-29 14:46
We have observed a recent an internal bug that is leading to a Failure while loading Personalization while user is assigned with Tenant profile. Personalization's are user specific and profile independent, meaning a personalization made is available across all other profiles. If there is a need to add Personalization for specific pages, try assigning the user to a closest System Profile, make necessary changes and then reassign the user to tenant profile, while the fix for the issue is made available. Sorry for the inconvenience.

Id you want specific configuration changes that needs to go with the extension, please the Profile and PageCustomisations constructs through the extension as shown in above example.

**Closed** 2018-08-06 10:59 UTC
Labels: cross-team-investigate
