### ISSUE TITLE
BUG - FlowFilters on Card & List pages don't work at all when passing in Guids/Text !!

### ISSUE THREAD

**Issue by eque2al** [microsoft/AL#5771] opened 2020-04-02 11:14 UTC
We have essential functionality in place in C/AL that has been used successfully for many years - we have found this just won't work in AL.  Basically, what we have in place is a 'User Access' system whereby each User of the system can be given a list of Customers that they can access and their view of the Customer Card / Customer List (etc.) is filtered to only show the records they have permission for.

15.0.0.0 (Cloud)

1. CREATE A NEW TABLE (to store Customer records by User)

table 50000 "User Customer Access"
{
    Caption = 'User Customer Access';
    fields
    {
        field(10; "User Security ID"; Guid)
        {
            Caption = 'User Security ID';
            DataClassification = CustomerContent;
            TableRelation = User;
        }
        field(20; "Customer No."; Code[20])
        {
            Caption = 'Customer No.';
            DataClassification = CustomerContent;
            TableRelation = Customer;
        }
    }

    keys
    {
        key(Key1; "User Security ID", "Customer No.")
        {
            Clustered = true;
        }
    }
}

2. Add 2 new fields to the Customer table (via a Customer TableExtension):
        field(50000; "User Access"; Boolean)
        {
            Caption = 'User Access';
            **FieldClass = FlowField;**
            CalcFormula = Exist ("User Customer Access" where("Customer No." = field("No.")));
            Editable = false;
        }
        field(50001; "User Access FlowFilter"; Guid)
        {
            Caption = 'User Access FlowFilter';
            DataClassification = CustomerContent;
            Editable = false;
        }

3. Add code to the Customer List OnOpenPage() trigger
            FilterGroup(2);
            **SetFilter("User Access FlowFilter", UserSecurityId());**
            CalcFields("User Access");
            SetRange("User Access", true);
            FilterGroup(0);

4.  Create records in the new Customer User Access table for 2 or 3 Customers (but not all of them)

5.  Run the Customer List page and instead of seeing just the 2 or 3 Customers as expected (and as is the case in BC140 On Prem) instead all customers are hidden!!

This worked perfectly in C/AL (all versions from 2009R2 onward (ie. 2015, 2017, BC13 OnPrem, BC14 OnPrem) and so I can be sure this is a bug (also because it works if I comment out the **SetFilter** in the Customer List OnOpenPage).  Is it that behind the scenes the application is missing a CalcFields command on it's FlowFilters or something along those lines?

**This is a show-stopper and needs to be resolved urgently.**

I've also noticed that the FlowField doesn't even function on the Customer Card (!) as the Card will open with the 1st Customer in the table regardless of whether there is a User Customer Access record for the current user and the 1st Customer .. if the record doesn't exist then the Page should open with the 1st record that the User does have access to (ie. the first Customer record for the user contained in the "User Customer Access" table).

I've seen an issue that was logged previously around FlowFields not working on cards (which MS confirmed as a bug) .. but it appears this issue is more wide-ranging hence logging this new call.

**Comment by atoader** [comment] 2020-04-02 20:16
Hi @eque2al ! I closed the issue by accident. Can you provide a zipped project that reproduces the issue to fast-track the resolution?

**Comment by PooyaKharamesh** [comment] 2020-04-14 12:37
I'll look into the issue 

/Pooya

**Comment by PooyaKharamesh** [comment] 2020-04-17 08:48
Ill close the issue with no repro since the investigation suggests that FLowFilter is not set correctly in the AL project that I received.

/Pooya

**Closed by PooyaKharamesh** 2020-04-17 08:48 UTC
