### ISSUE TITLE
OnInstallAppPerCompany changed behavior BC18

### ISSUE THREAD

**Issue by lktraser** [microsoft/AL#6570] opened 2021-04-08 10:39 UTC
**1. Describe the bug**
In the latest BC18 release something changed about the OnInstallAppPerCompany trigger. The previous behavior of BC was that all Objects were already available in the AllObjWithCaption Table. This doesn't seem to be the case anymore.

**2. To Reproduce**
Create an app with an install codeunit. Filter AllObjWithCaption with the current app's AppID and do a FindSet(). We were using this before for example to fill a test suit with all tests from a test app on install.

``` 
codeunit 50100 "Test Install"
{
    Subtype = Install;    

    trigger OnInstallAppPerCompany()
    var
        AllObjWithCaption: Record AllObjWithCaption;
        NAVAppInstalledApp: Record "NAV App Installed App";
        NavAPPModuleInfo: ModuleInfo;
        AppExtensionId: Guid;
    begin
        NavApp.GetCurrentModuleInfo(NavAPPModuleInfo);
        Evaluate(AppExtensionId, NavAPPModuleInfo.Id);
        NAVAppInstalledApp.SetRange("App ID", AppExtensionId);
        NAVAppInstalledApp.FindFirst();
        AllObjWithCaption.SetRange("App Package ID", NAVAppInstalledApp."Package ID");
        AllObjWithCaption.FindSet();
    end;
}
```

**3. Expected behavior**
AllObjWithCaption should hold the Objects of the app that is being installed.

**4. Actual behavior**
No records are present.

**5. Versions:**

- AL Language: 7.1.441584
- Visual Studio Code: 1.55.0
- Business Central: 18.0.23013.24113

**Comment by JohanStenberg100** [comment] 2021-04-09 08:43
Hi @lktraser, thank you for reporting this issue. From a first glance it looks like your filter `AllObjWithCaption.SetRange("App Package ID", NavAPPModuleInfo.Id);` is incorrect. The right-hand parameter is an App ID and the left-hand parameter expects a Package ID. Please double-check this and see if this resolves your issue.

**Comment by lktraser** [comment] 2021-04-09 08:57
Hi @JohanStenberg100, I have updated my example. Sorry for providing the wrong code. I was trying to execute the same thing through codeunit 130456 "Test Suite Mgt." procedure SelectTestMethodsByExtension but didn't look close enough at the filters. The Problem still remains that the app cannot be found in the tables. Hope this information helps.

**Comment by JohanStenberg100** [comment] 2021-04-09 10:11
Hi @lktraser, I see. We have changed so that the "Nav App Installed App" table isn't updated until after the triggers have ran (due to perf reasons). So the behavior here is _by design_. That said, I know this has been raised before. Let me get back to you and see if there's any mitigation as of now.

**Comment by JohanStenberg100** [comment] 2021-04-09 13:07
Hi again @lktraser, we will do a fix for this, aiming for 18.1. There's going to be a new Package ID property on the ModuleInfo. THis way you can avoid using the NAV App Installed App table. Thanks

**Comment by dNsl9r** [comment] 2021-04-15 07:34
@JohanStenberg100 will the code in codeunit 130456 "Test Suite Mgt." procedure SelectTestMethodsByExtension be fixed as well in 18.1? We are currently running in problems with our ATT Pipelines due this behaviour.

**Comment by nikolakukrika** [comment] 2021-04-15 07:51
> @JohanStenberg100 will the code in codeunit 130456 "Test Suite Mgt." procedure SelectTestMethodsByExtension be fixed as well in 18.1? We are currently running in problems with our ATT Pipelines due this behaviour.

We will update that method to unblock this way of setting up the pipelines. I would advise to stop using this one going forward and to add tests by extensionID. If you need to allow easy test discoverability for the consultants, you can add an action to add tests to the test runner page.

**Comment by dNsl9r** [comment] 2021-04-15 08:41
What do you mean with "I would advise to stop using this one going forward and to add tests by extensionID." ?
How would our Devs code it in future?

Consultants are not needed, the scenario is only in our pipelines where everythin runs automatically.

**Comment by nikolakukrika** [comment] 2021-04-15 09:59
> What do you mean with "I would advise to stop using this one going forward and to add tests by extensionID." ?
> How would our Devs code it in future?
> 
> Consultants are not needed, the scenario is only in our pipelines where everythin runs automatically.

The setup of test suite by using the OnInstall is an old approach. It has the problem that it can block the extension from being installed. Also installation of the test extension should not setup test suite, since you may want to setup test codeuntis differently.

The docker and new AL Test runner allow you to execute tests by specifying codeunit range or extensionID (run all tests from the extension). Writing OnInstall code is not needed any more and has the problems above.

**Comment by dNsl9r** [comment] 2021-04-15 12:35
Thank you @nikolakukrika. I have to see how ALOps handles this as we are working with their software for our pipelines.

**Comment by atoader** [comment] 2021-04-18 10:29
I am closing this issue because it appears that it has been resolved.

**Closed by atoader** 2021-04-18 10:29 UTC
Labels: in-progress, platform-api
