### ISSUE TITLE
Please improve exceptions

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#5889] opened 2020-05-16 16:21 UTC
It would be nice, if the AL Language Extension would produce more human readable error messages.

Please add more information, e.g. which AL file and which line this exception occurred, so I'm able to produce a proper bug report here. 

Currently both exceptions point to the **app.json**, which I can exclude by the class name **Rule087DoOnlyLowerPermissionsInsideTestProcedures** and **Rule205VariablesMustAlwaysBeInitialized**.

```
{
	"resource": "/c:/Users/myuser/source/repos/MyApp/app.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "AD0001",
	"severity": 4,
	"message": "Analyzer 'Microsoft.Dynamics.Nav.CodeCop.Design.Rule087DoOnlyLowerPermissionsInsideTestProcedures' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.VariableListDeclarationSyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.VariableDeclarationSyntax'.\r\n   at Microsoft.Dynamics.Nav.CodeCop.Design.Rule087DoOnlyLowerPermissionsInsideTestProcedures.AnalyzeVariableList(SyntaxNodeAnalysisContext ctx) in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeCop\\Design\\Rule087DoOnlyLowerPermissionsInsideTestProcedures.cs:line 45\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass52_1.<ExecuteSyntaxNodeAction>b__1() in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 742\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 1099'",
	"source": "AL",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}
```

```
{
	"resource": "/c:/Users/myuser/source/repos/MyApp/app.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "AD0001",
	"severity": 4,
	"message": "Analyzer 'Microsoft.Dynamics.Nav.CodeCop.Design.Rule205VariablesMustAlwaysBeInitialized' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.VariableListDeclarationSyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.VariableDeclarationSyntax'.\r\n   at Microsoft.Dynamics.Nav.CodeCop.Design.Rule205VariablesMustAlwaysBeInitialized.InitializeGlobalVariablesAnalyzer(SyntaxNodeAnalysisContext syntaxNodeAnalysisContext) in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeCop\\Design\\Rule205VariablesMustAlwaysBeInitialized.cs:line 105\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass52_1.<ExecuteSyntaxNodeAction>b__1() in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 742\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 1099'",
	"source": "AL",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}
```

**Comment by dtkb** [comment] 2020-05-18 09:07
There are various bugs with things being attributed to `app.json` when they shouldn't. Repros for these might help MS fix that.

**Comment by rdebath** [comment] 2020-05-26 11:58
This seems more like a systemic problem; these exceptions never give the file that they are triggered by so the only way to find them is some sort of project bisection. This is not really reasonable (currently for me 500 files and 6347 files -- a baseapp with about half the changes moved into another extension). 

It should be pretty easy for Microsoft to have the exception handler (carefully) rummage around for at least a source file; hopefully a line number too.

**Comment by atoader** [comment] 2020-05-29 08:00
This is a good point! The main challenge is that these rules do not run on a file or even an object, they are decoupled from that concept. We'll see what we can do

**Comment by DanielGoehler** [comment] 2020-05-29 10:53
Object Type and Object No. would also help

**Comment by pri-kise** [comment] 2020-06-09 14:45
I think this should me marked as bug, since theses errors let pipelines crash.

**Comment by pri-kise** [comment] 2021-02-02 12:58
@atoader I think i found one source for this problem.
An old compiler e.g. for BC16 isn't capable of handling a ruleset with CodeCop Rules that are only available in newer versions.
I compile a project with the a ruleset file containing the following part:
```json

        {
            "id": "AS0092",
            "action": "Info",
            "justification": "Only inform: The 'applicationInsightsKey' property must specify the instrumentation key of the Azure Application Insights resource for monitoring operations related to this extension. See https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/telemetry-overview for additional information."
        },
```

Everything works fine with the current AL Language Extension.
But as soon as I try to compile this with an old AL Language Extension (Downloaded together with the Artifacts), I receive the following error:

> warning AD0001: Analyzer 'Microsoft.Dynamics.Nav.CodeCop.Design.Rule205VariablesMustAlwaysBeInitialized' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Das Objekt des Typs "Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.VariableListDeclarationSyntax" kann nicht in Typ "Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.VariableDeclarationSyntax" umgewandelt werden.

**Comment by BazookaMusic** [comment] 2023-11-28 13:47
We are looking at old issues to evaluate if the problem is still there. The issue here is quite complex. The errors mentioned are all fatal errors that cause an analyzer rule to crash due to bugs in the rule implementation or the code that the rules are referencing.

We cannot give better error messages here than the stack trace since the failure could be from code trying to initialize some cache or analyzing some dependency of a file or anything else really.  Even we have to often dig into the code to find out where the issue came from and unfortunately there's no magic way to trace these to a file. The way to deal with these failures is to report the stack traces so they can be fixed.

It is also not possible to be more resilient to these failures through a generic way, because since they're fatal, they could be corrupting state. The fact that they exist points to a testing gap and we will keep this into account in the future to try to improve how we do with these.

With this, I will be closing this bug.

**Closed by BazookaMusic** 2023-11-28 13:47 UTC
Labels: enhancement
