### ISSUE TITLE
Cannot Convert from <type> to _MissingTypeSymbol 

### ISSUE THREAD

**Issue by petterssonmv** [microsoft/AL#7529] opened 2023-10-04 13:58 UTC
Please include the following with each issue:

**1. Describe the bug**
GIVEN
VSCode automatically updated AL extension from version 11.7.863928 to version 12.0.875970
WHEN
running alc.exe 
THEN
compilation of some apps in our project resulted in following errors
error AL0133: Argument 1: Cannot convert from 'Record Transaction Header' to '_MissingTypeSymbol_'

![MicrosoftTeams-image](https://github.com/microsoft/AL/assets/112394301/5b704a50-aaa2-4cec-a8dc-954c8d9f3977)

WHEN
reverting to version 11.7.863928
THEN
Compilation gives no errors,.

**2. To Reproduce**
1. Update AL extension from version 11.7.863928 to version 12.0.875970
2. Compile an app using alc.exe or use vscode F5

``` AL
AL code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally.
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**

**4. Actual behavior**
A clear and concise description of what happened accompanied by images, animations, or a link to a video showing the issue occurring

**5. Versions:**

- AL Language:
- Visual Studio Code:
- Business Central:
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by magpet01** [comment] 2023-10-04 15:02
The assignments are from a Norwegian vertical solution LSPharmacy NO on BC 14.0.41143 C/Side.
and they are assigned to AL-extensions in an app.

I have deleted existing symbols and re-downloaded - error still occurs
I have regenerated symbol references from C/Side by running finsql.exe Command=generatesymbolreference - error still occurs

Errors occurs in lines with Rec.
Rec is a C/Side table and it seems that the compiler fails to resolve Rec from the Source Table of the page.
```
pageextension 90444 CgiPhSalesFulfillmentDev extends "Transaction Register"
{
    actions
    {
        addlast(Creation)
        {
            action(testsettlement)
            {
                Image = Holiday;
                Promoted = true;
                PromotedOnly = true;
                PromotedCategory = Process;
                PromotedIsBig = true;
                CaptionML = ENU = 'Test salesfulfillment', NOR = 'Test salesfulfillment';

                trigger OnAction()
                var
                    TransactionHeader: Record "Transaction Header";
                    CgiPhSalesFulfillOperations: Codeunit "CgiPhSalesFulfill Operations";
                begin
                    CgiPhSalesFulfillOperations.SalesFulfilmentSale(Rec);
                    CgiPhSalesFulfillOperations.SalesFulfilmentReimbursement(Rec);
                    CgiPhSalesFulfillOperations.SalesFulfilmentInvoice(Rec);
                end;
            }
        }
    }
}
```

**Comment by pri-kise** [comment] 2023-10-05 13:42
I've got the same problem with BC14 and an AL App.

I use a function from another AL App in my code and I receive the same error:
> error AL0133: Argument 1: Cannot convert from 'Record Sales Line' to 'MissingTypeSymbol'

**Comment by DanielGoehler** [comment] 2023-10-05 14:37
+1

**Comment by MH1612** [comment] 2023-10-18 06:43
+1

**Comment by AndreasPrendke** [comment] 2023-10-18 06:47
+1

**Comment by ChrSt89** [comment] 2023-10-18 09:05
+1

**Comment by pri-kise** [comment] 2023-10-19 19:14
I enabled the Verbose mode for the editorServices.og, but there was not clue on the cause of this problem.

**Comment by magpet01** [comment] 2023-10-25 12:57
Still having same errors in BC 14.0.41143 with latest AL extension version:  12.1.887908

> error AL0133: Argument 1: cannot convert from 'Record "Prescription Order Line"' to '__MissingTypeSymbol__'

**Comment by OUAIRY** [comment] 2023-10-31 16:25
I have the same problem :(

BC 14.0.45012.0 / Microsoft (R) AL Compiler version 12.1.13.31069 

Pipeline is in error. It's a big problem.

**Comment by f0ffee** [comment] 2023-11-07 08:40
Same issue here. I understand that BC14 is not supported anymore, but I hope Microsoft understands we'll have to support it for many years to come, as partners around the world are still supporting Navision 3.70 or NAV 2009...

**Comment by MH1612** [comment] 2023-11-07 09:28
Timely announcement of the discontinuation of support for BC14 is crucial to provide developers and users with the opportunity to prepare. This enables users to make necessary adjustments, such as transitioning the compiler of the DevOps pipelines, to avoid unnecessary stress and additional effort. Clear communication is essential in this regard.

**Comment by bwdeleeuw** [comment] 2023-11-07 15:56
Same issue on all our BC14 installs. We work around it by loading the vsix from BC22, but that is a hassle.

**Comment by ThomasBrodkorb** [comment] 2023-11-09 08:35
Same here, it is a pain!!!

**Comment by PooyaKharamesh** [comment] 2024-01-12 14:59
I just investigated a case with some code provided from one of the partner and here I will share the result and finding which might be helpful

Here is the error message for the refrence 
![image](https://github.com/microsoft/AL/assets/39521917/ada5b5e1-88a3-43ed-96ad-9a323a116fee)

![image](https://github.com/microsoft/AL/assets/39521917/c135810e-633d-492f-91d7-1984a43496d9)

The problem arises because the record mentioned in the event subscriber doesn't align with the record used as a parameter in the event due to an inability to correctly resolve the record in the event.

The root cause lies in the dependency structure of "XX Bank Deposits." The Microsoft app "Bank Deposits" relies on the Application app, which, in turn, depends on the base app and it propagates its dependencies. The missing record belongs to the base app, causing the "Gen. Journal Line" record to be resolved accurately from the base while compiling Microsoft "Bank Deposits". In the provided sample code/app, direct dependencies exist for "XX Embed Application," but the Application app is not used. Consequently, the record from the base app is unavailable, while the "Posted Bank Deposit Line" record from the bank deposit app resolves correctly.

To address this issue, the partner should create an empty app resembling the Microsoft Application app. This new app should have dependencies on "XX Embed Application" and "System Application," with the "propagateDependencies" property set to true. Implementing this solution will resolve the problem. Then in other apps they should use Application property in the manifest instead of a direct dependency to their base app

**Closed** 2024-01-16 10:08 UTC
Labels: al-core-compiler, accepted

**Comment by petterssonmv** [comment] 2024-01-16 11:17
**@qutreson, How come you deem this as completed?**
 It has not been confirmed yet by anyone else that the workaround actually works. Also the solution does not give a concise step by step instruction how to correct this. What is "Application property in the manifest?" 
 
"To address this issue, the partner should create an empty app resembling the Microsoft Application app. This new app should have dependencies on "XX Embed Application" and "System Application," with the "propagateDependencies" property set to true. Implementing this solution will resolve the problem. Then in other apps they should use Application property in the manifest instead of a direct dependency to their base app"

**Comment by NKarolak** [comment] 2024-01-16 13:20
@petterssonmv manifest = app.json. It is about the `application` property in the app.json.

**Comment by bwdeleeuw** [comment] 2024-01-16 15:02
I'm also not clear on the instructions. We do not use custom base apps, and every project has an Application property.

**Comment by PooyaKharamesh** [comment] 2024-01-16 20:49
This GitHub repository is dedicated to handling issues and feedback for the latest Developer releases of the AL development tools for Dynamics 365 Business Central. 

Please note that this problem pertains to version 14. This version is moved out of mainstream support. The End of Life (mainstream support) for v14 was October 2023. https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/terms/lifecycle-policy-on-premises

I couldn't reproduce the issue using the provided code in this thread on version 14.5.35970.46481 and the latest AL language extension. 

The preceding comment summarizes an investigation where a partner offered detailed steps and code/projects, the issue in that case was regarding extension manifest(app.json file) and usage of Applicaton property in the app.json. 

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

**Comment by jmadrigalTCN** [comment] 2024-01-31 09:40
The same with BC20 not only BC14 or lower:

APP.json

    "screenshots": [],
    "platform": "1.0.0.0",
    "application": "20.0.0.0",
    "idRange": {
        "from": 7042930,
        "to": 7042959
    },
    "runtime": "9.0",

Errors in VSCode:

Argument 1: cannot convert from 'Record "Tracking Specification"' to '__MissingTypeSymbol__'
Argument 2: cannot convert from 'Record "Tracking Specification"' to '__MissingTypeSymbol__'
Argument 3: cannot convert from 'Record "Reservation Entry"' to '__MissingTypeSymbol__'

**Comment by kalberes** [comment] 2024-02-01 09:37
@jmadrigalTCN 
20.x is out of support. Can you repro the issue with a server providing symbols that is in support? If yes, we need a clear repro step and we may look into it.
The same for 14.x issues. Out of support. As I remember 14.x is a server generating symbols from C/SIDE based metadata. Can you repro the issue with a server providing symbols that is in support?

**Comment by OlafJorritsma1** [comment] 2024-02-14 12:38
An update from the Microsoft partner that provided examples and code to Microsoft on BC23.0 and by which Microsoft reported the solution offered.
The solution did not work, it turns out more complicated then expected and more time is needed to diagnose and come up with a correct solution.

**Comment by LogicLemur** [comment] 2024-05-03 10:26
This problem happened with BC24 for me.  Any info on when this is meant to be resolved?

**Comment by BazookaMusic** [comment] 2024-05-07 15:17
I looked at this issue and identified one case where this happens from the project that a customer helpfully provided. The issue is similar to what @PooyaKharamesh described.

The problem appears due to Embed ISV base apps using a different app ID for the base application. To reproduce it you can do the following:
1) Start developing a new app using AL:Go
2) Use the application property (or refer to the base application directly as a dependency)
3) Download symbols from an embed ISV cluster
4) Write a codeunit with a procedure with a record parameter coming from the base application (ex. MyParam: Record Customer)
5) Package the app so you get `myapp.app`

Inside the app file, we will have logged that **Customer** comes from the embed ISV base app.

Second app
1) Start developing a second app that depends on `myapp.app` by putting it into the package cache path.
2) Use the application property or refer to the base application directly as a dependency
3) Download symbols from a standard Microsoft cluster (different base application)
3) Try to use the procedure from your dependency

We try to resolve the parameter type for **Customer** and will try to find it in the modified base app. However, we only have the Microsoft base app in the symbols so it fails. The reason it used to work in the past was that we would resolve only by name, but we changed the symbols file specification so it can work with namespaces where duplicate names can exist between apps. Unfortunately, reverting to resolving only by name is not something we want to do to support this specific scenario.

**How to work around this**
For 24 and later, there is an alternateIds property for the app.json which allows Embed ISV base apps to say which apps they are replacing and then this issue does not exist. All they have to do is add the Microsoft base app ID in this list and symbols will be resolved properly.

For earlier than 24, there are two workarounds:
1) When developing apps for Microsoft clusters, ensure all dependencies have been compiled on a project using symbols only from Microsoft clusters. That means not copying symbol files across projects for Embed ISVs and Microsoft. If you have already published an app which was compiled this way, it may need to be recompiled with the correct symbols and republished so that downloading symbols brings in correct symbols
2) Use an older version of the VSIX for older projects if you have to share symbols between Embed ISV and Microsoft projects

**Comment by NKarolak** [comment] 2024-05-07 18:25
> For 24 and later, there is an alternateIds property for the app.json 

@BazookaMusic 
This property is not documented yet - could you please close the gap? 
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files#appjson-file

**Comment by NKarolak** [comment] 2024-12-03 10:03
@petterssonmv  
This issue is already closed. It means that Microsoft (usually) won't even read further comments on it.
Best is to create a new issue and link it to this one.
