### ISSUE TITLE
Wrong Analyzer for app.json

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#5835] opened 2020-04-24 10:53 UTC
**Describe the bug**
```
With the new AL Language Extension I receiv the following warnings for the `app.json` file. 
	"resource": "/c:/Users/DummyTest/Documents/Repos/ALDemo/app.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "AD0001",
	"severity": 4,
	"message": "Analyzer 'Microsoft.Dynamics.Nav.CodeCop.Design.Rule087DoOnlyLowerPermissionsInsideTestProcedures' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.VariableListDeclarationSyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.VariableDeclarationSyntax'.\r\n   at Microsoft.Dynamics.Nav.CodeCop.Design.Rule087DoOnlyLowerPermissionsInsideTestProcedures.AnalyzeVariableList(SyntaxNodeAnalysisContext ctx) in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeCop\\Design\\Rule087DoOnlyLowerPermissionsInsideTestProcedures.cs:line 45\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass52_1.<ExecuteSyntaxNodeAction>b__1() in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 742\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 1099'",
	"source": "AL",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}
{
	"resource": "/c:/Users/DummyTest/Documents/Repos/ALDemo/app.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "AD0001",
	"severity": 4,
	"message": "Analyzer 'Microsoft.Dynamics.Nav.CodeCop.Design.Rule205VariablesMustAlwaysBeInitialized' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.VariableListDeclarationSyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.VariableDeclarationSyntax'.\r\n   at Microsoft.Dynamics.Nav.CodeCop.Design.Rule205VariablesMustAlwaysBeInitialized.InitializeGlobalVariablesAnalyzer(SyntaxNodeAnalysisContext syntaxNodeAnalysisContext) in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeCop\\Design\\Rule205VariablesMustAlwaysBeInitialized.cs:line 105\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass52_1.<ExecuteSyntaxNodeAction>b__1() in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 742\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 1099'",
	"source": "AL",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}
```

**To Reproduce**
I have no idea how this can be reproduced.

**Expected behavior**
These Codecops shouldn't evaluate the `app.json` file.

**Screenshots**
--
**5. Versions:**

 - AL Language: 5.0.254558

 - Business Central: DE Business Central 16.0 (Plattform 16.0.11233.12061 + Application 16.0.12076.0)

**Comment by salgiza** [comment] 2020-04-28 11:10
If it helps: when the analyzer crashes it always says that the error is in the app.json file, instead of pointing to the real .al file that it was parsing when it crashed (unfortunately, I've been there a lot of times).

So, you seem to have found a bug in the analyzer (it should never crash), but it is probably unrelated to the app.json. You might want to remove *.al files from the app until the errors disappear, to try to find what in particular is causing these crashes.

**Comment by kasperdj** [comment] 2020-05-01 10:32
Any progress on this issue. Currently when there is a "runtime" error in the CodeCop Analyzer referencing app.json the CodeCop stops working and we will not see the error before our build pipeline fails. At the moment we have a lot over overhead due to this issue.

**Comment by atoader** [comment] 2020-05-05 19:23
@MarcHansenMicrosoft can you take a look?

**Comment by MarcHansenMicrosoft** [comment] 2020-05-06 11:16
CodeCop does run on app.json as well as code.

Could provide a sample repro solution, so we can investigate the issue?

**Comment by salgiza** [comment] 2020-05-06 11:23
@MarcHansenMicrosoft Regardless of whether this particular error is due to the app.json or not, could it be possible to catch error exceptions in CodeCop, so that when it crashes it tells you which file it was parsing? (instead of always pointing to the app.json)

**Comment by MarcHansenMicrosoft** [comment] 2020-05-06 11:26
@atoader that is more a question for you.

**Comment by AcererakTheLich** [comment] 2020-05-06 11:41
Hi,
I don't know if this can help or if really related but I encountered same kind of error linked to App.json recently. I did not succeed reproducing in fresh new hello world project but can observe it in our own.
In my case It came from declaring same type variables on single line. Once I rollback to one line by variable the error desapeared.

Here is the error received when variables are declared on same Line:
Analyzer 'Microsoft.Dynamics.Nav.CodeCop.Design.Rule205VariablesMustAlwaysBeInitialized' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.VariableListDeclarationSyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.VariableDeclarationSyntax'.
   at Microsoft.Dynamics.Nav.CodeCop.Design.Rule205VariablesMustAlwaysBeInitialized.InitializeGlobalVariablesAnalyzer(SyntaxNodeAnalysisContext syntaxNodeAnalysisContext) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeCop\Design\Rule205VariablesMustAlwaysBeInitialized.cs:line 105
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass52_1.<ExecuteSyntaxNodeAction>b__1() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 742
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1099'

**Comment by kasperdj** [comment] 2020-05-06 11:42
I can provide an al project with the problem if you setup a private file transfer workspace and send this link to the workspace to krj@elbek-vejrup.dk

**Comment by kalberes** [comment] 2020-05-12 14:09
@MarcHansenMicrosoft the issue maybe here that the codeanalyzer in place does not read correctly the diagnostic source file location.

**Comment by PaulIvan** [comment] 2020-10-16 13:23
Thank your for reporting this issue. I am closing it as it looks like a duplicate of #5889. Feel free to contribute on the issue linked.

**Closed by PaulIvan** 2020-10-16 13:23 UTC
Labels: CodeCop, bug, duplicate, static-code-analysis
