### ISSUE TITLE
Permission error after RAD publishing

### ISSUE THREAD

**Issue by tyurm** [microsoft/AL#7175] opened 2022-09-24 18:03 UTC
**1. Describe the bug**
Whenever you try to publish changes using "Rapid Application Publish with/without debugging" it breaks permissions, so you get "Your license does not grant you the following permissions on TableData ALBug Table: Read." error.

It looks like "RAD Publish" make any extension that have tables useless.

**2. To Reproduce**
1. Create HelloWord extension, and add these two object to the project (create separate al file for each object):
 ```
pageextension 50100 "ALBug Customer List" extends "Customer List"
{

    trigger OnOpenPage()
    var
        TestTable: Record "ALBug Table";
    begin
        if not TestTable.Get() then begin
            TestTable.Init();
            TestTable.Insert();
        end;
        Message('done');
    end;
}
```

```
table 50100 "ALBug Table"
{
    DataClassification = ToBeClassified;

    fields
    {
        field(1; PK; Code[20])
        {
            DataClassification = ToBeClassified;

        }
    }

    keys
    {
        key(PK; PK)
        {
            Clustered = true;
        }
    }

}
```

3. Publish extension.
4. Change a message text in CustomerListExt object 
5. Save, Build (check that rad.json file include your changes after build) and Publish extension using "Rapid Application Publish with debugging" action.

**3. Expected behavior**
Customer List onOpenPage trigger should show new message.

**4. Actual behavior**
 Customer List page will throw next error:
"Your license does not grant you the following permissions on TableData ALBug Table: Read."

**5. Versions:**

- AL Language: v9.5.674382
- Visual Studio Code: 1.71.1
- Business Central: 20.5.45456.45681 (SaaS Sandbox environment)
- List of Visual Studio Code extensions that you have installed:
AL Language, AL CodeActions, AL Formatter, AL Toolbox, AZ AL Dev Tools/AL Code Outline, waldo`s CRS AL Language Extension

**Comment by thloke** [comment] 2022-10-04 08:54
Duplicate of #7172 7169

**Closed by thloke** 2022-10-04 08:54 UTC
Labels: requires-triage, RAD

**Comment by kalberes** [comment] 2022-10-07 10:22
@tyurm 

I do not have a repro for your issue. Can you check that the app that you try to publish with RAD has an Entitlement folder with <your app id>.xml in it  (you can open the app with 7.zip)
