### ISSUE TITLE
PrintOnlyIfDetail for Saas

### ISSUE THREAD

**Issue by Steven-SBSI** [microsoft/AL#7148] opened 2022-08-30 11:33 UTC
Hello,

The PrintOnlyIfDetail method on Report for Saas is not available.

How can we expect a fix to the AL Compiler for Saas ?

Or Workaround ?

 Thanks.

**Comment by thloke** [comment] 2022-09-15 08:21
Closing as duplicate of #6498

**Closed by thloke** 2022-09-15 08:21 UTC
