### ISSUE TITLE
Nested repeater in Word Layout

### ISSUE THREAD

**Issue by TheHeino** [microsoft/AL#6628] opened 2021-05-14 14:48 UTC
I want to add some Sales Comment Lines under Sales Line in a report with Word Layout.

I am extending the Standard Sales invoice report (1306) with a new DataItem that I want under Each Line:
```AL
reportextension 50100 "SalesInvoiceExt" extends "Standard Sales - Invoice"
{
    dataset
    {
        add(Header)
        {
            column(External_Document_No_; "External Document No.")
            {
            }
            column(Your_Reference; "Your Reference")
            {
            }
        }
        addlast(line)
        {
            dataitem("Sales Comment Line"; "Sales Comment Line")
            {
                DataItemLink = "No." = field("Document No."), "Document Line No." = field("Line No.");
                DataItemLinkReference = line;
                DataItemTableView = sorting("Document Type", "No.", "Document Line No.", "Line No.") where("Document Type" = const("Posted Invoice"));
                column(Comment_; Comment)
                {
                }
            }
        }
    }
}
```

Simple enough... well it should be :-) 
This issue has been posted here before - but as far as I can see not solved :-) I get the exact same error as the ones here: https://github.com/Microsoft/AL/issues/3880
But the last comment on that issue was almost a year ago, so perhaps someone has solved it in the meantime?

When I Export the Word Layout from BC and open it I can see that dataitem and field have appeared in the XML mapping - Perfect!
![image](https://user-images.githubusercontent.com/35332398/118283080-455ec200-b4cf-11eb-9b38-e0225a5e673c.png)

I add a line to the "Line-repeater" here:
![image](https://user-images.githubusercontent.com/35332398/118283580-d170e980-b4cf-11eb-8b47-0dfee980631b.png)

I delete all the Content controls on the new line and now I have several options:
One option is to Open the XML mapping - mark the new line - right click on the Sales_Comment_Line and choose "Repeater" - this should be ok. Then inside the new line: Right click on the Comment_ (under Sales_Comment_Line) and choose as Plain text.
Beautiful:
![image](https://user-images.githubusercontent.com/35332398/118284677-f6b22780-b4d0-11eb-8c6b-fedc98ba14c9.png)
Am I really that good? Let's see...
Now I save the Layout and believe all is good. I Close MS Word... Just to make sure all is perfect I open the Layout again... and this is how it looks like now:
![image](https://user-images.githubusercontent.com/35332398/118284993-57d9fb00-b4d1-11eb-9166-5f59495179e0.png)
So appearently it refuses to remember the Comment_ Content Control :-(
When I try to upload it, it imports ok but when I run the report it ignores my changes.
If I just hardcode some letters in the Content Control and save the Layout again - it saves it... but this time it gives me the following error when importing it into BC:
![image](https://user-images.githubusercontent.com/35332398/118286196-80162980-b4d2-11eb-81c1-4ed8bd1cba41.png)

I have also tried creating a Table Inside the second row and "repeated" that - but same problem...

I have also seen this fine video about Nested Repeaters in Word - but appearently we do not agree what Nested Repeaters are :-)
https://community.dynamics.com/dynamicbusiness/b/videos/posts/how-do-i-use-nesting-repeaters-in-a-word-layout-in-microsoft-dynamics-nav-2015

Should I really do this in RDL?

Thank you in advance.

**Comment by Drakonian** [comment] 2021-05-23 21:44
Try this:

1. Add control
2. Select control
3. Add repeat from control dataitem
4. Add group only for control

**Comment by SanderCMD** [comment] 2021-07-14 07:49
Hey @TheHeino ,
I know this is very late, but I also had to make something like this this week.
I see that the error says something about Header/Line[2]. Maybe you should try to span the two rows when adding the Header/Line repeating control.
After that go and select the cells from the 2nd row, and insert the repeating of your Sales_Comment_Line.
After that insert the field in the cell.

I think that is how I solved it.

**Comment by MathurRahul** [comment] 2021-08-04 17:35
Hello @SanderCMD @TheHeino 

I'm encountering the same issue with nested repeaters. 
Did you manage to fix it? If yes can you please share your solution (with screenshot if possible).

Thank you.

**Comment by tyurm** [comment] 2022-01-04 11:31
There is a pretty old blog post written by Luc Van Vugt:
https://www.fluxxus.nl/index.php/bc/why-is-the-repeater-in-my-word-layout-not-showing-data/

The solution was - "Make sure when inserting the repeater to have a table row above and below it"
It helped me, probably it will help you as well.

**Comment by thloke** [comment] 2024-04-30 01:02
Duplicate of #7704

**Closed by thloke** 2024-04-30 01:02 UTC

**Comment by almqvist-it** [comment] 2024-10-17 08:24
Hi guys! 

I am very new to this, and i have had the same issues as you have regarding this subject. 
After a couple of days i managed to sort i out and create a nested repeater inside a word layout. 

1.
![Image](https://github.com/user-attachments/assets/3ed83255-d980-457f-a9f5-7946ccba6a49)

I created a reportextension on the report Standard Purchase - Order and added my dataitem. 
As you se i also set filters in both OnAfterGetRecord and OnPreDataItem so that we get the right comment for the right document. 

2.
![Image](https://github.com/user-attachments/assets/ca9a4c5a-f250-43ee-87a4-a28ffb58950a)
 
I merged the rows that were beneath the Lines and over the TotalAmount etc. 
![Image](https://github.com/user-attachments/assets/ad008bf8-80a1-4b92-a507-c498446521df)

I made the field a little wider and inserted a table that was 2x2
![Image](https://github.com/user-attachments/assets/de64ca46-cd5e-42b1-9b83-76f3e01e9c4c)

I went to my dataitem in XML Mapping and inserted the label first as plain text.
![Image](https://github.com/user-attachments/assets/d5726729-b76d-477c-85f7-de7c8ab9a463)

I then highlighted the entire row and right-clicked my dataitem - Insert content control - _Repeating
![Image](https://github.com/user-attachments/assets/cd3cd570-c2ba-4ff8-bcf6-0dac16fb091c)

I added my fields in the repeater as plain text. 
![Image](https://github.com/user-attachments/assets/8d218757-a4de-4581-b7b0-40a37c7a0cb4)

Now it should resemble something like this:
![Image](https://github.com/user-attachments/assets/3b5121a6-378b-4403-afdc-6f739763ea94)

Now save the layout and close word. 

Just import it to your Custom Layout and make sure when you try it that you have comments or the value that you are trying to repeat. 
I previewed my report and this is how it looks like now:
![Image](https://github.com/user-attachments/assets/d814333a-6416-4d47-882c-7d6372a53be3)

I may not be beautiful, but i have the values that i wanted to showcase. Just change the table design etc if you want it to look better. 
I really hope this was helpful!
