### ISSUE TITLE
Build output not displaying errors "cannot be used for extension development"

### ISSUE THREAD

**Issue by tinfister** [microsoft/AL#6786] opened 2021-10-06 08:41 UTC
- AL Extension Version: 
v8.1.525271

- Server Version: 
Any

1) Create new App using AL:GO command
2) Create object that calls function from product marked as OnPrem
![image](https://user-images.githubusercontent.com/29481795/136168226-19094948-0645-4865-b741-bbc8c890bbef.png)

3) Create another object that has error, for example table extension which extends table that doesn't exist
![image](https://user-images.githubusercontent.com/29481795/136168471-008549af-8f13-4eac-9737-2c8f1a529197.png)

Now you see 2 errors in Problems in VSCode
![image](https://user-images.githubusercontent.com/29481795/136168523-00684461-2cec-446c-939c-1a82936c42df.png)

4) AL:Package

Output displays only one error, and "cannot be used for extension development" is missing
![image](https://user-images.githubusercontent.com/29481795/136168649-5789609b-e72d-46d3-8f72-4a75ae54df03.png)

If you create different error in step 3 (my example was text to integer) then you get both errors in the output.
![image](https://user-images.githubusercontent.com/29481795/136169304-676bd0cb-be44-41ad-bcf4-692cc963fb7a.png)

So this doesn't happen all the time and with all types of errors.
We have a big project which we want to prepare for the cloud soon, but we cannot see all the problems in our pipelines because output doesn't display "cannot be used for extension development" errors when we call the function that is marked OnPrem.

**Comment by kalberes** [comment] 2021-10-14 17:10
Do you have al.incrementalBuild set to true?

**Comment by tinfister** [comment] 2021-10-19 15:21
Sorry but I don't understand. 
I can't get all errors in build output, no matter what I set al.incrementalBuild to.
If I set it to false I still don't get all the errors
![image](https://user-images.githubusercontent.com/29481795/137941130-ecdf23bc-7fdf-448a-97e3-0110d8155e18.png)
![image](https://user-images.githubusercontent.com/29481795/137941211-369850df-5600-4168-8b66-1dd86feb6662.png)

How do I get all errors in Output? This screenshot is from new AL project with total of 2 files, and it doesn't display all errors.

**Comment by JesperSchulz** [comment] 2021-11-05 07:05
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 32007 and VS Code Extension Version 9.0.538685. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by nndobrev** [comment] 2021-11-05 11:16
Hi @tinfister you can see that we closed the issue and the fix is going to be available in the version from the aforementioned comment. 
We added a new parameter to the compilation options, now you should be able to control the behaviour you were looking for. 
![image](https://user-images.githubusercontent.com/85873063/140502270-811b2264-4148-4a73-8c3e-8d0697e05db1.png)

**Comment by NKarolak** [comment] 2021-11-09 07:24
@nndobrev I've just tested the setting in AL Language 8.1.540594, but I could not see any change in behavior. I've tested with a variable declaration to a non-existing object + an unknown application area.
Both issues are displayed as errors in the Problems section, but building the app, only the first error is detected, then the compilation stops.
Am I missing some further piece of information?

**Comment by tinfister** [comment] 2021-11-09 07:26
Jesper commented that it will be available from VS Code Extension Version 9.0.538685.

**Comment by NKarolak** [comment] 2021-11-09 07:28
Oops ... well, the option however is already available - maybe just not yet working, but existing, and documented in the change log:
https://marketplace.visualstudio.com/items/ms-dynamics-smb.al/changelog

**Comment by NKarolak** [comment] 2021-11-09 07:30
But: stupid me! I've tested it with an older runtime (7.x) specified in app.json!

**Comment by nndobrev** [comment] 2021-11-10 14:47
Hi @NKarolak, could you please provide more info because I am testing it with the described scenario and it works just fine for me. 

vsix: v8.1.540594 (the latest one available in the marketplace)
target runtime version: 8.0 (tested also 8.1)
settings:
`
{
    "al.compilationOptions": {
        "continueBuildOnError": true
    }
}
`
and the result I am getting is the following:
![image](https://user-images.githubusercontent.com/85873063/141133691-250d50b0-e10e-4228-9da7-fc0f6f907014.png)

and then when I attempt to build:
![image](https://user-images.githubusercontent.com/85873063/141133794-f900e5bf-5e3f-45db-9995-5bd56db261df.png)

Please note that the behaviour of the compiler when you have the parameter set to true might be very strange in particular cases and this is why we strongly recommend using the default value: false. For example, if you have errors in parsing having `continueBuildOnError = true` might result in multiple and non-related errors during binding which is inevitable.

**Comment by NKarolak** [comment] 2021-11-10 15:12
It happens probably only if your error was an "upgraded" warning.

1. Enable the UICop
2. Use the following Cop.ruleset.json in your settings:
```
{
    "name": "AppSource ruleset",
    "rules": [
        {
            "id": "AA0189",
            "action": "Error",
            "justification": "Test"
        }
    ]
}
```
3. Test the following code

```
pageextension 50100 CustomerListExt extends "Customer List"
{
    layout
    {
        addlast(content)
        {
            
            field(Address; Rec.Address)
            {
                ToolTip = 'Specifies the value of the Address field.';
                ApplicationArea = ABC;
            }
        }
    }

    trigger OnOpenPage();
    var
        SalesLine: Record "Sales Line2";
    begin
        Message('App published: Hello world');
    end;   
}
```

We have two errors:
![image](https://user-images.githubusercontent.com/34504100/141138749-1fbff11e-7663-4550-9a05-0c34c7741f6a.png)

But using continueBuildOnError = true, on building the app we get only one error:
`error AL0185: Table 'Sales Line2' is missing`

**Comment by nndobrev** [comment] 2021-11-10 15:52
I will reopen the issue here and investigate :)

**Comment by nndobrev** [comment] 2021-11-12 16:12
Hi @NKarolak and @tinfister , 

Can you please check if you have incrementalBuild set to true and if you do disable it and try to reproduce the issue again? 

Thanks :)

**Comment by NKarolak** [comment] 2021-11-12 16:22
@nndrovev Not before Monday :-)

**Comment by tinfister** [comment] 2021-11-12 16:23
@nndrovev for me it was incrementalBuild  set to true, and indeed it is better when I set it to false. This is screenshot from "repro" app
![image](https://user-images.githubusercontent.com/29481795/141499896-cbdbd666-aa89-462f-9050-56074981fbbe.png)

Now I'm testing our core solution

**Comment by tinfister** [comment] 2021-11-12 16:28
Build output "error A" = 632 and problems view
![image](https://user-images.githubusercontent.com/29481795/141500535-7349ae91-6553-4126-baf7-04cdd690ec00.png)
I would say it is better with incrementalBuild set to false

**Comment by kalberes** [comment] 2021-11-12 16:33
yes but don't forget that if you want better resource governance in a workspace, project to project resolution,  and faster builds you should use incrementalBuild = true

**Comment by tinfister** [comment] 2021-11-12 16:36
Yes of course. We will use this on our nightly appsource validation build, not all the time.
It would be even better if this works with incrementialBuild set to true

**Comment by NKarolak** [comment] 2021-11-15 07:24
I can also confirm that `"al.incrementalBuild": false` solved my issue.

**Comment by JesperSchulz** [comment] 2021-11-16 07:39
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 32063 and VS Code Extension Version 9.0.539388. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by nndobrev** [comment] 2021-11-18 15:05
Closing the issue and we will update the documentation to reflect that the feature is now supported only when incrementialBuild is set to false.

**Closed by nndobrev** 2021-11-18 15:05 UTC
Labels: bug
