### ISSUE TITLE
Property DecimalPlaces is ignored

### ISSUE THREAD

**Issue by pjanfred** [Microsoft/AL#2155] opened 2018-05-06 15:22 UTC
Hi everyone,

if i set DecimalPlaces=3; in a table or in a page object the property is ignored. It only works when i run the table object directly.

Example (Table field):
`field(80;"Customer Price";Decimal)
{
DecimalPlaces=3;
}`

Example (Page field):
`field("Customer Price";"Customer Price")
{
DecimalPlaces=3;
}`

I use version: 11.0.20783

**Comment by dennisfrostlander** [comment] 2018-05-07 10:43
Seems to be the the duplicate of #1282. If that's the case, the related issue is being backported to Nav 2018 already.

**Comment by jrrdk** [comment] 2018-05-15 08:14
So can we expect this issue to be resolved in NAV2018 CU6 ?
Is not incluted in CU5 on pages the page does not inherits the decimalplaces from table and if you set decimalplaces on the page i dosent work

**Comment by DominikDitoIvosevic** [comment] 2018-05-15 09:53
yes the bug fix is in the pipeline planned for next CU

**Closed** 2018-08-03 13:44 UTC
Labels: duplicate
