### ISSUE TITLE
Trello Dotnet Addin Load Error

### ISSUE THREAD

**Issue by fortiuscva** [microsoft/AL#5202] opened 2019-08-16 15:30 UTC
I am having trouble while loading the dotnet dll. This is for an on premise implementation which is an upgrade from NAV 2013 to BC13. We have an AL codeunit that uses the assembly and executed from job que's(It is working fine in NAV 2013). After the upgrade to BC, job que is getting failed with an error:
Cannot create an instance of the following .NET Framework object: assembly Cristaux.TrelloNet, Version=0.6.2.0, Culture=neutral, PublicKeyToken=79d8255abbec0fdf, type .Label.

I already have changed the user setting's and declared the assembly type's as it should be done for AL, but no luck.

Any suggestion's?

**Comment by atoader** [comment] 2019-08-18 14:29
@fortiuscva is the type you are trying to create a nested type? I think you are hitting a bug that was present in BC13. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by fortiuscva** [comment] 2019-08-18 14:49
@atoader 
Yes, it's a nested type. Thanks for your suggestion and will do.

**Comment by qutreson** [comment] 2019-10-08 14:37
I am closing this issue because it appears that it has been resolved. Please open a new issue if you can still reproduce it in our latest developer previews and reference the current issue.

**Closed by qutreson** 2019-10-08 14:37 UTC
Labels: input-needed
