### ISSUE TITLE
Get-NAVAppInfo does not show dependency on Application app

### ISSUE THREAD

**Issue by cmuris** [microsoft/AL#5974] opened 2020-06-18 09:41 UTC
**Describe the bug**
When Get-NAVAppInfo is used on an (normal) app file, that has a dependency on Application via the Application property and not via dependencies, this dependency is not shown. If used on the runtime version of the same app, the dependency is shown properly. May be related to #5912  

**To Reproduce**

Create an app with following dependency settings in app.json
`{
  "dependencies": [],
  "application": "16.0.0.0"
}`

run Get-NavAppInfo on compiled app file

**Expected behavior**
Show the accurate dependency information for this app

**Screenshots**
![image](https://user-images.githubusercontent.com/20341187/85004715-28ebc580-b158-11ea-83dd-51024868cdfc.png)

**5. Versions:**

 - AL Language: not applicable

 - Business Central: BC16 CU1

**Comment by AndreyKorepanov** [comment] 2020-06-18 21:36
Hi @cmuris, thank you for reporting the issue. I tried to get a repro on the master branch, but both compiled app and runtime package gave the same result, namely the empty dependencies list, which I think is correct behaviour. Could you please try to reproduce it on the latest daily build to make sure that the issue is still there. Thank you!

**Comment by cmuris** [comment] 2020-06-19 08:22
hi @AndreyKorepanov,
I just checked with the following version
![image](https://user-images.githubusercontent.com/20341187/85112360-d07afd80-b215-11ea-8048-1c9d241a6a90.png)
and the results for any use (compiled app, runtime app, published app) of Get-NavAppinfo is looking the same, means the dependency list shows the Application 16.0.0.0 in my case:
![image](https://user-images.githubusercontent.com/20341187/85112791-7f1f3e00-b216-11ea-940b-028d3d259705.png)

In your case it is always empty?

**Comment by AndreyKorepanov** [comment] 2020-06-19 09:11
@cmuris, thank you for reply. Yes, in my case it is empty, apparently some changes are made recently in this part I'll check it again later. But if it works on your side, than I close the issue now. Thank you!

**Closed by AndreyKorepanov** 2020-06-19 09:11 UTC
Labels: input-needed
