### ISSUE TITLE
Error when enabling bank account

### ISSUE THREAD

**Issue by aeapcommerce** [Microsoft/AL#4484] opened 2019-01-18 21:49 UTC
**Describe the bug**
Bank accounts are not linking properly.  Bank account information is not showing the correct amount. 

**To Reproduce**
Cash management > Bank accounts > click on the bank account > blurp at the top opens up click on > set it up here > click on enable = error that reads: Validation results: cannot setup automatic bank statement import because the selected bank requires multi-factor authentication. 

Also when I go to bank accounts>click on the bank > click on bank statement service > refresh online bank account > it shows me a bank account balance but that balance does not match the balance it shows on bank account card balance $ value.

**Expected behavior**
Since the bank shows it is linked and I can see my balance I would expect the bank account card balance to match when I look at my online bank account. 

I also expect since it shows they are linked that I should be able to enable it and not get an error. 
 
**Screenshots**
I prefer to not put bank account screen shots up at this time.

**Versions:**

 - AL Langauge: 

 - Business Central:

US Dynamics NAV 13.1 (26678)

**Comment by JohanStenberg100** [comment] 2019-01-21 16:24
Hi @aeapcommerce. This issue seems like a general BC issue and not related to AL in particular. Have you verified if the first issue you are describing - that setting up automatic bank statement imports from banks with multi-factor authentication isn't by design? Is your target bank requiring multi-factor auth? As I understand it, you are not publishing any extension. I will therefore close this issue and suggest that you open up a support ticket with Microsoft or a local partner. Then you can get help regarding your specific tenant and desired configuration. Thanks!

P.S. If you are deploying an extension please re-open this issue and attach a ZIP file containing an anonymized version of that extension and also the AL extension version you are using. D.S.

**Closed by JohanStenberg100** 2019-01-21 16:24 UTC

**Comment by aeapcommerce** [comment] 2019-01-23 19:33
Hello Johan,

Do you or anyone else know of a good forum, or support portal I can use to submit this ticket to BC?  I am fairly new to BC and would like some more information on how to get support.  Any information would be appreciated.

Thank you,
Amanda Eklund
Direct Dial # 763-691-9702
AP Commerce, Inc.
www.apcommerce.com<http://www.apcommerce.com/>

**Comment by JohanStenberg100** [comment] 2019-01-24 07:39
Hi again, here are some forums you can try:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

You can also try and reach out to your Microsoft contact and get support. See your options at here: [https://dynamics.microsoft.com/en-us/contact-us/](https://dynamics.microsoft.com/en-us/contact-us/) 

Thanks,

Johan

**Comment by aeapcommerce** [comment] 2019-01-24 14:10
Ok thank you very much!

Thank you,
Amanda Eklund
Direct Dial # 763-691-9702
AP Commerce, Inc.
www.apcommerce.com<http://www.apcommerce.com/>
