### ISSUE TITLE
Cannot Download Symbols with multiple configurations in launch.json

### ISSUE THREAD

**Issue by rvanbekkum** [Microsoft/AL#4889] opened 2019-04-12 11:18 UTC
**Describe the bug**
When you have multiple configurations in your launch.json, the command "AL: Download Symbols" does not work at all. You _will_ be able to choose a configuration, but after that nothing happens. There is also no output in the "OUTPUT" frame at the bottom.
This did work with the previous version (2.1.109895) but then it gave another issue, see #4525 
With version 3.0.107312 it does not work at all.

**To Reproduce**
1. Have multiple configurations in your launch.json.
2. Open the command palette and choose "AL: Download Symbols"

**Expected behavior**
Have the extension download the symbols for the selected configuration.

**Versions:**

 - AL Language: 
```
AL Language
Id: microsoft.al
Description: AL development tools for Dynamics 365 Business Central
Version: 3.0.107312
Publisher: Microsoft
```

 - Business Central: 14.0.29537/29530

**Comment by wisa1** [comment] 2019-04-14 09:24
I ran into that problem a lot too. Using the "Clear Credential Cache" command in VSCode before downloading Symbols from another source seemed to help, so you can re-enter the credentials for your new Symbol-Source. 

Sometimes you need to "Clear Credential Cache" twice (yes...) to make it work, don't ask me why.

**Comment by mickcarr** [comment] 2019-04-17 08:14
I'm also getting this issue. Clearing the credential cache doesn't make any difference. Multiple configurations in the launch file. The drop down selection appears and vanishes instantly. This was working on a previous build of VSCode. Seems like the last two releases have maybe knocked something out of line. This is when targeting on-prem spring release BC.

VSCode
======
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by ajkauffmann** [comment] 2019-04-24 12:48
Probably same issue as this one: https://github.com/Microsoft/AL/issues/4861

**Comment by PooyaKharamesh** [comment] 2019-04-30 12:42
Thank you for reporting it. It appears to be duplicate of #4846 and #4861

**Closed by PooyaKharamesh** 2019-04-30 12:42 UTC
Labels: duplicate
