### ISSUE TITLE
The multi-part identifier could not be bound.

### ISSUE THREAD

**Issue by priteshsomani** [Microsoft/AL#570] opened 2017-08-31 09:52 UTC
Hi All,

I am getting the below error when i tried to filter Option data type filed in CalcFormula.

The multi-part identifier "No_ of Children$Employee Relative_e1.Relative Type" could not be bound.

Below is my code
      FieldClass=FlowField;
      CalcFormula=Count("Employee Relative" WHERE ("Relative Type"=const(Child),
                                                   "Employee No."=FIELD("No.")));

**Comment by esbenk** [comment] 2017-08-31 12:01
When are you getting the error? Compile-time, Deployment-time or Runtime?

**Comment by priteshsomani** [comment] 2017-08-31 12:13
Getting this error on Runtime

**Comment by priteshsomani** [comment] 2017-09-05 11:04
Getting  the error when I used the option field of Tableextension in Calcformula.

If i use STD table option field in Calcformula i am not getting any error.

**Comment by cmrudolph-msft** [comment] 2017-09-26 15:45
I have been unable to reproduce this issue. My extension project is attached here:

[GH570.zip](https://github.com/Microsoft/AL/files/1333784/GH570.zip)

1. I extended **Employee Relative** to have a **Relative Type** field of type Option.
2. I added a flow field to **Employee** to count children using your formula
3. Everything is aggregated correctly when I use the new flow field in a page extension

Can you let me know what differs between our scenarios?

**Comment by priteshsomani** [comment] 2017-09-26 17:34
HI Chris,

Thanks for the update.

As my old D365 Cloud server is expired\Deleted and now when i am login in Azue Portal and click on create new server and could not found the Dynamics NAV 2017 Developer preview server.



Could you please help me how to create new server so i can upload the AL code and send you the exactly where i am getting the error.

Thanks,
Pritesh

**Comment by cmrudolph-msft** [comment] 2017-09-26 17:39
Does the link on the homepage of this repository work for you? It takes me to the right place in the Azure portal:

https://aka.ms/navdeveloperpreview

**Comment by priteshsomani** [comment] 2017-09-26 18:21
Hi Chirs,

This link create only VM machine only, it is does not have installed NAV 2017 setup. As before when i created developer preview it should be installed NAV 2017 with development client.

Regards,
Pritesh

**Comment by cmrudolph-msft** [comment] 2017-09-26 18:25
The preview has changed a bit. See the information here:

https://blogs.msdn.microsoft.com/nav/2017/09/07/nav-development-preview-september-update/

**Comment by cmrudolph-msft** [comment] 2017-09-26 18:46
Also, so you are aware, I just set up a September dev preview and reproduced the issue there. The environment where it worked initially is running the latest internal code. It is very likely this has been fixed already, but I will dig around a bit more to try to confirm this.

**Comment by cmrudolph-msft** [comment] 2017-09-26 19:13
I believe we are dealing with the same underlying issue as #501. This explains why the scenario works for me on latest code and will be widely available in the October preview.

**Comment by priteshsomani** [comment] 2017-09-27 05:49
Hi Chirs,

Still i am getting error which you send me for example,  i am doing the below setup if i am doing something wrong please let me know.

1) Deployed you code 


2) Published successfully 



3) Run Employee Table directly on Development client and getting bellow error.



4) Once i run  Employee list page could not found the new extension field.

pageextension 50100 ExtendEmployeeList extends "Employee List"
{
layout
{
addafter("Last Name")
{
field("No. of Children";"No. of Children") { }
}
}
}






Please let me know if you need my RDP access.

Thanks,
Pritesh

**Comment by cmrudolph-msft** [comment] 2017-09-27 12:50
That is expected. Please read my previous responses where I indicate that this is a problem on the current release (September preview) and will be fixed in the next update.

**Comment by priteshsomani** [comment] 2017-09-27 13:09
Hi Chirs,

Sorry i could  not see your previous email, waiting for the new update.

Thank for you time..

Regards,
Pritesh

**Closed** 2017-10-12 09:55 UTC
Labels: bug, delivered
