### ISSUE TITLE
Please relax AppSourceCop rule AS0011 'A prefix is required'

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#4276] opened 2018-11-28 12:13 UTC
The rule AS0011 'A prefix is required' forces to use a prefix everywhere, including page controls and table fields in new objects. I would like to have this relaxed a bit and only require where you really would expect a possible conflict:

- All object names
- All new fields / keys in tableextensions
- All new controls in pageextensions

I don't see any possible conflicts inside new tables or new pages. Or do I miss something here?

**Comment by StanislawStempin** [comment] 2018-11-28 15:49
This is fixed in AL Language build 2.1.66478.

**Closed** 2018-11-28 15:49 UTC
Labels: bug, ships-in-future-update

**Comment by jwikman** [comment] 2019-01-17 16:42
Hi @StanislawStempin ,

Was this fix done in the BC14 branch only?
I've tried 2.1.69331 (the latest on VSCode Marketplace) and 2.1.79379 (BC13 CU3) - Both gives an overwhelming amount of "false" errors...

And is the fix implemented for all affixes settings in AppSourceCop.json? (mandatoryPrefix/mandatorySuffix/mandatoryAffixes)

**Comment by IvoMol** [comment] 2019-01-17 17:17
I tested this on AL 2.1.79379 (BC13 CU3 on premisses) too and can confirm: this is not implemented.
Please implement this to rule AS0012 in the same way.

**Comment by jwikman** [comment] 2019-01-17 19:30
Thanks @IvoMol, you just confirmed what I was guessing.

> Please implement this to rule AS0012 in the same way.

 It seems as they've extended AS0011 to include both Suffixes (AS0012) and Prefixes (AS0011) and added a mandatoryAffixes setting (which is also AS0011).

The Error message for AS0011 in BC14 says "The identifier 'xxxxxx' must have at least one of the mandatory **affixes** 'yyyy'".

So I think we now already answered my questions to @StanislawStempin... :-)

**Comment by rps6** [comment] 2019-04-30 08:48
seems to be an issue again. I have installt AL 3.0.121490 and do get this error if moving a field
