### ISSUE TITLE
Problem with Rule AL0126

### ISSUE THREAD

**Issue by StefanMaron** [microsoft/AL#6376] opened 2020-12-16 06:05 UTC
**Describe the bug**
The Code Cop rule "AL0126" reports an error, but my app is still able to compile.

**To Reproduce**
I added an overload for the procedure "AddNewEntry" on the table "Name/Value Buffer" in extension A.
In extension B, which depends on A, I call this procedure.

``` 
tableextension 50000 "A Name/Value Buffer" extends "Name/Value Buffer"
{
    var
        TemporaryErr: Label 'The record must be temporary.';

    procedure AddNewEntry(NewID: Integer; NewName: Text[250]; NewValue: Text)
    begin
        if not IsTemporary then
            Error(TemporaryErr);

        Clear(Rec);

        ID := NewID;
        Name := NewName;
        SetValueWithoutModifying(NewValue);

        Insert(true);
    end;
}

codeunit 50000 "B CallBuffer"
{
  procedure CallProcedure()
      var
      NameValueBuffer: Record "Name/Value Buffer" temporary;
      begin 
          NameValueBuffer.AddNewEntry(1,'Name','Value');
      end;
}

 ```

**Expected behavior**
The code cop should not only scan the base app but also dependent app for function overloads

**Screenshots**
![image](https://user-images.githubusercontent.com/24838311/102310917-3699d080-3f6c-11eb-806f-eaf9db2f349d.png)

**5. Versions:**
 - AL Language: 6.1.381323
 - Business Central: onprem/17.1.18256.18792/de

**Comment by atoader** [comment] 2021-05-03 12:54
Hi! Is this still a problem on the latest release?

**Comment by StefanMaron** [comment] 2021-05-03 14:14
Yes, still does not work as expected with the latest AL version v7.1.453917

**Comment by qutreson** [comment] 2023-11-28 13:25
@StefanMaron - Thank you for raising this issue. I could not reproduce it anymore on the latest AL extension. The overload is now correctly resolved in extension B and it finds the one specified in the table extension in extension A

![image](https://github.com/microsoft/AL/assets/31541422/8a63d4de-9beb-43df-8c0c-0bbea3bae1f1)

I am then closing this issue. If you still can reproduce it, please create a new issue with all the repro steps and reference this one.

**Closed by qutreson** 2023-11-28 13:25 UTC
Labels: bug
