### ISSUE TITLE
Request for regular expression handling .net classes

### ISSUE THREAD

**Issue by rrudalski** [Microsoft/AL#757] opened 2017-10-12 06:31 UTC
Hi, 
in few of our modifications we relay on .net regular expressions classes. We wanted to move them to V2 extensions but currently there is no available System.Text.RegularExpressions.Regex nor System.Text.RegularExpressions.Match. Is it possible to see it (and other regex handling classes) in future updates for VS Code AL ??

I know we can setup a service that hosts *.dll with necessary functions but calling it so often woulnd't be optimal solusion.

**Comment by Gallimathias** [comment] 2017-10-12 06:44
Duplicate of #266 and #636

**Closed** 2017-10-12 10:04 UTC
Labels: duplicate
