### ISSUE TITLE
The property RDLCLayout disables breadcrumbs and outline

### ISSUE THREAD

**Issue by achim-t** [microsoft/AL#7131] opened 2022-08-09 07:27 UTC
Please include the following with each issue:

**1. Describe the bug**
Including the property RDLCLayout (or WordLayout) disables breadcrumbs and outline.

**2. To Reproduce**

Create a report with the RDLCLayout property.

``` AL
report 50100 MyReport
{
    UsageCategory = ReportsAndAnalysis;
    ApplicationArea = All;

    RDLCLayout = 'somelayout.rdlc';

    dataset
    {
        dataitem(DataItemName; Integer)
        {
            column(Column1; Number) { }
            column(Column2; Number) { }
        }
    }

}
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
Breadcrumbs and outline should be available as they are if you don't use RDLCLayout: 

![image](https://user-images.githubusercontent.com/11352910/183589282-32102cd8-c608-4e8b-907f-3c2ad2344974.png)

**4. Actual behavior**
Breadcrumbs and outline are not available:

![image](https://user-images.githubusercontent.com/11352910/183589420-00f25cac-095f-41a2-8d84-161227108363.png)

**5. Versions:**

- AL Language: v9.4.663067
- Visual Studio Code: 1.70.0
- Business Central:
- List of Visual Studio Code extensions that you have installed: none

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by dnpb** [comment] 2022-08-09 07:39
seems a dupe of https://github.com/microsoft/AL/issues/7073

**Comment by thloke** [comment] 2022-08-09 08:37
Closing as duplicate.

**Closed** 2022-08-09 08:37 UTC
