### ISSUE TITLE
Txt2AL fails to convert table extension

### ISSUE THREAD

**Issue by ernestasju** [Microsoft/AL#2823] opened 2018-07-09 06:45 UTC
I am using Txt2AL from microsoft/bcsandbox build 12.2.22932.23097.

Delta file:
```
OBJECT Modification Item(Table 27)
{
  OBJECT-PROPERTIES
  {
    Date=20180615D;
    Time=120000T;
    Modified=true;
    Version List=NAVW112.10;
  }
  PROPERTIES
  {
    Target=Item(Table 27);
  }
  CHANGES
  {
    { Insertion         ;InsertAfter=SetLastDateTimeFilter(PROCEDURE 29);
                         ChangedElements=PROCEDURECollection
                         {
                           PROCEDURE UpdateVariants@60000(ChangedFieldNo@60001 : Integer);
                           VAR
                             cfmUpdate@60002 : TextConst 'ENU=Do you want to update all the Item Variants?';
                           BEGIN
                           END;

                         }
                          }
  }
  CODE
  {

    BEGIN
    END.
  }
}


```

Txt2AL output:
```
PS C:\Users\ernjus\Desktop\test> & 'C:\ProgramData\NavContainerHelper\Extensions\toc\Program Files\122\RoleTailored Client\Txt2Al.exe' --source=C:\Users\ernjus\Desktop\test\deltas --target=C:\Users\ernjus\Desktop\test\alfiles

----ERROR----
Error converting file:C:\Users\ernjus\Desktop\toc\alfiles\extensions\updated\TAB27.DELTA
Element Change does not support property Name
Total Time: 0:00:00,3270035
Errors: 1
```

After removing text constant translation, delta is converted without errors.

Delta file:
```
OBJECT Modification Item(Table 27)
{
  OBJECT-PROPERTIES
  {
    Date=20180615D;
    Time=120000T;
    Modified=true;
    Version List=NAVW112.10;
  }
  PROPERTIES
  {
    Target=Item(Table 27);
  }
  CHANGES
  {
    { Insertion         ;InsertAfter=SetLastDateTimeFilter(PROCEDURE 29);
                         ChangedElements=PROCEDURECollection
                         {
                           PROCEDURE UpdateVariants@60000(ChangedFieldNo@60001 : Integer);
                           VAR
                             cfmUpdate@60002 : TextConst;
                           BEGIN
                           END;

                         }
                          }
  }
  CODE
  {

    BEGIN
    END.
  }
}
```

Txt2AL output:
```
Overwriting: C:\Users\ernjus\Desktop\test\alfiles\TAB27.al

Total Time: 0:00:00,2479661
Errors: 0
```

This is not a high priority for me.

**Comment by qutreson** [comment] 2018-07-09 07:55
Duplicate of #2714

**Closed** 2018-07-09 08:03 UTC
Labels: duplicate
