### ISSUE TITLE
Actionref is not hidden, even if property 'visible' is set on false

### ISSUE THREAD

**Issue by Gwrsky** [microsoft/AL#7527] opened 2023-07-13 10:43 UTC
Hi, 
I wanted to hide standard PromotedActions on page ItemCard, and replace them with my other actions.
Unfortunately, it is not possible, or at least i don't know how to do it.
I've written following code:
![image](https://github.com/microsoft/ALAppExtensions/assets/72869582/ef69348c-36e0-4f10-8251-b71885c8588c)
Which should hide promoted actionrefs.
I've also set propety 'visible' to false on the actions itself.
![image](https://github.com/microsoft/ALAppExtensions/assets/72869582/913a3f6f-e60a-432d-85e3-3ce07f119f05)
Yet there's no result, actions are still visible on the page:
![image](https://github.com/microsoft/ALAppExtensions/assets/72869582/1e6dbbd3-7719-4aea-acf9-8d4ea5c98be8)
I Guess it's some kind of bug with property  visible = false.
Could you please assist?

**Comment by qutreson** [comment] 2024-02-28 10:31
@Gwrsky - We tried to reproducing he issue that you mentioned on the latest preview of Business Central, and it works as expected.

This is how the action bar looks like:

![image](https://github.com/microsoft/AL/assets/31541422/58178ce3-8614-4ff6-a180-95f805df657f)


This is the AL Code used:

```al
pageextension 50100 MyExtension extends "Item Card"
{
    actions
    {
        modify(SalesPriceLists_Promoted)
        {
            Visible = false;
        }
        modify(PurchPriceLists_Promoted)
        {
            Visible = false;
        }
        modify(PurchPriceLists)
        {
            Visible = false;
            Enabled = false;
        }
        modify("Set Special Prices_Promoted")
        {
            Visible = false;
        }
        modify(PricesDiscountsOverview_Promoted)
        {
            Visible = false;
        }
        modify("Set Special Discounts_Promoted")
        {
            Visible = false;
        }
        modify(PurchPricesDiscountsOverview_Promoted)
        {
            Visible = false;
        }
        modify(SalesPriceListsDiscounts_Promoted)
        {
            Visible = false;
        }
        modify(PurchPriceListsDiscounts_Promoted)
        {
            Visible = false;
        }
        modify(Action86_Promoted)
        {
            Visible = false;
        }
        modify(Action85_Promoted)
        {
            Visible = false;
        }
        modify(Action85)
        {
            Visible = false;
            Enabled = false;
        }
        addlast(Category_Category6)
        {
            actionref(MyAction_Promoted; MyAction) { }
        }

        addlast(Creation)
        {
            action(MyAction)
            {
                ApplicationArea = All;
                trigger OnAction()
                begin
                    Message('Test');
                end;
            }
        }
    }
}
```

Are you still facing this issue? 
Can you try this out on the latest preview?
Do you have other extensions or in-client customizations installed that are contributing to this page?

**Comment by BedrettinQdKc** [comment] 2024-03-18 20:53
I have the same issue. I also tried setting the main Actions visibility to false.
`actions
    {
        modify(SalesPriceLists)
        {
            Visible = false;
        }
        modify(SalesPriceLists_Promoted)
        {
            Visible = false;
        }
}`
The Action is still visible in the Item Card page.

**Comment by qutreson** [comment] 2024-03-21 07:31
Closing this issue as we couldn't reproduce it. If you are still experiencing it without having other extensions or in-client customizations on your environment, please log a new issue with additional information.

**Closed by qutreson** 2024-03-21 07:31 UTC
Labels: input-needed
