### ISSUE TITLE
Compilation Issue 

### ISSUE THREAD

**Issue by A-R-Shaji** [Microsoft/AL#4330] opened 2018-12-07 12:15 UTC
BC Build - 13.0.26474
AL Language Build - 2.1.70607.

```
[Error - 7:09:13 AM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/gotodefinition' failed with error: 'Position: 203, FullSpan: (0..0)
Parameter name: position'
Details:
System.ArgumentOutOfRangeException: Position: 203, FullSpan: (0..0)
Parameter name: position
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position) in C:\a\824\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 896
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.DocumentExtensions.<GetTokenAtPositionAsync>d__18.MoveNext() in C:\a\824\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Shared\Extensions\DocumentExtensions.cs:line 332
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.DocumentExtensions.<GetSymbolAtPositionAsync>d__9.MoveNext() in C:\a\824\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Shared\Extensions\DocumentExtensions.cs:line 182
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.DocumentExtensions.<GetSymbolAtPositionAsync>d__8.MoveNext() in C:\a\824\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Shared\Extensions\DocumentExtensions.cs:line 176
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.AlDefinitionRequestHandler.<ProcessRequestAsync>d__4.MoveNext() in C:\a\824\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\AlDefinitionRequestHandler.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`1.<HandleAsync>d__5.MoveNext() in C:\a\824\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\NavServerRequestHandler.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__10.MoveNext() in C:\a\824\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\a\824\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 58
```

**Comment by thpeder** [comment] 2018-12-07 13:58
Hi @A-R-Shaji,
Could you please provide some steps to reproduce the issue, and even better if you would include a zip file with the needed AL files to provoke the issue.

**Comment by A-R-Shaji** [comment] 2018-12-07 14:11
Hi @thpeder,
We are getting at the time of compilation/Creating the app. We have around 800 files in our App.

**Comment by thpeder** [comment] 2018-12-07 14:56
That sounds odd since the stack trace is coming from GoToDefinition, so maybe you are hovering the mouse over something.

**Comment by atoader** [comment] 2018-12-18 03:51
@A-R-Shaji do you have any more information that you could provide? Thanks!

**Comment by thpeder** [comment] 2018-12-18 10:52
It looks like the language server is out of sync with VSCode, but without a way to reproduce makes it next to impossible for us to find and fix the bug.

**Comment by JohanStenberg100** [comment] 2019-01-24 08:21
@A-R-Shaji, I'm going to close this issue now, please reply with repro steps if you find any in #4508

**Closed by JohanStenberg100** 2019-01-24 08:21 UTC
Labels: input-needed
