### ISSUE TITLE
PromotedActionCategories / PromotedActionCategoriesML does not work as expected.

### ISSUE THREAD

**Issue by calcifieddeveloper** [microsoft/AL#5373] opened 2019-10-21 04:48 UTC
Hi,

**Describe the bug**

PromotedActionCategories / PromotedActionCategoriesML does not work as expected.

**To Reproduce**

Created a Page Extension in a container and a online Sandbox.  I have added a promoted Category but it does show with either 
PromotedActionCategories = 'New,Process,Report,Bank,Prepare,Approve,Page,Post/Print,Line,Account,Cheque,NewFunction;

Or

PromotedActionCategoriesML = ENA = 'New,Process,Report,Bank,Prepare,Approve,Page,Post/Print,Line,Account,Cheque,NewFunction',
                                 ENZ = 'New,Process,Report,Bank,Prepare,Approve,Page,Post/Print,Line,Account,Cheque,NewFunction',
                                 ENU = 'New,Process,Report,Bank,Prepare,Approve,Page,Post/Print,Line,Account,Cheque,NewFunction';
 
                action(NewFunctionAction)
                {
                    ApplicationArea = All;
                    CaptionML = ENU = 'NewFunctionItem',
                            ENA = 'NewFunctionItem',
                            ENZ = 'NewFunctionItem';
                    Image = ElectronicRegister;
                    Promoted = true;
                    PromotedCategory = Category12;
                    PromotedIsBig = true;
                }

**Expected behavior**
I expect the new caption to be seen, but it is not.

**5. Versions:**
Version: Platform 15.0.36985.0 + Application 15.0.36626.37063
AL Language 4.0.184307

**Comment by qutreson** [comment] 2019-10-21 07:30
Hi @calcifieddeveloper, can you elaborate a bit more about what you are getting in the webclient (maybe adding a screenshot?) and what you would expect to see?

**Comment by calcifieddeveloper** [comment] 2019-10-22 06:48
Hi,
Sure.

![image](https://user-images.githubusercontent.com/48376898/67263478-d8459f00-f4da-11e9-9046-34c95550e306.png)

I would expect if I have new promoted actions defined as Category12 that the caption should show as "NewFunction"

**Comment by calcifieddeveloper** [comment] 2019-10-23 08:30
Anyone have any ideas ?

**Comment by AndreyKorepanov** [comment] 2019-10-25 14:41
Hi! We could not reproduce. The following code produces the expected result. 

```

pageextension 50100 CustomerListExt extends "Customer List"
{
    PromotedActionCategoriesML = ENA = 'New,Process,Report,Bank,Prepare,Approve,Page,Post/Print,Line,Account,Cheque,NewFunctionAction',
                                  ENZ = 'New,Process,Report,Bank,Prepare,Approve,Page,Post/Print,Line,Account,Cheque,NewFunctionAction',
                                  ENU = 'New,Process,Report,Bank,Prepare,Approve,Page,Post/Print,Line,Account,Cheque,NewFunctionAction';

    // PromotedActionCategories = 'New,Process,Report,Bank,Prepare,Approve,Page,Post/Print,Line,Account,Cheque,NewFunctionAction';

    actions
    {
        addlast("&Customer")
        {
            action(NewFunctionAction)
            {
                ApplicationArea = All;
                CaptionML = ENU = 'NewFunctionItemENU',
                        ENA = 'NewFunctionItemENA',
                        ENZ = 'NewFunctionItemENZ';

                Image = ElectronicRegister;
                Promoted = true;
                PromotedCategory = Category12;
                PromotedIsBig = true;

                trigger OnAction()
                begin

                end;
            }
        }
    }
}
```
![image](https://user-images.githubusercontent.com/43748195/67580225-4510a180-f746-11e9-994b-9a2ea478d98e.png)

**Comment by calcifieddeveloper** [comment] 2019-10-29 08:24
Hi,
Please find attached a project that can replicate the issue
[ALProject1.zip](https://github.com/microsoft/AL/files/3782363/ALProject1.zip)

**Comment by calcifieddeveloper** [comment] 2019-10-30 08:54
Hi Andrey,
Any update ?

**Comment by AndreyKorepanov** [comment] 2019-10-30 10:04
Hi @calcifieddeveloper, not yet. We are working on it and I'll let you know when we have anything new as soon as possible.

**Comment by calcifieddeveloper** [comment] 2019-10-30 12:40
Thanks @AndreyKorepanov

**Comment by AndreyKorepanov** [comment] 2019-10-31 12:52
Hi @calcifieddeveloper I've tested your project and it works as expected on my side, please find the screenshot below (the only thing I changed is the CreateFile action - I substituted it with the CreateApprovalWorkflow, to be able to compile it). I can not see any problems here. The only my guess regarding the "Category 12" title displaying (see the first your screenshot) is could it be that you are using different Regional & Language settings, not listed in the PromotedActionCategoriesML?   
![image](https://user-images.githubusercontent.com/43748195/67947643-5e04d100-fbe4-11e9-9a71-9e5a72a1a43f.png)

**Comment by calcifieddeveloper** [comment] 2019-11-06 07:37
Hi,
Sorry, I still don't get the expected result with this code.
![Category12](https://user-images.githubusercontent.com/48376898/68277971-5a24f300-00ab-11ea-8c03-fe3459fd321a.PNG)
[ALProject1.zip](https://github.com/microsoft/AL/files/3813073/ALProject1.zip)

**Comment by atoader** [comment] 2019-11-06 08:22
@calcifieddeveloper what localization of the application are you using? Is there a specific docker tag that you are using or is it a local installation?

**Comment by calcifieddeveloper** [comment] 2019-11-06 22:54
Yes indeed, I am using this one : mcr.microsoft.com/businesscentral/sandbox:au

**Comment by monchangg** [comment] 2019-11-08 06:18
@calcifieddeveloper @atoader  I have same issue on docker image: `mcr.microsoft.com/businesscentral/sandbox:us-ltsc2016`
But it works good on docker image `mcr.microsoft.com/businesscentral/sandbox:ltsc2016`

**Comment by calcifieddeveloper** [comment] 2019-11-11 00:26
Thanks @monchangg.

@atoader any ideas ?

**Comment by calcifieddeveloper** [comment] 2019-11-11 04:25
Tested again on this image bcinsider.azurecr.io/bcsandbox-master:au-ltsc2019 with the same code and I get the same result.

**Comment by atoader** [comment] 2019-11-28 19:43
We have identified the root cause a week ago. We have a fix in the pipeline and we plan to ship it for 15.2

**Comment by monchangg** [comment] 2019-12-03 06:11
@atoader Can I know when the 15.2 will be released?

**Comment by GTimmers** [comment] 2020-02-26 08:20
Any new regarding this bug?

**Comment by Drakonian** [comment] 2020-04-06 03:02
Issue still present...
Any updates?

**Comment by YSofiya** [comment] 2020-04-28 15:25
> 
> 
> We have identified the root cause a week ago. We have a fix in the pipeline and we plan to ship it for 15.2

Hello! Is this problem was fixed? I still have the same problem in 15.4 version. 
Thank you.

**Comment by atoader** [comment] 2020-05-05 19:37
@YSofiya can you provide a repro for this? We believe the original issue has been fixed, but there might be a different aspect that was not covered. Can you also test it on 16.0?

**Comment by YSofiya** [comment] 2020-05-06 12:44
> 
> 
> @YSofiya can you provide a repro for this? We believe the original issue has been fixed, but there might be a different aspect that was not covered. Can you also test it on 16.0?

Hello @atoader ! The problem appears in the next case. I put category names as PromotedActionCategories. (not ML, as I work on cloud). It works well for the default language (EN-US, in my case). If I don't have translation file for another language (for example, EN-CA), then if user has EN-CA as language, he would see Category9.. as name. It would be better to see the name from  PromotedActionCategories even if we don't have translation for the user's language. Thank you

**Comment by atoader** [comment] 2020-05-06 15:20
Can you provide a small sample project to reproduce this? As you can imagine, we have quite a number of issues to address, and it really helps a lot to have the exact repro.

**Comment by pri-kise** [comment] 2020-05-11 14:03
I have the same problem while working with PromotedActionCategories and the following version:
Version: DE Business Central 15.4 (Platform 15.0.40939.41271 + Application 15.4.41345.0)
`PromotedActionCategories = 'New,Process,Report,,,,,Status,,,,,Function,,,,,Navigate';`
![image](https://user-images.githubusercontent.com/56249171/81570285-aa557880-93a0-11ea-8e90-3dfbecca8b6c.png)

**Comment by atoader** [comment] 2020-05-21 15:48
@pri-kise can you provide a sample to reproduce this?

**Comment by pri-kise** [comment] 2020-05-22 06:07
@atoader 
You can check the behavior here: 
https://github.com/pri-kise/ALPromotedCategories

**Comment by neverbeam** [comment] 2020-06-30 10:09
@atoader Is there any update regarding this bug? We are currently facing the same issue with NL-nl translations and PromotedActionCategories (NL Business Central 16.1).

**Comment by radovandokic** [comment] 2020-08-18 08:39
Still the same in following version: Platform 16.0.14073.14279 + Application 16.3.14085.14363.
Works well for the default language (EN-US) but not for EN-CA.

**Comment by pri-kise** [comment] 2020-10-09 12:27
@atoader Any progress on this issue?
The problem still occurs for Version: DE Business Central 16.4 (Plattform 16.0.14648.15420 + Anwendung 16.4.15445.0)

**Comment by VPaas2** [comment] 2020-11-19 09:11
The Issue appears to be fixed in NL Business Central 17.0 

I have made a small investigation on version NL Business Central 16.5 and 17.0 to see if the issue persists. My test  added a couple of  actions and promotedActionCategories as a page extension to the purchase invoice page. A translation for the PromotedActionCategories was added in the Dutch XLF file. The issue remained on 16.5 but did not appear in 17.0

**Comment by pri-kise** [comment] 2020-11-20 07:27
I have to check for BC16, but it is still there for Plattform 14.0.44656.0 + Anwendung 44663 (DE Business Central 14.17) and I would expect that this issue will be solved for older versions too, since this issue is very old

**Comment by thpeder** [comment] 2020-12-08 14:01
Hi @pri-kise,
Thanks for the project pri-kise/ALPromotedCategories it doesn't work as you expect it.
```AL
PromotedActionCategories = 'New,Process,Report,,,,,Status,,,,,Function,,,,,Navigate';
```
behaves the same as
```AL
PromotedActionCategories = 'New,Process,Report,Status,Function,Navigate';
```
because empty spaces are removed and we are not going to prioritize work to change that at the moment.
What you need to do is to fill in the empty spaces with names. For instance you could just use names such as Category4, Category5 etc.


If there are other issues I have missed, please provide a sample project. That makes it much easier for us to investigate.

**Comment by pri-kise** [comment] 2020-12-08 14:05
Okay.
Now I know how i can solve this problem in my apps, eventhough I would have never expected that this would act this way.
Is this behaviour anywhere documend, since I couldn't find any information about this.

**Comment by NKarolak** [comment] 2020-12-08 14:27
@pri-kise 

> Is this behaviour anywhere documend, since I couldn't find any information about this.

Not yet, but see above :-) (between this post, and your last post).

**Comment by bussik** [comment] 2020-12-09 07:40
The same problem is with Belgium Business Central

**Comment by thpeder** [comment] 2020-12-09 08:44
I have checked back in the last 5 Major releases and all of them have this behavior.

**Comment by atoader** [comment] 2020-12-17 07:22
The documentation will be refreshed with a note on this behavior.

**Comment by atoader** [comment] 2020-12-17 07:22
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-promotedactioncategories-property

**Closed by atoader** 2020-12-17 07:22 UTC
Labels: bug, in-progress

**Comment by DanKinsella** [comment] 2021-01-07 15:16
This is still an issue:

pageextension 60000 "Sales Quote XP" extends "Sales Quote"
{
    PromotedActionCategories = 'New,Process,Report,Quote,View,Approve,Request Approval,History,Print/Send,Release,Navigate,Basket';

...

![image](https://user-images.githubusercontent.com/28391752/103908952-02dd4100-50fb-11eb-8c36-2a68f950cce9.png)

Version: GB Business Central 17.2 (Platform 17.0.19353.20441 + Application 17.2.19367.20615)
Azure AD tenant: (blank), Environment: Sandbox (Sandbox)

**Comment by dtkb** [comment] 2021-01-07 15:18
What is the problem? Seeing `Category 13`? Well, you only defined 12 captions, so of course you see the default `Category 13` if there's nothing more specific for BC to use.

**Comment by DanKinsella** [comment] 2021-01-07 15:32
Whoops, I'd been playing about with the code to try and get it to work.

![image](https://user-images.githubusercontent.com/28391752/103911106-87c95a00-50fd-11eb-9702-2d9347a90bb8.png)

Here's another showing the correct group

**Comment by DanKinsella** [comment] 2021-01-07 15:54
[CustomerListExtXP.PageExt.zip](https://github.com/microsoft/AL/files/5782583/CustomerListExtXP.PageExt.zip)

Just replicated in isolation, see attached. The caption is not being displayed.

Expecting caption "My Group", but getting "Category 10":

![image](https://user-images.githubusercontent.com/28391752/103913554-8fd6c900-5100-11eb-80ef-582751779b4a.png)

**Comment by DanKinsella** [comment] 2021-01-08 09:47
An update: it works fine with PromotedActionCategoriesML but not PromotedActionCategories:

    //PromotedActionCategories = 'New,Process,Report,Approve,New Document,Request Approval,Customer,Navigate,Prices & Discounts,My Group';
    PromotedActionCategoriesML = ENU = 'New,Process,Report,Approve,New Document,Request Approval,Customer,Navigate,Prices & Discounts,My Group',
    ENG = 'New,Process,Report,Approve,New Document,Request Approval,Customer,Navigate,Prices & Discounts,My Group';

**Comment by atoader** [comment] 2021-01-20 18:52
Please open a new issue if this does not work as described in the documentation.

**Comment by dtkb** [comment] 2021-03-25 14:22
The issue linked above seems like the new one for the translation/caption problem.

I just saw this again, and the correct caption was shown when viewing in English (US) language, but it reverted to Category9 when changed to English (UK).

**Comment by cet0bs** [comment] 2022-01-11 09:59
Since Business Central 19 we have the issue again, that in the source language the caption for the Promoted Action Category works, but as soon as we use another Language it shows Category9.

**Comment by JBlancoDynavics** [comment] 2022-08-26 15:58
I am facing the same issue (Version: GB Business Central 20.2 (Platform 20.0.41086.45177 + Application 20.2.41144.43400))
Item Journal Page extended.

pageextension xxxxx "Item Journal Ext." extends "Item Journal"
{

    PromotedActionCategories = 'CAT_1,CAT_2,CAT_3,CAT_4,CAT_5,CAT_6,CAT_7,CAT_8';
}
Expected result (Older BC On-Prem):
![image](https://user-images.githubusercontent.com/100702057/186944780-a0b254b7-f647-4f37-85c3-d5d645c36116.png)


Current result (Version: GB Business Central 20.2 (Platform 20.0.41086.45177 + Application 20.2.41144.43400):
![image](https://user-images.githubusercontent.com/100702057/186944412-f188d623-0515-4553-932c-e014cd7438e7.png)
