### ISSUE TITLE
Got blank pages from reports

### ISSUE THREAD

**Issue by zhaohowie** [Microsoft/AL#3411] opened 2018-08-21 21:52 UTC
Hi,

I converted my reports from 2018 database to AL code. When I run it from web client, I got all blank pages.
I also created a simple report, just show Item no. and description, still showed a blank page. Looks like when the report run, didn't grab layout at all.

[TestReport.zip](https://github.com/Microsoft/AL/files/2308189/TestReport.zip)

**Comment by thpeder** [comment] 2018-08-22 07:54
Hi @zhaohowie,
If you are publishing to the online sandbox, then you need to set the application area on all controls.
The report works just fine for me, so if you are working with the online sandbox then remember to use the latest version of the VSCode extension in the VSCode marketplace.

**Comment by strophanthus** [comment] 2018-08-22 12:46
I am experiencing the same behavior in the fall update preview. In my case this is testing an app that is already live in AppSource in order to prepare for the fall release. The reports have worked fine up until now (platform 12.X). 

This is using: 
Microsoft_Application_13.0.23759.0.app
Microsoft_System_13.0.12928.0.app
al-0.17.30289.vsix

**Comment by strophanthus** [comment] 2018-08-22 14:14
More information: 

The reports do not show up in the report selection table initially

If I switch to custom and back to built-in (in report layout selection), then they do show up in the selection table but the reports are still blank

If I take the same layout from the project, import it as a custom one, then choose it in the custom layout option, then the preview/print shows up as expected

**Comment by skoizumi-pbc** [comment] 2018-08-28 09:45
It can be reproduced also on my docker environment. I created a very simple report and tested with W1 13.0 (24153), and resulted in a blank report. When I tested the same report with W1 12.3 (23828), it was shown up normally. Attached is a project what I used to test.
[RepTest.zip](https://github.com/Microsoft/AL/files/2327465/RepTest.zip)

**Comment by pmohanakrishna** [comment] 2018-09-04 12:02
same issue. all custom reports are showing blank screen. standard reports are working fine in fall release.

**Comment by dennisfrostlander** [comment] 2018-09-04 14:48
Looks like a duplicate of https://github.com/Microsoft/AL/issues/3534

**Closed** 2018-10-15 11:52 UTC
Labels: duplicate
