### ISSUE TITLE
An implicit conversion is being performed from a value of type 'Enum "Gen. Journal Document Type"' to a value of type 'Integer'. This conversion can lead to unexpected runtime issues. This warning will become an error in a future release.AL(AL0603)

### ISSUE THREAD

**Issue by sami3187** [microsoft/AL#5832] opened 2020-04-24 03:36 UTC
<img width="884" alt="bcv16" src="https://user-images.githubusercontent.com/64240684/80172223-04271600-861f-11ea-906b-bd7adb6fd856.PNG">

**Title**
An implicit conversion is being performed from a value of type 'Enum "Gen. Journal Document Type"' to a value of type 'Integer'. This conversion can lead to unexpected runtime issues. This warning will become an error in a future release.AL(AL0603)

**Description**
After downloading symbols" version 16.xx there were about 400 + similar error , how to resolve it ? manually replace by appending **.AsInteger()** at the end. or any other way to replace at one-go ? or any other option ? pls advise . thanks

**Reason for the rule**

**Bad code sample**

``` Example of bad code ```

**Good code sample**

``` Example of good code ```

**Remarks**

**Comment by sami3187** [comment] 2020-04-24 03:37
After downloading symbols" version 16.xx there were about 400 + similar error , how to resolve it ? manually replace by appending **.AsInteger()** at the end. or any other way to replace at one-go ? or any other option ? pls advise . thanks

**Comment by thpeder** [comment] 2020-04-24 04:44
Duplicate of #5693

**Closed by thpeder** 2020-04-24 04:44 UTC
Labels: static-code-analysis
