### ISSUE TITLE
usePublicURLFromServer property not taking serverInstance into account

### ISSUE THREAD

**Issue by mynhardt7** [microsoft/AL#7431] opened 2023-06-05 12:31 UTC
**1. Describe the bug**
When the usePublicURLFromServer property in the launch.json file is set to false, the serverInstance is not taken into account. This leads to the final URL being a combination of launch.json and server settings.

**2. To Reproduce**

_Server config_
Server instance = MyServerInstance
PublicWebBaseUrl on server = https://domain.com/MyServerInstance_SSO
WebserverInstance1 = MyServerInstance
WebserverInstance2 = MyServerInstance_SSO

_launch.json_
"server": "https://domain.com/",
"serverInstance": "MyServerInstance",
"authentication": "UserPassword",
"usePublicURLFromServer": false,

**3. Expected behavior**
Resulting URL should be
```
https://domain.com/MyServerInstance/
(from launch.json )[from launch.json]
```

**4. Actual behavior**
Resulting URL is
```
https://domain.com/MyServerInstance_SSO/
(from launch.json )[from server       ]
```

**5. Versions:**

- AL Language: v11.0.810452
- Visual Studio Code: 1.78.2
- Business Central: 22.1
- List of Visual Studio Code extensions that you have installed: AL Language

**Comment by BazookaMusic** [comment] 2023-06-13 09:02
Seems to be a bug with the way the `usePublicURLFromServer` setting is applied

**Comment by BazookaMusic** [comment] 2023-07-14 15:01
I cannot reproduce this on the latest version. It must have been fixed with the previous fix to the same property. Download the latest version where it will work fine.

**Closed by BazookaMusic** 2023-07-14 15:01 UTC
Labels: al-core-compiler, accepted
