### ISSUE TITLE
Incorrect GetUrl in D365 Business Central app

### ISSUE THREAD

**Issue by kvaldik** [Microsoft/AL#3310] opened 2018-08-16 14:02 UTC
When using the GetUrl procedure inside the Business Central app, an incorrect protocol is returned. The protocol returned is `ms-dynamicsnav` but it should be `ms-businesscentral`.

I've reported this before in issue [#1719](https://github.com/Microsoft/AL/issues/1719) and it was fixed at some point. Now it is seams to be broken again.

**Comment by BgedankenSysSol** [comment] 2018-08-29 15:10
Incorrect GetUrl in D365 #1719 - This thread needs to be re-opened as the issue is still happening as detected on #3310. @thpeder Would you have a work around suggestion on this issue? What's the ETA?

**Comment by StanislawStempin** [comment] 2018-10-15 13:17
This was an issue in the service configuration. I should have been fixed by now.

**Closed by StanislawStempin** 2018-10-15 13:17 UTC
Labels: cross-team-investigate
