### ISSUE TITLE
Could not download reference symbols.

### ISSUE THREAD

**Issue by ravenboilinux** [microsoft/AL#6585] opened 2021-04-20 23:46 UTC
Please include the following with each issue:

**1. Describe the bug**
Whenever I create a new AL Project in vscode, i get this error:
[2021-04-20 19:39:46.46] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.
3. The dependencies are correctly specified in the app.json file.
Microsoft (R) AL Compiler version 7.1.6.48380
Copyright (C) Microsoft Corporation. All rights reserved

**2. To Reproduce**
1) Press Alt+A, Alt+L to trigger the AL Go! command, choose a path to a new empty folder and which version to run. Then choose Microsoft cloud sandbox as the server.
2) Enter the credentials that you provided for the sign-up.
3) watch the output window throw this error.

After you complete steps above:
1) Press Ctrl+Shift+B
2) watch the output window throw this error.

**3. Expected behavior**
Symbols should be download correctly from a fresh project.

**4. Actual behavior**

**5. Versions:**

- AL Language: 7.1.6.48380
- Visual Studio Code: 1.55.2
- Business Central: 18.0.23013.23532
- List of Visual Studio Code extensions that you have installed: None

**Comment by ravenboilinux** [comment] 2021-04-22 03:03
Here is my launch.json and app.json in the zip file
[zip.zip](https://github.com/microsoft/AL/files/6355200/zip.zip)

**Comment by kalberes** [comment] 2021-04-24 16:05
Is your environment called "sandbox" or "Sandbox" ?

**Comment by ravenboilinux** [comment] 2021-04-26 12:50
> Is your environment called "sandbox" or "Sandbox" ? Try with environmentname: Sandbox

I have tried it with "environmentName": "Sandbox", and I get the same results:
[2021-04-26 08:49:40.63] Using reference symbols cache path: c:\Games\ALProject2\./.alpackages
[2021-04-26 08:49:40.65] Authenticating...
[2021-04-26 08:49:41.51] Authenticated.
[2021-04-26 08:49:41.51] Authenticated as user 'michael.joye@darknightstudio.com'. Please note that these credentials are cached. Clear the credentials cache to authenticate as another user.
[2021-04-26 08:49:41.51] Targeting Dynamics 365 Business Central.
[2021-04-26 08:49:41.52] Sending request to https://api.businesscentral.dynamics.com/v2.0/Sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=18.0.0.0
[2021-04-26 08:49:41.52] Sending request to https://api.businesscentral.dynamics.com/v2.0/Sandbox/dev/packages?publisher=Microsoft&appName=System&versionText=1.0.0.0
[2021-04-26 08:49:42.37] The request for path /v2.0/Sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=18.0.0.0 failed with code NotFound. Reason: Not Found
[2021-04-26 08:49:42.49] The request for path /v2.0/Sandbox/dev/packages?publisher=Microsoft&appName=System&versionText=1.0.0.0 failed with code NotFound. Reason: Not Found
[2021-04-26 08:49:42.49] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.
3. The dependencies are correctly specified in the app.json file.
Microsoft (R) AL Compiler version 7.1.6.48380
Copyright (C) Microsoft Corporation. All rights reserved

Compilation started for project 'ALProject2' containing '1' files at '8:49:42.567'.

error AL1045: The package cache c:\Games\ALProject2\./.alpackages could not be found.

Compilation ended at '8:49:42.581'.

Error: The package could not be created.

**Comment by ravenboilinux** [comment] 2021-04-26 12:51
I also clear the credentials just in case that would cause an issue.

**Comment by ravenboilinux** [comment] 2021-05-03 23:11
Hello, is there any status on this ticket? Do i need to contact another support avenue for any support on this?

**Comment by atoader** [comment] 2021-05-06 08:09
If you require assistance within a short-time-frame, you should go through the support channels mentioned in the README of this repository. We only provide a best-effort approach to handling issues.

**Comment by atoader** [comment] 2021-05-06 08:09
We will look into this, but if this is a SaaS sandbox, you should reach out to customer support for a mitigation. What we are working on from the tooling side is improving the error message so that you know what the issue is.

**Comment by nbs33** [comment] 2021-06-07 21:52
hi @ravenboilinux were you able to find a solution for this? I am having a similar issue.

**Comment by ravenboilinux** [comment] 2021-06-07 22:05
Yes I was able to get help with MS Support for this issue

**Comment by nbs33** [comment] 2021-06-07 23:09
Thank you for the response. I've been running into dead ends on this one so
I will reach out for support. I haven't with AL or Microsoft products very
much. Can you where I can go for this specific support?

**Comment by ravenboilinux** [comment] 2021-06-08 00:59
This would be the business central support, my case was that I was trying to target a sandbox, which I need to create

**Comment by nbs33** [comment] 2021-06-08 01:12
Thanks again for the help. I will reach out to the BC support and
investigate the issue with the sandbox.

**Comment by atoader** [comment] 2021-06-22 13:46
Closing as the issue was redirected to support

**Closed by atoader** 2021-06-22 13:46 UTC
Labels: input-needed
