### ISSUE TITLE
InClient designer crashes with current docker image W1

### ISSUE THREAD

**Issue by megel** [microsoft/AL#5058] opened 2019-06-12 08:42 UTC
The InClient Designer crash every time:
![image](https://user-images.githubusercontent.com/15800069/59336191-5fe5fa80-8cfe-11e9-8f26-8f585b2efe0b.png)

Reproduce:
1) create new DockerContainer with image: `mcr.microsoft.com/businesscentral/sandbox:w1`
1) goto Item List
1) start InClient 
1) move a column in the list to a new position
1) the client crashes :(

Log from docker:
```log
TimeGenerated : 6/12/2019 10:36:34 AM
EntryType     : Error
Message       : Server instance: NAV
                Category: Extensions
                ClientSessionId: ddb53197-c1f8-4ff1-aa6c-4aa5f1c55e15
                ClientActivityId: a10a090c-85d6-45e3-a7f7-39aaccf157e8
                ServerSessionUniqueId: e25a7063-7e83-4904-8d2a-524845773146
                ServerActivityId: 7f04c74f-3956-4490-bd91-d71e8d0c3e01
                EventTime: 06/12/2019 08:36:34
                Message (NavDesignerCompilerException): RootException:
                NavDesignerCompilerException
                A package with publisher 'Microsoft', name 'Test', and a
                version compatible with '11.0.0.0' could not be loaded.
                ExceptionStackTrace:
                   at Microsoft.Dynamics.Nav.Runtime.Designer.NavDesignerCompil
                er.BuildDesignerPackage(IEnumerable`1 objectSyntaxList,
                NavAppManifest manifest, IFileSystem fileSystem, Boolean
                removeUnusedDependencies)
                   at Microsoft.Dynamics.Nav.Runtime.Designer.NavDevelopmentDes
                ignerExtension.CreatePackage()
                   at Microsoft.Dynamics.Nav.Runtime.Designer.NavDevelopmentDes
                ignerExtension.SaveDesignerData()
                   at Microsoft.Dynamics.Nav.Runtime.Designer.NavDevelopmentDes
                ignerExtension.Save()
                   at Microsoft.Dynamics.Nav.Runtime.Designer.NavDesignerManage
                mentTasks.MovePageField(Int32 pageId, String controlName,
                String parentControlName, String relativeControlName)
                CallerStackTrace:
                   at Microsoft.Dynamics.Nav.Runtime.Designer.NavDesignerManage
                mentTasks.MovePageField(Int32 pageId, String controlName,
                String parentControlName, String relativeControlName)
                   at Microsoft.Dynamics.Nav.Service.NSDesigner.<>c__DisplayCla
                ss15_0.<HandleMovePageFieldAction>b__0()
                   at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppDiagnosticSessi
                on.<>c__DisplayClass1_0`1.<SendTraceTagOnFailure>b__0()
                   at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppDiagnosticSessi
                on.SendTraceTagOnFailure(Action operation, String
                additionalInfo, Func`2 exceptionMap, String callerName)
                   at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppDiagnosticSessi
                on.SendTraceTagOnFailure[T](Func`1 operation, String
                additionalInfo, Func`2 exceptionMap, String callerName)
                   at Microsoft.Dynamics.Nav.Service.NSDesigner.HandleMovePageF
                ieldAction(MovePageFieldRequest action, NavSession session)
                   at Microsoft.Dynamics.Nav.Service.NSDesigner.InvokeAction(Na
                vSession session, DesignerRequest request)
                   at SyncInvokeInvokeDesignerAction(Object , Object[] ,
                Object[] )
                   at
                System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object
                instance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Ru
                nInTransactionCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass27_1.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Tr
                ansientErrorRetryCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass27_1.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Er
                rorMappingCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass27_1.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Pu
                shPopCombinator(ServiceOperation innerOperation, NSServiceBase
                serviceInstance, MethodBase syncMethod, Object[] inputs,
                Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass27_1.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationTracer.Tra
                ceScopeCombinator(Category telemetryCategory, ServiceOperation
                innerOperation, NSServiceBase serviceInstance, MethodBase
                syncMethod, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass27_1.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass9_0.<PerformanceCounterCombinator>b__0()
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Pe
                rformanceCounterCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass27_1.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.In
                itClientTelemetryIdsCombinator(ServiceOperation
                innerOperation, NSServiceBase serviceInstance, MethodBase
                syncMethod, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass27_1.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Tl
                sClearCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass27_1.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.In
                voke(Object instance, Object[] inputs, Object[]& outputs)
                   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.I
                nvokeBegin(MessageRpc& rpc)
                   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.P
                rocessMessage5(MessageRpc& rpc)
                   at
                System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean
                isOperationContextSet)
                   at System.ServiceModel.Dispatcher.MessageRpc.Wrapper.Resume(
                Boolean& alreadyResumedNoLock)
                   at System.ServiceModel.Dispatcher.ThreadBehavior.ResumeProce
                ssing(IResumeMessageRpc resume)
                   at Microsoft.Dynamics.Nav.Runtime.NavSynchronizationContext.
                <>c__DisplayClass1_0.<ClearThreadLocalStorageDelegate>b__0(Obje
                ct state)
                   at
                System.Threading.ExecutionContext.RunInternal(ExecutionContext
                executionContext, ContextCallback callback, Object state,
                Boolean preserveSyncCtx)
                   at System.Threading.ExecutionContext.Run(ExecutionContext
                executionContext, ContextCallback callback, Object state,
                Boolean preserveSyncCtx)
                   at System.Threading.QueueUserWorkItemCallback.System.Threadi
                ng.IThreadPoolWorkItem.ExecuteWorkItem()
                   at System.Threading.ThreadPoolWorkQueue.Dispatch()


                ProcessId: 2904
                Tag: 00000PL
                ThreadId: 81
                CounterInformation:
```

BC-Version:
`mcr.microsoft.com/businesscentral/sandbox:w1`
`14.1.32615.0-W1`

**Comment by qutreson** [comment] 2019-06-12 08:56
Closing a duplicate of #4877. A workaround for now is to publish and install the test symbols. If you have any further information, feel free to contribute to the thread on the other issue.

**Closed by qutreson** 2019-06-12 08:56 UTC
