### ISSUE TITLE
Duplicated entries in xlf file

### ISSUE THREAD

**Issue by makuhn** [microsoft/AL#5866] opened 2020-05-11 13:27 UTC
When compiling one of our apps duplicate entries for a translation (trans-unit-id) are created in g.xlf file. In total 4 trans-unit-ids are duplicated. 

Screenshots below show these entries:
first occurence of the first two entries
![image](https://user-images.githubusercontent.com/38248390/81565630-edf8b400-9399-11ea-83eb-dfc4dd7bdb09.png)

first occurence of second two entries
![image](https://user-images.githubusercontent.com/38248390/81565882-5b0c4980-939a-11ea-9dc0-732832affd7a.png)

duplicate entries (second occurence of entries - same frame color marks corresponding entries from above screenshots):
![image](https://user-images.githubusercontent.com/38248390/81566127-b807ff80-939a-11ea-8d19-466ee52fdb41.png)

It seems that duplication is caused by page customization objects. All controls with duplicated captions were added in page extension as well as used in page customization to move them to another position.
![image](https://user-images.githubusercontent.com/38248390/81583074-1b9d2780-93b1-11ea-9490-ef5ebfbdf614.png)

Issue occured the first time when making some minor changes in the app.

Issue can be reproduced by compiling the app with actual AL extension (Version: 5.0.270354).

**NOTE**
I cannot share the source code via GitHub because it's our IP.

**Comment by AndreyKorepanov** [comment] 2020-06-16 14:17
Hi @makuhn, thank for reporting the issue. This is a bug, I put corresponding label. It will be fixed in the next releases.

**Comment by AndreyKorepanov** [comment] 2020-06-16 14:21
[ALProject46.zip](https://github.com/microsoft/AL/files/4787075/ALProject46.zip)
Project to repro the issue

**Comment by makuhn** [comment] 2020-12-17 10:27
@AndreyKorepanov @JesperSchulz Any news to this issue? It is meanwhile open for more than half a year.

**Comment by JesperSchulz** [comment] 2020-12-17 19:54
Looping in @atoader, as this repository is managed by his team.

**Comment by atoader** [comment] 2020-12-28 14:57
The issue is in our backlog, but we have not started working on it. I will post an overview of how we prioritize issues coming in from GitHub over the following weeks to offer more visibility into the process.

**Comment by makuhn** [comment] 2021-08-31 12:40
@atoader Are there any news regarding this issue?

**Comment by sthiesyaveon** [comment] 2024-01-17 08:31
@atoader any news regarding this issue?

**Comment by NKarolak** [comment] 2024-01-17 08:36
@atoader has left Microsoft years ago, please leave him be ;-)
@BazookaMusic can you take over?

**Comment by BazookaMusic** [comment] 2024-01-17 17:47
There is a repro, marking this for triage.

**Comment by EmilDamsbo** [comment] 2024-05-07 15:08
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 25.0.18947.0 and VS Code Extension Version 14.0.1001176.

If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo

For more details on code branches and docker images please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://freddysblog.com/2020/06/25/working-with-artifacts/

**Closed by EmilDamsbo** 2024-05-07 15:08 UTC
Labels: i18n, accepted
