### ISSUE TITLE
Query Column with Count, Month or Year Method returns None as Data Type

### ISSUE THREAD

**Issue by Wiechardt** [microsoft/AL#7357] opened 2023-04-04 06:45 UTC
Good day,

With the AL 11 language release all columns defined in queries that use the Count(), Month() or Year() method return None as a Data Type and you cannot perform operations on these columns.

- AL Extension Version: 11.0.779295
- Server Version: Version: W1 21.4 (Platform 21.0.46384.46844 + Application 21.4.52563.52785)

This is my query:

query 50100 Customer_Open_Entry_Count
{
    QueryType = Normal;

    elements
    {
        dataitem(Customer; Customer)
        {
            column(No_; "No.") { }

            dataitem(Cust_Ledger_Entry; "Cust. Ledger Entry")
            {
                DataItemLink = "Customer No." = Customer."No.";

                filter(Cust_Ledger_Entry_Open_Filter; Open) { }

                column(Entry_Count)
                {
                    Method = Count;
                }
            }
        }
    }
}

This is a sample codeunit where the error occurs:

codeunit 50100 Sample_Codeunit
{

    trigger OnRun()
    var
        CustomerQuery: query Customer_Open_Entry_Count;
        CustomerCount: integer;
        
    begin
        CustomerQuery.Open();
        while CustomerQuery.Read() do
            if CustomerQuery.Entry_Count > 0 then
                CustomerCount += 1;
        CustomerQuery.Close();
    end;

}

![image](https://user-images.githubusercontent.com/44084862/229709274-7172a46a-dfdc-4faf-8079-2d2006df4c7c.png)

**Comment by thloke** [comment] 2023-04-05 03:51
This is a bad regression. :(

Confirmed that this works in v10 of the extension.

**Comment by BazookaMusic** [comment] 2023-04-05 14:00
I made a very simple repro with the latest version (11.0.779295) and it does not show the same error for me:
[Repro7357.zip](https://github.com/microsoft/AL/files/11159586/Repro7357.zip)

Do you see the same issue in this simple project? Usually 'None' data types come from missing symbols or some other kind of error.

**Comment by thloke** [comment] 2023-04-10 07:59
@Wiechardt  - do you by any chance have your "al.editorServicesLogLevel" set to verbose? I think I've found the regression, and it will only occur if that setting is set to verbose. As a workaround until we have a fix, you can set it to "Error" and it will avoid this.

**Comment by Wiechardt** [comment] 2023-04-10 11:36
@thloke Yes indeed, I have al.editorServicesLogLevel set to verbose.

Thanks for the workaround.

**Comment by JesperSchulz** [comment] 2023-04-13 06:26
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 23.0.10411.0 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Closed by JesperSchulz** 2023-04-13 06:26 UTC
Labels: ships-in-future-update, al-core-compiler, accepted

**Comment by pri-kise** [comment] 2023-05-24 11:04
@JesperSchulz when will this be fixed for the AL Language Extension on the VS Code Market Place?

**Comment by JesperSchulz** [comment] 2023-05-24 11:38
Looks like it is fixed with version 11.0.800245.
