### ISSUE TITLE
It is not possible to add new Key for exist table + system shows error that fields from standard range do not exits

### ISSUE THREAD

**Issue by RedFoxUA** [Microsoft/AL#2623] opened 2018-06-18 09:02 UTC
It is not possible to add new Key for exist table + system shows the error that fields from standard range do not exits.
To download Symbols (before or after) does not solve this issue.

E.g. we have the table "Extended Variant", where we have the field 10 "Item No." (code 20) and we need to create a new key:
tableextension 50105 ExtendedVariantExt extends "Extended Variant"
{
    fields
    {
        field(50000; Counter; Integer)
        {
            Caption = 'MyField';       
            DataClassification = ToBeClassified;
        }
    }
    keys
    {
        key(FK;Counter,"Item No.") { }        
    }
}
the error "- Reference '"Item No."' in application object 'ExtendedVariantExt' does not exist".

same problem for the case when we need to add just 1 more key for fields, which already exist in the table - key(FK;"Item No.","Field 2","Field 2".."Field n") { }

**Comment by qutreson** [comment] 2018-06-18 11:32
Hi @RedFoxUA, it is currently not possible to use fields from the base table for a new key created from a table extension. Closing as duplicate of #456. You can also read #730 for more information on the topic of adding keys.

**Closed by qutreson** 2018-06-18 11:32 UTC
