### ISSUE TITLE
Procedure Documentation

### ISSUE THREAD

**Issue by StefanHovenbitzer** [Microsoft/AL#707] opened 2017-09-21 14:55 UTC
Is it possible by now to define a comment for a procedure which results in a description in intellisense like this: 

![image](https://user-images.githubusercontent.com/24838311/30702529-8185c2c0-9eed-11e7-992f-dc221a582ef9.png)

Thanks in advance!

**Comment by StanislawStempin** [comment] 2017-09-22 11:08
This is not available yet but it's on our backlog.  Closing as duplicate of #132

**Closed by StanislawStempin** 2017-09-22 11:08 UTC
Labels: duplicate
