### ISSUE TITLE
Cannot set runonclient when subscribing to WordManagement event

### ISSUE THREAD

**Issue by jbakach** [microsoft/AL#5028] opened 2019-05-30 10:32 UTC
**Describe the bug**
I'm trying to fix a standard issue when designing "Custom Report Layout". As you introduced a new check in BC Spring that produces a runtime error when you do CANLOADTYPE while you do a write transactions. In BC 13 this is runtime error is not raised when you do the same CANLOADTYPE.

Here I show you the issue:
 
Attempted to issue a client callback while a write transaction started, this can impact performance: CodeUnit 5068 WordApplicationHandler GetApplication.

![image](https://user-images.githubusercontent.com/3531482/58626833-0204ec00-82d6-11e9-84a7-43af3a3ab9c5.png)

I'm trying to fix this through extensions. I want to subscribe to Codeunit 5054 WordManagement. 
Event:
LOCAL [IntegrationEvent] OnGetWord(VAR NewWordApplication : DotNet "Microsoft.Office.Interop.Word.ApplicationClass" RUNONCLIENT;VAR IsFound : Boolean)

But when I'm in VS Code, I cannot put RunOnClient on the subscriber event.
Because without RunOnClient, when you compile and publish the project, it will try to get the 
Microsoft.Office.Interop.Word from the server, and it's not what I want, I want that VS gets the DLL from the client side. But there's no way to approach this through VS.

**Versions:**

 - AL Language: 3.0.126610

 - Business Central: 14.0.29530

**Comment by kine** [comment] 2019-05-31 05:19
I think this issue is out of scope because from next release there will be no C/Side and no Win client, thus all will run on the server...

**Comment by jbakach** [comment] 2019-05-31 07:06
Hi @kine thanks for the answer, so, from what I understand from you, there won't be any possibility to run .NET through the client? How will this affect to "Custom Report Layout" functionality for letting the user editing for itself the word layout? There must be installed Office into the Server prior to execute it on it?

About the client callback runtime error, I saw that a new parameter was added into Server side configuration file in order to avoid it.

The setting to avoid this is:

**<add key="AllowSessionCallSuspendWhenWriteTransactionStarted" value="False" />**

By default is set in False, it should be set in **True.**

Thanks again for your answer.

**Comment by kine** [comment] 2019-05-31 10:32
No, the problem is, that the  function "Edit layout" is available only on Widows client. On Webclient, this action is not available and you are using only Export/Import to edit the layout.

**Comment by atoader** [comment] 2019-06-19 11:16
Thank you for replying to this issue @kine! You are right that this issue is not related to AL development. 
@jbakach  we suggest that you open a support case or file a bug in Collaborate if you need this issue to be addressed in the current release/

**Closed by atoader** 2019-06-19 11:16 UTC
