### ISSUE TITLE
Query objects not included in symbols file

### ISSUE THREAD

**Issue by vasla** [Microsoft/AL#3211] opened 2018-08-10 06:25 UTC
There some problem with Queries in AL symbols file.
After downloading symbols only one Query appears in AL editor intellisense "Sales Dashboard".
All other Queries from base W1 application not available, if enter existing query name manually, compiler show error that query no exists.
I'm using BC image 13.0.23620 and Al Extension al-0.17.30289.

**Comment by vasla** [comment] 2018-08-10 07:15
Problem occurs due to in NAV image symbols are not generated for queries by default.
If You look in table [Object Metadata] field [Symbol Reference] not null only for one Query [Sales Dashboard].
I'm using hybrid environment, docker is running on separate server, and devenv i run on my workstation using click once. So, compiling objects does not generate symbols.

To solve problem i connect with RDC to server with running docker container, run finsql.exe with parameter generatesymbolreference=1 and compile queries.
After downloading symbols in VSCode i can use other queries.

**Comment by vasla** [comment] 2018-08-10 07:43
It could be good if symbols for queries has been already generated in image.
And add parameter generatesymbolreference=1 to DevEnv ClickOnce installation.

**Comment by StanislawStempin** [comment] 2018-08-10 09:34
Yes, if we produce symbols for everything but Queries it sounds like a bug.

**Comment by StanislawStempin** [comment] 2018-11-02 12:57
I have tried the following image and I'm seeing all symbols correctly:
Using image bcinsider.azurecr.io/bcsandbox-master:latest
NAV Version: 14.0.25630.0-W1

Please comment on this issue if you're still encountering this problem on any recent docker images. I will keep this issue open for a few days.

**Comment by StanislawStempin** [comment] 2018-11-07 12:30
Closing due to the fact that we couldn't reproduce the issue and for lack of additional input.

**Closed by StanislawStempin** 2018-11-07 12:30 UTC
Labels: input-needed, investigate
