### ISSUE TITLE
Code analyzer error when accessing protected variable in report extension

### ISSUE THREAD

**Issue by MikeGlue** [microsoft/AL#6958] opened 2022-02-28 17:11 UTC
**1. Describe the bug**
The following CodeCop error appears when you StrSubstNo with a protected variable that has a placeholder in it.

**2. To Reproduce**
I replicated this with a report extension, not sure if it can happen with other extension objects. I've attached the example projects that I used to replicate the issue.

1. Create a report with a protected variable that has a placeholder in it.
2. Create a report extension to the report in step 1.
3. Use StrSubstNo to inject a value into the placeholder of the protected variable.

I have attached a zip of both the parent and child projects that replicate the issue:
[CodeAnalyserError.zip](https://github.com/microsoft/AL/files/8155260/CodeAnalyserError.zip)

**3. Expected behavior**
No code analysis error.

**4. Actual behavior**
The following error shows (it repeats if you have multiple instances of StrSubstNo being used:

```
[{
	"resource": "/c:/_dev/repos/Misc/CodeAnalyserErrorChild/app.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "AD0001",
	"severity": 4,
	"message": "Analyzer 'Microsoft.Dynamics.Nav.CodeCop.Design.Rule131StringParamsMustMatchPlaceholders' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SimpleNavTypeSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.ILabelTypeSymbol'.\r\n   at Microsoft.Dynamics.Nav.CodeCop.Design.Rule131StringParamsMustMatchPlaceholders.GetExpressionParamValue(IOperation expression) in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeCop\\Design\\Rule131StringParamsMustMatchPlaceholders.cs:line 103\r\n   at Microsoft.Dynamics.Nav.CodeCop.Design.Rule131StringParamsMustMatchPlaceholders.AnalyzeInvocation(OperationAnalysisContext ctx) in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeCop\\Design\\Rule131StringParamsMustMatchPlaceholders.cs:line 71\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass53_1.<ExecuteOperationAction>b__1() in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 764\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 1100'",
	"source": "AL",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]
```

**5. Versions:**

- AL Language: 8.4.586670
- Visual Studio Code: 1.64.2
- Business Central: Platform 19.0.35391.36452 + Application 19.4.35398.36475
- List of Visual Studio Code extensions that you have installed: none

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by sergiudina** [comment] 2022-03-17 09:02
Hi, @MikeGlue could you please share your AL settings from the settings.json file?

**Comment by MikeGlue** [comment] 2022-03-17 13:33
Here you go:

```
{
    "al.codeAnalyzers": [
        "${CodeCop}"
    ],
    "al.enableCodeAnalysis": true,
    "al.backgroundCodeAnalysis": true,
    "al.enableCodeActions": true
}
```

**Comment by nndobrev** [comment] 2022-04-04 08:59
@MikeGlue, we are unable to reproduce the issue, please check again on the latest version of our VSCode extension and make sure you don't have any other extensions installed.
![image](https://user-images.githubusercontent.com/85873063/161510203-33302f8a-5476-41bb-a99e-20a393da2807.png)

**Comment by MikeGlue** [comment] 2022-04-04 20:13
This is definitely still happening with the latest AL extension (v9.0.605172) and the sample project I provided to you. I confirmed that all extensions have been removed except for AL Language. I also confirmed that another developer on my team is seeing the same issue.

I've attached a fresh copy of the "child" project that just needs the base BC symbols added. Everything in this project was compiled and validated using the latest AL extension and using the official release of v20.

Same error happens:

```
Analyzer 'Microsoft.Dynamics.Nav.CodeCop.Design.Rule131StringParamsMustMatchPlaceholders' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SimpleNavTypeSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.ILabelTypeSymbol'.
   at Microsoft.Dynamics.Nav.CodeCop.Design.Rule131StringParamsMustMatchPlaceholders.GetExpressionParamValue(IOperation expression) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeCop\Design\Rule131StringParamsMustMatchPlaceholders.cs:line 103
   at Microsoft.Dynamics.Nav.CodeCop.Design.Rule131StringParamsMustMatchPlaceholders.AnalyzeInvocation(OperationAnalysisContext ctx) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeCop\Design\Rule131StringParamsMustMatchPlaceholders.cs:line 71
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass53_1.<ExecuteOperationAction>b__1() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 764
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1078'
```

[CodeAnalyserErrorChild.zip](https://github.com/microsoft/AL/files/8412848/CodeAnalyserErrorChild.zip)

**Comment by JesperSchulz** [comment] 2022-04-12 14:43
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 39052 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Closed by JesperSchulz** 2022-04-12 14:43 UTC
Labels: ships-in-future-update, CodeCop, accepted

**Comment by JesperSchulz** [comment] 2022-04-22 15:53
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 39197 and VS Code Extension Version 10.0.611940. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
