### ISSUE TITLE
Bug in table relation property in table extension

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#2686] opened 2018-06-21 12:39 UTC
Hi, When I want to add a new field to a base object and my field relates to another table, the intellisence give me wrong values (Not from related to table, but from current). 

For example:
![image](https://user-images.githubusercontent.com/29101017/41719522-ee421c04-7568-11e8-92d0-4a1d05e2cfc5.png)

![image](https://user-images.githubusercontent.com/29101017/41719536-fda2ca86-7568-11e8-8284-1bb36a050f4d.png)

![image](https://user-images.githubusercontent.com/29101017/41719567-143677b6-7569-11e8-804b-61408871e2cf.png)

**Comment by kalberes** [comment] 2018-06-21 21:34
This does not repro for me on the latest May release/latestdocker
Looks a duplicate of #1981 
Are you using Nav 2018?

**Closed** 2018-06-22 10:42 UTC
