### ISSUE TITLE
Publishing extension from VS code throws error

### ISSUE THREAD

**Issue by kavila02** [Microsoft/AL#4194] opened 2018-11-13 19:58 UTC
**Describe the bug**
When I try to deploy my extension from VS Code, I get an error "Could not publish the package to the server. See Visual Studio Code debug console for more details."

There are no errors in the debug console.

![image](https://user-images.githubusercontent.com/42249333/48439385-2c38f700-e754-11e8-9d8a-73d9a8e5daa2.png)

 - AL Langauge: 2.0.48254
 - Business Central: US Dynamics NAV 13.0 (25789)

**Comment by qutreson** [comment] 2018-11-13 20:23
Hi @kavila02, what is the content of your extension? 
Can you try publishing a simple HelloWord like this one?
```
pageextension 50100 MyExtension extends "Customer List"
{
    trigger OnOpenPage()
    begin
        Message('Hello World!');
    end;
}
```

**Comment by qutreson** [comment] 2018-11-13 20:33
Can I close this issue if the problem is now fixed for you?

**Comment by kavila02** [comment] 2018-11-13 20:34
The issue can be closed.

**Closed** 2018-11-13 20:41 UTC
