### ISSUE TITLE
TableExtension XXXXX ::They key name 'Key1' is used multiple times in table 'Reservation Entry'

### ISSUE THREAD

**Issue by bachii1010** [microsoft/AL#6489] opened 2021-02-25 11:34 UTC
Describe the bug
We are getting the above error when we publish our apps in 18.0.
Can anybody let us know what is the best way to solve this issue?

Also this is not coming as a warning or error in VSCode when it compiles with vsix file.

To Reproduce

Expected behavior
we expect the app to be published

Screenshots

5. Versions:

AL Language: 7.0.415152
Business Central: 18.0.22441.0

**Comment by dtkb** [comment] 2021-02-25 15:02
@AlexanderYakunin The previous version of this posted here was closed and requested to move to your repo instead. If it's not on-topic for either, can someone say so, instead of just bouncing it back and forth? ;-)

Saying that, the answer seems to be just 'rename your keys', but it would be good if MS documented what names were reserved for themselves. I guess in the meantime, any new keys' names should be prefixed/suffixed with the developer's affix (as should any symbols).

**Comment by AlexanderYakunin** [comment] 2021-02-25 15:58
@atoader

**Comment by bachii1010** [comment] 2021-02-26 05:42
> @AlexanderYakunin The previous version of this posted here was closed and requested to move to your repo instead. If it's not on-topic for either, can someone say so, instead of just bouncing it back and forth? ;-)
> 
> Saying that, the answer seems to be just 'rename your keys', but it would be good if MS documented what names were reserved for themselves. I guess in the meantime, any new keys' names should be prefixed/suffixed with the developer's affix (as should any symbols).

When you try to rename the key in table extension it is not publishing and also fails in Run-ALValidation

**Comment by atoader** [comment] 2021-03-07 13:40
Let's first get to the root cause of the issue and then we can discuss the best path forward. Can you provide a project and instructions on how to reproduce this?

**Comment by CarloAxians** [comment] 2021-03-26 13:06
We have the same issue.
We have a table extension for table Item and added an extra key:

```
key(Key1; "AXI Usable for Packing"
{
}
```

This is working fine in BC17, but in BC18 we get the error _They key name 'Key1' is used multiple times in table 'Item'_
When we rename the key to AXIKey1 we get a SQL error when installing the new version of our app:
_The new name '$AXIKey1' is already in use as a INDEX name and would cause a duplicate that is not permitted._

**Comment by atoader** [comment] 2021-04-02 10:39
@CarloAxians can you provide a project to reproduce the issue?

**Comment by CarloAxians** [comment] 2021-04-09 08:34
Hi @atoader,
In the GA version of BC18 the error _They key name 'Key1' is used multiple times in table 'Item'_ is resolved.
So we have renamed the keys back to their orginal names.

I haven't tried anymore to rename the key, but steps to reproduce are:
- Create an extension with a table extension with an key
- Publish this extension
- Change the keyname
- Publish the new extension by upgrading the previous version

**Comment by atoader** [comment] 2021-04-09 08:44
Could you provide the projects? We are prioritizing issues where we have projects that we can try out and debug right away.

**Comment by salgiza** [comment] 2021-04-26 11:01
We've been also hit by this bug, but it seems to be fixed in newer versions of BC18. In particular, this version failed with the error reported by @bachii1010:

Platform 18.0.22678.0 + Application 19.0.22882.0

But deploying the same app in this version works without problems:

Platform 18.0.22893.24526 + Application 18.0.23013.24585

Regardless, @atoader, here is a code example to trigger this bug. You just have to create this table extension:

```
tableextension 50100 "Item Extension" extends Item
{
    fields
    {
        field(50100; "Test"; Code[10])
        {
            Caption = 'Test';
        }
    }

    keys
    {
        key("Key1"; Test) { }
    }
}
```

And deploy it twice using F5. First time it works, second times you get the "The key name 'Key1' is used multiple times..." error.

As mentioned, though, it seems to be fixed now, but it would be nice to confirm it.

**Comment by jehelles** [comment] 2021-04-28 08:48
This issue was present in the preview release of 18.0, but has been fixed in the final version of the release.

**Closed by jehelles** 2021-04-28 08:48 UTC
Labels: input-needed
