### ISSUE TITLE
App.json: "showMyCode" flag not blocking downloading source code

### ISSUE THREAD

**Issue by mtaanquist** [Microsoft/AL#2791] opened 2018-07-04 10:25 UTC
- AL Extension Version: 0.12.17091
- Server Version: DK Dynamics NAV 11.0 (22292)

I've got the following `app.json` file below, with the `showMyCode` flag set to `false`, but when I open up the Extension Management in NAV, it still allows me to download the code.

```
{
  "id": "980adc3b-2d43-492c-8e41-de7e11b69b89",
  "name": "Customization Pack",
  "publisher": "mtaanquist",
  "brief": "",
  "description": "",
  "version": "1.0.1.0",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "logo.png",
  "capabilities": [],
  "dependencies": [],
  "screenshots": [],
  "features": "TranslationFile",
  "platform": "11.0.0.0",
  "application": "11.0.0.0",
  "idRange": {
    "from": 70200,
    "to": 70299
  },
  "showMyCode": false,
  "target": "Internal"
}
```

Images from Dynamics NAV 2018:

**"Download Source" button enabled**
![image](https://user-images.githubusercontent.com/12089874/42271954-f8079de2-7f84-11e8-94cc-2d1284ed431a.png)

**Zip package download**
![image](https://user-images.githubusercontent.com/12089874/42271974-08879a64-7f85-11e8-9054-0df68c2c4cad.png)

I also attempted to set the flag to `true` in case it was just a misplaced `not` somewhere in the code.

Please let me know if you need any further information.

**Comment by thpeder** [comment] 2018-07-04 11:38
Hi @mtaanquist,
Thanks for your feedback, 
The issue is fixed in Business Central and later versions but will not be backported because Nav 2018 is now only an on-premise release in which case you can simply open the database and find the package.

**Comment by mtaanquist** [comment] 2018-07-04 13:04
Hi @thpeder,

Thank you for your reply. I will have to disagree with your decision to not backport the fix. Even though NAV 2018 is purely on-premise, if you're deploying NAV 2018 to a customer, you would generally not give the end-users the permissions to access the SQL database, and they would be able to access it via the Extension Management page.

I realise that you can block access to the Extension Management page with permissions in NAV, but there will still likely be one or two people at a customer with *SUPER* rights on the system or other NAV partners, who could then potentially leak the source code--or give others the permissions to do so.

This is obviously not an issue for a small collection of page- or table-extensions, but may be for larger solutions or ISVs.

**Comment by thpeder** [comment] 2018-07-06 07:41
Hi @mtaanquist,
You make a great point, I'll backport it.

**Comment by thpeder** [comment] 2018-07-06 21:42
@mtaanquist, I can also recommend you take a look at [Runtime Packages](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-creating-runtime-packages) since they allow you to create and publish a package that doesn't contain the source code at all, so even if somebody get access to the database then there are no AL code to find.

**Closed** 2018-07-30 10:41 UTC
Labels: bug
