### ISSUE TITLE
BlankZero and Editable modification are not detected as "not supported"

### ISSUE THREAD

**Issue by dannoe** [microsoft/AL#6555] opened 2021-03-29 21:44 UTC
Please include the following with each issue:

**1. Describe the bug**
I was transforming code from C/AL to AL and neither the txt2al (it's okay) or the AL vsx did error (or at least warn) me about the following:

- BlankZero modifications on a existing field inside a TableExtensions are not supported
- Editable modifications on a existing part inside a PageExtensions are not supported

Only the publishing of the app has told me:

```
Reason: An error occurred while applying changes from the object of type 'PageExtension' with ID '50000' 
in the 'xyz by xyz 1.0.0.0' app to the application object of type 'Page' with the ID '5725'. Failing delta: 
Type: ContentChangeDelta; TargetKind: FactBoxes; TargetId: Control1905767507; TargetType: ControlBaseDefinition
The error was: InvalidOperationException - Metadata delta application failed due to the following error(s): 
Modifications to property Editable are not supported.
```

**2. To Reproduce**
- Create TableExtensions and modify BlankZero of a base field.
- Create PageExtension and modify Editable of a base part.

**3. Expected behavior**
VS Code should warn/error/tell me.

**4. Actual behavior**
Nothing.

**5. Versions:**

- AL Language: v6.6.434101
- Visual Studio Code: Version: 1.54.3
- Business Central: 17

**Comment by dtkb** [comment] 2021-03-30 08:33
Maybe those changes should be OK, though? They can't affect the schema and are really just cosmetic (in fact I wonder if `BlankZero` even belongs on a table, other than for convenience!)

**Comment by pri-kise** [comment] 2021-12-06 06:25
Is there any Progress on this feature?
I had the same problem with the Modifaction of the Editable Property.
Thankfully this error is recognized on publishing the extension in our buildpipeline resulting in the following error.

> ##[error]An error occurred while applying changes from the object of type 'PageExtension' with ID 'XXX' in the 'AppName publisher 0.1.0.9860' app to the application object of type 'Page' with the ID '7374'. Failing delta: Type: 'ContentChangeDelta'; TargetKind: 'FactBoxes'; TargetId: 'Control2'; TargetType: 'ControlBaseDefinition'; PropertyNames: 'Editable'; The error was: InvalidOperationException - Metadata delta application failed due to the following error(s): Modifications to property Editable are not supported.

**Comment by JavierFuentes** [comment] 2022-05-26 18:46
Same issue here with v20.1.ES SaaS.

CodeCops don't rise any error or warning... 

I can build the .APP but surprisingly I can't deploy it.

Please, allow this type of changes or at least add it to CodeCops.

**Comment by qutreson** [comment] 2024-02-21 12:34
Closing as duplicate of #7670 which is considered for triage.

**Closed by qutreson** 2024-02-21 12:34 UTC
Labels: bug, metadata

**Comment by dannoe** [comment] 2024-02-21 14:15
@qutreson is the "Editable" property for PageExtension parts also covered by the other issue? Or should I create a new issue for that?

**Comment by qutreson** [comment] 2024-02-21 16:24
@dannoe - We will cover both
