### ISSUE TITLE
report extension request page controls cannot use extension variables in properties: "The identifier p51234VarName could not be found."

### ISSUE THREAD

**Issue by db-bc** [microsoft/AL#6710] opened 2021-07-16 12:26 UTC
this code:
```al
reportextension 66666 Test extends "Standard Statement"
{
    requestpage
    {
        layout
        {
            modify("Start Date")
            {
                Visible = not TestBoolean; // or Editable, or Enabled, or probably more?
            }
        }
    }

    var
        TestBoolean: Boolean;
}
```

when run produces this error:
![image](https://user-images.githubusercontent.com/63455896/125946959-de2b412f-4909-4f22-8884-a5d17fe3dc29.png)

Please fix so that variables declared in the report extension can be used to control properties of request page fields. Thanks!

* AL: 7.3.486497
* BC: GB Business Central 18.3 (Platform 18.0.27224.27770 + Application 18.3.27240.27859)

**Comment by db-bc** [comment] 2021-07-16 14:52
I remembered that `[IncludeInDataset]` exists, but it makes no difference here; the error still occurs if the `Boolean` has `[IncludeInDataset]`.

That's arguably **better** than what happens in non-extension `report` objects, where if `[IncludeInDataset]` is not there, we'll get no error at runtime, but the properties just won't get the correct value...

**Comment by thloke** [comment] 2021-07-19 02:07
This is the same as #6660 

I'm currently working on a fix for this, including fixing the more insidious issue with base reports not getting the correct value (but no error!). Because the fix requires an update of the server as well, I'd expect this to be in the next 18.x release (18.5 I think, but I'll have to confirm based on the timing of when the fix goes in).

I'll close this as a duplicate of the other issue, since that's the issue our internal ticketing system is tracking against.

**Closed by thloke** 2021-07-19 02:07 UTC

**Comment by db-bc** [comment] 2021-07-19 08:18
thanks, and glad the issue with base reports is known! sorry for not searching better for dupe

**Comment by thloke** [comment] 2021-07-19 08:19
No worries, this was useful too because this reminded me about the InDataSet attribute, which as you know doesn't work for RequestPages in ReportExtensions. I might have missed that otherwise.

**Comment by dnpb** [comment] 2022-05-18 10:02
Hi @thloke Do you know if/when this got fixed?
> I'm currently working on a fix for this, including fixing the more insidious issue with base reports not getting the correct value (but no error!). Because the fix requires an update of the server as well, I'd expect this to be in the next 18.x release (18.5 I think, but I'll have to confirm based on the timing of when the fix goes in).

Peter is trying to determine whether `InDataSet` is now redundant, as apparently the platform should now detect when it needs to do anything special with variables used in properties:
https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1692379172651008

I'm going to try to test it myself, but if you know faster that it was already fixed, or not - that would save some work :-)
