### ISSUE TITLE
AL0604: The identifier "field name" could not be found

### ISSUE THREAD

**Issue by Nyryus** [microsoft/AL#6048] opened 2020-07-22 15:50 UTC
**Describe the bug**
Following the rule we added all Rec reference in every point of code requested.
When added in the "Enable" property of a modify of a standard action it returns the error:
"The identifier 'Rec.[Field Name]' could not be found."

**To Reproduce**
Steps and to reproduce the behavior:
1. Add a page extension to a standard page
2. Modify an action and it's related "Enabled" property with a field.
3. Specify the Rec.[Field Name] as requested by the rule AL0604

``` AL Code to reproduce the issue ```
```
pageextension 50000 "EOSPageExt50000" extends "Warehouse Shipment"
{
   actions
    {
        modify("Use Filters to Get Src. Docs.")
        {
            Enabled = Rec."CustomEnum" = Rec."CustomEnum"::" ";
        }
    }
}
```

**Expected behavior**
The page works normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/40896051/88189995-0444ab00-cc3a-11ea-987f-f39bc02411b9.png)

![image](https://user-images.githubusercontent.com/40896051/88189957-f7c05280-cc39-11ea-8889-93c717638943.png)

**5. Versions:**
 - AL Language: 
Version: 6.0.302409
 - Business Central:
IT Business Central 17.0 (Platform 16.0.14638.0 + Application 17.0.14837.0)

**Comment by dtkb** [comment] 2020-07-23 10:19
looks basically the same as #5916 and #6040

**Comment by NavDeb** [comment] 2020-10-15 14:03
Any update on this?

**Comment by deadmouse** [comment] 2020-10-20 11:34
I'm getting this but for page property Editable. So, when page opens, error appears automatically.

![image](https://user-images.githubusercontent.com/6352552/96580723-0241c500-12d9-11eb-8b49-87826661aefe.png)

**Comment by dtkb** [comment] 2020-10-20 15:52
The workaround, which will work equally in runtimes pre/post 7.0, which is the only place where this _should_ compile without warning... is to use `OnAfterGetRecord()` to set a global `Boolean` with the same expression, then use that `Boolean` as the property expression. It's just a bit uglier, but I have just been doing it and not looking back, not even putting `TODO`s at those lines for once upgraded to runtime 7 as it doesn't matter enough

**Comment by db0451** [comment] 2021-03-23 09:39
seems like a dupe of https://github.com/microsoft/AL/issues/6191

**Comment by nndobrev** [comment] 2021-07-29 11:20
Closing this issue as it seems we don't have the problem anymore.

@Nyryus thank you for reporting it, please feel free to reopen if you can reproduce it on the latest version.

**Closed by nndobrev** 2021-07-29 11:20 UTC
Labels: bug
