### ISSUE TITLE
Could not start the language service

### ISSUE THREAD

**Issue by DSaladinCH** [microsoft/AL#6508] opened 2021-03-04 07:55 UTC
**Describe the bug**
Since the new version (6.6.425415) the language service isn't starting properly.
So the commands like publishing and building doesn't work.

The error message in text:
Could not start the language service: [Error: spawn EPERM at ChildProcess.spawn (internal/child_process.js:394:11) at Object.spawn (child_process.js:549:9) at h:\vscode-extension\ms-dynamics-smb.al-6.6.425415\node_modules\vscode-languageclient\lib\main.js:376:40] { errno: 'EPERM', code: 'EPERM', syscall: 'spawn' }

**To Reproduce**
Steps and to reproduce the behavior:
1. Install latest version (6.6.425415)
2. Open a AL project

**Expected behavior**
Language service should start properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/43037258/109929447-bd865b80-7cc6-11eb-910e-da45c6c7a512.png)

**5. Versions:**
 - AL Language: 6.6.425415
 - Business Central: 16.0.14648.15420 (Platform) and 16.0.12076.0 (Application) (Shouldn't be important for this bug, but yeah)

**Comment by qutreson** [comment] 2021-03-04 11:02
@Daniamstutz @DSaladinCH which version of VS Code are you using? Which OS are you using?

**Comment by DSaladinCH** [comment] 2021-03-04 11:15
@qutreson VS Code Version 1.52.1 on Windows 10 Version 1607 (Build 14393.4225).
VS Code is installed on a citrix server, so I don't have admin privileges.

**Comment by qutreson** [comment] 2021-03-04 12:00
Did you experience this issue with previous versions of the AL extension for VS Code?

You can give it a try from the extension tab here:
![image](https://user-images.githubusercontent.com/31541422/109960794-7f4e6380-7ce9-11eb-8e93-25977e8f2758.png)

**Comment by DSaladinCH** [comment] 2021-03-04 12:08
No, the previous version (6.5.413786) worked without problems

**Comment by qutreson** [comment] 2021-03-04 12:10
A workaround would then be to revert to this version for now

**Comment by DSaladinCH** [comment] 2021-03-04 12:12
Okay easy, I'll use the previous version for now

**Comment by atoader** [comment] 2021-03-07 13:19
Can you reproduce this issue on other environments?

**Comment by DSaladinCH** [comment] 2021-03-07 13:25
I can't test that on other environments. The citrix server is the only environment I now with a language service.

**Comment by Daniamstutz** [comment] 2021-03-16 10:57
The problem was with the virus scanner on the Citirx environment.
You can close the issue, thank you for your support.

**Closed** 2021-03-16 10:59 UTC
Labels: bug, input-needed
