### ISSUE TITLE
Customise Launch URL for launch.json different to `url param & server public URL 

### ISSUE THREAD

**Issue by ShadowXVII** [microsoft/AL#7418] opened 2023-05-23 07:49 UTC
**1. Describe the bug**
In complex port/reverse proxy scenarios the developer services and launch URL might be different, or short-lived.
Can we please override the launch URL with something custom?

This was somewhat discussed in #7373 and #6807 but we'd like to point it to an entirely different URL altogether that isn't derived from either the `usePublicURLFromServer` OR the `url` parameter in `launch.json`.

**2. To Reproduce**
n/a

**3. Expected behavior**
Allow the launch URL to be customised.

**4. Actual behavior**
A clear and concise description of what happened accompanied by images, animations, or a link to a video showing the issue occurring

**5. Versions:**

- AL Language: v11.0.787898
- Visual Studio Code: v1.78.2
- Business Central: all
- List of Visual Studio Code extensions that you have installed: n/a

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue
* [x] Reproduce the issue after disabling all extensions except the AL Language extension
* [x] Simplify your code around the issue to better isolate the problem

**Comment by nndobrev** [comment] 2023-05-23 08:59
Hi @ShadowXVII, can you please provide examples  of what you want to achieve? Considering the information provided so far I think this sounds more like an idea then actual bug.

**Comment by nndobrev** [comment] 2023-05-23 09:01
Duplicate of #7419

**Closed by nndobrev** 2023-05-23 09:01 UTC
Labels: input-needed
