### ISSUE TITLE
TestPage field Caption giving error 

### ISSUE THREAD

**Issue by ashik-ivor** [Microsoft/AL#4743] opened 2019-03-19 12:39 UTC
Getting error while publishing the test app file. 

error CS1955: Non-invocable member 'Microsoft.Dynamics.Nav.Runtime.NavTestField.ALCaption' cannot be used like a method.

![image](https://user-images.githubusercontent.com/38459860/54606419-c944cd00-4a71-11e9-953c-a3ce820281d8.png)

Complier : AL 2.1.109895 & AL 2.1.91153

**Comment by tomasevicstefan** [comment] 2019-03-21 13:35
I had similar problem, but I can't remember how I fixed this issue.

Can you send test function?

**Comment by thpeder** [comment] 2019-03-22 10:02
The issue is fixed in the coming major release and in the coming CU for the fall release.

**Closed by thpeder** 2019-03-22 10:02 UTC
