### ISSUE TITLE
'CurrFieldNo' is inaccessible due to its protection levelAL(AL0161)

### ISSUE THREAD

**Issue by FSchneiderYav** [Microsoft/AL#4885] opened 2019-04-11 13:07 UTC
**Describe the bug**
I have a new page with Warehouse Receipt Line as SourceTable.
When I use the CurrFieldNo variable i got the following error.

(global) CurrFieldNo: Integer
'CurrFieldNo' is inaccessible due to its protection levelAL(AL0161)

**Versions:**
 - AL Langauge: 3.0.107312

**Comment by qutreson** [comment] 2019-04-17 08:59
@FSchneiderYav can you share with us a short code snippet we can use to reproduce the issue?

**Comment by PooyaKharamesh** [comment] 2019-05-03 09:53
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Closed by PooyaKharamesh** 2019-05-03 09:53 UTC
Labels: input-needed

**Comment by TomHedegaardTrimit** [comment] 2019-05-06 12:15
How was this solved and where to find the solution comment ?
