### ISSUE TITLE
AL Code working in Sandbox, but not in live environment

### ISSUE THREAD

**Issue by bernyd123** [microsoft/AL#5002] opened 2019-05-24 11:21 UTC
Hi there,

Thanks in advance for taking the time to assist with my below query.

I have written code for a customer that I tested in Sandbox and it worked perfectly fine, but when I deployed it in live it does not work. I have read every single blog and question I have been able to find on the possible differences between Sandbox and Live, and I have tried to do my research, but was not able to find an answer. I will give as much details as possible to assist in the troubleshooting process.

I am using a cloud environment, and both Sandbox and Live environments are version 14.0.29537.0

My development is that on the Posted Sales Invoice page, I need to make the Your Reference field editable for a customer, as they only get the customer order number after having invoiced the customer, And their customer requires their reference number on the Invoice for payment. I added a button that makes the field editable for when required. This was tested in Sandbox, and worked as desired, and as designed. However upon deploying to live, it does not work.

I have noticed that in the Sandbox environment when you go to the Posted Sales Invoice page, that the edit button (the one at the top that looks like a pencil) is active, but in the live environment, it is grayed out. Meaning that the entire page is non-editable, so I tried adding CurrPage.Editable:=true to my code, in case the page is non editable in live, but this also yielded no results.

I then tried to make the field permanently editable in my extension (in other words not having the user click on a button to make it editable when required), and once again, this was fine in Sandbox, but not in live.

I know that if your "runtime": "2.1" is set in APP.json then you could not set the editable property in code, but my setting in APP.json is "runtime": "2.2", and further I have the following settings in case you were wondering, or if this has any bearing.
{
...
  "platform": "13.0.0.0",
  "application": "13.0.0.0",
  "showMyCode": true,
  "runtime": "2.2"
}

I have a suspicion that this could have something to do with the "protected" tables in the system, and that the license on the Sandbox does not implement these protected tables, but I need some guidance on how to proceed. My thinking is that I'll have to get the user to click on the button to change the Customer's Reference, then I pop up with a different page that I design, and the user makes his changes there, and I implement the changes in code when the page is closed or something?

Thanks once again for taking the time to assist with this, looking forward to your response in this regard.

Greetings,
Berny During

**Comment by BartPermentier** [comment] 2019-07-12 13:15
That i exactly the problem. Sales Invoice Header is a protected table by design so the only way to change values is by doing it via a codeunit that has permissions on the "Sales Invoice Header".

See below a generic function that will popup a request page requesting a new value for a field:
![image](https://user-images.githubusercontent.com/24684493/61130569-382db200-a4b7-11e9-91c1-ba684b118b32.png)
The function would be called like this in your example:
SalesInvoiceHeader."Your Reference" := CopyStr(RequestNewValueForAField(SalesInvoiceHeader
, SalesInvoiceHeader.FieldNo("Your Reference"), SalesInvoiceHeader."Your Reference", true)
, 1, MaxStrLen(SalesInvoiceHeader."Your Reference"));

**Full Copy paste version**
Permissions = tabledata "Sales Invoice Header" = rim;
    //#region RequestNewValueForAField
    procedure RequestNewValueForAField(RecordVariant: Variant; FieldNo: Integer; InitialValue: Text; ThrowError: Boolean) Result: Text
    var
        FilterPage: FilterPageBuilder;
        FldRef: FieldRef;
        RecRef: RecordRef;
        GetFiltersText: Text;
        StringPosition: Integer;
        ModifyFieldLbl: Label 'New Value for Field:';
        TooManyParametersErr: Label 'You have used too many parameters. Please only use 1.';
    begin
        // #This function asks the user a new value for a field
        // @RecordVariant : Variant: The record
        // @FieldNo : Integer: The field No.
        // @InitialValue : Text: Optional the value of the current field
        // |Result: the value that the user entered
        FilterPage.PAGECAPTION(ModifyFieldLbl);
        FilterPage.ADDRECORD(ModifyFieldLbl, RecordVariant);
        RecRef.GETTABLE(RecordVariant);
        FldRef := RecRef.FIELD(FieldNo);
        FilterPage.ADDFIELD(ModifyFieldLbl, FldRef, InitialValue);
        IF NOT FilterPage.RUNMODAL() THEN
            if ThrowError then
                ERROR('');
        RecRef.SETVIEW(FilterPage.GETVIEW(ModifyFieldLbl));
        GetFiltersText := RecRef.GETFILTERS();
        StringPosition := STRPOS(GetFiltersText, ':');
        GetFiltersText := COPYSTR(GetFiltersText, StringPosition + 2);
        StringPosition := STRPOS(GetFiltersText, ':');
        IF StringPosition <> 0 THEN
            ERROR(TooManyParametersErr);
        EXIT(GetFiltersText);
    end;
    //#endregion RequestNewValueForAField
    //#region ModifyExternalDocumentNoFromSalesInvoiceHeader
    procedure ModifyExternalDocumentNoFromSalesInvoiceHeader(var SalesInvoiceHeader: Record "Sales Invoice Header");
    begin
        SalesInvoiceHeader."External Document No." := CopyStr(RequestNewValueForAField(SalesInvoiceHeader
                        , SalesInvoiceHeader.FieldNo("External Document No."), SalesInvoiceHeader."External Document No.", true)
                            , 1, MaxStrLen(SalesInvoiceHeader."External Document No."));
    end;
    //#endregion ModifyExternalDocumentNoFromSalesInvoiceHeader

**Comment by atoader** [comment] 2019-08-09 10:54
Thanks for the help @BartPermentier ! I will close this issue as it seems it has been resolved.

**Closed by atoader** 2019-08-09 10:54 UTC
Labels: investigate
