### ISSUE TITLE
OnAfterGetRecord trigger unexpectedly executed before OnAction trigger

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/AL#5129] opened 2019-07-11 09:55 UTC
**Describe the bug**
I have a wizard page (PageType = NavigatePage) with two actions on it.
When you click on one of the actions, the OnAfterGetRecord trigger of the page is executed before the OnAction trigger of the action. That results in unexpected behavior, especially when you initialize some variables based on the displayed record, but let the user change the value on the screen. After clicking on the action, the variables are reset to their original values.

**Expected behavior**
OnAction trigger should run without any running any other trigger before it.

**Versions:**
 - AL Language: 3.0.145991
 - Business Central: Platform 14.0.29530.34057 + Application 33849

**Comment by qutreson** [comment] 2019-10-10 09:15
Hi @ajkauffmann, I looked into our code base and our commit history and it seems that this behavior is this the intended behavior. This change was made in 2008 so even if it can look like an unexpected behavior, other partners may be relying on this behavior. Closing then as by design.

**Closed by qutreson** 2019-10-10 09:15 UTC
Labels: cross-team-investigate
