### ISSUE TITLE
Why AL0603 for assigning integers to an enum?

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#7698] opened 2024-03-27 12:18 UTC
Bug or feature?
Why is warning [AL0603](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/diagnostics/diagnostic-al603) raised when directly assigning an integer to `MyEnum`, and why not when assigning it indirectly in `foreach`?

```
procedure TestAL0603()
var
    MyEnum: Enum MyEnum;
    Integers: List of [Integer];
begin
    // both raise warning AL0603:
    MyEnum := 1;
    MyEnum := Integers.Get(1); 

    // both raise no warning
    foreach MyEnum in MyEnum.Ordinals() do ...;
    foreach MyEnum in Integers do ...;
end;
```

Don't get me wrong - I prefer it without the warning. So much cleaner ... But then I see no reason why we should get AL0603 at direct assignment.

**Versions:**

- AL Language: 13.0

**Comment by thloke** [comment] 2024-07-23 02:33
We've looked at this on and off again, and the problem is that the rule has value in direct assignment - but also if we were to enforce it in foreach it will end up with the overhead mentioned above. So I'm in favour of just closing this as "yes, we know about this and we'll keep it inconsistent for now" to avoid sparking a larger debate if we were to make it consistent.

**Closed by thloke** 2024-07-23 02:33 UTC
Labels: accepted
