### ISSUE TITLE
Filterpagebuilder.Runmodal always returns false and does not run the filter page

### ISSUE THREAD

**Issue by SPinkow** [microsoft/AL#4279] opened 2018-11-28 15:54 UTC
Hi,

every time a filterpagebuilder calls the method RunModal the return value is false an the filterpage is never displayed.

To reproduce this you can open the "Interaction Log Entries" for some contact. In the actions (Screenshot 1) you can find an action "Filter" which calls a filterpagebuilder from code (Screenshot 2).

![interaction log entries](https://user-images.githubusercontent.com/45430404/49163145-b3799380-f32c-11e8-94c1-404bc8b196b2.png)

![debug filterpagebuilder](https://user-images.githubusercontent.com/45430404/49163158-b96f7480-f32c-11e8-89dd-c37b390c1903.png)

**Versions:**
AL Language --> 2.0.58805
System Information --> DE Dynamics NAV 14.0 (26322)

**Comment by ChewKimPoh** [comment] 2019-01-25 13:50
In BC CU3, I am facing similar issue in using standard Workflow, to set condition, the dynamic request page did not show because the FilterPageBuilder.RunModal immediately returns false:

![image](https://user-images.githubusercontent.com/40346294/51749567-aab5fb80-20ea-11e9-86d1-617a9b6739f7.png)

So, I wrote a simple test with the following code:

FilterPageBuilder.AddTable('Purchase Header', 38);
FilterPageBuilder.AddFieldNo('PurchaseHeader', 2);
FilterPageBuilder.RunModal;

Running the code, there is an error: The metadata object page 9598 was not found.

I ran the same test code in NAV 2018 without problem and in there I can set the condition of Workflow as normal.

**Comment by Slindebaum** [comment] 2019-02-27 13:39
> 
> 
> In BC CU3, I am facing similar issue in using standard Workflow, to set condition, the dynamic request page did not show because the FilterPageBuilder.RunModal immediately returns false:
> 
>
> 
> So, I wrote a simple test with the following code:
> 
> FilterPageBuilder.AddTable('Purchase Header', 38);
> FilterPageBuilder.AddFieldNo('PurchaseHeader', 2);
> FilterPageBuilder.RunModal;
> 
> Running the code, there is an error: The metadata object page 9598 was not found.
> 
> I ran the same test code in NAV 2018 without problem and in there I can set the condition of Workflow as normal.

Same here.
btw... it did work in 13.0.24623.0! 

... any information from Microsoft (maybe it will be solved in CU4)

**Comment by rishiaurrishabh** [comment] 2019-03-01 07:12
Hi, I am using Business Central on Prem (Dynamics.365.BC.27233) and facing same issue with FilterPagebuilder.RUN. please let me know if any one is able to a workaround for the same.

**Comment by tinfister** [comment] 2019-03-20 09:28
I have the same problem using standard Workflows.
BC on premise CU 3 is not working
Latest Docker images sandbox:base and sandbox:nl is working.

I've created Workflow from template for Purchase Invoice and tried to click Condition - AssistEdit

I've debugged the code, and until T1520 Function RunDynamicRequestPage and code
IF NOT FilterPageBuilder.RUNMODAL THEN
everything is the same and all variables have the same value.

I guess it's the same problem you guys have.

**Comment by JJMadrigal** [comment] 2019-03-20 15:57
I have the same issue with BC on premise Cu3.
Do you know if it is solved in Cu4?

Thank you

**Comment by markbrummel** [comment] 2019-03-25 16:53
Seems to be fixed in CU4. Another two hours of life wasted chasing bugs...

**Comment by eric-silverw-com** [comment] 2019-04-09 01:27
I don't think it's entirely fixed.  It's certainly less broke in the latest BC release but it does not appear to be fully functional either.  I've checked the latest release plus several customers and while a FilterPageBuilder will come up, it has limited functionality.  If not filters were previously defined, it comes up blank.  If a filter was previously defined, you can edit that filter but you cannot delete it or add new ones.

**Comment by LarsMadsen** [comment] 2019-05-23 08:21
Quickfix : You can add an empty 9598 page and then the problem is gone in the version that has the bug. I have tryed this in a BC365Cu3

**Comment by tomasevicstefan** [comment] 2019-06-03 11:40
I have the same problem. We are running BC on docker, image "mcr.microsoft.com/businesscentral/onprem:13.6.29777.0-is"

and I still can't select filter on filter page

![1](https://user-images.githubusercontent.com/31925856/58799153-c6835e00-8604-11e9-9072-3af9dee89861.png)

did I missed something?

**Comment by atoader** [comment] 2019-11-09 20:38
Hi! In the last months, we've been working hard on adding new features that increase your productivity and on improving the quality of the tools. Unfortunately, this meant that we were not able to follow up on as many GitHub issues as we have liked.
Is this issue still a problem for you? Can you provide a sample project to reproduce the issue? Does it reproduce on the Wave 2 2019 release?

**Comment by atoader** [comment] 2019-11-18 17:53
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Closed by atoader** 2019-11-18 17:53 UTC
Labels: input-needed
