### ISSUE TITLE
Usage soap URL in .net web application..

### ISSUE THREAD

**Issue by srinivasdes** [Microsoft/AL#2018] opened 2018-04-13 13:01 UTC
I am trying to access the Business central sandbox SOAP service using dot net web application. While adding the web reference to project its getting unauthorized error.
I tried in postman tool by using the Basic Authorization its getting xml schema.

New Soap URL :  https://api.businesscentral.dynamics.com/v1.0/5db49010-0f87-4ff9-98f9-a0b33a40e46a/sandbox/WS/CRONUS%20USA%2C%20Inc./Page/WebShop_User  -- **Unable to access in web application**

Old Soap URL : https://dyneshop-sandbox.financials.dynamics.com:7047/MS/WS/CRONUS USA%2C Inc./Page/WebShop_User  -- **Able to access in web application**

Can anyone please suggest us the process to consume the service

Thanks.

**Comment by StanislawStempin** [comment] 2018-04-13 18:34
Can give you more details about what exactly is the error message that you get. 
Can you also check what is the SOAP URL listed on the Web Services page for your tenant and whether you can connect to your production tenant as comapared to a sandox?

**Comment by naveenpinnama** [comment] 2018-04-13 19:13
Hi Stan,

 The issue we are facing is when we try to add service reference in .net application and we are not able to add them with new url format in BC. 

We have an application that is built based on based on Old urls where we can add them as reference and see the definitions. Now we are trying to use the SOAPs urls that are are generated in BC which are different and not able to add them.


Will adding the reference in VS.Net work or is there a different way we need to access this urls in .net application and access the definitions ?  We have both page and codeunit services.

For eaxmple if i try o add this url as web reference in .NET we get this message. 
https://api.businesscentral.dynamics.com/v1.0/aad04b91-5076-4182-8c0e-35f73b8a70c8/WS/My%20Company/Page/workflowWebhookSubscriptions

As a web reference
![image](https://user-images.githubusercontent.com/34326092/38753270-ba6bb426-3f12-11e8-9c6b-c8e54cf65fbd.png)

If add as Service Reference
![image](https://user-images.githubusercontent.com/34326092/38753398-173c04f8-3f13-11e8-9d16-459ef8058ff3.png)

**Comment by StanislawStempin** [comment] 2018-04-16 10:06
This turns out to be a bug in the new Fixed Endpoint. The fix should be deployed to production during this week.

**Comment by zpfaltersack** [comment] 2018-04-16 15:28
So to be clear, that means that currently it is impossible to load service metadata but this week the ability to read metadata will be restored? We have some similar functionality in a service client and are running into the same problems. Thanks.

**Comment by StanislawStempin** [comment] 2018-04-16 18:08
In general you should be only seeing this problem in a browser, since full requests with an authorization header should go through fine. But it depends on how your service client is written.

The underlying issue is that the fixed endpoint doesn't return WWW-Authenticate header in 401 responses

**Comment by zpfaltersack** [comment] 2018-04-16 19:34
That's interesting, we're receiving the error programmatically even when we do include an access token. This is from a C# client. Again, we're not invoking the service itself though, we're trying to load metadata to then dynamically build the SOAP service client from wsdl. In your response it is still unclear to me whether or not we can expect the metadata to be available again once this authentication is resolved.

**Comment by StanislawStempin** [comment] 2018-04-16 19:43
Yes, the metadata should be available once this issue is fixed.

**Comment by naveenpinnama** [comment] 2018-04-20 16:27
Stan,
 
 Do you have a status on this Bug fix deployment to production?

Thanks

**Comment by zpfaltersack** [comment] 2018-04-23 13:32
I'm also still experiencing this issue. Any further updates? 

Thanks.

**Comment by naveenpinnama** [comment] 2018-04-25 18:34
Hi Stan,

 I think some part is fixed now able to able to add the new urls in Visual stuidio as web reference and able to see the metadata and able to browse Via browser. 

But now we are getting The request failed with HTTP status 400: Bad Request when we try to read data via new urls. Attached is the screenshot. 
![image](https://user-images.githubusercontent.com/34326092/39265578-754b78cc-487c-11e8-964f-81fe9e24947b.png)

The same works with old url format. Do we need to do anything different or is this a BUG?

**Comment by zpfaltersack** [comment] 2018-04-25 20:41
Yep, still seeing exactly that same behavior as well.

**Comment by naveenpinnama** [comment] 2018-04-25 22:01
Thanks Microsoft. The issue is fixed.

**Closed** 2018-04-26 09:05 UTC
Labels: question
