### ISSUE TITLE
RTC Crash

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#78] opened 2017-01-17 09:42 UTC
Created a field in "Jobs setup" and Job.
RTC crashing with below error in event viewer while selecting/entering values in Job Card. (working fine Job Setup page). 
Is it related to VS code extension or something else?
NOTE: if I unistall extension then Job card is working fine. I cannot modify any standard field also in Job card when extension is installed.
[crash event viewer.txt](https://github.com/Microsoft/AL/files/710538/crash.event.viewer.txt)

**Comment by StanislawStempin** [comment] 2017-01-17 12:07
It looks like a duplicate of #75

**Comment by esbenk** [comment] 2017-01-17 14:54
The crash is most likely caused by #75. Without the more details it is hard to say.

**Comment by StanislawStempin** [comment] 2017-01-23 19:14
We have fixed this bug and uploaded a new azure gallery image to http://aka.ms/navdeveloperpreview. Please give it a try.

**Comment by pmohanakrishna** [comment] 2017-01-24 05:26
Its working fine now. Thanks..

**Closed** 2017-01-24 07:25 UTC
Labels: bug, delivered
