### ISSUE TITLE
Multiroot workspace - wrong context fo code analyzer

### ISSUE THREAD

**Issue by kine** [Microsoft/AL#4054] opened 2018-10-16 12:04 UTC
I am using multiroot workspace to be able to work with MainApp and TestApp in one git repository. It is working nearly ok, but I have notice one thing. MainApp and TestApp have different idRange from/to defined in the App.json. The AL code analyzer is taking the range inconsistently.

**To Reproduce**
1. create workspace with two roots
2. in each root create what is needed for AL app
3. set not overlapping ID range for each app
4. create objects from the range in each app
5. Open the al file from second app.
6, The "problems" pane should now show 

> "The application object identifier xxx is not valid. It must be within the allowed range 'aaaaa - 'bbbbb'. 
the xxx is ID of the object from second app
aaaaa - bbbbb is range from the first app

7. If I select the file and open it in editor, the problem related to the object will go away, but will return in a while. 

**Expected behavior**
The code analyzer will take ID range from correct app.json from workspace root which the file belongs to

**Screenshots**
![image](https://user-images.githubusercontent.com/110221/47015156-88f0c400-d14c-11e8-89ed-f652f77a43d0.png)

**Versions:**
 - AL Langauge: 2.0.48254

**Comment by AndreyKorepanov** [comment] 2018-11-07 10:48
@kine Thank you for reporting the issue. I tried to reproduce it with no success. Do you use any specific project/workspace settings or any additional VS Code extensions? It would be very helpful if you could provide the code (workspace) causing the problem.

**Comment by StanislawStempin** [comment] 2018-11-30 08:51
Closing the issue due to lack of repro and additional input.

**Closed by StanislawStempin** 2018-11-30 08:51 UTC
Labels: bug, input-needed
