### ISSUE TITLE
Bug - Table DrillDownPageId Property

### ISSUE THREAD

**Issue by yarenkaplann** [microsoft/AL#7920] opened 2024-11-29 06:54 UTC
**Bug description:**
If table DrillDownPageId property defined and in that table there is a flowfield which uses lookup formula, then related document lines cannot be editable.

**Bug experience environment:**
Business Central Cloud - version: 24.5

**To Reproduce:**
1. create a new table
2. add two fields to table, one field just for the table requirements(field types are not important)
3. create a new page for newly created table and use newly created fields on page.
4. define DrillDownPageId property as newly created table for that new page.
5. create a new table extension object for "Sales Line" table and add new field to "Sales Line" extension table, new field must be defiend as flowfield and use calcformula with lookup and use newly created page for a new table.
6. create an extension page for "Sales Order Subform" and use new extension field in "Sales Order Subform" page.
8. publish app to Business Central.
9. try to open new sales order page or existing sales order page.
10. add new line into that order
11. try to move to second line 

Result: second line and other all lines cannot be editable.

**Code blocks for above mentioned objects:**

**1. New Table:**

table 50100 "Test Table"
{
    Caption = 'Test Table';
    DataClassification = ToBeClassified;
    DrillDownPageId = "Test Page";

    fields
    {
        field(1; "PK"; Boolean)
        {
            Caption = 'PK';
        }
        field(2; "Test Sales Line"; Decimal)
        {
            Caption = 'Test Sales Line';
        }

    }
    keys
    {
        key(PK; PK)
        {
            Clustered = true;
        }
    }
}

**2. New Page for a new table:**

page 50100 "Test Page"
{
    ApplicationArea = All;
    Caption = 'Test Page';
    PageType = ListPart;
    SourceTable = "Test Table";

    layout
    {
        area(Content)
        {
            repeater(General)
            {
                field("Test Sales Line"; Rec."Test Sales Line")
                {
                    ToolTip = 'Specifies the value of the Test Sales Line field.', Comment = '%';
                }
            }
        }
    }
}

**3. New FlowField added to Sales Line extension table:**

tableextension 50100 "Sales Line Ext." extends "Sales Line"
{
    fields
    {
        field(50100; "Test FlowField"; Decimal)
        {
            FieldClass = FlowField;
            CalcFormula = lookup("Test Table"."Test Sales Line");
        }
    }
}

**4. New Sales Order Subform extension page:**

pageextension 50101 "Sales Order Ext." extends "Sales Order Subform"
{
    layout
    {
        addafter("No.")
        {
            field("Test FlowField"; Rec."Test FlowField")
            {
                ApplicationArea = All;
            }
        }
    }
}

**Comment by thpeder** [comment] 2024-11-29 08:34
Duplicate of #7919

**Closed by thpeder** 2024-11-29 08:34 UTC
