### ISSUE TITLE
AutoFormat curley brackets

### ISSUE THREAD

**Issue by waldo1001** [microsoft/AL#1461] opened 2018-01-22 14:32 UTC
I would want to change the behavior of the AutoFormat feature (ALT+SHIFT+F): it now puts my "{" bracket automatically to the next line .. which I hate ;-).

Personally, I would avoid inserting carriage return alltogether, and focus only on formatting the line itself.. .

**Comment by thpeder** [comment] 2018-01-22 14:37
We don't provide a way for you to control the formatting rules but you can select a piece of the code and use "Format Selection [Ctrl+k, Ctrl+F]" instead to only format parts of the code.

**Comment by waldo1001** [comment] 2018-01-22 14:49
Then consider is as a feature request.
I know this particular request is being discussed internally.  And here you have my personal opinion ;-).

The "format selection" doesn't help much .. we should always be able to format all ... .

**Comment by vytjak** [comment] 2018-01-22 14:50
Well, this looks like something people will adamantly argue about...
I think Microsoft should release an AL guidelines document here, defining what is the preferred way of naming variables and functions, formatting code, etc.

**Comment by thpeder** [comment] 2018-01-23 13:54
We are working on releasing a style guide for these kind of situations.

**Comment by esbenk** [comment] 2018-01-26 10:23
The style guide and formatter will be aligned. When it comes to code style there will always be different opinions, and people will argue fiercely for their point of view. As a result we will ultimately end up with a style guide that not everyone is happy about.

We believe in only having one style/formatting, so that all (formatted) code have the same layout, is providing more overall goodness for everyone in the AL community than having a full customizable formatter.

**Comment by TKapitan** [comment] 2018-04-01 09:58
Is anything new about the AL guidelines?

**Comment by thpeder** [comment] 2018-04-05 09:57
Hi@TKapitan,
Take a look at [Best Practices for AL](https://docs.microsoft.com/en-us/dynamics-nav/compliance/apptest-bestpracticesforalcode)

**Comment by lvanvugt** [comment] 2018-04-06 16:24
Adding to waldo's request: when having a empty curly bracket set (like you can have on page when having added fields without any properties set or code added), please put this set on the same line as the field "heading", f.e.
`field("Example Enabled"; "Example Enabled") { }`
and not
`field("Example Enabled"; "Example Enabled")`
`{`
 `}`
This gives better overview on the object.

**Comment by gudrunleos** [comment] 2018-04-09 10:13
+1 from me

Reports are another objects that would have much more readability with the emplty curly brackets in the same line as the column declaration.

**Comment by qutreson** [comment] 2023-11-28 09:41
Closing this issue as the described behavior does not reproduce anymore. When curly braces are surrounding an empty section (as mentioned in the examples above), the AL formatting engine does not move the curly braces to new lines. Constructs like `column(ColumnName; Balance) { AutoCalcField = true; }` are also allowed to stay on the same line which helps readability. If there are additional formatting scenarios related to curly braces that aren't supported well, you can open a new issue and reference this issue. Thanks!

**Closed by qutreson** 2023-11-28 09:41 UTC
Labels: enhancement, al-format
