### ISSUE TITLE
labels don't get translated as per the Report currentReport.Language variable

### ISSUE THREAD

**Issue by drizztdourden08** [microsoft/AL#6928] opened 2022-02-07 19:43 UTC
Related to issue #6917. Has been closed without a final solution.

Here's my last reply. By using `labels{}`, they aren't translated to the currReport.Language selected in the code itself.

Label that are created as variable and then showed using column get translated fine however, which is not the ideal situation imo.

Original post:
-------------------------------
There is still something that doesn't work in this system.

I have used your recommendation and everything in "labels" isn't translated at all.

However, if it's a variable, it does get translated just fine. why  would it need to be a variable for this to happen? 

In the RDL report, I'm using the labels in the "parameters" section, why list all the labels I have. They're all appearing the the translation file just fine but can't get the translation to apply on them.

Labels code:

    labels
    {
        // Header
        lInvoice = 'INVOICE', Locked = false;
        lInvoiceNo = 'Invoice No.';

        //Bill Details
        lBillableTo = 'BILLABLE TO';
        lPayableTo = 'PAYABLE TO';
        lBillableToName = 'Payables Account';
        lPayableToName = 'Receivable Account';
        lAttentionTo = 'Attention To';

        //Bill Info
        lDocumentDate = 'Document Date';
        lPeriod = 'Period';
        lPO = 'PO';
        lMasterAgreement = 'Master Agreement';
        lPaymentMethod = 'Payment Method';

        //Lines Labels
        lConsultantName = 'Consultant Name';
        lConsultantRole = 'Role';
        lProjectName = 'Project Name';
        lProjectNumber = 'Project #';
        lCustomerPO = 'Customer PO';
        lHours = 'Hours';
        lTotalHours = 'Total Hours';
        lrate = 'Rate';
        lAmount = 'Amount';
        lDescription = 'Description';
        lQuantity = 'Quantity';
    }

I have this in the `OnAfterGetRecord()` trigger:

                //Set report language
                CurrReport.Language := Language.GetLanguageID(CustomerInfo."Language Code");

Debugging says the language is "FRA", which is my target here. I have a file generated with Nab AL Tool named "BCTest.g.fr-CA.xlf" and that contains the following (Part of it only:

      [...]
      <file datatype="xml" source-language="en-US" target-language="fr-CA" original="BCTest.g.xlf">
        <body>
          <group id="body">
            <trans-unit id="Report 2763558668 - Property 2879900210" size-unit="char" translate="yes" xml:space="preserve">
              <source>Sales - Invoice FX</source>
              <target>Ventes - Facture FX</target>
              <note from="Developer" annotates="general" priority="2"></note>
              <note from="NAB AL Tool Refresh Xlf" annotates="general" priority="3">New translation.</note>
              <note from="Xliff Generator" annotates="general" priority="3">Report DevInvoiceFX - Property Caption</note>
            </trans-unit>
            <trans-unit id="Report 2763558668 - NamedType 2491107794" size-unit="char" translate="yes" xml:space="preserve">
              <source>You must specify one or more filters to avoid accidently printing all documents.</source>
              <target>[NAB: SUGGESTION]Vous devez spécifier un ou plusieurs filtres pour éviter d'imprimer accidentellement tous les documents.</target>
              <note from="Developer" annotates="general" priority="2"></note>
              <note from="NAB AL Tool Refresh Xlf" annotates="general" priority="3">Suggested translation inserted.</note>
              <note from="Xliff Generator" annotates="general" priority="3">Report DevInvoiceFX - NamedType NoFilterSetErr</note>
            </trans-unit>
            [...]
            <trans-unit id="Report 2763558668 - ReportLabel 3025740591" size-unit="char" translate="yes" xml:space="preserve">
              <source>INVOICE</source>
              <target>FACTURE</target>
              <note from="Developer" annotates="general" priority="2"></note>
              <note from="NAB AL Tool Refresh Xlf" annotates="general" priority="3">Suggested translation inserted.</note>
              <note from="Xliff Generator" annotates="general" priority="3">Report DevInvoiceFX - ReportLabel lInvoice</note>
            </trans-unit>

original .g file:

          [...]
          <file datatype="xml" source-language="en-US" target-language="en-US" original="BCTest">
            <body>
              <group id="body">
                <trans-unit id="Report 2763558668 - Property 2879900210" size-unit="char" translate="yes" xml:space="preserve">
                  <source>Sales - Invoice FX</source>
                  <note from="Developer" annotates="general" priority="2"></note>
                  <note from="Xliff Generator" annotates="general" priority="3">Report DevInvoiceFX - Property Caption</note>
                </trans-unit>
                <trans-unit id="Report 2763558668 - NamedType 2491107794" size-unit="char" translate="yes" xml:space="preserve">
                  <source>You must specify one or more filters to avoid accidently printing all documents.</source>
                  <note from="Developer" annotates="general" priority="2"></note>
                  <note from="Xliff Generator" annotates="general" priority="3">Report DevInvoiceFX - NamedType NoFilterSetErr</note>
                </trans-unit>
                [...]
              <trans-unit id="Report 2763558668 - ReportLabel 3025740591" size-unit="char" translate="yes" xml:space="preserve">
                <source>INVOICE</source>
                <note from="Developer" annotates="general" priority="2"></note>
                <note from="Xliff Generator" annotates="general" priority="3">Report DevInvoiceFX - ReportLabel lInvoice</note>
              </trans-unit>

And part of the actual result (to make the above make sense) when I run the report, which is a custom invoice:

The Report (invoice) itself is behaving as I described it. I added a few debugging field to ensure that the language set was the right one. My interface is set in English (Canadian one) and the customer is in fact set to French Canadian.

- The Title is not translated (Which reside in labels as shown above)
- The test variable Label is translated correctly ( I just used an error message I already had)
![image](https://user-images.githubusercontent.com/36481532/152596854-fcf57c5f-83da-47ca-a992-958c777c023c.png)

and for good measure, I checked that the language code I got was in fact the one for fr-CA (like my xlf file says)
![image](https://user-images.githubusercontent.com/36481532/152597440-9b53f047-8d14-4704-9554-32cd08f660d1.png)

Big issue (well imo) is that the second method requires every single label to have a column associated with it, and hence need to be part of the dataset. So when used in the RDL report, it is used with "First" keyword. That method doesn't make any sense to me.

What am I doing wrong here or is that by design? What's going on in the background?

EDIT:
Changing my interface language to French Canadian DOES translate the labels, which is NOT the wanted behavior. If I set the report language, I expect the report to be translated to this.
![image](https://user-images.githubusercontent.com/36481532/152598139-976dd326-dd52-4bac-9eb8-28ac80a71f35.png)

**Comment by thloke** [comment] 2022-02-08 04:16
I just realised that this is the duplicate of the updated issue. I'm going to close as a duplicate of #6917 which has been re-opened and accepted since there's more discussion there.

**Closed by thloke** 2022-02-08 04:16 UTC
