### ISSUE TITLE
Unable to publish - index error

### ISSUE THREAD

**Issue by NavBitsAndBytes** [Microsoft/AL#185] opened 2017-05-08 19:23 UTC
When I try and publish my extension I get the following error. The NAVX package is created fine but won't publish. I can "sometimes" fix this by removing objects from the extension folder, publishing (via F5) and then putting back the objects, but it is not any specific object that causes this.

```
[2017-05-08 15:21:18.32] Publishing package to http://localhost:7049/navision_main/dev/apps?tenant=default
[2017-05-08 15:21:30.68] Error: The request failed with code 500, reason: Index was out of range. Must be non-negative and less than the size of the collection.  Parameter name: index
```

**Comment by esbenk** [comment] 2017-05-08 19:26
Please look in the event log on the machine. There should be an error with a stack-trace from the NAV server from somewhere between the two timestamps. That will help us diagnose the problem.

**Comment by NavBitsAndBytes** [comment] 2017-05-08 19:37
Here's the a stack trace. An additional note is that manually I can publish the NAVX, but I get the same error when I try and do the installation of the extension manually.

```
Server instance: Navision_main
Category: Extensions
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 50fd5776-e67b-4374-b299-2d3e4591d1fd
ServerActivityId: 23028370-49c8-4958-9067-6af887374f84
EventTime: 05/08/2017 19:21:30
Message <ii>(ArgumentOutOfRangeException): <ii>Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
ExceptionStackTrace:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaTable.AssignFromMetaTable(MetaTable metaTable, Boolean databaseConvertedFromNav2013, Boolean isAppArchiveTable)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaTable.LoadMetadata()
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaApplicationObject.Populate()
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.InitializeAppGroupNewObject(NavAppGroup appGroup, NavAppGroupObjectMetadataSummary newObjectSummary)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.InitializeNewAppObjectsExceptQueries(NavAppGroup appGroup, PerformanceLog perfLog, IReadOnlyList`1 newObjectsFromApps)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.InitializeAppGroup(NavAppGroup appGroup)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.InitializeAppGroup(NavAppGroup appGroup)
   at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppGroupUpdater.PrepareAppGroup(NavAppGroup group, String activityId, PerformanceLog performanceLog)
   at Microsoft.Dynamics.Nav.Runtime.NavManagementTasks.PrepareAllAppGroupsForInstallChain(NavAppInstallPreCheckHelper precheckResult, String activityId, PerformanceLog outerPerfLog)
   at Microsoft.Dynamics.Nav.Runtime.NavManagementTasks.InternalInstallNavApp(NavAppInstallPreCheckHelper precheckResult, String name, NavTenant tenant, Boolean doNotLoadData, String activityId, PerformanceLog outerPerfLog)
   at Microsoft.Dynamics.Nav.Runtime.NavManagementTasks.InstallNavApp(InstallNavAppArguments installNavAppArguments)
CallerStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.NavManagementTasks.InstallNavApp(InstallNavAppArguments installNavAppArguments)
   at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppDiagnosticSession.<>c__DisplayClass1_0`1.<SendTraceTagOnFailure>b__0()
   at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppDiagnosticSession.SendTraceTagOnFailure(Action operation, String additionalInfo, String callerName)
   at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppDiagnosticSession.SendTraceTagOnFailure[T](Func`1 operation, String additionalInfo, String callerName)
   at Microsoft.Dynamics.Nav.Service.Dev.DevService.<>c__DisplayClass4_0.<PublishAndInstallExtension>b__0()
   at Microsoft.Dynamics.Nav.Service.Dev.DevService.PublishAndInstallExtension(NavSession session, Stream packageStream, PerformanceLog performanceLog)
   at Microsoft.Dynamics.Nav.Service.Dev.Web.Controllers.AppsController.<PublishAndInstall>d__0.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at Microsoft.Dynamics.Nav.Runtime.NavSynchronizationContext.<>c__DisplayClass1_0.<ClearThreadLocalStorageDelegate>b__0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

</ii></ii>
ProcessId: 3360
Tag: 00000BG
ThreadId: 9
```

**Comment by esbenk** [comment] 2017-05-08 19:39
Thanks. We will investigate the problem.

**Comment by markbrummel** [comment] 2017-05-20 09:02
Any updates on this one? I keep getting the same error.

Thanks.

**Comment by waldo1001** [comment] 2017-05-22 09:40
I remember to have had this error when I had a page extension with a same ID of a page, or a table extension with the same ID of a page.  Seems the id's of a table and a table extension should not conflict..

![image](https://cloud.githubusercontent.com/assets/12088142/26302079/629d46c2-3ee3-11e7-97d9-db0aceecb6dd.png)

**Comment by markbrummel** [comment] 2017-05-22 16:57
My bad.

I had corrected the double numbers and then created a new table that had an overlapping number with an extension.

So the problem is bigger than just having a table extension with the same number as its table. It also occurs when the table extension has the same number as any existing table.

I really hope this is fixed in the next update.

Thanks Waldo for your suggestion.

**Comment by StanislawStempin** [comment] 2017-05-23 19:18
I cannot reproduce the problem on the latest builds but we are still investigating the root cause.

**Comment by StanislawStempin** [comment] 2017-05-23 19:34
We believe the root cause to be the same as #174 and that it is fixed in the next update.

**Closed** 2017-06-20 07:45 UTC
Labels: bug, delivered
