### ISSUE TITLE
Suggestion: drop ID for pagecustomization objects

### ISSUE THREAD

**Issue by vjekob** [Microsoft/AL#643] opened 2017-09-07 11:36 UTC
I believe page customization objects should not have IDs at all.

Page customizations are on the same level with profile objects, and since profile objects don't use IDs, neither should page customizations.

When delivering profiles, you can expect people to customize massive amounts of pages across the standard application. You could easily exceed the allotted extension object range with page customizations.

**Comment by DominikDitoIvosevic** [comment] 2017-09-07 11:37
Duplicate of #642

**Comment by vjekob** [comment] 2017-09-07 11:39
Great :) Glad that you made that decision already.

**Closed** 2017-09-07 12:53 UTC
Labels: duplicate
