### ISSUE TITLE
"Syntax error, ':' expected" when pasting variable declaration from global to local scope

### ISSUE THREAD

**Issue by dzzzb** [microsoft/AL#6276] opened 2020-11-03 15:17 UTC
**Describe the bug**
An error is thrown when it shouldn't be.

**To Reproduce**
Steps and to reproduce the behavior:

1. (Be using the `vim` keybindings, in case that matters...)
2. Have a `Record` or `Integer` or whatever else declared in the global `var` scope
3. Cut and paste it from globals to between the function's `local` and `begin` lines
4. Add the missing `var` on the line above where you just pasted
5. See the result in the Screenshots.
6. Have to edit the line in someway, e.g. replace one char with itself, to clear the error.

**Expected behavior**
No error, of course, because the final code that gives the error is valid, yet VS Code doesn't realise it, until I kick it into realising by making some no-op change.

This is a real waste of time when refactoring to remove global variables, and clogs up the problems tab with false errors, distracting from the real ones I'm trying to fix!

**Screenshots**
![image](https://user-images.githubusercontent.com/63455896/98003899-347a1900-1de7-11eb-9383-19a5bf506d29.png)
![image](https://user-images.githubusercontent.com/63455896/98003933-3d6aea80-1de7-11eb-8de5-3d8e71ade6d8.png)

**5. Versions:**
 - AL Language: 6.1.359074

**Comment by dtkb** [comment] 2021-06-15 14:40
still happens (step #4 is key; if a `var` is already at the destination, the error does not occur)

**Comment by qutreson** [comment] 2023-11-28 13:35
@dzzzb - Thank you for reporting this issue, however I was not able to reproduce it anymore. I followed the repro steps and tried to first move the variable and then the var keyword. After adding the variable declaration (without var) some diagnostics are reported, but as soon as I add the var keyword, the diagnostics disappear:
![Github6276-2](https://github.com/microsoft/AL/assets/31541422/08eb1926-11f4-40ae-9938-31e52ca256fe)

Same if I copy the variable declaration including the var:
![Github6276](https://github.com/microsoft/AL/assets/31541422/02b9c3ae-1e97-49cc-ac2f-657f7d6a299c)

Closing then this issue as no repro as it seems to have been fixed since it was logged. If you are still able to reproduce it, please log a new action with additional information on the repro steps and reference this issue.

**Closed by qutreson** 2023-11-28 13:35 UTC
Labels: bug, al-compiler-frontend
