### ISSUE TITLE
Create package failed with error: 'Unexpected value 'Property' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.SymbolKind''

### ISSUE THREAD

**Issue by eluchev** [Microsoft/AL#3756] opened 2018-09-17 13:12 UTC
I am building a small extension for D365 BC GB customer. I've received the following error message: 
 
Processing of message 'al/createPackage' failed with error: 'Unexpected value 'Property' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.SymbolKind''

Attached stack trace file.
Attached my solution file that causes the problem, I've narrowed the problem down to line no. 407, when commented out and replaced with line 406 there are no issues with the compiler.

- AL Extension Version: 0.16.19969

- Server Version: GB Dynamics NAV 12.3 (23918)

![image](https://user-images.githubusercontent.com/32514346/45624756-293ac680-ba83-11e8-93a4-c937715813c4.png)
[StackTrace.txt](https://github.com/Microsoft/AL/files/2388653/StackTrace.txt)

[PagExt50004-Ext39.XPEIOM3 General Jounral.txt](https://github.com/Microsoft/AL/files/2388656/PagExt50004-Ext39.XPEIOM3.General.Jounral.txt)

**Comment by atoader** [comment] 2018-11-02 14:34
Hi @eluchev ! I am not able to reproduce the issue on the latest version of the extension. Are you still facing this issue?

**Comment by eluchev** [comment] 2018-11-05 15:20
Hi @atoader ! Following the October release I am now running on AL 2.0.48254 and I can still reproduce the issue. Attached my code - I've created a new AL project, targeting runtime 2.0 and I've reduced the pagextension to the minimum required to reproduce. If you need me to try on a different version of AL please let me know I am not yet registered on Collaborate so I normally don't have access to daily builds. 
[HelloWorld.txt](https://github.com/Microsoft/AL/files/2549268/HelloWorld.txt)

**Comment by atoader** [comment] 2018-11-06 13:08
Hi @eluchev ! Thank you very much for the repro! I took your code and added it to an extension.
```
pageextension 50104 "XPEIOM3 General Journal" extends "General Journal"
{
    layout
    {
    }

    actions
    {
        // Add changes to page actions here
        addlast("F&unctions")
        {
            action(TestAction)
            {
                ApplicationArea = All;
                Caption = 'Test Function';
                Image = CopyFixedAssets;
                ToolTip = 'Test Function';

                trigger OnAction()
                var

                    GenJBatch: Record "Gen. Journal Batch";
                    BAccount: Record "Bank Account";

                begin
                    GenJBatch.Init();

                    GenJBatch.Name := StrSubstNo('BACS%1', BAccount."Currency Code"); // This is ok
                    GenJBatch.Validate(Name, StrSubstNo('BACS%1', BAccount."Currency Code")); //This doesn't compile
                    GenJBatch.Validate(Name, 'TEST'); //This doesn't compile
                end;

            }
        }
    }
}
```

It compiles successfully, publishes, and runs without any issues. It looks like this has been fixed in master.  
Just to double check: Are you getting the error when building the package from VSCode using Ctrl+Shift+B?

**Comment by atoader** [comment] 2018-11-12 07:40
I will assume that this problem does not reproduce anymore and close this issue. Feel free to reopen the issue and add steps to reproduce the problem on the latest build.

**Closed by atoader** 2018-11-12 07:40 UTC
Labels: bug, in-progress
