### ISSUE TITLE
Reference to enum field does not exist in TableRelationship

### ISSUE THREAD

**Issue by TheDenSter** [microsoft/AL#4567] opened 2019-02-04 19:59 UTC
Two tables (table A and B). One new enum type field in table A. In table B I have a field with a table relationship to table A. The table relationship has a filter on the enum field. In the table relationship, the new field is listed by Intellisense, but when I select it, the filter value gets the red squigly line, and the problems window says the reference field does not exist.

**To Reproduce**
The enum: 
![image](https://user-images.githubusercontent.com/23434319/52233353-13843d00-287c-11e9-9318-1b1fbaabfbb7.png)

Table A:
![image](https://user-images.githubusercontent.com/23434319/52233388-2991fd80-287c-11e9-81e7-87d57fb8ca2e.png)

Table B with error:
![image](https://user-images.githubusercontent.com/23434319/52233409-3f072780-287c-11e9-900e-5434defc135b.png)

Note that I selected the field using Intellisense, so AL is aware of the field.

 - AL Langauge: 2.1.79379
 - Business Central: GB Dynamics NAV 13.2 (26556)

Related to  #4313

**Comment by TheDenSter** [comment] 2019-02-05 19:33
Using the filter option does result in showing only the proper values from TableA, but now I get weird validation results. Obviously I have different tables in my actual development project but this is what I am getting (we added an enum field to the Dimension Value table and filtering the tablerelationship on a particular value that I have not been able to make work):
![image](https://user-images.githubusercontent.com/23434319/52298948-7c81b880-2941-11e9-9603-4ed2115a7dad.png)
So even though the field is implemented as an enum field, the validation seems to try to find an option string. IMO using the index of the enum as a filter is dead wrong, it should be possible to use the value itself. Also there is definitely something not right with the enum implementation if the validation is still trying to find an optionstring.

**Comment by nareshbandariD365** [comment] 2019-02-06 06:21
Hi @TheDenSter , 
I created a simple project "Enum" in that I created one Enum object and two tables to test Enum as shown below:

![image](https://user-images.githubusercontent.com/43364621/52323052-8a970e00-2a01-11e9-9308-f732918f57a4.png)
![image](https://user-images.githubusercontent.com/43364621/52323136-e2357980-2a01-11e9-86c2-9c794bd41c14.png)
![image](https://user-images.githubusercontent.com/43364621/52323260-68ea5680-2a02-11e9-8c51-18149a47052b.png)

Test Results:
![image](https://user-images.githubusercontent.com/43364621/52323582-8f5cc180-2a03-11e9-94b3-e15ebc70016d.png)
![image](https://user-images.githubusercontent.com/43364621/52323664-e6629680-2a03-11e9-82d1-1495ba23462f.png)
![image](https://user-images.githubusercontent.com/43364621/52323670-ea8eb400-2a03-11e9-82bc-c867c7e4e56b.png)
![image](https://user-images.githubusercontent.com/43364621/52323672-ee223b00-2a03-11e9-99e7-8acbe2d913c1.png)
![image](https://user-images.githubusercontent.com/43364621/52323679-f11d2b80-2a03-11e9-8525-946d12ae60b5.png)


@TheDenSter ,It seems good, I didn't face any difficulty with Enum here, try it in this way if it will not resolve your issue, post us your code to reproduce the issue.


Versions:

AL Language: 2.1.79379
Business Central: 13.0.27183

**Comment by esbenk** [comment] 2019-02-06 12:55
@TheDenSter I have you something very similar on the latest bcinsider without any issues. We that the 13 have had some issues around using extended enum fields in TableRelations, but they should have been fixed in the latest CU.

I'm unsure about the validation error. Can you supply a repro? We would definitely like to have this fixed.

**Comment by esbenk** [comment] 2019-02-06 14:49
I have done some digging. The fix for using extended values is not backported to the current CU only in the upcoming master for the Spring release. 
We will backport the fix an make available in the next CU as well.

**Comment by TheDenSter** [comment] 2019-02-06 22:34
Well slap me with a trout.... straight out of the Twilight Zone... I have two containers, both created from the same sandbox:gb Docker image. One is for my full on development project (which I obviously can't share the details about in here) and another is to repro this issue. I copied the enum (changed the values a little bit though) and the other objects. In my full dev container I am getting the weird error message, and in the repro AL workspace (see attached) everything works as expected.
[EnumTableRelation.zip](https://github.com/Microsoft/AL/files/2838538/EnumTableRelation.zip)

The only thing that is different in my full development container is that there is a ton of additional stuff in there. This field and enum is identical. By the way, with the tablerelationship working, I would just remove the validation code, but since that is not working in my environment, I have to make sure the user picks the right value.

**Comment by qutreson** [comment] 2019-04-17 12:42
Hi @TheDenSter are you still facing this issue? We believe it should have been fixed by now.

**Comment by TheDenSter** [comment] 2019-04-18 09:59
This is still causing the same error. I still can't reproduce it in a standard BCsandbox, but it is definitely not working right in this development database. We've worked around it with the validation code, but this should really work through the table relationship alone.

The tablerelationship seems to work using the literal value and the FILTER (so where "Enum Field" = FILTER(1)). The value 1 represents an enum value 'inventory'. The dropdown properly filters, but when I select one of the values I get this error:
![image](https://user-images.githubusercontent.com/23434319/56353276-51cd9f00-61d1-11e9-918e-4be08873fb71.png)
Note that the 'Spend Type' field is the enum field, and the index value '1' represents the value 'Inventory'

**Comment by mariafores** [comment] 2019-06-20 07:53
Hi,
this seems to still happen in Spring Release.

The tablerelation can be defined with const(value) or with filter(number), that's working ok, but I've come to the same problem as @TheDenSter in a Spring Release sandbox container. Creating the same example as @nareshbandariD365 posted, BUT adding captions to the enum, the thing is that when the caption doesn't exactly match the enum value, you get the validation error:

![image](https://user-images.githubusercontent.com/44401427/59830635-5aad2f00-9340-11e9-8e92-09a23eaf0327.png)

![image](https://user-images.githubusercontent.com/44401427/59830751-8fb98180-9340-11e9-815a-c36285052f72.png)

That's why it also happens in @TheDenSter code, because he said that the option value is INV, but the caption is Inventory.

That is absolutely intolerable, given that it ALWAYS happens if you are not working in English, as the caption never matches the enum value.
Any suggestions on how we can solve/workaround this?

**Comment by esbenk** [comment] 2019-06-21 09:05
This fixed and will be available in a upcoming CU.

**Closed by esbenk** 2019-06-21 09:05 UTC
Labels: bug, input-needed

**Comment by rtwcolumbus** [comment] 2019-08-23 13:34
Shouldn't be closed until it is actually shipped - I will go look into the CUs to see if its been fixed yet
