### ISSUE TITLE
Processing of message 'al/downloadSymbols' failed with error: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by ElmarFV** [microsoft/AL#5843] opened 2020-04-27 17:59 UTC
**Describe the bug**
When trying to debug a cloud sandbox I would get a message stating "Error: An internal error has occurred". I then tried to Download Symbols for the same tenant and get this huge message.:
"[Error - 1:48:33 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/downloadSymbols' failed with error: 'Object reference not set to an instance of an object.'
Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dynamics.Nav.Deployment.Authentication.AccessTokenManager.TryGetAccessToken(String authority, String resourceId, String clientId, String redirectUrl) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\Authentication\AccessTokenManager.cs:line 103
   at Microsoft.Dynamics.Nav.Deployment.Authentication.AccessTokenManager.GetAccessToken(String authority, String resourceId, String clientId, String redirectUrl) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\Authentication\AccessTokenManager.cs:line 44
   at Microsoft.Dynamics.Nav.Deployment.Http.CloudHttpClientFactory.ObtainAccessToken(ConnectionOptions connectionOptions, IEmitLogger logger) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\Http\CloudHttpClientFactory.cs:line 174
   at Microsoft.Dynamics.Nav.Deployment.Http.CloudHttpClientFactory.GetTenantToken(ConnectionOptions connectionOptions, IEmitLogger logger) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\Http\CloudHttpClientFactory.cs:line 95
   at Microsoft.Dynamics.Nav.Deployment.Http.CloudHttpClientFactory.Create(ConnectionOptions connectionOptions, IEmitLogger logger, Boolean skipRequestLogging) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\Http\CloudHttpClientFactory.cs:line 71
   at Microsoft.Dynamics.Nav.Deployment.ApiClients.PackagesApiClient.DownloadPackages(ImmutableArray`1 references, String targetDir) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\ApiClients\PackagesApiClient.cs:line 49
   at Microsoft.Dynamics.Nav.Deployment.ReferenceDownloader.NavServerPackageDownloader.DownloadPackages(ImmutableArray`1 packages, String targetDirectory) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\ReferenceDownloader\NavServerPackageDownloader.cs:line 32
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.DownloadSymbolsRequestHandler.DownloadFiles(DownloadSymbolsRequest request, String cacheDirectory, ImmutableArray`1 referencesToDownload) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\DownloadSymbolsRequestHandler.cs:line 82
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.DownloadSymbolsRequestHandler.ProcessRequestAsync(DownloadSymbolsRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\DownloadSymbolsRequestHandler.cs:line 64
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`1.HandleAsync(T request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\NavServerRequestHandler.cs:line 38
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 54
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80"

**To Reproduce**
Steps and to reproduce the behavior:
1. Go to Visual Studio
2. Create a new project
3. Update Launch.json to the following...

"{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Sandbox",
            "sandboxName": "Sandbox",
            "tenant": "01093d2c-cb20-40d7-b7d9-46a8c0c37165",
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true,
            "launchBrowser": true,
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true
        }
    ]
}
"
4. do AL: Download Symbols.

``` AL Code to reproduce the issue ```
No AL Code needed.

**Expected behavior**
When doing AL: Download Symbols, should get a message stating "All reference symbols have been downloaded."

**Screenshots**

**5. Versions:**

 - AL Language: 5.0.254558

 - Business Central:16.0.11240.11946

**Comment by thpeder** [comment] 2020-04-28 12:02
Duplicate of #5829

**Closed by thpeder** 2020-04-28 12:02 UTC
