### ISSUE TITLE
Image "Filter" on Action Group Compiler Error

### ISSUE THREAD

**Issue by Walwode** [microsoft/AL#5273] opened 2019-09-12 11:44 UTC
**Describe the bug**
I'm able to add an image (icon) to an action group. (Sadly, those images are not used by List Pages for top level action groups.) If i use the image "Filter", the VSC code check doesn't give an error, but the compiler does. As well, it says "warning" but the compilation is aborted. It works fine for other icons, such as "Status".

**Expected behavior**
VSC code check already marks the line red. The image name is missing in the warning, i assume (2 spaces between "image" and "is" in the screenshot).

**Screenshots**
![image](https://user-images.githubusercontent.com/33229214/64781423-1a3a0780-d563-11e9-8cbb-aea3aa754aff.png)

**Versions:**
 - AL Language: 4.0.170493
 - Business Central: Version: Platform 14.0.36027.0 + Application 36050 (DE Business Central 14.5)

**Comment by atoader** [comment] 2019-09-17 09:59
Does the compilation pass if you remove this property? You are using the latest VSIX with an older runtime, are you using the runtime property? https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files

**Comment by Walwode** [comment] 2019-09-25 15:33
yes, if i remove the property, it compiled (and worked). Correct, i was using the latest VSIX, but i'm still developing an 14.x app (because of OnPremise projects). Therefore i have runtime "3.2" in my app settings.

**Comment by qutreson** [comment] 2019-10-07 07:23
Hi @Walwode, I can reproduce the issue on the version you are mentioning, but not in our latest master or when using the extension from the marketplace.

The actual error is because the image name `filter` (which is also a keyword in AL) cannot be parsed properly on the version of the compiler used in your server. This results in an Error diagnostic which makes your publish fail.

![image](https://user-images.githubusercontent.com/31541422/66292136-d4fbc200-e8e3-11e9-8c3b-551b8f1348a4.png)

Can you try using `Image = "Filter";` instead of `Image = Filter;`? This is the workaround for the version of BC that you are using.

**Comment by qutreson** [comment] 2019-10-07 07:27
Digging into our commit history, it seems that this issue was originally reported here #4798

**Comment by qutreson** [comment] 2019-10-07 07:29
@Walwode, closing this issue as it is now fixed in our latest compiler previews and because a workaround exists in the version you are targeting.

**Closed by qutreson** 2019-10-07 07:29 UTC
