### ISSUE TITLE
Report Preview isn't working using Report.Execute method in BC16

### ISSUE THREAD

**Issue by faaizahmed1995** [microsoft/AL#6332] opened 2020-12-01 12:28 UTC
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

**Comment by faaizahmed1995** [comment] 2020-12-01 12:28
Describe the bug
We have upgraded an existing AL code from BC15 to BC16 (both on prem) and noticed that the behaviour of Report.Execute method has changed. Previously it opened a report in preview mode for the user for further action. Now it automatically downloads a PDF without displaying the preview mode.

To Reproduce
Steps and to reproduce the behaviour:
For example, create a new action in Sales Order page that runs a report (via variable) using Execute method. And run the action to see the system behaviour.

AL Code to reproduce the issue
//Below is an example. Report and record variables should be replaced with different.

            action(JobPrintPreview)
            {
                ApplicationArea = Basic;
                Caption = 'Job Print Preview';
                trigger OnAction()
                var
                    JobCardRep: Report "My Report";
                    RecRef: RecordRef;
                    ServHeader: Record "Service Header";
                begin
                    ServHeader.Reset;
                    ServHeader.SetRange("Document Type", "Document Type");
                    ServHeader.SetRange("No.", "No.");
                    RecRef.GetTable(ServHeader);

                    JobCardRep.Execute('', RecRef);
                end;
            }

**Comment by thpeder** [comment] 2020-12-01 14:14
Duplicate of #6333

**Closed by thpeder** 2020-12-01 14:14 UTC
Labels: customer-support
