### ISSUE TITLE
Cannot Publish Extension to Cloud Sandbox

### ISSUE THREAD

**Issue by Tonygithub17** [Microsoft/AL#4739] opened 2019-03-19 06:46 UTC
Recently when i try to publish cloud sandbox using Visual Studio Code hit the follow message.

![image](https://user-images.githubusercontent.com/34825577/54585722-d94eb380-4a55-11e9-953b-9fd162318d25.png)

**Comment by Kowa63** [comment] 2019-03-19 08:28
Sounds like the same issue here: https://github.com/Microsoft/AL/issues/4733

**Comment by tomasevicstefan** [comment] 2019-03-19 15:33
Are you using Docker environment for publishing extensions? It's the safest to install AL extension from latest docker image (container), not from VS marketplace

**Comment by Tonygithub17** [comment] 2019-03-20 00:33
> container

Hi Tomasevicstefan,

Already try both way but also fail to publish the to Cloud Sandbox. I notice that cloud platform on build 13.4 but my latest docker version only 13.3.

**Comment by qutreson** [comment] 2019-03-22 09:48
Hi @Tonygithub17, this looks like a duplicate of #4733. It should be fixed by now if you download the latest AL extension from the VS Code market place.

**Closed by qutreson** 2019-03-22 09:48 UTC
