### ISSUE TITLE
CaptionClass - tableextensions

### ISSUE THREAD

**Issue by kdldk** [Microsoft/AL#2680] opened 2018-06-21 09:45 UTC
Hi,
I have created a table extension, and try to use CaptionClass. I have created new field as well as modified NAV std-fields.

![image](https://user-images.githubusercontent.com/39760364/41711202-da234782-7547-11e8-81c4-2263d2e37f76.png)

I have created a Pageextension
![image](https://user-images.githubusercontent.com/39760364/41711319-262c6974-7548-11e8-9b16-7245e02857b4.png)

And the result is
![image](https://user-images.githubusercontent.com/39760364/41711349-3b07aeda-7548-11e8-8b71-92c04c530a00.png)

If You have fixed it - pls backport it to OnPrem

Using NAV2018-CU6 - AL 0.12.17091

**Comment by DominikDitoIvosevic** [comment] 2018-06-25 08:32
I believe this is a duplicate of #1304 . I'll look into backporting it

**Closed** 2018-07-30 10:41 UTC
Labels: bug
