### ISSUE TITLE
Fatal Error when executing existing test routines in the Web Client (Windows Client works)

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/AL#4823] opened 2019-04-03 09:08 UTC
**Describe the bug**
The execution of existing test routines currently does not work correctly in the Web Client. In the Windows Client, however, the execution works without problems. The tests are also run here without errors. But the Web Client simply crashes. 

The following error appears in the Event Log:
```
Server instance: NAV
Category: Runtime
ClientSessionId: 6979508a-03b3-4e40-b5bf-96dc51e7ff2d
ClientActivityId: 075d214e-7a6f-4cb4-bc89-60d71a72ec31
ServerSessionUniqueId: d6a18a24-6f0a-4a48-b60a-df98ce1929ab
ServerActivityId: 779398f0-0990-4eb3-934b-cf6b4c031275
EventTime: 04/03/2019 08:55:30
Message (NavNSConcurrencyException): RootException: NavNSConcurrencyException
An internal error has occurred. Multiple concurrent calls have been issued to the server from 
this client.
ExceptionStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.SessionAccessLock.BeginCallStackExecution()
   at Microsoft.Dynamics.Nav.Service.ServiceCallStack.Push()
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PushPopCombinator(ServiceOperation 
innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& 
outputs)
CallerStackTrace:
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PushPopCombinator(ServiceOperation 
innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& 
outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass27_1.<Combine>b__1(N
SServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationTracer.TraceScopeCombinator(Category 
telemetryCategory, ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase 
syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass27_1.<Combine>b__1(N
SServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass9_0.<PerformanceCoun
terCombinator>b__0()
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PerformanceCounterCombinator(ServiceO
peration innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, 
Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass27_1.<Combine>b__1(N
SServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.InitClientTelemetryIdsCombinator(Serv
iceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] 
inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass27_1.<Combine>b__1(N
SServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TlsClearCombinator(ServiceOperation 
innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& 
outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass27_1.<Combine>b__1(N
SServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Invoke(Object instance, Object[] 
inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)
   at System.ServiceModel.Dispatcher.MessageRpc.Wrapper.Resume(Boolean& alreadyResumedNoLock)
   at System.ServiceModel.Dispatcher.ThreadBehavior.ResumeProcessing(IResumeMessageRpc resume)
   at Microsoft.Dynamics.Nav.Runtime.NavSynchronizationContext.<>c__DisplayClass1_0.<ClearThreadLo
calStorageDelegate>b__0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, 
ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback 
callback, Object state, Boolean preserveSyncCtx)
   at 
System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
**Expected behavior**
The execution of the tests must be equally successful in both the Web Client and the Windows Client.

**Screenshots**
![image](https://user-images.githubusercontent.com/22373356/55466680-f495f300-55ff-11e9-86b5-ba2038e738e8.png)

**Versions:**

 - AL Langauge: 3.0.106655

 - Business Central: 14.0.29537.0-DE

**Comment by AskeHolst** [comment] 2019-04-03 14:40
I have the same problem but with a batch posting job.
The process will not stop running when the error is shown though, I can keep stepping through it with the debugger. So it seems it is the web-server part that fails first. Then minutes later the processing will stop and rollback will happen. 

I can recreate it on 1904:rtm (both onprem and bcsandbox) and also on the latest insider bcsandbox-master. 
I cannot recreate it on a online sandbox (14.0.29537.29654) hosted by Microsoft.

**Comment by atoader** [comment] 2019-04-04 16:46
Hi! Can you please provide repro steps? What tests are you running? How are you running them? Are these standard tests or your own tests?

**Comment by FSharpCSharp** [comment] 2019-04-05 05:30
As you have been able to read from @AskeHolst , the specified behavior also occurs with batch posting. So I wonder why you're asking how to recreate it when @AskeHolst has already described it? It's the same error that only occurs in the web client. I can't say what this behavior will cause in the test routines, so I can't report any steps because it doesn't work. I assume, however, that it also affects the standard tests, because they also work in this way.

**Comment by AskeHolst** [comment] 2019-04-05 06:32
In my case it happens about a minute into a job creating an evaluation setup including a creating and updating records and posting documents on top of a Cronus database. 
As the debugger never breaks it is very hard to pinpoint the exact spot. The closest I get (by commenting out code) is that it might be around batch posting pf Job Ledger Entries where we have a lot of subscribers in place. 
It is very hard to isolate as this is happening in an app calling into a library app with 800+ objects. Also due to documents being posted there are commits which requires a fresh company for each run. 
If run the same postings one by one there is no problem. 

After dozens of failed runs I got one run through yesterday on a bcsandbox-master:14.0.29651.0-se so it seems to not consistently fail.

**Comment by FSharpCSharp** [comment] 2019-04-05 06:37
I've done some research now. It also affects all standard test routines. Luc van Vugt has already described this in detail in Yammer. [Here](https://www.yammer.com/dynamicsnavdev/threads/89109648351232) is his message.

**Comment by ekawatani** [comment] 2019-05-28 09:24
Hi, could you provide us repro steps that we can follow to reproduce this issue on our end? We really need to know what those tests do, and how exactly the tests are executed.

**Comment by atoader** [comment] 2019-06-24 07:32
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Closed by atoader** 2019-06-24 07:32 UTC
Labels: cross-team-investigate
