### ISSUE TITLE
There was an Error in Rule "Rule0017" of type "InvalidCastException" 

### ISSUE THREAD

**Issue by dsaveyn** [microsoft/AL#6963] opened 2022-03-02 10:47 UTC
Please include the following with each issue:

**1. Describe the bug**
When accessing a Text using an Indexer and assigning it to another Text using the same Indexer, the CodeAnalyser throws the error "There was an Error in Rule "Rule0017" of type "InvalidCastException" "

**2. To Reproduce**
See simulation in the attachments:

![image](https://user-images.githubusercontent.com/92365904/156346090-b5deb2de-513a-4e9f-a40b-d4c48f25f28f.png)

``` AL
pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var
        Text1: Text;
        Text2: Text;
        i: Integer;
    begin
        Text1 := 'A';
        Text2 := 'B';
        Text2[1] := Text1[1];
    end;
}
```

**3. Expected behavior**
No Error nor Warning should be thrown.

**4. Actual behavior**
The CodeAnalyser throws an Error

**5. Versions:**

- AL Language:

  ![image](https://user-images.githubusercontent.com/92365904/156346496-5067b574-a659-4916-a1bf-da77083b6870.png)

- Visual Studio Code:

  ![image](https://user-images.githubusercontent.com/92365904/156346723-cdf8a347-824a-4cae-af79-be23cdb972be.png)

- Business Central:

  ![image](https://user-images.githubusercontent.com/92365904/156346801-4fca2d66-487f-4be6-8af1-30b5442c3797.png)

- List of Visual Studio Code extensions that you have installed:

  - AL Language

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem
[SimulateInvalidCastException.zip](https://github.com/microsoft/AL/files/8168922/SimulateInvalidCastException.zip)

**Comment by sergiudina** [comment] 2022-03-17 08:54
Hi, @dsaveyn thank you for logging the issue, could you please share your settings.json file so we can see your AL settings?

**Comment by StefanMaron** [comment] 2022-03-21 10:48
The message came from the linter cop. See the linked issue https://github.com/StefanMaron/BusinessCentral.LinterCop/issues/179 for reference. 

The problem is resolved by now and the message should no longer show up.

This issue can be closed as well.

**Comment by dsaveyn** [comment] 2022-03-21 10:52
@StefanMaron Thanks!

**Closed** 2022-03-21 10:52 UTC
Labels: input-needed, static-code-analysis, accepted
