### ISSUE TITLE
Publish Errors not shown in VScode

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/AL#2367] opened 2018-05-27 07:57 UTC
With the May Update when I publish an App and Error occurs, VScode doesn't do anything after **Sending request to**:
**VScode-Output:**
```
Success: The package is created.
[2018-05-27 09:38:21.21] Publishing package to tenant 'default'
[2018-05-27 09:38:21.26] Sending request to https://bcsandbox.westeurope.cloudapp.azure.com:7049/NAV/dev/apps?tenant=default&SchemaUpdateMode=recreate
```
In the Event Log of the Service Tier, I get something to work with:
```
[..]
Message Unexpected event subscriber failure -- SubscriberType:CodeUnit; SubscriberId:20; TargetType:Table; TargetId:17; SubscriberCLRMethod:OnInsertGLEntry; SubscriberALName:OnInsertGLEntry; TargetMethod:OnAfterInsertEvent; Error:Value cannot be null.
Parameter name: element
[..]
```
Would be nice to get this same error message in VScode.

**Comment by qutreson** [comment] 2018-05-28 12:52
Hi @DanielGoehler, I think you are facing two unrelated issues here.

The first one is that the webclient does not open automatically after publishing the app in VS Code which seems to be a bug. We also experienced it, but we couldn't get a stable repro for it yet. A workaround is to try to re-publish many times until it succeeds.

The error you can see in the Event Log is a runtime error from the base app because one subscriber is missing the element name property (in C/AL). In AL, this is something we verify at compile time so you shouldn't get into this situation. As this is a runtime error, the AL extension does not know about it.

**Comment by pzentner** [comment] 2018-05-29 09:00
@qutreson I also have the issue that the webclient can't open after publishing the app in VS Code and therefore, I cannot debug. I can reproduce this every time I try to publish in the master:us (but also in other master images). 

I even used just AL:GO and then published the sample and am receiving the error after going with the latest master image. When I try to go back to a previous image (or also downgrade the AL extension to a previous build), it does not resolve the issue. So, this is a dead stop for debugging. Do you need this reported In a new issue?

**Comment by DanielGoehler** [comment] 2018-05-29 11:10
@qutreson On May Update (13.0.22267.0 DE), which I create from "Daily Builds - Developing for a future release of Dynamics 365 Business Central" as Azure VM, I get this problem repeatedly every time I hit F5.
When I change the Size of that VM from D2_v3 (2 CPUs and 8 GB RAM) to D4_v3 (4 CPUs and 16 GB RAM) I get a proper error message:
```
[2018-05-29 11:53:12.64] Publishing package to tenant 'default'
[2018-05-29 11:53:12.65] Sending request to https://sfcxthuxppfcupx.westeurope.cloudapp.azure.com:7049/NAV/dev/apps?tenant=default&SchemaUpdateMode=recreate
[2018-05-29 11:56:51.85] The request for path /NAV/dev/apps?tenant=default&SchemaUpdateMode=recreate failed with code 422. Reason: Value cannot be null.
Parameter name: element
```
It would be nice if instead of the publishing suddenly stops, I get an error if RAM is insufficient (see also #1632). Also it would be nice if the details of the error would be shown (Message Unexpected event subscriber failure -- SubscriberType:CodeUnit; SubscriberId:20; TargetType:Table; TargetId:17; SubscriberCLRMethod:OnInsertGLEntry; SubscriberALName:OnInsertGLEntry; TargetMethod:OnAfterInsertEvent; Error:Value cannot be null. Parameter name: element).

**Comment by AndreaAntolini** [comment] 2018-07-13 16:42
Hi all, have the same issue on my D365BC Trial sandbox.
When trying to load the .app file on the "production" tenant of the trial, i get a deployment error with this detail info:

`Deployment failed. Errors: App ID : <myAppID> Message : { The server "MS" was unable to process the request. The application will close. } - Job Id : 468330fa-ce95-4b8e-941e-053ae25f386c`

**Comment by StanislawStempin** [comment] 2018-08-03 14:30
This might be related to duplicate event subscriber names. If you're still facing this issue please try to rename your subscribers to ensure uniqueness.  Otherwise, we would need more specific repro to find the root cause.

**Comment by DanielGoehler** [comment] 2018-08-06 18:31
@StanislawStempin Would it be possible to see which event subscriber that are? I have so many in my converted ISV solution.

**Comment by StanislawStempin** [comment] 2018-10-10 21:35
Are you still encountering the issue on latest bcsandbox-master?  There were several issues fixed in this area and hopefully your scenario should work now.

**Closed** 2018-10-23 09:00 UTC
Labels: input-needed
