### ISSUE TITLE
Extend existing dataset of any report

### ISSUE THREAD

**Issue by worldofthenavcraft** [Microsoft/AL#4482] opened 2019-01-18 14:46 UTC
**Is your feature request related to a problem? Please describe.**
At this moment there is now way to add new field inside the existing report.  

**Describe the solution you'd like**
As a Business Central dev I would like:
1.	Extend existing dataset of any report (standard and own maded) as we do with pages and tables. 
2.	I would recommend split AL report object to dataset object and layout object
Eg: dataset Id MyExtension extends MyTargeDataset
{
    fields
    {
        // Add changes to datasset fields here
    }
    
    var
        myInt: Integer;
}
3.	After extending the dataset I would like to add new custom field to report layout with DEV tools or with business central report layout designer 

**Describe alternatives you've considered**
As a business Central dev I would like to set up dataset extensions:
1.	I would like to use Business Central and extend or add new datasets inside applications without any coding. More like the click and point.
2.	I would like to make those datasets also available to AL developer.
3.	After defining the dataset inside Business central I would like to add new custom field to report layout with DEV tools or with business central report layout designer 

**Additional context**
Sorry if it sounds like a dublicate!

**Comment by JohanStenberg100** [comment] 2019-01-23 09:20
Hi @worldofthenavcraft!

This is an interesting suggestion, I'll mark it as a suggestion and then we'll take a look when we have time. Thanks!

**Comment by gudrunleos** [comment] 2019-03-28 09:28
see Report extendibility #1452

**Comment by JohanStenberg100** [comment] 2019-04-01 11:59
Thanks @gudrunleos, I'll close this as a duplicate of #1452.

**Closed by JohanStenberg100** 2019-04-01 11:59 UTC
Labels: suggestion
