### ISSUE TITLE
Business Central: Error 'The type or method 'Open' cannot be used for 'Extension' development'

### ISSUE THREAD

**Issue by zeeahmed-16** [microsoft/AL#5402] opened 2019-10-29 09:57 UTC
I am trying to create a report to read csv file data and import it into a Business Central table.
When I a method 'Open' which is a method of 'File Management' codeunit, I am getting this error:

_The type or method 'Open' cannot be used for 'Extension' development_

Can anybody help me find out the code to import data into a table from a file using AL code.

**Comment by atoader** [comment] 2019-10-29 12:22
Hi! Have you used the search functionality on this repository to find similar issues such as https://github.com/Microsoft/AL/issues/4721 ?

**Comment by atoader** [comment] 2019-10-29 12:31
Duplicate of #4721

**Closed by atoader** 2019-10-29 12:31 UTC
