### ISSUE TITLE
The name of Record is not valid. The name of variables and parameters must be suffixed with the type or object name in app.json

### ISSUE THREAD

**Issue by CorpitalFDP** [microsoft/AL#6372] opened 2020-12-15 08:32 UTC
**Describe the bug**
Warning AA0022 in line 1 of app.json when a codeunit have the parameter TableNo

**To Reproduce**
use this settings.json:
{
    "al.enableCodeAnalysis": true,
    "al.codeAnalyzers": [
        "${CodeCop}",
        "${PerTenantExtensionCop}",
        "${UICop}"
    ]
}

``` AL Code to reproduce the issue ```
create this codeunit:
codeunit 50000 "Test AA0072"
{
    TableNo = "Customer";

    trigger OnRun()
    begin
    end;

}

**Expected behavior**
Not to get the warning

**Screenshots**
![image](https://user-images.githubusercontent.com/40599682/102189777-6e930c00-3eb7-11eb-8b3d-9becc0ffd1c7.png)

**5. Versions:**

 - AL Language: v6.1.381323

 - Business Central: 17.2.19367.19525

**Comment by PaulIvan** [comment] 2020-12-18 11:26
Thank your for reporting this issue. I am closing it as it looks like a duplicate of #6246. Feel free to contribute on the issue linked.

**Closed by PaulIvan** 2020-12-18 11:26 UTC
Labels: CodeCop, bug, static-code-analysis
