### ISSUE TITLE
Please let us have out With command back

### ISSUE THREAD

**Issue by peikba** [microsoft/AL#6250] opened 2020-10-24 13:12 UTC
I cannot think of a reason to deprecate the with command and force the rec. to all commands referring to the source table.
Is there a special reason for that?

**Comment by NKarolak** [comment] 2020-10-24 16:28
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-deprecating-with-statements-overview#the-explicit-with-statement

**Comment by NKarolak** [comment] 2020-10-26 08:26
The "why" is probably clearer here in the readme: https://github.com/microsoft/BCTech/tree/master/samples/WithOrWithout

**Comment by rdebath** [comment] 2020-10-26 10:31
That is not a good reason to stop `with` working.
The correct fix is to do the (at least part of) first stage of the compile when the `APP` file is  "compiled".
The normal way (if you can't go down to binary) is to compile to an intermediate language when building the "shared library".
For BC it would be sufficient for Microsoft to run their "Fix all the WITH statements" on the code that they put into the APP file.

Also raised: https://github.com/microsoft/BCTech/issues/45

**Comment by dtkb** [comment] 2020-10-26 12:38
surely a dupe of https://github.com/microsoft/AL/issues/5817 and links therein.

**Comment by PooyaKharamesh** [comment] 2020-10-27 14:33
Closing this issue since @esbenk discussed the topic here #5817 

/Pooya

**Closed by PooyaKharamesh** 2020-10-27 14:33 UTC

**Comment by rdebath** [comment] 2020-10-28 10:58
@PooyaKharamesh In that case do you have the missing response to nicolassaleron's suggestion?
Explicitly that some intermediate language be used in the APP file, implicitly that this language would be "AL without WITH and other problematic constructs".

NB: Other problematic constructs could probably include conditional compilation and error suppression.

**Comment by esbenk** [comment] 2020-10-28 11:08
We have no plans for implementing an intermediate language for AL.

**Comment by rdebath** [comment] 2020-10-28 11:57
@esbenk 
You already have implemented everything for it. 
You have implemented "AL without WITH".
You have implemented automatic translation from "with WITH" to "without WITH".
Your "source" in the app file is already different from the source in the project and has to be manually fixed if you "unzip" it. Nobody wants to use the "source" in the APP file! 
You provide distinct "source" and "app" files for the BaseApp and every other extension! 
**It is already an "intermediate language for AL".** 

All you're doing now is making two more dialects of the language at our end depending on if this instance is targeting SaaS or OnPrem.

So we'd probably have to forbid WITH OnPrem too or perhaps implement **your translation** as part of the SaaS build chain. The second will likely end up fragile and the first damages readability.
Remember WITH is not a feature that's nearly always bad (like goto) it's one that is only bad if badly abused or if the toolchain is actively broken. Even if it looks like it's being abused a simple "does it create a shadow" check at compile time prevents developer problems for working toolchains.
