### ISSUE TITLE
BC2021w1. Return record from table procedure

### ISSUE THREAD

**Issue by dkatson** [microsoft/AL#6529] opened 2021-03-15 09:56 UTC
**Describe the bug**
When i create a procedure on the table or tableextension and return the record this doesn't work 

**To Reproduce**

this returns empty record
`tableextension 50100 "PurchaseLineExt" extends "Purchase Line"
{
    procedure FindFirstRec(): Record "Purchase Line"
    begin 
        Rec.FindFirst();
    end;
}`

this returns first record
`tableextension 50100 "PurchaseLineExt" extends "Purchase Line"
{
    procedure FindFirstRec() PurchLine: Record "Purchase Line"
    begin 
        PurchLine.FindFirst();
    end;
}`

**Expected behavior**
Should return Rec

**Screenshots**

**5. Versions:**

 - AL Language: 
7.0.426055
 - Business Central:

**Comment by IamLerxx** [comment] 2021-03-15 10:29
Please clarify.
`
tableextension 50100 "PurchaseLineExt" extends "Purchase Line" { 
    procedure FindFirstRec(): Record "Purchase Line" 
    begin 
        Rec.FindFirst(); 
    end; 
}`

": Record "Purchase Line"" just says, that the return type of the function is a Record of Type Purchase Line.
This return type has no connection to the Rec.
To get the desired functionality add a "exit(Rec);" after the FindFirst.
`
tableextension 50100 "PurchaseLineExt" extends "Purchase Line" { 
    procedure FindFirstRec(): Record "Purchase Line" 
    begin 
        Rec.FindFirst();
        exit(Rec);
    end; 
}`

**Comment by dtkb** [comment] 2021-03-15 10:29
Do you mean the first one? Why should it return `Rec`?? `Rec` means the global current record, not the result of the function.

**Comment by dtkb** [comment] 2021-03-15 10:31
> To get the desired functionality add a "exit(Rec);" after the FindFirst.

Sure, but then doing that is pointless, since the `Rec.FindFirst()` already changed the state of the instance on which the method was called, so they can just use that, instead of also copying it to the result.

**Comment by IamLerxx** [comment] 2021-03-15 10:45
> > To get the desired functionality add a "exit(Rec);" after the FindFirst.
> 
> Sure, but then doing that is pointless, since the `Rec.FindFirst()` already changed the state of the instance on which the method was called, so they can just use that, instead of also copying it to the result.

In case of TableExtensions you are right.

In case of PageExtensions returning the Rec would be good as it would make the difference between:
`myPage.FindFirstRec();`
`myPage.GetRecord(myRec);`
and
`MyRec := MyPage.FindFirstRec();`

Also in the example provided by dkatson the return type of the function is set, so it should return something.

**Comment by qutreson** [comment] 2021-03-30 06:04
I am closing this issue as this is the expected behavior. The other comments on the issue provide more information on how to handle this scenario.

**Closed by qutreson** 2021-03-30 06:04 UTC
