### ISSUE TITLE
Option index offset

### ISSUE THREAD

**Issue by Joriek** [Microsoft/AL#3082] opened 2018-07-31 09:07 UTC
Hello,

A colleague and me encountered the following while testing an option field from the card page in a test codeunit.

Code:
Assert.AreEqual(Card.Status.GetOption(CalculationHeader.Status::Open),Card.Status.Value(),'Status not valid');

Error:
"Unexpected CLR exception thrown.: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.\Parameter name: index\   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgu"

While debugging this issue we noticed that when we use the GetOption function on the card page the index starts at 1. The status from the table the index starts at 0.
This means that the status 'Open' has an index 0 on the table, but an index 1 on the page.
We can always work around this by iterating the table index by 1 in order to match is the the index for the page but I'm not sure if this is best practice.
Is this by design? Is there an enhancement possible?

You can reproduce this using the following code sample:

Procedure OptionFunction();
var
    IntegerOptionTable: Integer;
    TxtOptionCardPage: Text;
begin
    IntegerOptionTable := Table.Status::Open;
    TxtOptionCardPage := CardPage.Status.GetOption(1);
    Message('Table: %1 with page: %2',IntegerOptionTable, TxtOptionCardPage);
end

- AL Extension Version: 0.12.25327

- VS Code Version: 
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

**Comment by JohanStenberg100** [comment] 2018-10-30 14:54
Hi @Joriek, can you provide us with a program which consistently reproduces your issue? If we can get a clear repro we can treat this as a potential improvement.

**Comment by StanislawStempin** [comment] 2018-11-07 12:29
Closing due to the fact that we couldn't reproduce the issue and for lack of additional input.

**Closed by StanislawStempin** 2018-11-07 12:29 UTC
Labels: input-needed
