### ISSUE TITLE
Permission Problem NAV 2018 CU7

### ISSUE THREAD

**Issue by hhfiddelke** [Microsoft/AL#3108] opened 2018-08-02 12:25 UTC
A Customer having an Application developer License may develop a Codeunit that hooks for example the OnInsert- Event from Cust. Ledger Entry, and modify data in the record without having or giving the corresponding permissions to this Object.

I think that should not be possible.

**Comment by hhfiddelke** [comment] 2018-08-07 06:39
[CU50000.txt](https://github.com/Microsoft/AL/files/2265273/CU50000.txt)
Here a small example for Cust, Ledger Entries, that removes "Customer No." on Inserting Entries in a Database with Cronus- license, and no permission in the Codeunit.

P.S.: NAV2018 CU8 has the same problem.

Important: DO NOT USE/TEST THIS CODEUNIT WITH A DATABASE THAT IS NEEDED FOR FURTHER USE.

**Comment by StanislawStempin** [comment] 2018-08-07 12:31
This is by design. The actual insert or modify is executed within the base object which does have permissions to do the operation. Having access to develop new event subscribers means it's possible to do things as you described. Anyone installing new code on the system has to be a trusted user, who would typically have most of the permissions anyway.

**Comment by hhfiddelke** [comment] 2018-08-07 12:52
Sorry, currently OnPremise a Customer with Application-Developer License may develop all code incl. Codeunits except changing LedgerEntries directly. If he writes a Report to modify Entries he will not allowed to save that report. If he develops a Codeunit with a subscriber he may change the record- parameter tha should also not been allowed. He also may read that he normaly is not allowed to read  and write it to an area, where he is allowed to read.
We as  Partner are normaly deny the responsibility for the status of the accounting if a customer has a Dolution Developer License, so now we can't assure that a customer which may design a Exventsubscriber may kill accounting. That's very bad, and we are unable to preserve that.

**Comment by StanislawStempin** [comment] 2018-08-07 15:01
Note that this has been the case since NAV 2016 when event subscribers were introduced. So it's not new nor specific to Business Central/AL development tools. Couldn't the customer modify that data in SQL directly anyway?

**Comment by hhfiddelke** [comment] 2018-08-07 15:22
That this - i would say bug - was not found earlier doe not make it better.

There are many developments, that are done by Customers who have access to the Development-Client, but not realy to the SQL-Server. 
This permission is also mostly required to prohibit modifications by accident, not because somebody wants to compromise NAV/BC, but may be. But sometimes poeple are interested, which salary their boss gets.
As far as i know there is a license- permission- setup to disallow running a table from Dev-Client. so this would be the way getting the data anyway.

**Comment by gudrunleos** [comment] 2018-08-09 09:30
The customer is the owner of the data - right? Therefor he can do whatever he wants with it 😄.

**Comment by hhfiddelke** [comment] 2018-08-09 10:11
@gudrunleos 
This was not the previous intention of NAV and i do not know if it is always allowed bei law.

In Germany for example you have to assure that important information in posted documents and ledger entrie is not changeble by user. Currently this is done with the License.

Why does Microsoft currently assure that posted documents and ledger entries are not changeble by user?

**Comment by gudrunleos** [comment] 2018-08-09 11:39
@hhfiddelke Intention or not - the technology used in the early days made the data much less accessible than today, I think we can agree on that. What the law states in each country should be implemented as localizations IMO.

**Comment by hhfiddelke** [comment] 2018-08-09 12:17
@gudrunleos the problem is not accessible of data but the data modification. 

And you can't implement security by localisation, if the system has no option to do that.

It seems also that there is no permission setting that prohibits grabbing confidential data while posting, and that is also a problem.

**Comment by NKarolak** [comment] 2018-08-09 13:27
@hhfiddelke Just FYI, my colleague has already created a NAV support request for it recently, No. 118080718737663

**Comment by hhfiddelke** [comment] 2018-08-09 13:37
@NKarolak : Thank you.  
I am not the only one, who does not like that feature.

**Comment by NKarolak** [comment] 2018-08-09 13:41
Indeed!

**Comment by StanislawStempin** [comment] 2018-10-10 21:11
This was actually a bug that got fixed in BC Fall 2018. Please give it a try and let us know if you encounter any other issues.

**Closed by StanislawStempin** 2018-10-10 21:11 UTC
Labels: question
