### ISSUE TITLE
AL Compiler does not catch Query errors when an option field has been changed to an Enum.

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/AL#6864] opened 2021-12-08 10:33 UTC
When you have a query that works on an Option field (f.ex. filtering on the „Document Type“ of a Sales Header), and that field is then changed to an Enum field, compiler does not catch that anything is wrong with the code that is setting a filter to that field in the query, and you get a runtime error.

This was a problem 18 months ago when we did our first upgrade to BC17, and again now in BC19 when more Option Fields were changed to Enum fields, and our queries stopped working.

Here is a picture with an example of a code setting a filter on an Option field, that has been changed to an Enum field:

![image](https://user-images.githubusercontent.com/57808351/145193154-b2845a53-9376-4731-bdcd-71735ba49247.png)

**Comment by dnpb** [comment] 2021-12-08 12:07
What runtime error?

Does it work if you change it to `Enum::"Purchase Document Type [or whatever]"::"Order"`?

**Comment by KristjanGaukur** [comment] 2021-12-08 13:13
Here is a picture of the error:
![image](https://user-images.githubusercontent.com/57808351/145213802-c1f5e810-172a-464e-ba50-3d43b4d67671.png)

By changeing the code to reference the enum values directly corrects the error (but the compiler or codecop do not pick up on this).

So the error line was:
**QueryVariable**.SetFilter(Document_Type, '%1..%2', **QueryVariable**.Document_Type::Order, **QueryVariable**.Document_Type::Invoice);

And we corrected it with:
QueryVariable.SetFilter(Document_Type, '%1..%2', **DocTypeEnumVar**::Order, **DocTypeEnumVar**::Invoice);

**Comment by dnpb** [comment] 2021-12-08 13:15
Since the old Option-type syntax still works for Record.Field::LikeThis, I'd expect it to work too with Query.Field::LikeThis. Hopefully MS agree!

https://github.com/microsoft/AL/issues/6598 is related.

**Comment by dnpb** [comment] 2021-12-08 13:29
Btw, you don't need to declare a `DocTypeEnumVar` to reference the enumerated values. You can just do `Enum::"The Enum's Name"::"The Value's Name"`, and in fact the `Enum::` prefix is not even required (unless to disambiguate presumably).

**Comment by dnpb** [comment] 2021-12-08 13:30
It seems this may only occur in some cases. For instance, this using a base query is fine:

```al
pageextension 50100 Test extends "Customer List"
{
    trigger OnOpenPage()
    var
        SalesOutstdAmountOnVAT: Query "Sales Outstd. Amount On VAT";
    begin
        SalesOutstdAmountOnVAT.SetFilter(Document_Type, '%1|%2', SalesOutstdAmountOnVAT.Document_Type::Invoice, SalesOutstdAmountOnVAT.Document_Type::"Credit Memo");
        Message('OK!');
    end;
}
```

Maybe it needs to be a user-defined query, and/or a user-defined field/enum?

**Comment by KristjanGaukur** [comment] 2021-12-08 13:41
I have fixed this in my code, so I do not have a problem anymore (unless maybe if MS changes more option fields to enums).
So, I just wanted to notify you of the problem.
Thank you.

**Comment by dnpb** [comment] 2021-12-08 13:43
I don't work for MS, if that's what you mean.

It does seem like a bug, which should be fixed. Preferably by making the platform not crash on code the compiler says is valid... but at least by, if that syntax is not meant to work, making it error at compile-time.

**Comment by KristjanGaukur** [comment] 2021-12-08 13:47
Will MS notice this here, do you think?

**Comment by dnpb** [comment] 2021-12-08 13:59
Yeah, I think so, although it might take a while as there's quite a backlog of issues already. Sometimes newer ones are picked up quicker though.

**Comment by thloke** [comment] 2021-12-14 05:33
Hi, sorry for taking a while to get to this - as mentioned, we've got a backlog of issues we're working through. Right now what we need is a minimal repro to take action on this, can you provide a small project that reproduces the issue?

**Comment by thloke** [comment] 2022-01-17 11:22
Closing as no response has been given in more than two weeks.

**Closed by thloke** 2022-01-17 11:22 UTC
Labels: input-needed

**Comment by KristjanGaukur** [comment] 2022-01-17 12:16
Hmmm... strange.

Response was given last Friday from my boss, see attachments.

Cheers,
Kristján

**Comment by thloke** [comment] 2022-01-17 12:21
@KristjanGaukur - I think your boss will need to comment on this issue directly rather than replying to the github emails. There's no record of any reply on this issue itself.
