### ISSUE TITLE
Enlarge max. Count of Problem Entries

### ISSUE THREAD

**Issue by Koepisch** [microsoft/AL#6998] opened 2022-04-13 10:05 UTC
I've noticed that the **maximal count** of listed **problems** are restricted to **100 entries** per AL object.
I havn't found any setup, where i can lift these restriction up to show ALL problems. 

Background: I grab these information to solve the problems automatically.

Is there any setup to do this?
Can i change the source code to do it myself?
Can these max. showed problems count be part of the setup parameter?

Regards
Koepisch

**Comment by dnpb** [comment] 2022-04-13 11:54
seems like a dupe of https://github.com/microsoft/AL/issues/6198

**Comment by Koepisch** [comment] 2022-04-15 09:14
> 

It's not quite the same issue, because i never get more than 100 entries. It's not due to the 50 file limit or due to undiscovered errors. I simply want to see all errors which are occurring in a file.

**Comment by Koepisch** [comment] 2022-08-17 16:36
I want to bump my request. There are a lot of C/AL conversions and we need that feature urgently.

**Comment by kalberes** [comment] 2022-08-22 20:16
Have you tried using the continueBuildOnError:true for the al.compilationOptions property?

**Comment by Koepisch** [comment] 2022-09-08 07:57
> Have you tried using the continueBuildOnError:true for the al.compilationOptions property?

Thanks yes, i have. Still only max. 100 problems per file. It's a really annoying problem.

**Comment by EmilDamsbo** [comment] 2023-09-14 14:03
Update in 2023: We currently show up to 500 diagnostics per file, which is the maximum which VSCode supports. There is currently an active issue in their repository to increase this number: https://github.com/microsoft/vscode/issues/181045

I believe that if you use the ALC.exe compiler directly, you can circumvent this limitation.

**Closed by EmilDamsbo** 2023-09-14 14:03 UTC
Labels: static-code-analysis
