### ISSUE TITLE
Analyzer: check for Overflows on FlowFields

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/AL#5753] opened 2020-03-26 15:52 UTC
Title
The AL analyzer should check for overflows when a FlowField is defined
Description
While updating old project with Flowfields to some table that have had their Name/Description fields extended in previous BC/NAV versions, I discovered that FlowFileds to those fields were not raising any warnings. That is, fields in our app were defined as Text[50], but the related Field now was defined as Code[100]
Reason for the rule
This can be important because, for example, our app had lots of references to a field that had been extended in BC standard but, as no variables were assigned by code, no warnings were raised and the app seemed to be working with no problems.
Bad code sample
        field(100; "Sell-to Customer Name"; Text[50])
        {
            CalcFormula = lookup (Customer.Name where("No." = field("Sell-to Customer No.")));
            Caption = 'Sell-to Customer Name';
            Editable = false;
            FieldClass = FlowField;
        }
Good code sample
        field(100; "Sell-to Customer Name"; Text[100])
        {
            CalcFormula = lookup (Customer.Name where("No." = field("Sell-to Customer No.")));
            Caption = 'Sell-to Customer Name';
            Editable = false;
            FieldClass = FlowField;
        }
Remarks
No warnings were raised using the VS Code AL Language extension v5.0.249661

**Comment by dnpb** [comment] 2022-05-11 10:02
dupe of https://github.com/microsoft/AL/issues/4494
and isn't this already done in some recent AL extension version?

**Comment by mazhelez** [comment] 2022-06-21 13:09
Progress will be tracked in #4494

**Closed by mazhelez** 2022-06-21 13:09 UTC
Labels: static-code-analysis
