### ISSUE TITLE
Reference to object File Management is ambiguous.

### ISSUE THREAD

**Issue by Kowa63** [Microsoft/AL#2088] opened 2018-04-25 10:54 UTC
Since #1637 is locked:
The misleading ambiguous message bug still exists in vsix 15.18771, using bcsandbox Build 21229.
AL files were created with txt2AL.
In my case it is Codeunit 419
`Reference to object File Management is ambiguous. Make sure you are not referencing packages containing objects with the same names.`
A workaround is to replace 
**FileMgt : Codeunit "File Management";**
with
**FileMgt : Codeunit 419;**
then the error message goes away.

**Comment by StanislawStempin** [comment] 2018-05-03 12:01
Do you have any other errors in your project, especially syntax errors? Otherwise, could you provide a simple AL example of code that triggers this situation, including the app.json? 
We are not able to reproduce it.

This could also be caused by stale symbol files. Just to eliminate other variables it's good to try on a fresh container sandbox, delete local .app symbol files and redownload them from the server.

**Comment by StanislawStempin** [comment] 2018-05-11 08:54
Ok thanks. With syntax errors present this is most likely not an actual bug but just a result of parsing incorrect code. I will close this issue, please log a new one if you're still hitting the error on a correctly structured code. 

An issue that we have seen in the past is if any of the structural keywords are missing (for example an Area inside of layout) then the parser might pick up variable declarations as object declarations leading to duplicate objects. 

I recommend using ExportToNewSyntax and txt2al from the latest bcsandbox-master Docker images. There were many bugs fixed in the tool since NAV 2018 shipped.

**Closed by StanislawStempin** 2018-05-11 08:54 UTC
Labels: investigate
