### ISSUE TITLE
Go to Definition don't work if there is '/' in the object name

### ISSUE THREAD

**Issue by sdelikostov** [microsoft/AL#7009] opened 2022-04-21 11:26 UTC
1. Go to Definition don't work if there is '/' in the object name
When I am trying to see definition of a object contains '/' in the name, an error occurs:
cannot open al-preview://allang/IRIM/Codeunit/3/G/L%20Account-Indent.dal. Detail: Unable to resolve text model content for resource al-preview://allang/IRIM/Codeunit/3/G/L%20Account-Indent.dal.
Same from the app object explorer, same in the code.

2. To Reproduce
Open Base Application app objects and try to open Codeunit 3 or table 15

3. Expected behavior
Open the object code

4. Actual behavior
Un error occurs:
cannot open al-preview://allang/IRIM/Codeunit/3/G/L%20Account-Indent.dal. Detail: Unable to resolve text model content for resource al-preview://allang/IRIM/Codeunit/3/G/L%20Account-Indent.dal.

5. Versions:

- AL Language: v9.0.605172
- Visual Studio Code: 1.66.2
- Business Central: 19.1
- List of Visual Studio Code extensions that you have installed:
AL Language
AL XML Documentation
AZ AL Dev Tools/AL Code Outline
GitLens — Git supercharged
waldo's CRS AL Language Extension

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by EmilDamsbo** [comment] 2022-04-21 12:54
This is a duplicate of !6972 which has been addressed. Thank you for your contribution.

**Closed by EmilDamsbo** 2022-04-21 12:54 UTC
