### ISSUE TITLE
Warning 'with' will be removed in the future

### ISSUE THREAD

**Issue by josejggil** [microsoft/AL#6189] opened 2020-10-02 07:00 UTC
Hi.

In my code the following warning has started to appear

![Screenshot_1](https://user-images.githubusercontent.com/47104041/94896106-02466600-048d-11eb-8dc8-3ac3fd5b4202.jpg)

However, if I fix it by putting Rec.

![Screenshot_2](https://user-images.githubusercontent.com/47104041/94896242-4f2a3c80-048d-11eb-89f1-553f349aaedf.jpg)

When executing I get the following error

![Screenshot_3](https://user-images.githubusercontent.com/47104041/94896296-71bc5580-048d-11eb-8d24-a41907b144f9.jpg)

I have seen this happen in the Enabled, Editable, .... properties of the pages

A greeting

**Comment by dtkb** [comment] 2020-10-02 08:29
dupe of https://github.com/microsoft/AL/issues/6095 and others

**Comment by ZepposBE** [comment] 2020-10-02 13:42
We had the same problems. Best to use a global boolean which u set in the trigger OnAfterGetCurrentRecord() and then set the boolean there.
This will make the page run for both BC17 and previous.

**Comment by kalberes** [comment] 2020-10-02 17:19
True they are all duplicates. As far as I know it is fixed in our master, thus it just need to be backported.

**Comment by esbenk** [comment] 2020-10-06 13:01
The AL604 warning (and hence the code fixer) will in not show for runtime < 6.0 from the next CU.

**Comment by nndobrev** [comment] 2021-07-29 10:07
Hello everyone, as @kalberes said the issue should be already fixed. I will close the issue because we can't reproduce it in our latest version. @josejggil, please feel free to reopen if you can still see the issue.

**Closed by nndobrev** 2021-07-29 10:07 UTC
Labels: bug
