### ISSUE TITLE
Reference by name in calculation properties not working on RunPageLink

### ISSUE THREAD

**Issue by sschuh** [microsoft/AL#7205] opened 2022-10-11 10:29 UTC
hi,

AL Language: v10.0.687650
Runtime: 10

the new Reference by name in calculation properties features seems not to work in pages with RunPageLink...

Page/PageExt:
RunPageLink
<img width="699" alt="image" src="https://user-images.githubusercontent.com/34685182/195065133-41daccb9-c161-4ff3-9516-59704a1e4334.png">

Bug or Feature? :)

**Comment by dnpb** [comment] 2022-10-11 10:39
What is the error? Could it be about conversion between different options/integers?

**Comment by sschuh** [comment] 2022-10-11 10:58
Another example:
<img width="747" alt="image" src="https://user-images.githubusercontent.com/34685182/195072754-1e5f5890-0c36-4290-904c-3fea68356e3f.png">

<img width="284" alt="image" src="https://user-images.githubusercontent.com/34685182/195072857-5d0be406-3200-4132-8aea-13c6aa6a27be.png">

**Comment by sschuh** [comment] 2022-10-11 11:21
Additional:
The same problem exists for RunPageView:
<img width="833" alt="image" src="https://user-images.githubusercontent.com/34685182/195077063-7ee321cb-8606-41be-9d30-02ec509f1ca5.png">

**Comment by NKarolak** [comment] 2023-01-25 09:26
@qutreson @thloke What's the current status?

**Comment by Duizy1971** [comment] 2023-02-08 11:39
Issues 7280 and 7281 have been closed and I would also like to know the status on this issue. We would like to change all the
"Line No." = const(11222671); to "Line No." = const(Page::"A106 Complaint Card"); but even in 21.04 with runtime 10.1 it still raises error in some places.

**Comment by qutreson** [comment] 2023-02-09 07:24
@Duizy1971 - The Github issues have been closed as duplicate of this one, so the underlying issue is not fixed yet.

@NKarolak - We are working on a fix for this issue. It should hit the preview docker images in the next days and is likely to be part of the next upload of the AL extension in the marketplace.

**Comment by JesperSchulz** [comment] 2023-02-13 12:13
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 22.0.53131.0 and VS Code Extension Version 11.0.752605. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Closed by JesperSchulz** 2023-02-13 12:13 UTC
Labels: ships-in-future-update, al-core-compiler, accepted
