### ISSUE TITLE
Enums are being evaluated by element position, not by its value

### ISSUE THREAD

**Issue by DragonMrak** [microsoft/AL#5646] opened 2020-02-07 08:32 UTC
**Describe the bug**
When using Enum value to show or hide groups on the page elements position is used instead of its value

**To Reproduce**
Steps and to reproduce the behavior:
1. Run the code supplied
2. Click on any customer to show its card
3. On a "Test" section change value to Date or Decimal

``` AL Code to reproduce the issue ```

enum 50120 TestEnum
{
    Extensible = false;

    value(1; Text) { Caption = 'Text'; }
    value(3; Date) { Caption = 'Date'; }
    value(2; Decimal) { Caption = 'Decimal'; }
}

tableextension 50120 CustomerExt extends Customer
{
    fields
    {
        field(50100; "Enum Value"; Enum TestEnum) { DataClassification = CustomerContent; }
        field(50101; "Text Value"; Text[250]) { DataClassification = CustomerContent; }
        field(50102; "Date Value"; Date) { DataClassification = CustomerContent; }
        field(50103; "Decimal Value"; Decimal) { DataClassification = CustomerContent; }
    }
}

pageextension 50120 CustomerListExt extends "Customer Card"
{
    layout
    {
        addlast(content)
        {
            group(TestGroup)
            {
                Caption = 'Test';

                field("Enum Value"; "Enum Value") { ApplicationArea = All; }

                group(TextValue)
                {
                    Caption = 'Text Value';
                    Visible = "Enum Value" = "Enum Value"::Text;

                    field("Text Value"; "Text Value") { ApplicationArea = All; }
                }
                group(DateValue)
                {
                    Caption = 'Date Value';
                    Visible = "Enum Value" = "Enum Value"::Date;

                    field("Date Value"; "Date Value") { ApplicationArea = All; }
                }
                group(DecimalValue)
                {
                    Caption = 'Decimal Value';
                    Visible = "Enum Value" = "Enum Value"::Decimal;

                    field("Decimal Value"; "Decimal Value") { ApplicationArea = All; }
                }
            }
        }
    }
}
**Expected behavior**
The group which corresponds Visible expression should be displayed.

**5. Versions:**

 - AL Language: 4.0.176004

 - Business Central: Platform 15.0.36510.0 + Application 15.0.36649.0

**Comment by atoader** [comment] 2020-03-07 08:36
Hi! This seems to have the same root cause as https://github.com/microsoft/AL/issues/5651 . Can you confirm that it is fixed?

**Comment by atoader** [comment] 2020-04-01 19:01
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Closed by atoader** 2020-04-01 19:01 UTC
