### ISSUE TITLE
new parameters in the launch.json do not work

### ISSUE THREAD

**Issue by srenders** [microsoft/AL#6222] opened 2020-10-14 11:29 UTC
Is there any documentation about these new parameters in the launch.json?
, "environmentType": "Sandbox"
, "environmentName": "Sandbox"

 They do not work. Downloading symbols works, publishing a helloworld app does not...
When I revert back to:  , "sandboxName": "Sandbox" it works again...

- AL Extension Version: v6.1.350698

- Server Version: Version: BE Business Central 17.0 (Platform 17.0.17020.17400 + Application 17.0.16993.0)

, "environmentType": "Sandbox"
, "environmentName": "Sandbox"

**Comment by kalberes** [comment] 2020-10-14 11:43
Should work. There must have been some other  reason. What was your error message? I could also look it up our Azure logs what has failed but I need to identify your request somehow.
I just tested again had no issues publishing.
![image](https://user-images.githubusercontent.com/12760483/95984017-d3cc7180-0e22-11eb-97ea-1c0464c7cf03.png)

**Comment by wisa1** [comment] 2020-10-14 11:47
To Add to this: 

The "Test" property also seems broken. I assume it's meant to get rid of all the test-dependencies we have all over the place. 
Tested with artifact https://bcartifacts.azureedge.net/onprem/17.0.16993.0/at

![image](https://user-images.githubusercontent.com/19393084/95984612-bc41b880-0e23-11eb-874b-6abcca804975.png)

**Comment by kalberes** [comment] 2020-10-14 11:50
@wisa1 
That is a different issue. Please open a new request for that. Let's not mix issues, please.
This is about the new configuration setting introduced for supporting downloads of symbols on production environment for the 17.x(x>0) runtime and the newest visx

**Comment by kalberes** [comment] 2020-10-14 12:20
Duplicate of #6219 

Until we have a fix do not use the environmentname but the old sandboxname

**Comment by kalberes** [comment] 2020-10-15 12:48
The issue should be fixed in version  v6.1.352568.

**Comment by kalberes** [comment] 2020-10-16 09:54
Closing because of a duplicate

**Closed** 2020-10-16 09:54 UTC
Labels: bug, duplicate, ships-in-future-update
