### ISSUE TITLE
[Bug] Incorrect use of custom report layouts if contained in extension package

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/AL#4397] opened 2018-12-18 06:33 UTC
Here's the case:
We have included our own report layout in our customer extension. This will also be installed and uninstalled during installation. But unfortunately the customer cannot use it at the moment, because always an error message appears on report execution. I have analyzed the problem and here is my evaluation of the problem: 

If the extension is installed, then an entry is made in the table "Custom Report Layout" with the added layout. This is incorrectly marked as "Built-In". OK, "Built-In" could also refer to the extension. But here is the error, more information below.

When executing a report, the error message that the system cannot find the layout always appears. This indicates that the system is missing an entry in the system table "Report Layout". Here you can also attach the debugger and see that the error comes from the C/AL code of the existing logic. This is because the imported report layout is marked as "Built-In". 

From my point of view, the problem lies in the routines that install the layout. There is no entry in the table "Report Layout", although the imported report layout is marked as "Built-In". According to logic, the system searches for the appropriate layout when it executes the report. The layouts marked with "Built-In" are all in the "Report Layout" table. However, the actual layout is imported in the column "Layout" in the table "Custom Report Layout". This means that this is the problem.

Before the questions come. The errors occur here in CU2 from Business Central with the corresponding AL language version.

**Comment by atoader** [comment] 2019-11-09 20:25
Hi! In the last months, we've been working hard on adding new features that increase your productivity and on improving the quality of the tools. Unfortunately, this meant that we were not able to follow up on as many GitHub issues as we have liked. 
Is this issue still a problem for you? Can you provide a sample project to reproduce the issue?

**Comment by FSharpCSharp** [comment] 2019-11-15 10:37
Yes, the problem still exists. But I don't understand why an example is needed here. It is described above exactly how to achieve this behavior.

**Comment by StefanMaron** [comment] 2020-11-02 08:45
Seems like this issue still exists. I get the same error if I try to upgrade an app with custom report layouts included.

**Comment by IhorHandziuk** [comment] 2021-08-04 07:08
We have finally had time to look into this issue and implemented the following solution:
- When an extension with a custom report layout is installed, a record in the `Custom Report Layout` table will _still_ be inserted with `Built-In` set to `true` (because this layout needs to be immutable).
- When a report layout is _chosen_,  a `Custom Report Layout` will always be chosen if the `Layout` field has content (even if `Built-In` is set to `true`).

This fix will be shipped in the next minor update. Thanks for reporting this issue 😊.

**Comment by JesperSchulz** [comment] 2021-08-04 07:09
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 28375 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Closed by IhorHandziuk** 2021-08-04 07:08 UTC
Labels: bug, in-progress
