### ISSUE TITLE
Object Name Character Length

### ISSUE THREAD

**Issue by muratkarabek** [microsoft/AL#5174] opened 2019-07-21 15:00 UTC
Hi,

There is 30 characters length restriction for object and field names for years. Isn't that possible for you to allow more than 30 characters of length? As of now when developing extensions we have to add affixes to object and field names and this makes it really difficult to find short version of the name.

Thanks in advance!

**Comment by atoader** [comment] 2019-08-02 09:58
Hi @muratkarabek ! Thank you for your suggestion. We have considered this, but as Johan mentions in  #4488 , it would require a major refactoring of our system. As an alternative, we are investigating support for namespaces in AL.
I will close the issue as it is a duplicate of #4488

**Closed by atoader** 2019-08-02 09:58 UTC
