### ISSUE TITLE
Caption is not displayed in extended report

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/AL#6612] opened 2021-05-03 12:34 UTC
**The bug**
I have reported the issue on [yammer ](https://www.yammer.com/dynamicsnavdev/threads/1180504588468224) already. On request of @pborring I am reporting the issue also here.

For the 2nd edition of my [book on test automation](https://www.packtpub.com/product/automated-testing-in-microsoft-dynamics-365-business-central/9781789804935) I wanted to build a **reportextension** to report 1010 (Customer - List):

```
reportextension 50000 "CustomerListExt" extends "Customer - List"
{
    RDLCLayout = './reportlayouts/CustomerList.rdl';

    dataset
    {
        add(Customer)
        {
            column(Customer_Lookup_Value_Code; "Lookup Value Code")
            {
                IncludeCaption = true;
            }
        }
    }
}
```
The field **Lookup Value Code** has been added, through a tableextension, to the _Customer_ table. All code for this can be found in the [GitHub repo](https://github.com/PacktPublishing/Automated-Testing-in-Microsoft-Dynamics-365-Business-Central) that goes with the 1st edition of the book.

The report (extension) builds, can deployed and runs, but there is a bug:

![image](https://user-images.githubusercontent.com/18466198/116875559-698ee900-ac1b-11eb-8e13-8459cbf5ff07.png)

**Expected behavior**
Not the column/parameter name is displayed on the report, but the content of the column/parameter.

**Actual behavior**
The caption, that is the content of the caption parameter, of the added column **Customer_Lookup_Value_Code** is not displayed, but instead the column/parameter name.

**Versions**
- AL Language: v7.1.453917 and v8.0.446271
- Visual Studio Code: 1.55.2
- Business Central: 18.0.23013.23795 and 19.0.24847.0
- List of Visual Studio Code extensions that you have installed: a lot

**Comment by thloke** [comment] 2021-05-17 03:03
I cannot reproduce this on the latest 18.1 build. We had a bug that would have caused this, but was fixed in 18.1. I suspect that this ran into that issue. Can you try on a 18.x version of BC with 18.0.24800.0 or greater? Or the latest 19.x version? If it still repros, tag me and reopen this issue and I'll look into it. 

One way to quickly tell if you're running into the issue that has been fixed is to upload your layout as a custom layout, instead of publishing. If the caption works there, then it's the same issue.

**Closed by thloke** 2021-05-17 03:03 UTC
Labels: bug, in-progress

**Comment by lvanvugt** [comment] 2021-05-19 15:20
Tested on 19.0.25706.0 and it works fine.

**Comment by lvanvugt** [comment] 2021-05-19 15:39
And also tested on 18.1.24822.25711. Also working fine.
