### ISSUE TITLE
Inserting record method `.RecordId` from Intellisense omits 'required' brackets and does not fire AA0008

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6357] opened 2020-12-08 16:32 UTC
See also https://github.com/microsoft/AL/issues/6356

Typing `SomeRecordVariable.RecordId` or similar, and selecting the suggested `RecordId()` method call, omits parentheses, but it is a method call, so they should always be included, shouldn't they?

Then, once that call is inserted with missing `()`, rule `AA0008` does **not** warn about it, as it would with e.g. `SomeRecordVariable.Get;`

example result of Intellisense + absence of warning:
![image](https://user-images.githubusercontent.com/63455896/101512504-fab2aa00-3972-11eb-8ed2-a7599068c4b9.png)

**Comment by dnpb** [comment] 2022-02-03 09:26
apparently intentional: https://github.com/microsoft/AL/issues/6908#issuecomment-1028644117

**Comment by mazhelez** [comment] 2022-06-21 13:51
Closing as "by design/intenrional"

**Closed by mazhelez** 2022-06-21 13:51 UTC
Labels: bug, static-code-analysis, CodeCop
