### ISSUE TITLE
An error occured while compiling the App on latest Business Central (24.0.16410.17628)

### ISSUE THREAD

**Issue by ManishKutar** [microsoft/AL#7726] opened 2024-04-23 09:00 UTC
**1. Describe the bug**
There is an error message when first publish are made on latest Business Central version (24.0.16410.17628)
![image](https://github.com/microsoft/AL/assets/44708071/ab00df79-4da2-489f-b45d-edd75a9fb1ee)

After this on compiling again there is a below error:
![image](https://github.com/microsoft/AL/assets/44708071/49d6ff47-2f7c-49b0-b04f-7658602a2960)

**2. To Reproduce**
Business Central version was updated yesterday:
![image](https://github.com/microsoft/AL/assets/44708071/a7938c6e-159b-49c8-ad39-a24644add071)

1. Go to 'VS Code' and do 'AL! Go'.
2. On getting files update launch.json with correct tenant ID and authentication.
3. Download symbols works fine (even after clearing .alpackages).
4. After this compiling throws an error.

**3. Expected behavior**
An App should be Compiled, Published and Installed on provided Business Central tenant and environment.

**4. Actual behavior**
An App only Compiles, Publishes and but **_does not Install_** on provided Business Central tenant and environment.

**5. Versions:**

- AL Language: Version 13.0
- Visual Studio Code: 1.88.1
- Business Central:
![image](https://github.com/microsoft/AL/assets/44708071/a7938c6e-159b-49c8-ad39-a24644add071)

### Final Checklist
* [x] Search the issue repository to ensure you are reporting a new issue
* [X] Reproduce the issue after disabling all extensions except the AL Language extension
* [X] Simplify your code around the issue to better isolate the problem

**Comment by thloke** [comment] 2024-04-26 01:54
Duplicate of #7721

**Closed by thloke** 2024-04-26 01:54 UTC
