### ISSUE TITLE
Issue converting report from C/AL to AL when textconst is used as column value.

### ISSUE THREAD

**Issue by niku-live** [Microsoft/AL#1192] opened 2017-12-13 20:13 UTC
There seems to be an issue with report code conversion from C/AL to AL.
Let's say I have a report with global TextConst defined like this:
VAR
  V6CaptionLbl@1140420891 : TextConst 'LTH=6'; 

And later this TextConst is used as dataitem column value like this:
 DATASET
  {
    { 9871;    ;DataItem;Header;
               DataItemTable=Integer;
               DataItemTableView=SORTING(Number) WHERE(Number=CONST(1));
                                 }

    { 1101261052;1;Column;V6Caption          ;
               SourceExpr=V6CaptionLbl }
In this case TextConst is converted to label like this:
VAR
  V6CaptionLbl : Label '6';
And converted dataitem will look like this:
    dataset
    {
        dataitem(Header;"Integer")
        {
            DataItemTableView = SORTING(Number) WHERE(Number=CONST(1));
            column(V6Caption;V6CaptionLbl)
            {
            }
In fact, this code compiles without any problems, but when I try to deploy it, I get an error "The request for path /DynamicsNAV110/dev/apps failed with code InternalServerError. Reason: Requested value 'V6CaptionLbl' was not found."

If I change original code and add another translation to textconst:
VAR
  V6CaptionLbl@1140420891 : TextConst 'ENU=6;LTH=6'; 
this this is converted to textconst as well:
VAR
  V6CaptionLbl@1140420891 : TextConst ENU='6',LTH='6'; 
But this time it deploys successfully. So it seems that labels cannot be used as dataitem column value. If this is by design, then I think compiler should inform that this is an error before application deployment starts.

**Comment by DominikDitoIvosevic** [comment] 2017-12-14 09:25
Hi. Thank you for the repro for this bug. I have verified and this has already been fixed. This is a duplicate of #988

**Closed** 2017-12-20 13:17 UTC
Labels: bug, delivered
