### ISSUE TITLE
Report Extension: Request page: SaveValues: true not working for extension fields

### ISSUE THREAD

**Issue by ZepposBE** [microsoft/AL#6694] opened 2021-07-06 08:34 UTC
**1. Describe the bug**
When adding a field to the requestpage of a report, where the parameter 'SaveValues = true' does not save the values of the fields in the report extension.

**2. To Reproduce**

1. Create a Report extension for a report where the requestpage has 'Savevalues = true;'
2. Add a field to the request page.
3. Publish, Open the report, on the request page, set the extra field to true  run the report,
4. Open the report again --> extra field is false instead of true.

``` AL
reportextension 50000 "ESCCReportExtensionSaveValues" extends "Create Invt Put-away/Pick/Mvmt" //7323
{
    requestpage
    {
        layout
        {
            //Original Report's requestpage has 'SaveValues' set to 'true'
            addafter(ShowError)
            {
                field(ESCCIncludeLinkedEmptiesField; RequestPageBoolean)
                {
                    ApplicationArea = Warehouse;
                    Caption = 'RequestPageBoolean';
                    ToolTip = 'This is a RequestPageBoolean';
                    trigger OnValidate()
                    begin 
                        //Set the RequestPageBoolean value in some table to use it the next time
                    end;
                }
            }
        }

    }
    trigger OnPreReport()
    var
        //SomeSetuptable to get the RequestPageBoolean value from last time
    begin
        //If Table.Get() then
        //RequestPageBoolean := Table.RequestPageBoolean;
        //This trigger is too late to set the value
    end;

    trigger OnPostReport()
    begin
    end;

    //No other triggers to use to set the value of RequestPageBoolean?

    protected var
        RequestPageBoolean: Boolean;
}
```

**3. Expected behavior**
The SaveValues should work for fields on the request page (in the report extension).
If that cannot be done, a trigger should be provided to be able to set the value when the request page is opened /  report is initialized.

**4. Actual behavior**
The request page of the report saves the values of the standard fields, but not the fields on the report extension.
No trigger is provided where we can set the value to show correctly on the request page.

**5. Versions:**

- AL Language: v7.3.486497
- Visual Studio Code: 1.57.1
- Business Central: 18.2.26217.26331
- List of Visual Studio Code extensions that you have installed:
- AL Language, AL Language Tools, AL CodeActions, AL Toolbox, Waldo CRS AL Language extension, AL Object Designer, CRS AL Language Extension, GitLens, AL Variable Helper

**Comment by db-bc** [comment] 2021-07-06 08:46
Yes, I think I had noticed this too, but didn't have time to report and forgot about it.

**Comment by db-bc** [comment] 2021-07-06 08:48
> No trigger is provided where we can set the value to show correctly on the request page.

Can't you just use `trigger OnOpenPage()` within the `requestpage` block? It is available and seems to build fine, although I didn't specifically test it yet.

**Comment by ZepposBE** [comment] 2021-07-06 08:55
> > No trigger is provided where we can set the value to show correctly on the request page.
> 
> Can't you just use `trigger OnOpenPage()` within the `requestpage` block? It is available and seems to build fine, although I didn't specifically test it yet.

You're right, I was so stuck in my head with the report triggers at the end that I forgot to check the ones on the request page block itself... That did it. Thank you and sorry for reporting this as an issue while overlooking this simple solution.

**Comment by db-bc** [comment] 2021-07-06 09:02
I think it should be an issue anyway, unless it gets documented that `SaveValues` shouldn't work for extension controls. Can you reopen perhaps?

**Comment by ZepposBE** [comment] 2021-07-06 09:29
> I think it should be an issue anyway, unless it gets documented that `SaveValues` shouldn't work for extension controls. Can you reopen perhaps?

Reopened :) Even though I can now get the last value on the onopen page, I still need to set the last value somewhere stored in a table. So the SaveValues does indeed still not work as one would expect.

**Comment by thloke** [comment] 2021-07-07 07:59
This is a straightforward bug. Thank you for the really clear repro steps. We've added this to our queue to fix.

**Comment by db-bc** [comment] 2021-07-13 11:38
This seems to be working OK now, in my Docker image of GB Business Central 18.3 (Platform 18.0.27224.27770 + Application 18.3.27240.27859)

**Comment by nndobrev** [comment] 2021-07-16 07:36
@db-bc Could you please try to reproduce it again, I don't see it being fixed and I am working on the fix now.

**Comment by db-bc** [comment] 2021-07-16 08:49
I was testing it with the Customer Statement, which now that I think about it does not run the Standard Statement report (1316) directly, but instead runs report 153 "Customer Statement", which itself calls codeunit `CustomerLayoutStatement.RunReport`. So that presumably still goes through the Custom Layout Reporting machinery, which might be saving the values including extension controls, some different way?

The code posted by the OP indeed does not save the extended control's value for me.

Sorry for the confusion.

**Comment by JesperSchulz** [comment] 2021-07-26 02:50
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 28208 and VS Code Extension Version 8.0.493428. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Closed by JesperSchulz** 2021-07-26 02:50 UTC
Labels: bug, in-progress, ships-in-future-update
