### ISSUE TITLE
Txt2AL: Multi-word tablerelations without quotes

### ISSUE THREAD

**Issue by epernst** [Microsoft/AL#915] opened 2017-11-11 10:00 UTC
In the November build when exporting and converting objects with multi-word tablerelation's, then the table name is without quotes.

Example from table 36:
    field(23;"Payment Terms Code";Code[10])
    {
      Caption = 'Payment Terms Code';
      TableRelation = Payment Terms;

Here are the files exported and converted:
[T36.txt](https://github.com/Microsoft/AL/files/1463632/T36.txt)

[Table 36 - Sales Header.al.txt](https://github.com/Microsoft/AL/files/1463634/Table.36.-.Sales.Header.al.txt)

**Comment by qutreson** [comment] 2017-11-12 20:37
We find out about this bug as well, this will be fixed in the next update.

**Comment by NicolaiEsbensen** [comment] 2017-11-14 15:34
Out of curiosity as we continously convert our text objects, will this bug result in an .al compile error? 

Could be nice to know before we update our development environment to the november release.

**Comment by qutreson** [comment] 2017-11-14 15:51
In the case of a table with a name that should be quoted (like in the example, since the table contains a space), it will result in a compilation error. However, if the table relation does not need to be quoted or if the table relation contains if conditions, the property value given by the converter is correct.

**Comment by bwdeleeuw** [comment] 2017-12-06 05:28
Did this fix not make it into the NAV 2018 update? I'm still running into missing quotes on RunPageLink, RunPageView, SubPageLink and SubPageView.

**Comment by qutreson** [comment] 2017-12-06 12:05
The fix went into our December update and also made it into NAV 2018. I tried to reproduce it on the properties you mentioned, but it seemed to work for me. Were your files exported using the new syntax?

**Comment by bwdeleeuw** [comment] 2017-12-06 14:07
@qutreson I did export using the new syntax.

I ran through the following steps:

1. Technical Upgrade of NAV 2017 cu4 database to NAV 2018 RTM
2. Export with finsql, command=ExportToNewSyntax
3. Split using Split-NAVApplicationObjectFile
4. Create Delta using Compare-NAVApplicationObject
5. Run txt2al on Delta files
6. Import into new AL project

 I'm attaching one of the files here:

[TAB232.TXT](https://github.com/Microsoft/AL/files/1535384/TAB232.TXT)

**Comment by bwdeleeuw** [comment] 2017-12-06 14:15
@qutreson 

I think I found it. Your remark that the object should be compiled had me go back and compile the object after the technical upgrade. After that, I do end up with a better file. 
This was a customer database, so all objects were compiled, both before and after the TU, but there must be something in the compilation routine that does need to be explicitly rerun.

Thanks for the assist!

[TAB232.TXT](https://github.com/Microsoft/AL/files/1535452/TAB232.TXT)

**Closed** 2017-12-07 09:14 UTC
Labels: bug, delivered
