### ISSUE TITLE
AA0181 - Function Next for TestPage

### ISSUE THREAD

**Issue by FSchneiderYav** [microsoft/AL#7459] opened 2023-07-14 11:37 UTC
Hello,

the CodeCop Warning AA0181 (The FindSet() or Find() methods must be used only in connection with the Next() method.) shows also for the Next() function on a Test Page
![image](https://github.com/microsoft/AL/assets/47736215/51b84118-0ebf-4802-82af-c90b3264dd19)

**5. Versions:**

- AL Language: 11.0.827766
- Visual Studio Code: 
  Version: 1.80.1 (user setup)
  Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
  Date: 2023-07-12T17:22:07.651Z
  Electron: 22.3.14
  ElectronBuildId: 21893604
  Chromium: 108.0.5359.215
  Node.js: 16.17.1
  V8: 10.8.168.25-electron.0
  OS: Windows_NT x64 10.0.22621

**Comment by sergiusignacius** [comment] 2024-05-07 08:02
Hi @FSchneiderYav, 

Can you clarify further what you're experiencing with a full code snippet that reproduces the issue? From the description it's not exactly clear where you see the warning. In #7731 something similar is happening, but I want to make sure we got your issue right before closing this as a duplicate.

Thanks!

**Comment by thloke** [comment] 2024-09-10 01:52
Closing as duplicate of #7731

**Closed by thloke** 2024-09-10 01:52 UTC
Labels: requires-triage, CodeCop
