### ISSUE TITLE
Page parts/tabs cannot be made visible dynamically

### ISSUE THREAD

**Issue by rdebath** [Microsoft/AL#2007] opened 2018-04-12 16:35 UTC
I have some code that enables different parts of a page dynamically, Like the example in the docs
https://docs.microsoft.com/en-us/dynamics-nav/Visible-Property but with page parts too.

This is in the Windows client on 11.0.20783 and 12.0.21229.

If the user does no customisation it appears to still work, but if the user brings the "shipping tab" onto the page when the "payments tab" is not visible it will not become visible again. If the user resets the page when the tab should be being displayed it returns.

If the condition isn't a simple boolean flag (eg it's an Option comparison) the tab(s) cannot be brought back onto the page.

This code is working fine in NAV2017.

**Comment by StanislawStempin** [comment] 2018-04-16 19:37
Does it work if instead of customization using the new web client Personalization feature? 

In general, since this is NAV 2018 issue/question you should contact Support through regular channels.

**Comment by rdebath** [comment] 2018-04-17 14:33
Umm, my understanding is ...
If you remove the "shipping tab" with a profile the web client personalisation feature is disabled.
You can't add fast tabs or fact boxes with the web client personalisation (even if you previously "hid" the fact box).
The web client "designer" isn't "personal".

So what exactly do you mean?

Nb, is the "regular channel" still "pay to file a bug report then beg for the money to be returned" style?

**Comment by StanislawStempin** [comment] 2018-05-15 13:11
My apologies, I just noticed this is related to the windows client and not to the new Personalization/Designer features in the web client. In that case it is even more out of scope for this forum:
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-not-related-to-al-development-what-do-i-do
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/

**Comment by rdebath** [comment] 2018-05-25 19:47
Sigh,  None of those links say that.

1. The bug is in V12.0.21229. as well as 2018.
2. The code is in a V2 extension using vscode and AL.
3. The only mention of the windows client on that page is in the comments BY ME where I indirectly reference _this issue_. 
4. It is not, currently, a customer facing issue and when it becomes so I have a kludgy (and really ugly looking) workaround.
5. Your FAQ/Wiki explicitly references "On-Premise" issues as in scope. (Twice)

Note: I'm actually following [your first FAQ reference](https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do) because I'm raising the bug with you as it replicates on 12.0.21229 and only when (if? → kludgy workaround) it becomes a customer issue would I request that you incur the additional cost of making a 2018 update.

So do you want to fix this V12, vscode, On-premise, AL bug in 'main' ?

**Comment by dennisfrostlander** [comment] 2018-09-03 11:34
Hi @rdebath,

Apologies for a late reply on this issue.
I have tested this now on the latest versions of AL extension and Windows client, and could not reproduce it.
Could you please double check if my steps match your initial description?

Created an AL extension like this:
```JavaScript
pageextension 50109 MyExtension109 extends "Customer Card"
{
    layout
    {
        modify(Payments)
        {
            Visible = NOT "Allow Line Disc.";
        }
    }
}
```

Then, testing in Windows client:
![hidetab](https://user-images.githubusercontent.com/16953692/44984676-ef939700-af7d-11e8-83f3-47db6be64c92.gif)

**Comment by rdebath** [comment] 2018-09-05 10:39
I've just re-confirmed the bug on V11cu8 and 12.3.23730.
However, like yourself I cannot reproduce the bug on V13 (13.0.24266)
So I expect it's on Vnext of BC (but it cannot confirm as `bcinsider.azurecr.io/bcsandbox:gb` is currently broken) and this issue can be closed.

**Comment by dennisfrostlander** [comment] 2018-09-05 11:01
Thanks for the confirmation.

**Closed by dennisfrostlander** 2018-09-05 11:01 UTC
Labels: investigate
