### ISSUE TITLE
AL0999 Compiler Error: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Kowa63** [Microsoft/AL#3883] opened 2018-09-27 12:45 UTC
It's AL0999 time again, but this time it's not ValuesAllowed ;-).

Docker sandbox NAV Version: 12.3.23590.23945-DE 
VSIX 0.16.26193 
al.enableCodeAnalysis off (tried on also, to no avail)

The project is build upon a dependency (own app) and was already successfully compiled, published and installed into a sandbox some weeks ago. Now, with a current public sandbox, a total breakdown occurs.
The background compiler shows no problems in the workspace.
Compilation with Ctrl+Shift+B leads to the following output. Any hints where I might look?

> error AL0999: Internal error: 'Mindestens ein Fehler ist aufgetreten.', Stack trace=unknown
Error: The package could not be created.
[Error - 1:38:01 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/documentSymbol' failed with error: 'Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.'
StackTrace:
   bei Microsoft.Dynamics.Nav.CodeAnalysis.SymbolReference.SerializableSymbolModelConverter.ResolveApplicationObjectReference(ModuleSymbol module, SymbolKind kind, Subtype subType) in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolReference\SerializableSymbolModelConverter.cs:Zeile 758.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.SymbolReference.SerializableSymbolModelConverter.ResolveElementType(ModuleSymbol module, Symbol owner, TypeDefinition typeDefinition) in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolReference\SerializableSymbolModelConverter.cs:Zeile 854.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.SymbolReference.SerializableSymbolModelConverter.ResolveType(ModuleSymbol module, Symbol owner, TypeDefinition typeDefinition) in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolReference\SerializableSymbolModelConverter.cs:Zeile 82.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ReferenceGlobalVariableSymbol..ctor(ContainerSymbol containingSymbol, VariableDefinition variable) in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Reference\ReferenceGlobalVariableSymbol.cs:Zeile 24.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ReferencePageTypeSymbol.<LazyGetMembers>b__29_0(VariableDefinition f) in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Reference\ReferencePageTypeSymbol.cs:Zeile 131.
   bei System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   bei System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bei System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   bei System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ReferencePageTypeSymbol.LazyGetMembers() in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Reference\ReferencePageTypeSymbol.cs:Zeile 129.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ReferencePageTypeSymbol.GetMembers() in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Reference\ReferencePageTypeSymbol.cs:Zeile 80.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ReferencePageTypeSymbol.GetMembers(String name) in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Reference\ReferencePageTypeSymbol.cs:Zeile 86.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.TypeSymbol.Microsoft.Dynamics.Nav.CodeAnalysis.IContainerSymbol.GetMembers(String name) in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\TypeSymbol.cs:Zeile 35.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceAttributeSymbol.FindEvent(Compilation compilation, SymbolKind objectKind, Int32 objectId, String eventName, Location applicationIdLocation) in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceAttributeSymbol.cs:Zeile 199.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceAttributeSymbol.FindEventMethod() in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceAttributeSymbol.cs:Zeile 183.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceAttributeSymbol.LazyGetEventMethod() in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceAttributeSymbol.cs:Zeile 167.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.SourceMethodOrTriggerSymbol.InternalCheckEventSubscriber(AttributeSymbol attribute, DiagnosticBag diagnostics) in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceMethodOrTriggerSymbol.cs:Zeile 530.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.SourceMethodOrTriggerSymbol.CheckEventAttribute(DiagnosticBag diagnostics) in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceMethodOrTriggerSymbol.cs:Zeile 458.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.SourceMethodOrTriggerSymbol.LazyMethodChecks() in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceMethodOrTriggerSymbol.cs:Zeile 251.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.SourceMethodOrTriggerSymbol.get_Parameters() in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceMethodOrTriggerSymbol.cs:Zeile 386.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.SymbolDisplayVisitor.VisitMethod(MethodSymbol symbol) in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolDisplay\SymbolDisplayVisitor.cs:Zeile 386.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.SymbolDisplay.ToDisplayParts(ISymbol symbol, SemanticModel semanticModelOpt, Int32 positionOpt, SymbolDisplayFormat format, Boolean minimal) in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolDisplay\SymbolDisplay.cs:Zeile 106.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbol.ToDisplayString(SymbolDisplayFormat format) in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Symbol.cs:Zeile 504.
   bei Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.DocumentExtensions.<>c__DisplayClass0_0.<GetSymbolInformations>b__2(ISymbol s) in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\DocumentExtensions.cs:Zeile 36.
   bei System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   bei System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bei System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   bei Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.DocumentExtensions.<GetSymbolInformations>d__0.MoveNext() in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\DocumentExtensions.cs:Zeile 0.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DocumentSymbolRequestHandler.<HandleAsync>d__3.MoveNext() in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DocumentSymbolRequestHandler.cs:Zeile 32.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:Zeile 59.

**Comment by Deepakalle123** [comment] 2018-10-24 11:19
is there any update why this is happening,same issue i am also facing ,earlier with the same compuiler it was working now on new environment it is giving error.

**Comment by atoader** [comment] 2018-11-02 12:16
Hi! Could you provide code that reproduces this issue? It looks like the problem is coming from a subscriber to an event from a page in your extension.

**Comment by atoader** [comment] 2018-11-02 12:19
You can try compiling the first extension with the latest version of the AL Language extension. Take the app file and copy it into the .alpackages folder of the second extension.

**Comment by atoader** [comment] 2018-11-12 07:40
I will assume that this problem does not reproduce anymore and close this issue. Feel free to reopen the issue and add steps to reproduce the problem on the latest build.

**Closed by atoader** 2018-11-12 07:40 UTC
Labels: bug, input-needed
