### ISSUE TITLE
System.FormatException if ID is not in Range

### ISSUE THREAD

**Issue by FSchneiderYav** [microsoft/AL#4976] opened 2019-05-16 11:31 UTC
**Describe the bug**
When I create for example a new Page with a ID who is not in my App ID Range then I got aSystem.FormatException

**To Reproduce**
1. go in the app.json file and add
  "idRange": {
    "from": 50000,
    "to": 51000}

2. Create a new Object. For example a Page with a ID who is not in the Range
page 59999 "New Page out of range"
{
}

3. Now will the extension crash

**Versions:**
 - AL Language: 3.0.107312

**Comment by qutreson** [comment] 2019-05-16 19:02
This looks like a duplicate of #4628.

Please use the latest extension from the marketplace: 3.0.126610 to get the fix.

**Closed by qutreson** 2019-05-16 19:02 UTC
