### ISSUE TITLE
Issue converting Blockchain value to decimal

### ISSUE THREAD

**Issue by johndcollins** [microsoft/AL#6699] opened 2021-07-07 17:58 UTC
I'm trying to import a wallet value from a blockchain to display on a page for the accounting department. 
The value from the web service api is 0x1b1ae4d6e2ef500000 which is equal to 500000000000000000000 and this would then be equal to 500.00 coins as it's based of 18 decimal places.

There is no way to import a large number like this and convert it to a decimal value. We only have BigInteger which is not large enough. We need a function to convert a hex value to a decimal value based on a specific number of decimal places and a very large Integer.

**Comment by db-bc** [comment] 2021-07-08 08:43
You don't *need* a very large integer, as the ultimate result can fit in a decimal, so you could take the arriving hex value as a string, parse that digit by digit, and accumulate it into a decimal with each step already divided by the right number of places.

I don't imagine this is a common enough requirement for BC to provide a function, and especially not a new integer type; the issue is not that you need to store a number that large, but rather that an intermediate representation _seems_ larger. In any case, it doesn't seem like an issue for this repo to me, although of course I could be wrong...

**Comment by nndobrev** [comment] 2021-07-08 09:33
Hi @johndcollins, I think you should follow @db-bc  advice and write a parser yourself converting a hexadecimal string to decimal. I believe **Decimal** type in AL would serve the purpose to store it. 

You can also see how "big" **Decimal** is here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/decimal/decimal-data-type

Thank you, I will close this as it seems to not be related to the AL language itself.

**Closed by nndobrev** 2021-07-08 09:33 UTC

**Comment by johndcollins** [comment] 2021-07-08 15:22
I'd like to ask how you would calculate this in BC then. This is the calculation of each individual hexvalue:
(1 × 16¹⁷) + (11 × 16¹⁶) + (1 × 16¹⁵) + (10 × 16¹⁴) + (14 × 16¹³) + (4 × 16¹²) + (13 × 16¹¹) + (6 × 16¹⁰) + (14 × 16⁹) + (2 × 16⁸) + (14 × 16⁷) + (15 × 16⁶) + (5 × 16⁵) + (0 × 16⁴) + (0 × 16³) + (0 × 16²) + (0 × 16¹) + (0 × 16⁰) 

(1 × 16¹⁷) for example is 1,600,000,000,000,000,000 which larger than what I can fit in a variable in BC. This could of cause be even larger as this just represents a value of 500.
999,999,999,999,999.99 is the largest I can fit in a decimal.

**Comment by db-bc** [comment] 2021-07-08 15:42
I didn't sit and try to do it, but I _think_ something like this should work...

Chop the hex string into sections small enough that you can work with them (a single digit at a time, if you like) .Convert each section to a decimal. Divide that down by whatever power of 10 is needed to put it in the correct place wrt the decimal point. Multiply it up according to its position in the hex string (so the LSbyte character by 1, next char by 16, next by 32, etc.). Each time, add the result to a decimal variable, and maybe round at the end, and that should be it.

It is not something that I see being the AL language or BC runtime's responsibility to solve for you, given how it's probably a relatively infrequent need, and you can use existing smaller types to do that calculation.

**Comment by johndcollins** [comment] 2021-07-08 15:56
Ok, thanks @db-bc, I'll try that.

**Comment by db-bc** [comment] 2021-07-08 16:32
Hmm, maybe then you can multiple iteratively, by 16 each time, or suchlike. Hopefully it won't overflow the Decimal if you already scaled the value down to the right place wrt decimal point. I didn't think it through in too much depth, so maybe there's a detail that breaks the whole thing, but worth a try for you anyway hopefully ;-)

**Comment by johndcollins** [comment] 2021-07-08 16:38
Thanks again for your comments, always good to get another perspective.
I see Blockchain being more and more popular. We just have one customer requesting this now, but I'm sure this will change very soon.

**Comment by johndcollins** [comment] 2021-07-08 17:38
Ok, so just an update. I didn't see this in the Decimal Type definition:
**Maximum calculating value.This is the maximum value that can be calculated by code statements while not assigning to a field variable, storing to the database, or formatting to a text variable. | +/- 79,228,162,514,264,337,593,543,950,335**

I was able to create a function which now calculates the correct wallet value. I was trying to use a BigInt for this before as I thought that was bigger than the decimal field.

Thanks again for your help.

**Comment by db0451** [comment] 2021-07-08 19:39
Good to know, and glad to hear you figured it out and I was able to help in some way :-)

**Comment by db-bc** [comment] 2021-07-08 19:41
Good to know, and glad to hear you figured it out and I was able to help in some way :-)
