### ISSUE TITLE
Unable to assign values when passing an array of variants to a method.

### ISSUE THREAD

**Issue by DavyVerbeek** [Microsoft/AL#3105] opened 2018-08-02 08:40 UTC
I am unable to assign values when passing an array of variants to a method.
When I assign an arrayvalue to a field, I get the following error:

Typeconversion of the expression Microsoft.Dynamics.Nav.Runtime.NavIndirectValue to a Microsoft.Dynamics.Nav.Runtime.NavText-value is not possible.

- AL Extension Version: 0.16.19969

    procedure ArrayVarTest();
    var
        VariantArray : array [3] of Variant;
    begin
        VariantArray[1] := 1;                //Option(integer)
        VariantArray[2] := 2.99;           //Decimal
        VariantArray[3] := 'TestText';   //Text
        PassArrayToMethod(VariantArray);
    end;

    procedure PassArrayToMethod(VariantArray : array [3] of Variant);
    var
	OptionField : Option;
	DecimalField : Decimal;
	TextField : Text;
    begin
	OptionField := VariantArray[1];
	DecimalField := VariantArray[2];
	TextField := VariantArray[3];
    end;

**Comment by DavyVerbeek** [comment] 2018-09-14 11:33
Is this being investigated? Or should I try and think of a workaround?

**Comment by StanislawStempin** [comment] 2018-10-09 15:14
This is a potential bug and on our investigation backlog. We have a lot of cases right now so can't comment on the resolution time.

**Comment by esbenk** [comment] 2018-10-09 15:20
Is this working with C/AL?

**Comment by DavyVerbeek** [comment] 2018-10-09 15:33
Yes this should work in C/AL.

**Comment by JohanStenberg100** [comment] 2018-10-30 14:40
Hi @DavyVerbeek! Thanks for reporting this issue. With VS Code version 1.28.2, AL Extension version 2.0.48254 and the latest cloud sandbox, I can't reproduce your issue. Here is my AL file:

```
pageextension 50150 MyExtension extends "Customer List"
{
    trigger OnOpenPage();
    var
        VariantArray: array[3] of Variant;
    begin
        VariantArray[1] := 1; //Option(integer)
        VariantArray[2] := 2.99; //Decimal
        VariantArray[3] := 'TestText'; //Text
        PassArrayToMethod(VariantArray);
    end;

    procedure PassArrayToMethod(VariantArray: array[3] of Variant);
    var
        OptionField: Option;
        DecimalField: Decimal;
        TextField: Text;
    begin
        OptionField := VariantArray[1];
        DecimalField := VariantArray[2];
        TextField := VariantArray[3];

        Message(Format(OptionField));
        Message(Format(DecimalField));
        Message(TextField);
    end;
}
```

The values are printed correctly here. Can you try this out again? If you are running another version of BC / NAV, please contact the regular support channel:

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company. For more details please read: 

* [https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/](https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/)
* [https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do](https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do)

Thanks again for reporting this issue.

**Comment by StanislawStempin** [comment] 2018-11-07 12:29
Closing due to the fact that we couldn't reproduce the issue and for lack of additional input.

**Closed by StanislawStempin** 2018-11-07 12:29 UTC
Labels: input-needed
