### ISSUE TITLE
DownloadFromStream multiple files in web client

### ISSUE THREAD

**Issue by FSchneiderYav** [microsoft/AL#5093] opened 2019-06-26 11:45 UTC
Hello,

I call the following function two times in a row. But the web client downloads only the second file. The RTC downloads both.
```
local procedure DownloadLog(var piTempBlob: Record TempBlob temporary; piFileName: Text)
var
    lstmiLog: InStream;
    lFileName: Text;
begin
    Clear(lstmiLog);
    lFileName := piFileName;
    piTempBlob.CalcFields(Blob);
    piTempBlob.Blob.CreateInStream(lstmiLog);
    DownloadFromStream(lstmiLog, '', '', '', lFileName);
end;
```

**Versions:**
 - AL Language: 3.0.107312
 - Business Central:14.0.29487.0

**Comment by OleTeichmann** [comment] 2019-06-26 12:07
Duplicate of #3575
We solved it by archiving the files in a zip archive

**Comment by FSchneiderYav** [comment] 2019-06-26 12:19
I think that's a bug. I don't want to zip it. And It should be posible to download multiple files.

**Comment by OleTeichmann** [comment] 2019-06-26 12:37
Yes its already in the client team backlog

**Comment by thloke** [comment] 2019-06-27 08:40
@OleTeichmann - thanks for responding. Yes, this is in the backlog for the client team already. Closing.

**Closed by thloke** 2019-06-27 08:40 UTC

**Comment by dnpb** [comment] 2021-09-29 13:49
[On Yammer](https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1408260536655872), Andreas Glöckner [indicates](https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1408260536655872) that changing your browser/settings might enable multiple downloads to work:

> But sometimes the browser ask like "the website is triying to download mulitple files. Do you want to allow that?". I think that would be more practial.
>
>Nevertheless, with your answer I looked up my browser (edge) settings and could find a solution that may makes it easier. Want to share it here:
>
>Search for "automatic download" ("automatische downloads").
>
>The first settings says exactly what I wrote in the beginning (see screenshot) but it is not considered by BC? Maybe another setting or a "bug"?
>
>I just added my localhost to allow multiple downloads and suddenly my client downloads multiple files simultaneously :)
>
>Hope this might help.
>
> ![image](https://user-images.githubusercontent.com/63455896/135281410-0e968518-8d78-41a6-9a2a-07f5c69d5200.png)

Both these issues say this is on the client team's backlog. I don't know whether that's still the case, whether they know about this setting, etc. - but maybe it's not fully under their control?
