### ISSUE TITLE
Changes to Launch.json, requires Close Folder,Open Folder

### ISSUE THREAD

**Issue by JSebastianN** [Microsoft/AL#3276] opened 2018-08-15 08:30 UTC
When making a change in Launch.json.

The changes does not take effect until VSCode is restarted or at least, the Folder is re-opened.

- AL Extension Version: 0.17.30289

**Comment by Deepakalle123** [comment] 2018-08-16 06:10
Have you tried in older version- i have 0.16.19969  it is getting changed without restarting or re-opened

once save the file have you tried with click on refresh.

**Comment by JSebastianN** [comment] 2018-08-16 07:47
Thanks @Deepakalle123 
I have tried with 0.16.26913 and it works there.
So it's a bug in newer versions it seems.

Not a big deal, just wanted to add it to the backlog :)

**Comment by Deepakalle123** [comment] 2018-08-16 09:51
Welcome @JSebastianN  ok no issue..

**Comment by JohanStenberg100** [comment] 2018-10-30 14:47
Hi @JSebastianN, thanks for reporting this issue. I can't reproduce your issue with VS code version 1.28.2 and AL Extension version 2.0.48254 on the Online Sandbox environment.

Can you try and upgrade your extension and possibly VS Code version and try to reproduce this issue?

**Comment by StanislawStempin** [comment] 2018-11-07 12:30
Closing due to the fact that we couldn't reproduce the issue and for lack of additional input.

**Closed by StanislawStempin** 2018-11-07 12:30 UTC
Labels: input-needed
