### ISSUE TITLE
BC Version from Runtime Package

### ISSUE THREAD

**Issue by lktraser** [microsoft/AL#7153] opened 2022-09-02 07:15 UTC
**Question**
Is there a way to identify the BC version a Runtime Package was created against just from the app itself? Since the ServiceTier can obviously identify this it would be great if we had a way to do this via Powershell. For us it would be helpful to have this for ISVs from other partners who provide us with different runtimes but we have to store them in a recognisable way.

Thanks in advance, Leon

**Comment by freddydk** [comment] 2022-09-02 07:39
Transferring to the AL repo

**Comment by thloke** [comment] 2024-04-11 04:05
A year and a half later (sorry) : right now we have no way of doing this, so this will be a new feature. It sounds useful though.

Since this is an improvement and not a bug, you can post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Closed by thloke** 2024-04-11 04:05 UTC
Labels: question
