### ISSUE TITLE
Unbound Action completes but request still runs into a timeout

### ISSUE THREAD

**Issue by ChrisChristophers** [microsoft/AL#7777] opened 2024-06-21 10:02 UTC
**1. Describe the bug**

When consuming the UnboundAction via POST request Business Central fails to deliver the following payload.

[UnboundAction.json](https://github.com/user-attachments/files/15924372/UnboundAction.json)

**2. To Reproduce**
Create an Unbound Action as demonstrated in the following picture: 
(Read the payload from the attached file UnboundAction.json into a jsonObject and write it into the outputtext) 
![image](https://github.com/microsoft/AL/assets/118542597/dbf6e655-a5b7-49a0-8d54-d5a57266976d)
Consume the API e.g. with Postman/KeyRunner etc.

**3. Expected behavior**
The  request should be completed without issues
**4. Actual behavior**

![image](https://github.com/microsoft/AL/assets/118542597/047d4e0f-8d3b-43c1-9109-f7107189b26e)

While the code within the UnboundAction executes with no issues and the request even returns a Status 200 according to requesting party , the request runs into a timeout.

It is worthy to mention, that if i remove 4 field ( doesn't matter which ones)  from contractLines  so the total fieldnumber is 74 the request completes without issues 

![image](https://github.com/microsoft/AL/assets/118542597/dc72401f-7baf-4934-af92-e186ee8ca4ea)

**5. Versions:**

- AL Language:  Runtime 13.0 
- Visual Studio Code: 1.90.2
- Business Central: Version: DE Business Central 24.0 (Platform 24.0.20409.0 + Application 24.0.16410.18056)
- List of Visual Studio Code extensions that you have installed: AL Language Extension

**Comment by wbor-nvt** [comment] 2024-06-21 14:09
Running into the same issue.

Testing API's via Postman on a BC24 environment in a local Docker Container on Windows 10.
It appears easy to reproduce by calling the $metadata api.

This has made testing of api's very difficult, hoping for a fix for this problem.

**Comment by BazookaMusic** [comment] 2024-06-21 21:17
Hi, this issue is out of scope of for this repository. You should do one of the following:

Open a support request to CSS through the PartnerSource portal
Open a bug in Collaborate
Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company


As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

**Comment by BazookaMusic** [comment] 2024-06-21 21:18
Also feel free to post this on yammer, it seems to be an issue with the runtime and this repo does not track these issues

**Closed** 2024-06-22 12:45 UTC
