### ISSUE TITLE
Extension Table field cannot be used in a property (Editable/Visible) at a page

### ISSUE THREAD

**Issue by Easystep2** [microsoft/AL#6191] opened 2020-10-02 09:36 UTC
**Describe the bug**
When using a new field in an extension (by example Customer Table) in a page to set the properties Editable, we receive an error when loading/opening the page "Cannot find <FieldName>!

**To Reproduce**
Steps and to reproduce the behavior:
 Set a boolean expression includsing the Field in the property, but only occurs after removing the Im/Explicit with statement warning in code by adding Rec.<FieldName>

``` AL Code to reproduce the issue ```

![image](https://user-images.githubusercontent.com/17320737/94909132-04b3ba80-04a3-11eb-89c2-e1229d039dde.png)

The problem is solved by moving the expression to a Boolean variable and by setting the variable in a local procedure

![image](https://user-images.githubusercontent.com/17320737/94909216-26ad3d00-04a3-11eb-8e5e-8ee5a2500784.png)

**Expected behavior**
Either throw a compile error or warning but the code compiles normally but the page cannot be opened!!

**Screenshots**

**5. Versions:**

 - AL Language:  v6.0.344420

 - Business Central: 

![image](https://user-images.githubusercontent.com/17320737/94909472-83105c80-04a3-11eb-9367-1a1770fb9ea6.png)

**Comment by dtkb** [comment] 2020-10-02 12:37
seems like basically a dupe of https://github.com/microsoft/AL/issues/6189 and hence https://github.com/microsoft/AL/issues/6095 and others.

**Comment by kalberes** [comment] 2020-10-02 17:18
Yes, they are all duplicates. Looks like we forgot to backport an important fix.
@esbenk  @qutreson

**Comment by Easystep2** [comment] 2020-10-06 08:57
Great we see it coming:-)

**Comment by esbenk** [comment] 2020-10-06 11:56
What is the server runtime version? 16?

**Comment by ABaludin** [comment] 2020-10-19 14:53
Just got the same error. Want to subscribe on bug status.
Throws warning if you use any "Rec." in editable\visible property. Without Rec. works ok.

For example:

Page extension for Sales Order Subform.
Any field property:
Editable = (Rec.Type = Rec.type::Item);

Result on open page:
The identifier 'Rec.Type' could not be found.

**Comment by esbenk** [comment] 2020-10-19 18:07
Using Rec. in property expressions is not (and will not be) supported in server versions before 17.x. The compiler will issue warnings when runtime < 7.0.

**Comment by dtkb** [comment] 2020-10-20 15:53
another dupe: #6048

**Comment by db0451** [comment] 2021-03-23 09:39
> Using Rec. in property expressions is not (and will not be) supported in server versions before 17.x. The compiler will issue warnings when runtime < 7.0.

When are these warnings going to be implemented? People are still encountering duplicates of this: https://github.com/microsoft/AL/issues/6548

**Comment by nndobrev** [comment] 2021-07-29 10:12
Dear @Easystep2, we think this has been fixed. Please feel free to reopen if you can reproduce it again on our latest version.

**Closed by nndobrev** 2021-07-29 10:12 UTC
Labels: bug, in-progress

**Comment by marcowintherJCD** [comment] 2026-02-05 08:08
@nndobrev @kalberes I have this exact issue in a 27.2 Sandbox. Was this somehow reintroduced?
