### ISSUE TITLE
VS Code Debugger shows incorrect Variable fields

### ISSUE THREAD

**Issue by daansaveyn** [microsoft/AL#5674] opened 2020-02-17 10:53 UTC
**Describe the bug**
VS Code sometimes shows incorrect variable fields in the debugger: the first screenshot shows a record variable TempAddress of type "NVT Transportaddress". Below the variable the fields ("Entry No.", "Anomaly Type",...") are displayed.  The second screenshot shows the actual fields of the "NVT Transportaddress" table: the fields "Entry No.", "Anomaly Type",... are nowhere to be seen in this table. In fact, the debugger shows the variables of the Rec variable (in which a function using the "NVT Transportaddress" function is present (see third & fourth screenshot).  

**To Reproduce**
(See Screenshots & info above)

**Expected behavior**
The debugger shows the correct fields for a variable

**Screenshots**
![image](https://user-images.githubusercontent.com/48217797/74646942-11d1a280-517b-11ea-9e75-c4582e0ff098.png)

![image](https://user-images.githubusercontent.com/48217797/74647155-72f97600-517b-11ea-9820-8d7c05e435f6.png)

![image](https://user-images.githubusercontent.com/48217797/74647403-df747500-517b-11ea-8638-d4a11536acab.png)

![image](https://user-images.githubusercontent.com/48217797/74647439-ea2f0a00-517b-11ea-96df-4fcad1ac8562.png)

**5. Versions:**

 - AL Language: 
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 5.0.229698
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

 - Business Central:
Version: W1 15.2 (Platform 15.0.38951.0 + Application 14.0.29530.0)

**Comment by kalberes** [comment] 2020-02-18 14:53
Do you by any chance have another global variable called TempAddress or any variable that may be in scope and is called like that?

**Comment by daansaveyn** [comment] 2020-02-18 15:05
> Do you by any chance have another global variable called TempAddress or any variable that may be in scope and is called like that?

Not that I can see. All other TempAddress variables are of the record type "NVT Transportaddress" anyway. Ihave this issue quite frequently. I can send you another sample if I encounter it again.

**Comment by kalberes** [comment] 2020-02-19 08:03
I have meant whether the name TempAddress is already used in the document's scope. If yes that is the issue and it is by design. The type does not matter for the debug engine, only the scope. If you have a variable with the same name in global scope that takes precedence in evaluation. If possible try using different names for your variables.

**Comment by daansaveyn** [comment] 2020-02-19 08:04
> I have meant whether the name TempAddress is already used in the document's scope. If yes that is the issue and it is by design. The type does not matter for the debug engine, only the scope. If you have a variable with the same name in global scope that takes precedence in evaluation. If possible try using different names for your variables.

That makes since and I'm aware of that. But this is not the case in the sample above.

**Comment by kalberes** [comment] 2020-02-19 08:07
If you can find a simple repro it would help us fixing the issue. Otherwise it is just guessing.

**Comment by daansaveyn** [comment] 2020-02-19 08:37
> If you can find a simple repro it would help us fixing the issue. Otherwise it is just guessing.

I've just created a sample but the issue does not occur at this point. We've had this problem at multiple occasions, but reproducing will be quite hard I'm afraid. I'll try to provide some extra samples when it occurs again. It might have something to do with WITH statements (of which we use plenty), but I'm not 100% sure.

**Comment by atoader** [comment] 2020-04-02 09:57
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Closed by atoader** 2020-04-02 09:57 UTC
Labels: input-needed
