### ISSUE TITLE
Webclient crash (FormNotFoundException)

### ISSUE THREAD

**Issue by fvet** [Microsoft/AL#169] opened 2017-04-25 20:29 UTC
While creating a custom setup page (similar to 'Sales & Receivables Setup') containg the trigger code below and debugging the code using the 'message' function ...

_trigger OnOpenPage();
  begin
    RESET;
    IF NOT GET THEN BEGIN
      INIT;
      INSERT;
    END;
    **message('text');**
  end;_
 
... the Webclient keeps crashing (tested on the april update) when closing the page. Here's an extract of the eventlog (same as reported in #122 ):

_Error accessing Website Microsoft Dynamics NAV TENERIFE Web Client
Raw Url: /Navision_main/WebClient/cbs?aid=NAV
Url: http://localhost:8080/Navision_main/WebClient/cbs?aid=NAV
Type: Microsoft.Dynamics.Framework.UI.FormNotFoundException
Message: The logical form as specified in parameter with name 'LogicalControlReference' could not be found in the current session.
StackTrace:
   at Microsoft.Dynamics.Framework.UI.InteractionParameterHelper.GetLogicalControl(UISession uiSession, ClientLogicalControlReference clientLogicalControlReference)
   at Microsoft.Dynamics.Framework.UI.Client.InvokeActionExecutionStrategy.Initialize(IInteractionContext context, IDictionary`2 namedParameters)
   at Microsoft.Dynamics.Framework.UI.InteractionManager.&lt;InvokeInteractions&gt;d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Framework.UI.WebBase.WebBaseInteractionManager.&lt;InvokeInteractions&gt;d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Framework.UI.CultureAwaiter`1.GetResult()
   at Microsoft.Dynamics.Framework.UI.Web.WebInteractionManager.&lt;InvokeInteractions&gt;d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Framework.UI.CultureAwaiter`1.GetResult()
   at Microsoft.Dynamics.Framework.UI.Web.CallbackHandler.&lt;HandleRequestCore&gt;d__4.MoveNext()
Source: Microsoft.Dynamics.Framework.UI_

Calling the page directly via the browser with 
http://localhost:8080/Navision_main/WebClient/default.aspx?company=CRONUS%20USA%2C%20Inc.&page=70051000 shows the message once (OnOpenPage) and a second time when closing the page (?), making the Webclient to crash as well.

**Comment by StanislawStempin** [comment] 2017-05-01 07:58
I cannot reproduce neither of the issues. Could you provide a complete code sample that causes this condition?

**Comment by StanislawStempin** [comment] 2017-05-09 19:28
I will close this issue for now. Please reopen if you can still reproduce on April Update bits or later.

**Closed by StanislawStempin** 2017-05-09 19:28 UTC
Labels: bug, input needed
