### ISSUE TITLE
Codeunit 80 - OnBeforePostUpdateOrderLine is not called while posting Sales transaction in Extension 2.0 build

### ISSUE THREAD

**Issue by chavansachin20** [Microsoft/AL#1885] opened 2018-03-29 12:11 UTC
in Extension 1.0 we have raised custom event which is not working in Extension 2.0. 

Event details 
```
    [EventSubscriber(ObjectType::Codeunit, 80, 'OnBeforePostUpdateOrderLine', '', false, false)]
    local procedure OnBeforePostUpdateOrderLine(SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line");
    var
        LocalSalesLine: Record "Sales Line";
    begin
        //this will use updated sales line while creating sales invoice lines with updated tax
        message('Posted lines updated');
            SalesLine.DELETEALL;
            LocalSalesLine.SetRange("Document Type", SalesHeader."Document Type");
            LocalSalesLine.SetRange("Document No.", SalesHeader."No.");
            if LocalSalesLine.FindSet then
                repeat
                    SalesLine := LocalSalesLine;
                    SalesLine.Insert;
                until LocalSalesLine.Next = 0;
    end;
```

**Comment by chavansachin20** [comment] 2018-04-03 05:33
**Purpose** of this event : update TempSalesLineGlobal with new values (in our case : update Tax amount on sales line) which will be used to create Sales Inv Line. 
**Expected behavior** : Sales Invoice line will have **Amount including Tax** with **Tax amount**  updated properly.
**current behavior** :  Sales Invoice line is created without **Tax amount** have **Amount including Tax** updated properly.

**Comment by StanislawStempin** [comment] 2018-04-06 14:58
We will treat this issue as an event request.

It is not clear to us why your custom event didn't fire. You should mark it as FunctionVisibility = External in C/SIDE and then regenerate your symbol files. See https://github.com/Microsoft/AL/wiki/Useful-resources

**Comment by thpeder** [comment] 2018-04-12 09:15
Hi @chavansachin20,
If you are not using the sandbox, then could you try and see if the virtual table "Event Subscription" contains some more information why your subscription isn't called.

**Comment by chavansachin20** [comment] 2018-04-17 10:10
@StanislawStempin , this was working in Ext 1.0 and in latest release (Extn. 2.0), this is not called which resulted in to wrong amount updated to Posted transactions (Sales invoice lines with wrong amount + tax amount)

**Comment by thpeder** [comment] 2018-06-13 07:44
Hi @Chavansachin20,
I'm not able to reproduce the issue you are having. I create a new Event on Codeunit 80 "Sales-Post", as a local procedure with FunctionVisibility as Internal and matched the parameters. I then created a procedure next to it to invoke it which I made a available for extensions. In my extension I have a page action to invoke said function and a codeunit to subscribe to this event and it works for me.

Which version of the server and the extension are you running?
Have you checked if the Virtual Table "Event Subscription" contained any more information?
Is there anything in the event viewer?

**Comment by chavansachin20** [comment] 2018-06-26 05:45
@thpeder  please see below screenshot : Error Information is blank.

![image](https://user-images.githubusercontent.com/5293496/41891482-3c7b0940-7932-11e8-9e67-6b2fa00aa38e.png)

**Comment by thpeder** [comment] 2018-06-26 10:59
@chavansachin20, Thanks for sending the screenshot.
Could you try and regenerate the symbol file and download it to your project, like StanislawStempin recommended.

**Comment by chavansachin20** [comment] 2018-07-05 06:42
After changes made inside my docker for CU80, my docker is corrupted, resolving my docker issue.
Once complete my changes suggested for CU80 by @StanislawStempin will test and update status here.
code changes :  FunctionVisibility = External in C/SIDE

**Comment by chavansachin20** [comment] 2018-07-11 08:01
@thpeder : I have followed below steps:

1. applied changes to CU 80 and set FunctionVisibility = External in C/SIDE for **OnBeforePostUpdateOrderLine**.
2. Reloaded symbols successfully.
3. event subscription list (no error)
![image](https://user-images.githubusercontent.com/5293496/42558370-a1439292-850e-11e8-8d34-6ec7bcef05e3.png)
4. But while accessing it from VS code getting error as below 
![image](https://user-images.githubusercontent.com/5293496/42558006-9d99b9a6-850d-11e8-844c-3d510b87c7e8.png)


please suggest further steps.

**Comment by thpeder** [comment] 2018-07-11 09:00
Hi @chavansachin20,
For your symbols to contain the new parameter you need to open C/Side with `generatesymbolreference=yes` and for your case probably recompile that object. You can read more about it here: [Running C/SIDE and AL Side-by-Side](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-running-cside-and-al-side-by-side)

For the specific error in the screenshot you have flipped the type and the name, meaning it should look like `SuppressCommit: Boolean`, but intellisense should help you to find the parameters:
![image](https://user-images.githubusercontent.com/24276180/42561478-84adb5a0-84f9-11e8-9a9d-ef9975db065a.png)

**Comment by chavansachin20** [comment] 2018-07-11 11:56
@thpeder : as you suggested, mage changes to **FunctionVisibility = External** in C/SIDE for **OnBeforePostUpdateOrderLine**. and then downloaded the symbol. but still **OnBeforePostUpdateOrderLine** is not called or tracked in my debugger.

**Comment by thpeder** [comment] 2018-07-11 12:36
@chavansachin20,
Can you please send the minimum amount of changes to your database, the AL code and the steps needed to reproduce the issue.

**Comment by kalberes** [comment] 2018-07-12 08:02
Have you also changed OnBeforePostUpdateOrderLine not to be local?

**Comment by chavansachin20** [comment] 2018-07-12 09:52
Created below event inside my app, to write updated values to temp table with current data : 
`
[EventSubscriber(ObjectType::Codeunit, 80, 'OnBeforePostUpdateOrderLine', '', false, false)]
    local procedure SalesOnBeforePostUpdateOrderLine(SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line");
    var
        LocalSalesLine: Record "Sales Line";
    BEGIN
        //this will use updated sales line while creating sales invoice lines with updated tax
        //https://github.com/Microsoft/AL/issues/1885
        IF AVAValidateCall.IsValidDocument(SalesHeader) THEN BEGIN
            SalesLine.DELETEALL();
            LocalSalesLine.RESET();
            LocalSalesLine.SetRange("Document Type", SalesHeader."Document Type");
            LocalSalesLine.SetRange("Document No.", SalesHeader."No.");
            IF LocalSalesLine.FINDSET() THEN
                repeat
                    SalesLine := LocalSalesLine;
                    SalesLine.Insert();
                until LocalSalesLine.Next() = 0;
        END;
    END;
`

**Steps**: 
- Create a Sales Order
- insert a single line & update Tax Group Code
- Post with Ship & invoice
- open posted document you will see below results 
![image](https://user-images.githubusercontent.com/5293496/42626113-11074c26-85e7-11e8-8f1e-786aa534575e.png)

Click on navigate : open G/L entry and yo can see difference as this posted entry has tax in it
![image](https://user-images.githubusercontent.com/5293496/42626188-4a42a436-85e7-11e8-96f1-becbfb97fa31.png)

**Comment by StanislawStempin** [comment] 2018-08-03 12:00
I'm somewhat confused as to what the actual problem is. From the screenshot you shown you're running on version 12.0. This version is for Business Central cloud release only. You have no way of modifying base application in the cloud.

Can you provide the following pieces of information:
1) What is your runtime environment (Docker sandbox, online sandbox, On-Prem installer)
2) What is your Business Central version
3) What is you AL Language extension version
4) C/AL code that introduces the custom event publisher
5) AL code that subscribes to the custom event

**Comment by paragpardhi123** [comment] 2018-09-26 14:48
Hello @StanislawStempin ,

please find the answers to your questions as below : 

1. What is your runtime environment (Docker sandbox, online sandbox, On-Prem installer)
   - Docker sandbox
![image](https://user-images.githubusercontent.com/33540581/46087461-05385d00-c1c8-11e8-9124-2e5cd400dbc2.png)


2. What is your Business Central version
   - US Dynamics NAV 12.0 (21229)
![image](https://user-images.githubusercontent.com/33540581/46087489-15e8d300-c1c8-11e8-8372-28e4675931d2.png)


3. What is you AL Language extension version
   - 0.16.19969
![image](https://user-images.githubusercontent.com/33540581/46087601-4d577f80-c1c8-11e8-8c74-54b3a3059500.png)


4. C/AL code that introduces the custom event publisher
   - applied changes to CU 80 and set **FunctionVisibility = External** in C/SIDE for function -> **OnBeforePostUpdateOrderLine** as below
![image](https://user-images.githubusercontent.com/33540581/46088018-22216000-c1c9-11e8-90a4-ccddeb1ea7a7.png)


5. AL code that subscribes to the custom event
   - added below code inside "codeunit 70004822 "Ava SalesExtendCU80.al" 
![image](https://user-images.githubusercontent.com/33540581/46087423-efc33300-c1c7-11e8-99c0-2de431d597ae.png)

**Comment by paragpardhi123** [comment] 2018-10-03 05:49
hi @StanislawStempin , Are there any updates regarding this issue? Is there any more information required from our side?

**Comment by chavansachin20** [comment] 2018-10-04 14:38
@StanislawStempin , please reply to thread as we are in last phase of our release to MS for technical validation.

**Comment by StanislawStempin** [comment] 2018-10-05 11:11
I'm sorry but I still don't understand the problem. 
You are saying that you are adding a custom event publisher and at the same time you are saying that this is related to technical validation of an app for AppSource. These two statements just don't fit together. 
You cannot have any custom event publishers for an app for AppSource. If you need a new event in the base application you need to request Microsoft to add it through this GitHub forum (see any other entry marked with 'Event-Request' label for some examples).

It also looks like you're using application symbols 12.3 with a nav server at 12.0. Both need to be either on 12.3 or now on 13.0 since the Business Central Fall has been released.

**Comment by StanislawStempin** [comment] 2018-10-10 21:34
Closing this thread. Let's discuss this issue through App Source Validation team.

**Closed by StanislawStempin** 2018-10-10 21:34 UTC
Labels: input-needed
