### ISSUE TITLE
Very bad debugger performance

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#6520] opened 2021-03-09 10:48 UTC
**Describe the bug**
Likely depending on the object that the debugger is currently in, the startup, loading of variables or moving to the next step takes a very long time (10 seconds), making it unable to use.

According to https://github.com/microsoft/AL/issues/5882#issuecomment-631387001, I've created a DebuggerServices.log with a verbose log level. 
I will pass it personally to @kalberes, because it contains fragments of our IP.

**Versions:**

 - AL Language: 6.6.425415

 - VS Code: 1.54.1

**Comment by NKarolak** [comment] 2021-03-09 12:34
@dtkb Did you encounter this as well?

**Comment by dtkb** [comment] 2021-03-09 12:36
Yeah, I have noticed some quite long delays. The BC client freezes up, and VS Code starts to flash in the taskbar that it has something for me - both in fairly normal times - but then I have to sit and wait while VS Code realises that it needs to focus a particular file/line and show the debugging info for it. I didn't yet investigate to ascertain whether it's universal or affected by any particular features of projects.

**Comment by NKarolak** [comment] 2021-03-09 12:40
In my case, it seems to be related that the initial variable loading takes lots of time. The debugger itself opens quickly, but when you try to open any of the variables sections (e.g. Locals), you only see some progress indicator ... Wait 10 seconds until it's loaded, then you continue with the debugger, but that variable problem repeats in the next step. Really weird.

**Comment by kalberes** [comment] 2021-03-09 17:39
Looks like in case of Natalie RecRef.GetTable , case has perf issues resolving AL variables from the associated .net variables.
I will investigate it as far as I have some air to bread.

**Comment by NKarolak** [comment] 2021-03-10 07:49
My issue is currently on hold due to another extension (see automatic comment above). I will update or close this case as soon as possible.

**Comment by martonsagi** [comment] 2021-03-10 11:10
Hey, this issue was caused by a custom Reference provider in AL Studio extension, the provider ran excessively in debug mode. I have fixed the [issue](https://github.com/dynasist/ALStudio/issues/24) with the help of @NKarolak

**Closed** 2021-03-10 11:11 UTC
Labels: bug, debugger

**Comment by kalberes** [comment] 2021-03-12 21:09
@NKarolak , @martonsagi 
Thanks for the info.
Maybe we need to update our template that when something is reproduced then it should only be with MS extensions.
