### ISSUE TITLE
SLQ Error in Flowfield on v20

### ISSUE THREAD

**Issue by oscarfernandezkurago** [microsoft/AL#6943] opened 2022-02-21 10:40 UTC
**1. Describe the bug**
On v20 we´re getting an "An unexpected error occurred after a database command was cancelled" error that SQL Server Profiler confirms it´s an SQL error. On v19 it works fine

**2. To Reproduce**
Create two projects

- Project 1: basic dependencies and defines an extension for table Prod. Order Line and a new table Warnings
- Project 2; depends on Project 1 and defines an extension for table Prod. Order Line with a flowfield involving new table Warnings

[Link to the GitHub repository](https://github.com/oscarfernandezkurago/BCv20)

When I try to apply a filter to the FlowField created in Project 2 and error "An unexpected error occurred after a database command was cancelled" is risen.

The query that the SQL Profiler is showing is this one:

SELECT COUNT("Prod_ Order Line"."Status") AS "$CNT" FROM "default".dbo."CRONUS International Ltd_$Prod_ Order Line$437dbf0e-84ff-417a-965d-ed2bb9650972" AS "Prod_ Order Line" WITH(READUNCOMMITTED)  OUTER APPLY (SELECT  TOP (1) CAST (1 AS TINYINT) AS "Warnings$Warnings$EXISTS" FROM "default".dbo."CRONUS International Ltd_$Warnings$426a9c6d-333f-4a41-9a3a-d2a4a598c95e" AS "Warnings$Warnings" WITH(READUNCOMMITTED)  WHERE ("Warnings$Warnings"."No"="Prod_ Order Line_e8"."MyField")) AS "SUB$Warnings"  WHERE (ISNULL("SUB$Warnings"."Warnings$Warnings$EXISTS",0)=@0) OPTION(FAST 50)

**3. Expected behavior**
Filter applied with no errors.

**4. Actual behavior**
Error "An unexpected error occurred after a database command was cancelled"

**5. Versions:**

AL Language: v9.0.578744
Visual Studio Code: 1.64.2
Business Central: 20.0.36137.0

**Comment by krishnaGottuparthi** [comment] 2022-03-04 06:10
We are also facing same issue with flowfield when a filter is applied.
This problem occurs only in BC20 and works fine with BC19

**Comment by kalberes** [comment] 2022-03-05 12:39
@oscarfernandezkurago 
And what is the exact repro step? What page have you opened, what action have you run?

**Comment by krishnaGottuparthi** [comment] 2022-03-07 05:43
@kalberes Since the issue is reproable, can we expect the fix in BC 20.0 version?

**Comment by jehelles** [comment] 2022-03-08 09:39
Thanks for reporting this issue, it has been fixed and will be included in the final version of v20.

**Closed by jehelles** 2022-03-08 09:39 UTC
Labels: accepted
