### ISSUE TITLE
Built-In Workflow Approval - error when referencing page from extension

### ISSUE THREAD

**Issue by RonSkalski** [Microsoft/AL#1824] opened 2018-03-20 16:10 UTC
We have an extension that works with the built-in Workflow approval. When an approval request exists, the approval list looks up the caption of the page to review the record. Since Object is not aware of the extension tables, the code below in table 454 - Approval Entry cannot find the page caption. I changed the code as shown in a test environment to get around the problem temporarily. 

RecordCaption() : Text
IF NOT RecRef.GET("Record ID to Approve") THEN
  EXIT;
PageNo := PageManagement.GetPageID(RecRef);
IF PageNo = 0 THEN
  EXIT;
//Changed to work with Extension objects
//Object.GET(Object.Type::Page,'',PageNo);
//Object.CALCFIELDS(Caption);
//EXIT(STRSUBSTNO('%1 %2',Object.Caption,"Document No."));

AllObject.GET(AllObject."Object Type"::Page, PageNo);
EXIT(STRSUBSTNO('%1 %2',AllObject."Object Caption","Document No."));

**Comment by JesperSchulz** [comment] 2018-03-21 10:49
Thank you for reporting this issue. I actually think, this issue should be resolved in the platform, rather than in the app. Just like the AllObj table contains extension objects, so should the Object table. I have created a bug for the platform team and will await their feedback.

**Comment by JesperSchulz** [comment] 2018-03-21 15:23
I received reply from the platform team and the behavior is "By Design" as the Object table is available to multiple tenants and it hence can't disclose which extensions are installed on given tenants. I will hence go though our application code and identify all places, where we need to change this. Most places should have  been fixed, but it would appear we're missed at least one spot. Thanks again for reporting!

**Comment by JesperSchulz** [comment] 2018-03-29 12:24
I haven't found a suitable solution yet. The one I think you suggest won't work, as the AllObj table only contains object names, which are always in English, whereas captions are translated. Your sample code does state AllObject."Object Caption" though, which I can’t seem to find anywhere. Which table are you referring to?

**Comment by JesperSchulz** [comment] 2018-03-29 12:31
Thank you for your suggestion. I had a little problem finding which table you were referring to, but I assume it's record 2000000058 - "AllObjWithCaption", which does the trick nicely. I will fix the code as you suggest. Thanks again!

**Closed** 2018-05-25 11:52 UTC
Labels: application, bug, shipped
