### ISSUE TITLE
Ensure that local variable/parameter names do not conflict with Field names inside a 'with' statement

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/AL#5752] opened 2020-03-26 15:33 UTC
**Title**
Ensure that local variable/parameter names do not conflict with Field names inside a 'with' statement.

**Description**
Ensure that local variable/parameter names do not conflict with Field names inside a 'with' statement. There is an error shown if this is the case inside a table object (Argument x: must be a member"). I assume this is because of a higher priority of local variables against globals/fields.
But when used inside a with-block, the same rules should apply or additional rules should jump in to avoid any conflict.

**Reason for the rule**
This can cause the application to not work as intended, because in a with-block, local variables with same names as table fields do not trigger any codecop rules but instead are handled like they were the record fields.

**Bad code sample**
This Table contains fields Code and Description.

```
    // No warning, description is interpreted as Description
    procedure Lala2(description: Text[50])
    var
        thisTable: Record "This Table";
    begin
        with thisTable do begin
            Validate("Description", description);
        end;
    end;

    // No warning, code is interpreted as Code. Reads the current record again if Code contains a value.
    procedure Lala5(code: Code[10])
    var
        thisTable: Record "This Table";
    begin
        with thisTable do begin
            if not Get(code) then begin
                exit;
            end;
        end;
    end;
 ```

**Good code sample**

``` 
    var
        NewDescription: Text[50];

    // Shows Argument 1: must be a member
    procedure Lala(description: Text[50])
    begin
        Validate("Description", description);
    end;

   // Works, no conflicts, even with the global having the same name (which is OK)
    procedure Lala3(newDescription: Text[50])
    begin
        Validate("Description", newDescription);
    end;

    // Works, no conflicts, locals have priority
    procedure Lala4(code: Code[10])
    begin
        if not Get(code) then begin
            exit;
        end;
    end;
 ```

**Good and bad practices for fixing the rule**
Local variable and parameter names should never conflict with table fields in a with-block.

**Remarks**

**Comment by qutreson** [comment] 2020-04-21 06:00
Related, as we are now reporting a warning for with constructs: #5817

**Comment by esbenk** [comment] 2020-04-21 07:36
Please read the comment in #5817 for why we are starting to warn about the use of with. Your examples highlights the ambiguity issues with the with-statement, but the risk of breaking dependent extensions is the main driver for starting an obsoleting process for the `with` statement.

**Comment by atoader** [comment] 2020-05-06 05:38
Will close this as by design.

**Closed by atoader** 2020-05-06 05:38 UTC
Labels: bydesign, static-code-analysis
