### ISSUE TITLE
Error in converter?

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#301] opened 2017-06-21 19:21 UTC
I'm updating my PowerShell function to export objects to AL.

and I bump into an error - apparently when I call the new version of the converter, powershell is noticing an error while executing (finishing) the conversion:
![image](https://user-images.githubusercontent.com/12088142/27402585-68631888-56c7-11e7-9628-8001fa84f4bc.png)

Conversion goes fine - if I simulate the same command into a command box, i don't see an error.  Looks like there is some internal error that PowerShell still "feels", but the command box is ignoring.. .

just want to give the heads up .. nothing serious .. the conversion of all objects does work.. .

**Comment by StanislawStempin** [comment] 2017-06-21 20:22
We will have a look

**Comment by StanislawStempin** [comment] 2017-07-03 13:32
I cannot repro it. Could you share the powershell code that you use to invoke the command? Looking at the source code, unless we run into an exception (which would be shown on the screen) we return exit code 0 from the console app so powershell should treat it as success.

**Comment by waldo1001** [comment] 2017-07-03 14:20
I'm using this function:
https://github.com/waldo1001/Cloud.Ready.Software.PowerShell/blob/master/PSModules/Cloud.Ready.Software.NAV/ModelTools/Export-NAVALfromNAVApplicationObject.ps1

**Comment by StanislawStempin** [comment] 2017-07-03 15:40
I still cannot reproduce it. My guess is that it's something related to the specific files that you're converting. Could you try identifying the subset of files that might be causing it?

**Comment by StanislawStempin** [comment] 2017-07-13 20:01
Waldo, please let us know if you run into this one again. Closing the issue for now.

**Closed by StanislawStempin** 2017-07-13 20:01 UTC
Labels: bug, input needed

**Comment by waldo1001** [comment] 2017-07-13 20:44
will do
