### ISSUE TITLE
reports disappears

### ISSUE THREAD

**Issue by clausmacali** [Microsoft/AL#2677] opened 2018-06-21 09:28 UTC
When we mak an ext. that has a report, thats not is add a ribbon, you can only searche for it, and pick
its desappears form theBC after fwe hours, the you have to uninstall /install the ext again
then its back again for a few hours

**Comment by qutreson** [comment] 2018-06-21 14:20
It looks related to #2448.

**Comment by StanislawStempin** [comment] 2018-06-21 15:23
This is a duplicate of #2448, fixed on the latest master build and fixed in online version 12.2

**Closed** 2018-06-21 15:23 UTC
Labels: duplicate
