### ISSUE TITLE
CU 6060 Hybrid Development External Request

### ISSUE THREAD

**Issue by jaadkins81** [Microsoft/AL#3610] opened 2018-09-07 22:03 UTC
AL Extension Version: 0.17.30289

Server Version: 10.0.017134

NavServer Version: 13.0.23802.0

Need External access put back on the CreateIntegrationRuntime, EnableReplication, and Initialize methods.

Error is the type or method xxxxxx cannot be used for 'Extension' development.  These methods have been enabled until build 24181.

**Comment by zeande** [comment] 2018-09-12 14:45
The change to remove the [External] tag from those AL procedures was by design. I have a refactoring of the base extension used in your scenarios, which will make it so that you no longer need to call those directly. You should see it checked in to master in the next few days, and those changes will be seen in the first update after the fall release.

**Closed** 2018-10-15 11:49 UTC
Labels: function-expose, ships-in-future-update
