### ISSUE TITLE
Debugging: Hovering over variables is not working with quoted variable names

### ISSUE THREAD

**Issue by DavidFeldhoff** [microsoft/AL#7226] opened 2022-10-27 10:24 UTC
Please include the following with each issue:

**1. Describe the bug**
While debugging I'm often hovering over variables to get their state. Unfortunately that isn't working if I'm in a .dal file and the variable name contains quotes and spaces.

**2. To Reproduce**

Create two projects, so that project 1 has .dal files of project 2 while debugging.
Then debug and hover over the variables. On the variable with quotes it says "Out of scope" instead of showing the values

Project 1
``` AL
codeunit 50101 HoverSampleInDAL
{
    procedure test(var "Sales Line": Record "Sales Line"; var SalesLine: Record "Sales Line")
    begin
        SalesLine.FindFirst();
        "Sales Line".FindFirst();
    end;
}
```
Project 2
``` AL
pageextension 50101 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var
        SalesLine: Record "Sales Line";
        "Sales Line": Record "Sales Line";
        HoverSampleInDAL: Codeunit HoverSampleInDAL;
    begin
        HoverSampleInDAL.test(SalesLine, "Sales Line");
    end;
}
```

https://user-images.githubusercontent.com/53570297/198260336-3459da36-d077-499f-9749-208af8c2b8d4.mp4

**3. Expected behavior**
That the variable state is displayed correctly.

**4. Actual behavior**
On the variable with quotes it says "Out of scope" instead of showing the values

**5. Versions:**

- AL Language: v10.0.687650
- Visual Studio Code: Version: 1.72.2 (user setup)
- List of Visual Studio Code extensions that you have installed: AL Language Extension

**Comment by thloke** [comment] 2022-11-15 10:02
This is a duplicate of #7225

**Closed by thloke** 2022-11-15 10:02 UTC
Labels: debugger, requires-triage
