### ISSUE TITLE
[PageExtension] - Modify property "Editable" at STD Page fields  

### ISSUE THREAD

**Issue by kdldk** [Microsoft/AL#2563] opened 2018-06-12 09:44 UTC
I am trying to change property "editable" at std. NAV fileds.
1) "Editable" property do not exist 
2) I can not use function call (function with return = Boolean) only simple expressions. Ofcause I can use "OnAfterGetRecord"

![image](https://user-images.githubusercontent.com/39760364/41282982-b3317c84-6e35-11e8-82ee-96335adf0c68.png)

**Comment by qutreson** [comment] 2018-06-12 12:15
Hi @kdldk,

1. I tried the following snippet and the property Editable is recognized.

![image](https://user-images.githubusercontent.com/31541422/41289478-3979c6fc-6e4a-11e8-8fb1-2bf939f04625.png)

However, it is not possible to modify it from extensions (not all properties can be modified, triggering IntelliSense inside the modify element will tell you which ones can be modified as IntelliSense willl only suggest you the modifiable properties).

2. It is also not possible to use the result of method calls in the Enabled property as stated on the error message below:

![image](https://user-images.githubusercontent.com/31541422/41289547-7b69c0bc-6e4a-11e8-9c14-2709811455a0.png)

Your approach with a boolean variable can be used as a workaround.

**Comment by kdldk** [comment] 2018-06-12 13:04
Re 1) You can do it in C/AL - a workaround to solve this problem could be  

![image](https://user-images.githubusercontent.com/39760364/41292051-b121b58c-6e51-11e8-9bc5-9289d02fcb0a.png)


- But I do not think that is nice

**Comment by StanislawStempin** [comment] 2018-08-07 15:11
There is currently no supported way to do it. The problem is that some other extension might require that field to be editable and there is no way to solve that conflict. Long-term we plan on providing functionality for resolving these types of conflicting modifications.

**Closed** 2018-10-10 20:58 UTC
Labels: question
