### ISSUE TITLE
Multiple configurations in launch.json are no longer supported in v5.0.236243

### ISSUE THREAD

**Issue by ekesteloot** [microsoft/AL#5742] opened 2020-03-20 20:05 UTC
**Describe the bug**
In v5.0.236243 of the AL Language extension in VS Code, the user is no longer queried for which configuration to use when there are multiple configurations, when publishing the app or downloading symbols.  (This was working just fine in v4 of the AL Language extension.)

**To Reproduce**
Steps and to reproduce the behavior:
1.  Create a launch.json file with more than one configuration
2.  Download symbols or publish app
3.  The editor does not ask for which configuration to use, it just picks one (I haven't figured out a pattern)

**Expected behavior**
As with past versions, to be asked which configuration to use for publishing app or downloading symbols.

**Screenshots**
n/a

**5. Versions:**

 - AL Language: 5.0.236243

 - Business Central: US Business Central 16.0 (Platform 16.0.11233.11843 + Application 16.0.11240.11853)

**Comment by kalberes** [comment] 2020-03-22 12:47
There is a new setting (per workspace folder by default) called defaultLaunchConfigurationName which controls the default launch configuration to use in scenarios that involve server resolution (goto definition (DAL files), download symbols, F5 variations, etc,

**Comment by ekesteloot** [comment] 2020-03-24 15:33
I can see where that will helpful when consistently working with the same Docker image, but it will be a bit of a hassle when you're trying to publish to multiple environments in succession.

In any case, the setting has not affected the extension's behavior - it seems to ignore the setting.  In my workspace settings:
`    "settings": {
        "al.enableCodeAnalysis": true,
        "al.codeAnalyzers": [
            "${AppSourceCop}",
            "${CodeCop}",
            "${UICop}"
        ],
        "al.enableCodeActions": true,
        "al.packageCachePath": ".alpackages",
        "al.CompilationOptions": {
            "generateReportLayout": false
        },
        "al.backgroundCodeAnalysis": true,
        "al.defaultLaunchConfigurationName": "Next Major"
    },
`

Per this setting, I expect it to use the "Next Major" configuration.  It chooses another.

**Comment by ekesteloot** [comment] 2020-03-30 17:54
> There is a new setting (per workspace folder by default) called defaultLaunchConfigurationName which controls the default launch configuration to use in scenarios that involve server resolution (goto definition (DAL files), download symbols, F5 variations, etc,

Kalberes, have you actually had success with the defaultLaunchConfigurationName  workspace setting in v5.0 of the AL Language extension?  I have tried it with no luck.

**Comment by kalberes** [comment] 2020-04-02 10:47
It is a per folder setting by default. It is there.
Have you looked here?
![image](https://user-images.githubusercontent.com/12760483/78241040-16120f00-74e0-11ea-8a79-cf8bb3c01567.png)

**Comment by Avanti05** [comment] 2020-04-03 11:05
I think it is an issue that you can not disable this feature. 

When deploying against multiple environments, it is not preferable to have to delete the setting when you wish to deploy to a new environment.

Is there a way to override so the default will not be set on deployment?

**Comment by kalberes** [comment] 2020-04-04 15:09
We will move it to per user settings when VsCode will support and add an optout. If the optout is chosen then go-to definition will not work if multiple debug configurations are specified and symbols need to be resolved based on server knowledge.

**Comment by ekesteloot** [comment] 2020-04-06 18:14
Yes, I have found the "per folder" setting, as shown below.  It has no effect on the behavior.
![image](https://user-images.githubusercontent.com/13574308/78591084-20921880-7800-11ea-825b-d32a3b5b325c.png)

**Comment by ekesteloot** [comment] 2020-04-06 18:22
My apologies.  The folder setting has the desired effect.

I look forward to the "optout" user setting.

**Comment by sonicadv27** [comment] 2020-05-20 15:51
The problem is not that we can't set this per folder or per workspace. The settings itself assumes everyone only deploys to one environment on any project. It actually makes the whole launch.json file configurations useless. I seriously don't understand why this settings exists and the fact that i can't turn it off in any way makes it worse. 

Please, someone changes this.

**Comment by AndreyKorepanov** [comment] 2020-06-25 12:09
It seems the source problem is solved with the defaultLaunchConfigurationName settings, I close the issue now.

**Closed by AndreyKorepanov** 2020-06-25 12:09 UTC
Labels: input-needed
