### ISSUE TITLE
The identifier 'StyleTxt' could not be found.

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#708] opened 2017-09-22 14:29 UTC
I found that if I use "StyleExpr" option on page field I get error `The identifier 'StyleTxt' could not be found.`

![image](https://user-images.githubusercontent.com/29101017/30749226-72998c5a-9fbb-11e7-89bd-4256bee11335.png)

StyleTxt is global
![image](https://user-images.githubusercontent.com/29101017/30749265-8475e9dc-9fbb-11e7-89f4-898a4ba9c9f2.png)

I get StyleTxt on aftergetrecord
![image](https://user-images.githubusercontent.com/29101017/30749285-95a840c4-9fbb-11e7-96bb-075797081037.png)
There are no errors on compiler. I get error after publishing.
![image](https://user-images.githubusercontent.com/29101017/30749339-bba990c0-9fbb-11e7-911d-c9b3b8c1f839.png)

![image](https://user-images.githubusercontent.com/29101017/30749350-c7995b7c-9fbb-11e7-8c1c-5a4c42317fce.png)

**Comment by johndcollins** [comment] 2017-09-22 15:21
Duplicate of #538

**Closed** 2017-09-25 13:37 UTC
Labels: duplicate
