### ISSUE TITLE
"NavHttpContent variable not initialized" thrown in newest Business Central release

### ISSUE THREAD

**Issue by HrolfurHj** [microsoft/AL#7574] opened 2023-11-08 11:18 UTC
**1. Describe the bug**
The error message: Microsoft.Dynamics.Nav.Runtime.NavHttpContent variable not initialized. 
is thrown when calling `HttpContent.GetHeaders(HttpHeaders)` after `HttpContent.Clear()` and before `HttpContent.WriteFrom(Text)`. This only happens in the newest release of Business Central and caused runtime errors with our customers because our tests did not cover the code calling a web service.

Seems the main issue is the `HttpContent.Clear()` procedure working differently than before and somehow "un-initializing" the variable.

**2. To Reproduce**
Simply call `HttpContent.GetHeaders(HttpHeaders)` after  `HttpContent.Clear()` and before `HttpContent.WriteFrom(Text)`

``` AL
procedure ContentErrorSample()
var
        content: HttpContent;
        headers: HttpHeaders;
begin
        content.Clear();
        content.GetHeaders(headers);
end;
```

**3. Expected behavior**
I expect no error to show up and the Content variable to be actually initialized. This worked before actually and you could set some headers before writing the content, though Content-Type and other headers got overwritten.

**4. Actual behavior**
"Microsoft.Dynamics.Nav.Runtime.NavHttpContent variable not initialized." is thrown when calling `HttpContent.GetHeaders(HttpHeaders)` after `HttpContent.Clear()`

**5. Versions:**

- Business Central: IS Business Central 23.0 (Platform 23.0.13605.0 + Application 23.0.12034.12676)

**Comment by BazookaMusic** [comment] 2023-11-11 17:37
Although this issue is out of scope for this repository because this is a runtime issue, the relevant team has already released a fix for this issue for the runtime.

It will arrive on all environments around the world within the next week.

The issue was a regression introduced to how the http content is cleared in the last release.

Thus, I will close this issue

**Closed by BazookaMusic** 2023-11-11 17:37 UTC
Labels: requires-triage
