### ISSUE TITLE
Spring release fails with "Call Back" errors

### ISSUE THREAD

**Issue by Pieterheinevdm** [Microsoft/AL#4942] opened 2019-05-01 09:24 UTC
There is a LOT of standard Cronus code (also in the localizations) which is failing now failing on the "Attempted to issue a client callback" check.

example1:
onopen rolecenter PRESIDENT - SMALL BUSINESS
Attempted to issue a client callback while a write transaction started, this can impact performance: Table 485 Business Chart Buffer Update.__
example2:
on running Post Inventory Cost to G/L report
Microsoft Dynamics 365 Business Central
Attempted to issue a client callback while a write transaction started, this can impact performance: Report 1002 Post Inventory Cost to G/L ApplicationObjectRootScope.
example3:
on use contact-Create Interaction:
Attempted to issue a client callback while a write transaction started, this can impact performance: Table 5077 Segment Line FinishWizard.
example4:
on preview posting 
etc etc

Even when these problems are quickly fixed and released in the next CU we have to offer a solution for our customers

Question1: Please make it possible to disabled the check "Attempted to issue a client callback" at the servicetier level. 
Question2: Please test and fix the complete W1 database (and all localizations!) to support this new check.
Question3: I cannot remember this check was there in the last preview build. How is it possible this check is added in finale release with these breaking changes / go live show stoppers?

**Comment by PooyaKharamesh** [comment] 2019-05-02 09:29
Hi,

Please provide us all the information mentioned in the template including the AL extension Language and Server version.

/Pooya

**Comment by AndreyKorepanov** [comment] 2019-05-02 15:41
Duplicate of #4930

**Closed** 2019-05-03 12:06 UTC
Labels: duplicate
