### ISSUE TITLE
New version always publish to default sandbox

### ISSUE THREAD

**Issue by OsebergTSO** [microsoft/AL#6221] opened 2020-10-14 10:55 UTC
**Describe the bug**
When publishing from VS Code to sandbox, the app gets published to default sandbox, and debugger opens up in the right sandbox.. 

used v6.1.350698

metadata request goes to the sandbox in launch.json environmentname, but publishing and sync goes to sandbox with name sandbox.. 

**To Reproduce**
Steps and to reproduce the behavior:
1. change launch.json to sandbox other than default, publish app..  

**Expected behavior**
app will be published in default sandbox, if you publish with debugger, debugger will open in then sandbox in launch.json, will not find breakpoints or code. 

**Screenshots**

**5. Versions:**

 - AL Language: v6.1.350698

 - Business Central: 17

**Comment by kalberes** [comment] 2020-10-14 12:15
Workaround is to use the sandboxname property for now and delete the environmentname.

**Comment by kalberes** [comment] 2020-10-14 12:16
Duplicate of #6219

**Comment by kalberes** [comment] 2020-10-15 12:48
The issue should be fixed in version  v6.1.352568.

**Comment by kalberes** [comment] 2020-10-16 09:54
Closing because of a duplicate

**Closed** 2020-10-16 09:54 UTC
Labels: bug, duplicate, ships-in-future-update
