### ISSUE TITLE
AL0604 Quickfix - Qualify with Rec > does not update "IndentationColumn"

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#6066] opened 2020-08-03 14:01 UTC
**Describe the bug**
When hitting a warning AL0604, the Quickfix code action is shown, with the option to fix all occurences within the current object. If you have a 'IndentationColumn' setting using a Field value, the value is not replaced with Rec.

**AL Code to reproduce the issue**

![image](https://user-images.githubusercontent.com/25268332/89190642-0a277e00-d5a2-11ea-8f0a-f159e82e593a.png)

After applying the quickfix.

![image](https://user-images.githubusercontent.com/25268332/89190833-5377cd80-d5a2-11ea-9bc8-da50abd969c3.png)

**Expected behavior**

Using the quickfix "all occurences within the current object", should also fix the 'IndentationColumn' setting.

**5. Versions:**

 - AL Language: 6.0.293448

**Comment by dtkb** [comment] 2020-08-03 14:03
dupe of #6042

**Closed** 2020-08-03 14:25 UTC
