### ISSUE TITLE
Do not have identifiers with quotes in the name (AA0100) -> Wrong for PageExtensions

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#5990] opened 2020-06-26 11:29 UTC
**Describe the bug**
When I modify a field with quotes inside the name I receiv a warnig for this field name. 
This Warning doesn't make sense, since I can't change its name.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a new Page Extension for the "Sales Order Subform"
2. Add  a modify to the layout for the field `"TotalSalesLine.""Line Amount"""`
``` 
layout
{
    modify("TotalSalesLine.""Line Amount""")
    {
        Visible = false;
    }
}
 ```

**Expected behavior**
Don't show this warning since I cannot change this name.

**Screenshots**

**5. Versions:**

 - AL Language: 5.0.288712

 - Business Central:

**Comment by AndreyKorepanov** [comment] 2020-06-27 11:45
Hi @pri-kise, thank you for reporting the issue. I found that the issue is not reproducible on the master (You can try to get a repro on the latest daily build). Apparently it has been already fixed there and will be delivered in the future release. So I am closing the issue now. Thanks

**Closed by AndreyKorepanov** 2020-06-27 11:45 UTC

**Comment by pri-kise** [comment] 2020-07-21 13:05
@AndreyKorepanov is there an ETA when this will be delivered to the VS Code Store?

**Comment by atoader** [comment] 2020-08-09 18:28
Hi! The extension will be available in the VS Code Store starting with the 1st of October. Can you confirm that the issue is solved by using the developer preview?
