### ISSUE TITLE
SchemaUpdateMode = synchronize failed with code 422. Reason: Value cannot be null.

### ISSUE THREAD

**Issue by srinivasdes** [Microsoft/AL#1816] opened 2018-03-20 09:32 UTC
Hello,

Facing the following error while publishing the app to sandbox.

SchemaUpdateMode=synchronize failed with code 422. Reason: Value cannot be null.  Parameter name: value

Al Version : 0.14.17461

Can someone suggest me on what i am missing 

Launch.json file : 

{
    "version": "0.2.0",
    
    "configurations": [
        {
            "name": "Microsoft cloud sandbox",
            "type": "al",
            "request": "launch",
            "startupObjectId": 22,
            "schemaUpdateMode": "Synchronize",
        }
    ]
}

**Comment by srinivasdes** [comment] 2018-03-21 04:13
Hi Qutreson,

Thanks for your response.

what is meant by repro steps. Can you please explain bit more

Thanks

**Comment by qutreson** [comment] 2018-03-21 08:49
By repro steps, I mean a sequence of actions for us to do in order to trigger this error. Or, if you cannot find a clear one, could you provide us with more details about the context in which the error happened? (For instance, the code you had that trigger this error, what where you trying to do, if it was the first time you were publishing, if it happened only once or still reproduces regularly etc)

This way, it makes it easier for us to reproduce, understand and fix the issue you are describing

**Comment by srinivasdes** [comment] 2018-03-21 10:17
I have done development with AL and fixed the compile related issues. while i am trying to publish my application to the sandbox i am facing this error. 

**SchemaUpdateMode=synchronize failed with code 422. Reason: Value cannot be null. Parameter name: value**

Please find the attachment..

![error](https://user-images.githubusercontent.com/35101458/37704578-32f05bc8-2d1f-11e8-9044-eb6e01ca7aa6.JPG)

**Comment by qutreson** [comment] 2018-03-23 08:37
Hi @srinivasdes, what happens if you created a new empty extension with AL:Go using the same launch.json and try to publish it to the same sandbox environment? Do you also get the same error? If not, can you try to cut down your extension until you get a minimal extension that reproduces the error?

**Comment by srinivasdes** [comment] 2018-03-23 12:46
Hi Qutreson,
I can able to publish my test application with the same launch.json . I didn't get any error , But as you said i can not cut down my extension until i get a minimal extension, Because there are some dependencies between the al objects.

Can i have any other alternate 

Thanks

**Comment by qutreson** [comment] 2018-03-23 13:13
So, you can either try to update to a newer version of the extension (in case this problem has already been fixed), or, you can also try to publish using the schema update mode recreate in your launch.json (but you will lose the data you have in your tables, see [Retaining table data after publishing](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-retaining-data-after-publishing)).

**Comment by srinivasdes** [comment] 2018-03-25 16:58
Current extension version is  0.14.17461. I couldn't find the update option to update the extension.

I have modified the launch.json and using the schema update mode recreate , Still having the same issue

any other suggestion..

**Comment by TKapitan** [comment] 2018-04-03 09:29
Hello, 
I have the same issue

Testing against NAV 2018/CU03 with AL 15.18771

```
[2018-04-03 11:23:16.68] Sending request to http://localhost:7059/ArtexAddOn-NAV2018/dev/apps?SchemaUpdateMode=recreate
[2018-04-03 11:23:17.80] The request for path /ArtexAddOn-NAV2018/dev/apps?SchemaUpdateMode=recreate failed with code 422. Reason: Value cannot be null.
Parameter name: value
```

**Comment by qutreson** [comment] 2018-04-04 07:48
Hi @TKapitan, is it possible for you to try to comment out some parts of your extension in order to see if you can get a minimal project that reproduces the error?

**Comment by julienDecottignies** [comment] 2018-04-04 09:31
Hi,

I was facing the same issue. **Solved by deleting Translation folder with .xlf files**. I suppose all my captions and labels were not in my .xlf file (because of renaming it) and maybe it's the cause (?).

**Comment by DominikDitoIvosevic** [comment] 2018-04-04 09:35
@julienDecottignies thank you for narrowing the issue. Could you maybe try removing only parts of the xliff file? It could be there is an issue with a single label. Also, a newer version of the compiler will report more diagnostics about the xliff files so it might be easier to identify the problem with the latest version

**Comment by julienDecottignies** [comment] 2018-04-04 09:42
Ok.
I tried to:
Delete Translations folder - Rebuild (wich recreate Translation folder) -> There was no probleme the first time I ran the app, but if I build it (without **any** change) the second (and next times), it fails. 
The only solution is to delete and build ...

I added some tooltips just thirty minutes ago, the problem is probably there. I come back with the answer, but why does only the first time I build after deleting translation folder works ..?

**Comment by DominikDitoIvosevic** [comment] 2018-04-04 09:52
are you on nav 2018 or latest dev preview?

**Comment by julienDecottignies** [comment] 2018-04-04 10:02
I'm on NAV 2018 CU3 and AL extension installed from VSIX

**Comment by DominikDitoIvosevic** [comment] 2018-04-04 10:37
I think that this was fixed in the meantime on main. You will have to go through our standard support channels to get it backported for Nav2018

**Comment by TKapitan** [comment] 2018-04-05 11:46
@julienDecottignies Thank you! That's it!

@DominikDitoIvosevic Is the solution described somewhere? We had no problems with that until we upgraded AL Language extension to the latest version...

**Comment by StanislawStempin** [comment] 2018-04-06 13:31
@TKapitan - if you're using NAV 2018 you should be using the AL Language extension that comes with the product installer (version 0.12.XXX).  Newer versions are for Business Central only.
See the FAQ: https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#which-version-of-the-al-language-extension-should-i-use

**Closed by StanislawStempin** 2018-04-06 13:31 UTC
Labels: input needed, investigate

**Comment by TKapitan** [comment] 2018-04-06 18:39
@StanislawStempin 
Maybe there is something wrong? 

The new AL Extension (version 0.15.18771) has different XLIFF file than the older one. The old version had only source-language - then the XLIFF editor (we use "Transolution Xliff Editor") allows defining the target language at the start of translating. The new version has source-language and target language. Both contain same values (en-US). Than the XLIFF editor presumes the target language will be en-US and is not possible to redefine the language (so the only possibility how to translate is to change target-language manually)

When I change the target-language to something different (like cz-CS), the XLIFF editor is OK.

Another thing is the error "failed with code 422. Reason: Value cannot be null. Parameter name: value". I resolved it with the same - the error is happening because of the same values of source and target languages - it can be solved by changing the target-language in xliff.

**Comment by wcld** [comment] 2018-05-17 11:55
Hello Friends;
I want to tell about of this Error : The request for path /DynamicsNAV110/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: TableExtension 50111 :: Unsupported field change. Field:MyComment; Change:Remove

We can solve This error

Please Go to Launch.json
Change "schemaUpdateMode": "Synchronous" to "schemaUpdateMode": "Recreate"   

Save and Create Package:
Thank you
![capture](https://user-images.githubusercontent.com/31481149/40175883-3c1fe43e-59f7-11e8-9309-013247e5646e.PNG)

**Comment by Tharangac** [comment] 2018-06-07 00:57
Had the same issue. Managed to resolve by deleting translation file (.xlf)
