### ISSUE TITLE
AL Profiler has performance issues

### ISSUE THREAD

**Issue by bjarkihall** [microsoft/AL#6874] opened 2021-12-16 14:44 UTC
**1. Describe the bug**
Hi, I've been trying out the AL Profiler in vscode and I've been trying to record a specific user interaction in an OnPrem localhost environment.

A lot happens when the page is opened, so I'd like to start the profiling once it's over but `Initializing Snapshot Debugging` doesn't seem to be able to hook-into an already opened browser window.

The only way I could record the interaction was by recording before opening the page, which outputs a .zip file which is `157.769 KB`.
However, when I try the `Generate Profile File` command, it takes a lot of time and eats up all resources on my machine, it's already crashed it twice (in the latter case I had nothing open on my machine except 1 vscode window with a small .al file and the .snapshot folder). Note, that I've tried smaller recordings of another page where the .zip file was only 11.368 KB, which generates a profile successfully, the tool just becomes unusable if there's too much recorded.

According to the DKWC045 webinar, MS seems to be aware of this but I thought it would help to have this tracked here on Github and even get some feedback from partners and tips in general.

**2. To Reproduce**
I followed MS steps to initialize a snapshot recording and generate a profile:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-profiler-overview

I'm using the following launch.json configuration (inline comments indicate properties I've tried adding/removing/changing):
```jsonc
{
    "type": "al",
    "request": "snapshotInitialize",
    "name": "snapshotInitialize: BC",
    "environmentType": "OnPrem",
    "server": "http://localhost",
    "serverInstance": "BC",
    "authentication": "Windows",
    // "userId": "b65faf78-a975-4265-b454-2a4bc2869f2d",
    // "sessionId": 5,
    "breakOnNext": "WebClient",
    "executionContext": "Profile", // "DebugAndProfile",
    // "snapshotVerbosity": "Full", // "SnapPoint"
    "tenant": "default"
}
```

**3. Expected behavior**
I know you're working on improving these things but until then we're not able to record the areas of interest because the tool records too much.
Either we need to be able to limit how much is recorded by only recording the step we need or allow a process to generate the report in the background without being too greedy on resources (or hopefully both!).

* Shouldn't **sessionId** be able to "start recording" on a browser tab that's already loaded?
* I've tried placing the debuggingContext that's logged by the profiler into the url but that doesn't work either.
* I was also hoping I could limit how much was being recorded by using snapshotVerbosity or executionContext but it doesn't change much.
* It would even make sense if the profile generation could be paused/continued if it takes an hour to execute.
* The most serious bug I think is the resource consumption, can I by some means limit how much RAM/CPU is being used up by the AL Extension?

Is there something I can do now while we wait for improvements?
Could the AL Team maybe introduce improvements gradually with small extension updates?

**4. Actual behavior**
First time I tried generating the profile it crashed my computer, I had vscode with the whole project loaded.
When I started my computer again, I only had 1 vscode window open with bare-minimum to generate the profile (1 empty .al file and the .snapshot folder). Then I took this screenshot, before it crashed at ca. 27%:
![image](https://user-images.githubusercontent.com/8615374/146389923-21002861-4177-4710-8546-65e06ece85a8.png)

You can see the memory lane has been stuck at 100% consumption for some minutes:
![image](https://user-images.githubusercontent.com/8615374/146390010-f035b90b-445f-4c0d-a276-c4e301eea6fb.png)

**5. Versions:**

- AL Language: v8.2.552672
- Visual Studio Code: 1.63.1
- Business Central: W1 19.1 (Platform 19.0.31889.32155 + Application 19.1.31886.32186)
- List of Visual Studio Code extensions that you have installed: I disabled all but the AL Language one from MS

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by bjarkihall** [comment] 2021-12-16 14:53
I hope I'm providing enough information:

* recording can't be started in the middle of a session
* recording consumes a lot of CPU
* generating a profile from "too large" .zip files seems to be impossible since it eats up the RAM and crashes the computer

I'm not able to share our internal codebase or the .zip files publicly but you're welcome to reach out if you'd like to take a look at it in more detail.

Please share any tips or ask if something's not clear.

**Comment by bjarkihall** [comment] 2021-12-20 14:24
Regarding the sessionId not being picked up, the snapshot recording initializes (nothing is indicated in the client though), but once I download the .zip, it's empty (only includes a "version" file), so no profile can be generated from it.

Not sure if it relates to this issue, but if I can get this working I can at least limit how large the recorded .zip file gets and hopefully prevent my computer from crashing again. I saw the sessionId being used in the webinar recording but I'm not able to imitate the steps, closing/opening the browser might help so I'll take a look at that, but if anyone can share tips to be able to use the Profiler in a more reliant way, I'll gladly appreciate it. :)

Is there an easy way to limit resource consumption by the EditorService, so I could maybe let it run in the background?

**Comment by thloke** [comment] 2021-12-21 07:00
Hi, sorry it took us a while to get to this! We're a bit short-handed this time of the year.

First, you are correct in that generating the cpu profile file from a snapshot file can be really resource intensive. We don't have a good way to throttle CPU usage (in exchange for longer processing times) at the moment, so your approach of trying to limit the snapshot file to begin with is the correct approach, so I'll focus on getting the "attach to a specific session ID" approach to work.

We know we have some problems with this in SaaS due to issues in getting the request to hit the same cloud cluster node that is hosting the session, but this should be reliable OnPrem/localhost since it's essentially a single-machine scenario. You should not need to open/close browser tabs in this case.

As far as the launch.json config goes, you can omit UserID. In an OnPrem scenario, this is not necessary and just adds another restriction. As long as the sessionId is correct, it should work. To confirm, are you getting the sessionId from the help and support page? That one should be the definitive sessionId to target.

If the sessionId is also correct, then we'll need to look at both the server logs and the VSCode extension logs. 

**Having said all that**, it's also really suspicious that a 157KB file is taking forever to process and consuming a lot of CPU and memory. By snapshot standards, that's not big at all. If It's okay, can you send the file for us to investigate? There might be an infinite loop in our cpuprofile generation causing you grief.  If you're okay with sending it to us to investigate, you can send it to me directly at: thloke@microsoft.com - I can't promise an ETA on how long an investigation will take, but I should be able to let you know if we can reproduce a similar issue at least. If we can repro with the same file, it's likely (but no promises) that we'll take it as a bug to fix in the short term.

**Comment by bjarkihall** [comment] 2021-12-21 08:40
Hi @thloke and thanks for the response, the delayed response is fully understandable,

The sessionId wasn't available in Help and support, like was shown in the webinar:
![image](https://user-images.githubusercontent.com/8615374/146893056-5ab962ec-03e5-40d0-adca-51b14ffde757.png)

So I tried to get it from the Session table: `?table=2000000009` and "Connection ID" field, is there a way to get the additional information that I don't have turned on? If it's a 19.2 feature I could place a Message(SessionID) in OnOpenPage, if that's a better way, until we upgrade (soon).

In regards to the configuration, I might have had both User ID and Session ID at the same time (I tried various combinations though) but I'll give it a few more shots while skipping the User ID. I expected the client to display a message once it started recording, but I've looked at the webinar again where I can see that no message is displayed in the client.

The file is `157769 KB` -> `~154 MB`, my language formatting standard (which my OS is using) has dots for thousands-separation instead of commas (just like Danish), sorry about that. It also means the file I **successfully** converted was `11365 KB` -> `~11 MB`. There's a lot happening in these places, which further justifies our focus on profiling them, to find out if there's code we can skip or move around.

Since the file is too large for email, I'll keep trying to hook into the current session to get a smaller file.

Wish you and your team happy holidays btw :)

**Comment by thloke** [comment] 2021-12-21 09:52
Hm, that's strange that it doesn't show the session ID on the help and support page, but that might be a difference between the test environment I tried it in and the actual BC Container environment (I'm running the equivalent of the latest insider build).  The session table should also give you the correct information, except that there's the risk that you're picking up a background/child session instead of the actual webclient session. I think the session table doesn't distinguish between these types.

Another place where you can find the session ID (along with its type) is if you connect to the SQL DB, and check the `[Active Session]` table. WebClient sessions should have a `[Client Type]` value of `7`. The value you want will be under the `[Session ID]` column.

Just be aware that these sessions time out after some inactivity, so you'll want to click around in the webclient while you query the DB if it's slow to be sure you're picking up the correct ID.

And that makes more sense! Yes, a 154MB file is on the larger side (though we've seen snapshots near 1GB - I don't think those can be processed either....).

**Comment by ricardopaiva** [comment] 2021-12-21 10:11
Hi,
I'm having the same issue as OP. On BC 19.0, on a custom database. Didn't tried on a standard Cronus though. I'll try it again on BC 19.2, either on a custom and standard Cronus database and share my findings.

**Comment by ricardopaiva** [comment] 2021-12-21 11:45
On BC 19.2 I was able to attach the snapshot debugging to the running session - the session id is available in the Help & Support page. This way I was able to just profile a single process and the zip file is now 30 Mb (instead of 150-500 Mb) but I still was not able to generate the profile output. I can confirm that the memory usage is too high as well and the profile generation runs till 49% then it stalls it out.
I've tested on a custom database but this part seems to be related to the VSCode extension, not to the BC version.

**Comment by ricardopaiva** [comment] 2021-12-21 12:50
It took several minutes but it seems like it was able to finish generating the profile file. I'll have to try with a larger file but at least for now, with this one, it worked fine although it took too long to finish.

**Comment by thloke** [comment] 2021-12-22 01:02
Being unable to process a 30MB snapshot file (or taking forever) is something concerning. This is well within the range of an expected snapshot file size. We are aware that it is resource intensive due to the nature of the transformation, but it looks like it we'll need another look at its performance.

**Comment by tyurm** [comment] 2021-12-30 11:01
@ricardopaiva had the same issue with 50mb file, and it took about 2-3 hours to pass 49-50%. After 50% process was finished within a few minutes.

**Comment by ricardopaiva** [comment] 2022-01-04 16:26
@tyurm thanks for the feedback! Yes, it seems like the profiler file generation takes too long!
As long as VSCode doesn’t crash, then at least we’re able to use this feature.
But it would be great if the generation time could be somehow improved.

**Comment by kalberes** [comment] 2022-01-13 09:53
There should be some improvements done for the next release of the vsix package (19.3)

**Comment by thloke** [comment] 2022-02-03 06:38
Closing as the performance improvements have been implemented.

**Closed by thloke** 2022-02-03 06:38 UTC
Labels: bug, snapshot debugger, profiler
