### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by ThomasBrodkorb** [microsoft/AL#6320] opened 2020-11-25 16:21 UTC
I do not have any idea on how to replicate the issue.
It just happens when downloading the symbols.

[2020-11-25 17:18:12.53] Using reference symbols cache path: d:\Data\Dynamic Retail\17\DR17\./.alpackages
[2020-11-25 17:18:12.59] Targeting server 'http://tbnb5' and server instance 'BC170W1'.
[2020-11-25 17:18:12.59] Using Windows authentication.
[2020-11-25 17:18:12.64] Sending request to http://tbnb5:7049/BC170W1/dev/packages?publisher=Microsoft&appName=System Application&versionText=17.0.0.0
[2020-11-25 17:18:12.68] Sending request to http://tbnb5:7049/BC170W1/dev/packages?publisher=Microsoft&appName=Base Application&versionText=17.0.0.0
[2020-11-25 17:18:14.85] The following dependencies will be queried for propagated dependencies:

[2020-11-25 17:18:14.88] All reference symbols have been downloaded.
[Error - 17:18:23] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/didChange' failed with error: 'Specified argument was out of the range of valid values. (Parameter 'index')'
Details:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at Microsoft.Dynamics.Nav.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\SourceText.cs:line 661
   at Microsoft.Dynamics.Nav.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\TextLineCollection.cs:line 67
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.BufferManager.UpdateBuffer(DidChangeTextDocumentRequest updateRequest, CancellationToken token)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DidChangeTextDocumentRequestHandler.HandleAsync(DidChangeTextDocumentRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DidChangeTextDocumentRequestHandler.cs:line 50
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80

**Comment by thpeder** [comment] 2020-12-01 14:50
Hi,
Thanks for reporting the issue, but we have a hard time to act on it.
It looks like it happened 9 seconds after downloading of symbols completed, so it doesn't seem to be related.
From looking at the stack-trace it seems like the compiler got a request from VSCode that a document is changed, but something was out of sync in what the compiler thought that document looked like and what VSCode had.

Please see if you can reproduce the issue so we can fix the issue.

**Comment by AxelLeder** [comment] 2021-01-20 14:36
I have the same error.

What I noticed, is that it only occurs if you download more than one symbol packages.

My steps:
1.1 delete .alpackages folder
1.2 AL:Download symbols --> 3 packages downloaded --> 2 error messages

2.1 delete two packages
2.2 AL:Download symbols --> 2 packages downloaded --> 1 error messages

3.1 delete one package
3.2 AL:Download symbols --> 1 packages downloaded --> 0 error messages

**Comment by atoader** [comment] 2021-01-20 17:02
What error messages are you getting?

**Comment by AxelLeder** [comment] 2021-01-21 07:38
I received the same messages as Thomas described above.

But for any reason I can't reproduce that now anymore. Something must have changed since yesterday.

**Comment by AxelLeder** [comment] 2021-01-21 07:49
well, tried it again on another pc and it occured again.
I downloaded 4 symbol files and got 3 error messages...

[error.txt](https://github.com/microsoft/AL/files/5847625/error.txt)

**Comment by JesperSchulz** [comment] 2021-03-23 10:22
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 23580 and VS Code Extension Version 7.0.436375. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Closed by JesperSchulz** 2021-03-23 10:22 UTC
Labels: bug, in-progress, ships-in-future-update, workspaces
