### ISSUE TITLE
Issue with actions in creation action area of document pages

### ISSUE THREAD

**Issue by wdet** [microsoft/AL#6597] opened 2021-04-28 08:30 UTC
**1. Describe the bug**
Actions added to the creation action area of a documents page aren't displayed in the client. 

**2. To Reproduce**
This issue can be reproduced by adding an action in the creation action area of a documents page.

**3. Expected behavior**
Would it be possible to introduce a compiler rule for this? This will indicate in VS Code that this is not supported.

**4. Actual behavior**
No errors occur, the actions are not visible in the client

**5. Versions:**

- AL Language: 8.0.446271
- Visual Studio Code: 1.55.2
- Business Central: 17.5

**Comment by atoader** [comment] 2021-04-29 09:20
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by atoader** [comment] 2021-04-29 09:21
@hoovercj could you take a look at this suggestion?

**Comment by qutreson** [comment] 2024-02-16 11:12
Closing as duplicate of #7651 which was accepted

**Closed by qutreson** 2024-02-16 11:12 UTC
