### ISSUE TITLE
Txt2AL does not convert page delta with action container insertion

### ISSUE THREAD

**Issue by ernestasju** [Microsoft/AL#2802] opened 2018-07-05 12:57 UTC
I am using Txt2AL from microsoft/bcsandbox build 12.2.22932.23097.

Delta file:
```
OBJECT Modification "Item Variants"(Page 5401)
{
  OBJECT-PROPERTIES
  {
    Date=20180615D;
    Time=120000T;
    Modified=true;
    Version List=NAVW112.10;
  }
  PROPERTIES
  {
    Target="Item Variants"(Page 5401);
    TargetPageType=List;
  }
  CHANGES
  {
    { Insertion         ;ChangedElements=ActionCollection
    {
      { 70000   ;    ;ActionContainer;
                      Name=ActionContainer70000;
                      ActionContainerType=ActionItems }
    }
     }
  }
  CODE
  {

    BEGIN
    END.
  }
}
```

Txt2AL output:
```
PS C:\Users\ernjus\Desktop\test> & 'C:\ProgramData\NavContainerHelper\Extensions\toc\Program Files\122\RoleTailored Client\Txt2Al.exe' --source=C:\Users\ernjus\Desktop\test\deltas --target=C:\Users\ernjus\Desktop\test\alfiles

----ERROR----
Error converting file:C:\Users\ernjus\Desktop\test\deltas\PAG5401.DELTA
Object reference not set to an instance of an object.

Total Time: 0:00:00,2278374
Errors: 1
```

This is not a high priority for me.

**Comment by qutreson** [comment] 2018-07-06 13:37
Hi @ernestasju, thank you for reporting this issue. I was not able to reproduce the issue on our latest builds and I believe this issue should have been fixed in the meanwhile as we did some fixes on the txt2al over the past weeks.

**Closed** 2018-08-07 15:37 UTC
Labels: bug, shipped
