### ISSUE TITLE
 'The stream was already consumed. It cannot be read again.'

### ISSUE THREAD

**Issue by moulikaku** [Microsoft/AL#705] opened 2017-09-21 11:45 UTC
I'm fallowing this link to develop apps for Dynamics 365 and i'm using source as Cloud and provided my Dynamics 365 credentials 
https://msdn.microsoft.com/en-us/dynamics-nav/developer/devenv-develop-apps-for-fin?f=255&MSPPError=-2147217396

After the credentials when i try to download Symbols i'm getting below error.

I'm new to vs code can you please help me to resolve this error 

[2017-09-21 12:36:11.05] Using reference symbols cache path: c:\Users\mouli\Documents\AL\ALProject4\.alpackages
[2017-09-21 12:36:11.08] Authenticating...
[2017-09-21 12:36:37.65] Sending request to https://api.financials.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=US&versionText=11.0.0.0
[2017-09-21 12:36:37.66] Sending request to https://api.financials.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=System&versionText=11.0.0.0
[2017-09-21 12:36:39.26] The request for path /v1.0/sandbox/dev/packages?publisher=Microsoft&appName=System&versionText=11.0.0.0 failed with code NotFound. Reason: No published package matches the provided arguments.
[Error - 12:36:45] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/downloadSymbols' failed with error: 'The stream was already consumed. It cannot be read again.'

**Comment by StanislawStempin** [comment] 2017-10-18 09:15
Hi, Could you please let us know if the problem is still relevant or if you have found a solution in the meanwhile.

**Comment by moulikaku** [comment] 2017-10-18 09:41
Hi, i'm getting the same error when I try to access D365 at the same time it is working with NAV Development Preview – October Update . Don't exactly where i'm doing wrong

**Comment by waqaszahoor** [comment] 2017-11-12 13:39
I got same error on my laptop. when i try on clean VM on Azure it work. 

[2017-11-12 17:18:22.05] Using reference symbols cache path: c:\Users\WaqasZahoor\Documents\AL\ALProject4\.alpackages
[2017-11-12 17:18:22.07] Authenticating...
[2017-11-12 17:18:23.98] Sending request to https://api.financials.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=US&versionText=11.0.0.0
[2017-11-12 17:18:23.99] Sending request to https://api.financials.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=System&versionText=11.0.0.0
[2017-11-12 17:18:26.31] The request for path /v1.0/sandbox/dev/packages?publisher=Microsoft&appName=System&versionText=11.0.0.0 failed with code Forbidden. Reason: You do not have the following permissions on TableData NAV App: IndirectRead
[Error - 5:18:26 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/downloadSymbols' failed with error: 'The stream was already consumed. It cannot be read again.'
StackTrace:
   at System.Net.Http.StreamContent.PrepareContent()
   at System.Net.Http.StreamContent.SerializeToStreamAsync(Stream stream, TransportContext context)
   at System.Net.Http.HttpContent.LoadIntoBufferAsync(Int64 maxBufferSize)
   at System.Net.Http.HttpClient.StartContentBuffering(HttpRequestMessage request, CancellationTokenSource cancellationTokenSource, TaskCompletionSource`1 tcs, HttpResponseMessage response)
   at System.Net.Http.HttpClient.<>c__DisplayClass55_0.<SendAsync>b__0(Task`1 task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.Deployment.ReferenceDownloader.NavServerPackageDownloader.<SendRequest>d__3.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\ReferenceDownloader\NavServerPackageDownloader.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.DownloadSymbolsRequestHandler.<SaveToFile>d__4.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\DownloadSymbolsRequestHandler.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.DownloadSymbolsRequestHandler.<ProcessRequestAsync>d__3.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\DownloadSymbolsRequestHandler.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`1.<HandleAsync>d__5.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\NavServerRequestHandler.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__5.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 50

[2017-11-12 17:18:26.38] The request for path /v1.0/sandbox/dev/packages?publisher=Microsoft&appName=US&versionText=11.0.0.0 failed with code Forbidden. Reason: You do not have the following permissions on TableData NAV App: IndirectRead

**Comment by StanislawStempin** [comment] 2018-04-09 08:44
This bug has been fixed in the meanwhile. Please log a new issue if you're still encountering it on the latest release of Business Central.

**Closed** 2018-04-09 08:44 UTC
Labels: bug, shipped
