### ISSUE TITLE
SetCurrencyCode MAKE EXTERNAL

### ISSUE THREAD

**Issue by alvarotellez** [Microsoft/AL#2298] opened 2018-05-21 11:55 UTC
Plase make function SetCurrencyCode external in TAB290 - "VAT Amount Line" . Its necessary to replicate the report 206.

**Comment by JesperSchulz** [comment] 2018-05-21 17:39
This appears to be a duplicate of https://github.com/Microsoft/AL/issues/2289? Unfortunately I could not resolve your ticket, as the SetCurrencyCode function doesn't exist. Closing issue.

**Closed by JesperSchulz** 2018-05-21 17:39 UTC
Labels: function-expose
