### ISSUE TITLE
Error on compile

### ISSUE THREAD

**Issue by superjma** [Microsoft/AL#4201] opened 2018-11-14 13:46 UTC
I get the following error now. I have no idea how to reproduce.
It worked yesterday.

[Error - 2:41:40 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.Details:
System.NullReferenceException: Objektreferencen er ikke indstillet til en forekomst af et objekt.
   ved Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.GetBoundOptionValueOrdinal(BoundEqualsPropertyExpression expression) i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:linje 149
   ved Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.GetConstConditionValue(BoundEqualsPropertyExpression expression) i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:linje 241
   ved Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.WriteFilterAttributes(XmlWriter writer, BoundEqualsPropertyExpression equalsExpression, String filterValueAttribute, String filterTypeAttribute, String filterGroup, Boolean isCondition) i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:linje 294
   ved Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.<>c__DisplayClass1_1.<WriteTableFilters>b__0() i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:linje 51
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteStartEndElement(XmlWriter xmlWriter, String elementName, Action action) i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:linje 24
   ved Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.WriteTableFilters(XmlWriter writer, Boolean isCondition, String metadataElement, BoundTableRelationConditionExpression tableRelationExpression, String filterGroup) i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:linje 49
   ved Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.<>c__DisplayClass2_0.<WriteCalculationFormulaPropertyValue>b__1() i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:linje 78
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteStartEndElement(XmlWriter xmlWriter, String elementName, Action action) i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:linje 24
   ved Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.<>c__DisplayClass2_0.<WriteCalculationFormulaPropertyValue>b__0() i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:linje 76
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteStartEndElement(XmlWriter xmlWriter, String elementName, Action action) i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:linje 24
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Emit.TableBaseMetadataEmitter`1.TryUseSpecialPropertyValueMetadataEmitter(XmlWriter xmlWriter, PropertySymbol property) i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\TableBaseMetadataEmitter.cs:linje 128
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitter.WritePropertyValueMetadata(XmlWriter xmlWriter, PropertySymbol property) i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitter.cs:linje 50
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteElementProperties(XmlWriter xmlWriter, IEnumerable`1 properties, Action`2 writePropertyMetadata) i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:linje 62
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Emit.TableBaseMetadataEmitter`1.<>c__DisplayClass4_0.<WriteField>b__0() i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\TableBaseMetadataEmitter.cs:linje 48
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteStartEndElement(XmlWriter xmlWriter, String elementName, Action action) i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:linje 24
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Emit.TableExtensionMetadataEmitter.<EmitMetadata>b__1_0(XmlWriter xmlWriter) i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\TableExtensionMetadataEmitter.cs:linje 44
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitter`1.EmitMetadata(Action`1 content) i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\GenericObjectMetadataEmitter.cs:linje 36
   ved Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileObject(ObjectTypeSymbol containingType) i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:linje 239
   ved Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.<>c__DisplayClass17_0.<CompileObjectAsTask>b__0() i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:linje 216
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:linje 150
   ved System.Threading.Tasks.Task.Execute()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.WaitForWorkers() i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:linje 161
   ved Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethodBodies(Compilation compilation, ModuleBuilder moduleBeingBuiltOpt, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:linje 145
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.CompileImpl(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:linje 806
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.Compile(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:linje 783
   ved Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.PackageTheModule(Compilation compilation, CompilerTextWriter consoleOutput, CancellationToken cancellationToken, ErrorLogger errorLogger, AnalyzerDriver analyzerDriver) i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:linje 531
   ved Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:linje 413
   ved Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:linje 312
   ved Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<HandleAsync>d__3.MoveNext() i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:linje 32
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:linje 59

**Comment by qutreson** [comment] 2018-11-14 14:13
Hi @superjma, which version of the compiler are you using?

This looks similar to #1826. Can you see if you are in a similar situation?

**Comment by superjma** [comment] 2018-11-14 14:34
Yes. I had a const(1).
I changed it to const("Order") and then it worked.
Thanks

**Comment by qutreson** [comment] 2018-11-14 16:07
@superjma, which version of the compiler were you using? Are you using the latest one from the marketplace?

So that we can now if we had a regression since #1826 got fixed, or if your version just did not have the fix.

**Comment by superjma** [comment] 2018-11-14 16:53
Visual studio
Version: 1.29.0 (system setup)
Commit: 5f24c93878bd4bc645a4a17c620e2487b11005f9
Date: 2018-11-12T07:47:15.448Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
AL: 11.0.25466

**Comment by StanislawStempin** [comment] 2018-11-14 17:02
Closing since this is fixed in newer versions

**Closed by StanislawStempin** 2018-11-14 17:02 UTC
