### ISSUE TITLE
You must use all lowercase letters for reserved keyword

### ISSUE THREAD

**Issue by DominicSaladin** [microsoft/AL#7233] opened 2022-11-08 07:11 UTC
Please include the following with each issue:

**1. Describe the bug**
When creating a codeunit variable, the compiler shows a message that the keyword "Codeunit" must be lowercase. The DropDown still shows "Codeunit" with an uppercase "C", I don't think it is normal to write "Codeunit" lowercase, right?

**2. To Reproduce**

1. Create a function
2. Add a Codeunit variable with the "Codeunit" keyword

**3. Expected behavior**
Nothing should happen. The keyword was always with an uppercase "C".

**4. Actual behavior**
![image](https://user-images.githubusercontent.com/43037258/200497166-d8aad579-6a63-45db-8350-9210867cd0b0.png)

**5. Versions:**

- AL Language: v10.0.687650
- Visual Studio Code: 1.73.0
- Business Central: 2022 Wave 2

**Comment by NKarolak** [comment] 2022-11-08 07:28
Duplicate of #7156.

**Comment by thloke** [comment] 2022-11-14 06:18
Closing as duplicate.

**Closed by thloke** 2022-11-14 06:18 UTC
