### ISSUE TITLE
Import Data File in BC Error on Extension 

### ISSUE THREAD

**Issue by dtcseverijns** [Microsoft/AL#4217] opened 2018-11-16 11:49 UTC
**Describe the bug**
When I import a Data File form a database to another database. The import of the File get the following error message: Cannot import the data because the specified file contains the following extensions that has not been synchronized to the database.

In the original database the extension is Uninstalled and delete

**To Reproduce**
Steps and/or AL code to reproduce the behavior:

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/40247000/48618479-cdfd5580-e999-11e8-836a-b54e7f19e388.png)

**Versions:**

 - AL Langauge:  

 - Business Central: 13.02.24623.0

**Comment by StanislawStempin** [comment] 2018-11-19 10:48
Can you try unpublishing the extension from the original database instead of just uninstalling?

**Comment by StanislawStempin** [comment] 2018-11-26 08:46
Closing due to lack of input

**Closed by StanislawStempin** 2018-11-26 08:46 UTC
Labels: input-needed

**Comment by nost2** [comment] 2019-03-07 13:14
Check the contents of these two tables and delete rows that reference extensions that are no longer used:

[$ndo$navappuninstalledapp]
[$ndo$navappschematracking]

**Comment by tokoskel** [comment] 2020-04-23 20:03
In version 14.0.37587 similiar error comes, when someone has modified layout using Web Client UI tool. Unistalling extension does not help and importing data will fail to similiar error regarding extension as descriped in this post start.

nost2 tip helps in this case, thank you!

**Comment by GhOnBc** [comment] 2020-07-09 08:24
This problem still exists in 16.1..

**Comment by SteveKrisjanovsD365** [comment] 2020-08-07 17:29
I too can repro this issue. I tried exporting navdata from one tenant and importing it into a new tenant and its complaining the target tenant is missing a designer extension. 

both tenants have all the same extensions installed. 

early on, there were some designer extensions installed on the source tenant. Even after unpublishing them and running a new navdata export, the import still refuses to work. there is no reason why the import should fail

**Comment by atoader** [comment] 2020-08-09 18:02
Can you please open a new issue with a complete repro? This issue has been closed because it did not provide sufficient information as to how to reproduce the issue.

**Comment by SteveKrisjanovsD365** [comment] 2020-08-19 01:13
@atoader will do. as noted in @nost2 's remark, it would appear that unpublishing an extension may not always clear the extension record from the [$ndo$navappuninstalledapp] and [$ndo$navappschematracking] tables. These orphaned records affect the import process. 

I suspect it's more to do with a bug in extension unpublishing that has effects downstream with exporting and importing. 

It's going to be hard to repro however because these orphaned [$ndo$navappuninstalledapp] and [$ndo$navappschematracking] records appear to be random. Most times, unpublishing an app leaves no orphaned records. When it does, it breaks the export/import process.

**Comment by atoader** [comment] 2020-08-20 03:54
When an extension is uninstalled, a record is inserted in navappuninstalledapp recording the version and the time when the extension was uninstalled. The navappschematracking table contains information about the version of the extension that has been synchronized (physical tables were created from AL tables).  Unpublishing does not clear any of these tables.
Sync-NavApp -Mode Clean would clear these entries, but it would also clear the extension's data and any physical tables.

**Comment by SteveKrisjanovsD365** [comment] 2020-08-20 13:17
@atoader understood! Your feedback is helpful and I think I can repro the issues with Import-NavData and these "dead" unpublished extensions. If I can reproduce what I suspect is happening, I'll submit a new ticket if I can reproduce it.
