### ISSUE TITLE
[BUG] PageExtension is not able to access protected variables 

### ISSUE THREAD

**Issue by dennisroczek** [microsoft/AL#6735] opened 2021-08-13 10:45 UTC
We produced the code in 18.2: a page extension extending a FactBox with background tasks using protected vars to simply display another flowfield from the record item.

With 18.3 we get the following error:

```
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\180\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\65\65C38CC50980F0B6C018DFE5E27E0BA7D5CD63A2CBB46CF2B6DD78811B53EB34.cs(74,287): error CS1061: 'PageExtension71757' does not contain a definition for 'Page71555_Item' and no accessible extension method 'Page71555_Item' accepting a first argument of type 'PageExtension71757' could be found (are you missing a using directive or an assembly reference?) C:\ProgramData\Microsoft\Microsoft Dynamics NAV\180\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\65\65C38CC50980F0B6C018DFE5E27E0BA7D5CD63A2CBB46CF2B6DD78811B53EB34.cs(75,229): error CS1061: 'PageExtension71757' does not contain a definition for 'Page71555_Item' and no accessible extension method 'Page71555_Item' accepting a first argument of type 'PageExtension71757' could be found (are you missing a using directive or an assembly reference?)
```

Changing the code using another record (so not using the Item record from the page) in the page extension works.

The compiler does not throw any errors, code cop does not throw any warnings, but in the process of installing the extension stops the process. (publishing works somewhat, it is listed in the page extensions)

**5. Versions:**
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043
- AL Language: 7.4.496506
- Visual Studio Code: 1.59.0 (user setup)
- Business Central: Microsoft_Application_18.3.27240.27480

**Comment by thloke** [comment] 2021-08-20 07:02
This is a duplicate of #6711 and has been hotfixed for 18.3 in SaaS. OnPrem/Docker should be fixed as well in 18.4.

**Closed by thloke** 2021-08-20 07:02 UTC
