### ISSUE TITLE
Extension compilation error: "Doesnt exist in the current context"

### ISSUE THREAD

**Issue by txeriff** [microsoft/AL#7011] opened 2022-04-22 10:15 UTC
Hi All,

I think this could be a bug, very strange thing:
-BC13 on prem.
-pageextension 50089 UserList extends Users
-I've tried adding the Rec but it doesn't work

Rec is nav virtual table User (2000000120)
   Clear(R50027); //custom report
   **R50027.SetSourceUserID(Rec."User Name", Rec."Full Name");**
   R50027.run;

Before compiling all is fine. Compiler error:

Objects/Page%20Extensions/Pag-Ext50089.UserList.al(17,44): error AL0118: The name 'Rec' does not exist in the current context
Objects/Page%20Extensions/Pag-Ext50089.UserList.al(17,61): error AL0118: The name 'Rec' does not exist in the current context

thanks a lot.

**Comment by dnpb** [comment] 2022-04-22 14:10
dupe of https://github.com/microsoft/AL/issues/7005

**Comment by txeriff** [comment] 2022-04-22 14:30
> dupe of #7005

Can someone replicate in latest BC? I don't see why this is discarded because it's not latest BC.

**Closed** 2022-04-28 08:55 UTC

**Comment by txeriff** [comment] 2022-04-28 08:59
I'm sorry but I don't see where's collaborate. can you provide a link?

**Comment by AbsolutelyFreeWeb** [comment] 2024-10-21 22:38
I was getting:
`error AL0118: The name 'Rec' does not exist in the current context`
as well as
`Error AL0284 - Expected type __MissingTypeSymbol__ - Virtual table not recognized when publishing extension`
with the same code that was compiling on a different workstation.

Turned out, re-installing the vs code AL extension helped to fix the problem
