### ISSUE TITLE
TableExtension BlankZero

### ISSUE THREAD

**Issue by tonyabriccomeske** [microsoft/AL#7670] opened 2024-02-20 18:52 UTC
Please include the following with each issue:

**1. Describe the bug**
When creating a table extension, you are able to modify an existing field, and change the value of the BlankZero property. You can build, and receive no errors. When you go to publish, you receive the following error:
<img width="756" alt="image" src="https://github.com/microsoft/AL/assets/26098636/27a2bf33-80e2-4e45-b496-fd16e2806f12">

**2. To Reproduce**
1. Create a new table extension like the code provided below

``` AL
tableextension 70100 "TBM_PurchaseLine" extends "Purchase Line"
{
    fields
    {
        modify(Quantity)
        {
            BlankZero = true;
        }
    }
}

```

2. Build your app. You don't receive any errors.
3. Attempt to deploy your app. You should receive an error.

**3. Expected behavior**
When compiling / building, I would expect to receive the error (if you cannot change the BlankZero property)

**4. Actual behavior**
I do not receive any sort of indication that I cannot modify the BlankZero property on a table extension

**5. Versions:**

- AL Language: v12.6.936426
- Visual Studio Code: 1.86.2
- Business Central: 23.3.14876.15103
- List of Visual Studio Code extensions that you have installed: AL Language Extension for Microsoft Dynamics 365 Business Central

**Comment by dannoe** [comment] 2024-02-21 07:03
Duplicate of #6555

**Comment by JesperSchulz** [comment] 2024-03-06 10:20
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 25.0.16995.0 and VS Code Extension Version 14.0.953267. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Closed by JesperSchulz** 2024-03-06 10:20 UTC
Labels: ships-in-future-update, accepted
