### ISSUE TITLE
Page Preview like in C/SIDE

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#1954] opened 2018-04-06 16:02 UTC
Any plans on conceiving a Page Preview in VSCode like we have in C/SIDE?

The question was posed during one of my workshops. The relevance wasn't just the visual display, but more about being able to click on elements in the page object seeing it's visual counterpart and vice versa like in C/SIDE page designer.

**Comment by StanislawStempin** [comment] 2018-04-08 07:34
This is something we would eventually like to implement but not a high priority at the moment. I will use this issue for tracking progress on this suggestion.

**Comment by StanislawStempin** [comment] 2018-11-05 14:03
This is actually a duplicate of https://github.com/Microsoft/AL/issues/400

**Closed by StanislawStempin** 2018-11-05 14:03 UTC
Labels: duplicate, suggestion
