### ISSUE TITLE
0T <> 000000T

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/AL#4840] opened 2019-04-04 12:29 UTC
**Describe the bug**
The txt2al tool converts 0T to 000000T. However in AL 0T <> 000000T. 

**To Reproduce**
```
    procedure TimeTest();
    var
        Time1: Time;
    begin

        if (Time1 <> 000000T) then begin
            Message('considered not equal');
        end else begin
            Message('not hit');
        end;

        if (Time1 <> 0T) then begin
            Message('not hit');
        end else begin
            Message('considered equal');
        end;

    end;
```

**Versions:**
 - AL Langauge: 3.0.106655
 - Business Central: 14.0.29530

**Comment by PooyaKharamesh** [comment] 2019-05-01 14:45
closing this since the issue is addressed in the upcoming release.

/Pooya

**Closed by PooyaKharamesh** 2019-05-01 14:45 UTC
Labels: bug

**Comment by coffeecup007** [comment] 2019-05-01 14:49
To clarify: 0T <> 000000T has been fixed is that correct?  This is the bigger part of the problem.  The txt2al tool incorrectly converting, although annoying, is manageable.

**Comment by PooyaKharamesh** [comment] 2019-05-01 16:38
The txt2AL is fixed. This behavior of not considering 0T, 000000T equal, is aligned with CAL. 

/Pooya
