### ISSUE TITLE
Autoformat should save code in this way the Intellisens suggest it

### ISSUE THREAD

**Issue by Nody85** [microsoft/AL#6254] opened 2020-10-27 18:26 UTC
Hello together,
our team would be glad if the style of reserved words/ variables are written in the Code like the Intellisens suggest it after the Autoformat goes over it on the Save event.

If we are lucky we have some quick wins here with other format Topics.

Reserved Words like if,begin and end are always lowercase.
Variables should be always like the definition is written in the VAR block.

```
**Bad example :**
Procedure MyProcedure()
Var
    MYVARIABLE : TEXT;
BeGIN
    myvariable := 'TESTVALUE';
    If MYvariable = '' tHen BEGIN
      do something;
      do something other;
    EnD;
ENd;
```

```
**Good example:**
Procedure MyProcedure()
Var
    MyVariable : TEXT;
begin
    MyVariable := 'TESTVALUE';
    if MyVariable = '' then begin
      do something;
      do something other;
    end;
end;

```

**Comment by qutreson** [comment] 2020-10-27 19:38
Duplicate of #6153 

The formatter only deals with white spaces and trivias, keyword casing should be handled by code actions. For more information see #6153

**Closed by qutreson** 2020-10-27 19:38 UTC
Labels: suggestion
