### ISSUE TITLE
Cannot debug or view source via AL Explorer for objects with forward slash in the name

### ISSUE THREAD

**Issue by MikeGlue** [microsoft/AL#7386] opened 2023-05-02 23:34 UTC
**1. Describe the bug**
Cannot debug or view source via AL Explorer for any object that has a forward slash '/' in the name. Seems to be a resurgence of the issue covered here that was described as fixed in April 2022.

[Issue 6972](https://github.com/microsoft/AL/issues/6972#issuecomment-1105197125)

**2. To Reproduce**

1. Using AL Explorer, find report 96 (Copy G/L Budget) and select it
2. Press the Source button

Nothing happens.

Setting a breakpoint ahead of that object and executing code that triggers the breakpoint ends up showing you an empty object with no source code.

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
Should be able to debug and view source for objects with forward slash in the name.

**4. Actual behavior**
When debugging: object shows no source code
When using source button in AL Explorer: nothing happens

**5. Versions:**

- AL Language: 12.0.779795
- Visual Studio Code: 1.77.3
- Business Central: 22.1
- List of Visual Studio Code extensions that you have installed: none (uninstalled them all)

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by NKarolak** [comment] 2023-05-03 06:02
Duplicate of #7369

**Comment by thloke** [comment] 2023-05-09 06:15
This is actually something on the VSCode side. I've raised the issue with them, but I'll ping them again.

https://github.com/microsoft/vscode/issues/172108

**Comment by SBalslev** [comment] 2023-08-17 08:56
Closing this as we have done work in #7369 that should give us most of the solution. Further enhancements will happen after/if vscode decides to improve the scenario from their end.

**Closed by SBalslev** 2023-08-17 08:56 UTC
Labels: external, al-explorer
