### ISSUE TITLE
Questions or Problem: app.json logo not displayed - size requirements needed?

### ISSUE THREAD

**Issue by megel** [Microsoft/AL#1211] opened 2017-12-15 12:48 UTC
Size matters :)

Microsoft (R) AL Compiler version 0.12.15355
Copyright (C) Microsoft Corporation. All rights reserved

I have added a logo to my project (2 pictures):
![grafik](https://user-images.githubusercontent.com/15800069/34042520-67cc02ca-e19d-11e7-9df0-1bace1667fe5.png)

The logo is used in the ```app.json``` and works fine for the large logo (512x512):
![grafik](https://user-images.githubusercontent.com/15800069/34042562-90267a3e-e19d-11e7-96c1-8e849a1fbe49.png)

![grafik](https://user-images.githubusercontent.com/15800069/34042595-c6d96a5a-e19d-11e7-8a0d-04b496a2166d.png)
----
The small logo is not displayed:
![grafik](https://user-images.githubusercontent.com/15800069/34042641-ee107532-e19d-11e7-80af-b79ed007daac.png)

![grafik](https://user-images.githubusercontent.com/15800069/34042582-b82163fa-e19d-11e7-8af7-80604b919ea8.png)
----

Questions:
1) Are there any size requirements?
1) Is it possible to print out a warning after build?

**Comment by HunterFeltman-MSFT** [comment] 2017-12-18 15:31
There should not be any minimum size requirements for logo images, the platform will be able to scale the provided logo to the appropriate height/width on request. 

I am not able to reproduce this as of yet, is this consistent for you? Is it only these images?
Are you running on the Developer Preview? If not, then what version of the NAV platform are you using?

**Comment by megel** [comment] 2017-12-19 12:42
My version is from Docker ```microsoft/dynamics-nav:2018-w1```:
![grafik](https://user-images.githubusercontent.com/15800069/34157442-cc09348e-e4c1-11e7-87af-492376bfcc36.png)

Here is the sample project (Logo 108x108 is used) of the last try, where the logo was not displayed:
[Sample.zip](https://github.com/Microsoft/AL/files/1571667/Sample.zip)

**Comment by HunterFeltman-MSFT** [comment] 2017-12-29 19:29
Bug is fixed in latest developer preview, and in the latest version of the D365 code base.
However, at this time it will not be hotfixed immediately for NAV2018, but will instead go out during the NAV2018 R2 release in spring.

**Closed** 2018-02-15 16:48 UTC
Labels: bug, delivered
