### ISSUE TITLE
Object Type PermissionSet : auto-completion for the next object number is not working

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/AL#6577] opened 2021-04-13 13:10 UTC
**1. Describe the bug**
When you create a new PermissionSet object, you have to specify an object id. 
For all object type, intellisense is able to give the next available number. But nothing is proposed for PermissionSet.

**2. To Reproduce**

1. Create a new .al file in VSCode
2. Type ```tpermissionset``` 
    You got the following code:
```
permissionset Id MyPermissionSet
{
    Assignable = true;
    IncludedPermissionSets = SomePermissionSet;
    Permissions = 
        ObjectType ObjectName = ObjectPermissions;
}
```
3. Remove the "Id" placeholder and type Ctrl+Space to open code completion box.

**3. Expected behavior**
An object ID is expected:
![image](https://user-images.githubusercontent.com/44807684/114557823-59ae6580-9c6a-11eb-98e5-2b94678d60c7.png)

**4. Actual behavior**
No object is is proposed:
![image](https://user-images.githubusercontent.com/44807684/114557711-3be10080-9c6a-11eb-8d05-1bb6a094c802.png)

**5. Versions:**

- AL Language: 7.1.441584
- Visual Studio Code: 1.55.1

**Comment by EmilDamsbo** [comment] 2021-04-21 09:54
We have been unable to reproduce this problem with the information you have provided:
![image](https://user-images.githubusercontent.com/67266681/115534299-2b8ede00-a287-11eb-88ff-d2b227f863d9.png)
Please make sure the your app.json has specified the 'idRanges'-property like so:
![image](https://user-images.githubusercontent.com/67266681/115534535-68f36b80-a287-11eb-9a7b-7d660267d9fa.png)

If you cannot provide a reproducible bug I will close this as already fixed.

**Comment by nicolassaleron** [comment] 2021-04-23 07:06
I have not the behavior you are presenting on my side: but it is definitely what I would expect

The repro steps are simple:

1. Open VSCode
2. F1 + AL Go
3. Create a new .al file
4. Type tpermissionset
5. Remove the placeholder Id and type Ctrl+Space

I have the ID Ranges set in the app.json file (instead I would not get an ID for other object types) and I tried again by disabling all other VSCode extension : the issue is still there.

What is your AL Language version? Are you using the one from the marketplace or a more recent version?

**Comment by EmilDamsbo** [comment] 2021-04-27 09:35
We have investigated your issue and it will be fixed with the next extension update.
I am closing this issue because it appears that it has been resolved.

**Closed by EmilDamsbo** 2021-04-27 09:35 UTC
Labels: bug, in-progress
