### ISSUE TITLE
error AL0161: 'Code Unit' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by marcoleosbz** [microsoft/AL#5854] opened 2020-05-04 13:30 UTC
**Describe the bug**
We have two apps ("Master" + "Slave") that are linked together by dependency: "Slave" depends on "Master". The app "Master" has a few internal methods (internal procedure and internal event) in a code unit (Access = Internal;) and in app.json the "internalsVisibleTo" property refers to "Slave". One would expect that "Slave" can call those internal methods in "Master". 
And : he can! But only as long as Master is NOT a **runtime package** (e.g. generated with Get-NavContainerAppRuntimePackage from previously deployed app) . 
We have verified the manifest inside the runtime package of "Master" and the InternalsVisibleTo-part is still there and correct. 
Yet, "Slave" can access those methods **ONLY** if "Master" is a NOT runtime package.

**Versions**
_Host_:   Windows 10
_Docker container_:
  - mcr.microsoft.com/businesscentral/onprem:2004-rtm-w1
     container started with "includeTestToolkit" and "includeTestLibrariesOnly"
     used e.g. c:\shared  as  "shared volume folder" with container 
  - platform: 16.0.11233.12061
  - application version:  16.0.11240.12076

_VSCode_:
  use 2 different instances of VSCode (1 for master app + 1 for slave app)
  don't use workspace with both apps!!!

  AL Language: 5.0.244558

**To Reproduce**
1. create master app 
   add code unit with attribute  Access = internal  and a internal procedure or/and a internalevent
2. create slave app with dependency to master app
3. add app id, name, ... of slave app to "internalsVisibleTo" tag in app.json of master app
4. deploy master app to container (from VSCode)
5. download symbols to slave app (including symbols for just deployed master app)
6. add a new codeunit  that include a refernce to codeunit of master app
7. build/deploy slave app:  no errors should be found
8. from powershell get runtime package of  master app
   Get-NavContainerAppRuntimePackage -containerName xyz -appName "master" -appVersion 1.0.0.0 -appFile "shared volume folder\master_1.0.0.0.app"
9. uninstall, synch clean and unpublish  slave and master app
10. publish and install previous runtime app
   Publish-NavContainerApp -containerName xyz -appFile "shared volume folder\master_1.0.0.0.app" -install -sync -skipVerification
11. in VSCode (slave app) delete symbols folder (.alpackages)
12. download symbols again for slave app 
13. build slave app -->  error AL0161 

zip-file with master/slave test apps:
[err_al0161_example.zip](https://github.com/microsoft/AL/files/4574769/err_al0161_example.zip)

 ps! we published this issue also on Yammer in "App development"

**Comment by atoader** [comment] 2020-05-05 18:50
Thank you for taking the time to reproduce this! The issue is most likely caused by the fact that we do not persist the internalsVisibleTo property in the manifest created for the runtime package. I will mark it as a bug.
We will pick up the bug as soon as we have capacity.

**Comment by qutreson** [comment] 2020-09-08 13:52
This issue has been fixed in our latest developer preview.

**Closed by qutreson** 2020-09-08 13:52 UTC
Labels: bug, in-progress
