### ISSUE TITLE
New Report isn't shown on Web client

### ISSUE THREAD

**Issue by hgnamvn** [Microsoft/AL#837] opened 2017-10-24 07:18 UTC
Hi !

I have a problem when i run a new report. Report view isn't shown on Web Client.

1. I create new report.
    ![image](https://user-images.githubusercontent.com/24407031/31928912-14a13586-b8c4-11e7-8336-575f0939fd6f.png)

2. I add a action on Posted Sales Shipment to run the new report.
3. I run new report as bellow.
     ![image](https://user-images.githubusercontent.com/24407031/31929049-8cf546a8-b8c4-11e7-98b8-c0da610d5192.png)
     ![image](https://user-images.githubusercontent.com/24407031/31929114-d3753a52-b8c4-11e7-99b1-d31da519603d.png)

**_And this is result:_**
     ![image](https://user-images.githubusercontent.com/24407031/31929141-fcbf5a28-b8c4-11e7-8922-fa9df3d0632c.png)

**_Note:_** After I close report viewer, I can't do anything (close page, open another page), I must refresh Web Browser again to continue.

5. But, it run OK on Window client.
    ![image](https://user-images.githubusercontent.com/24407031/31929416-266b2c48-b8c6-11e7-8965-4785a1121060.png)

I test on October version (W1 11.0 (18712)).

**Comment by rslovak** [comment] 2017-10-26 09:01
I have the same problem. Sending report to excel to word or excel works.

**Comment by DominikDitoIvosevic** [comment] 2017-12-14 10:17
Hi @hgnamvn . Could you maybe test on a newer version than October preview? Also, could you maybe give us a more specific repro? I tried doing the same as you did and I had no issues.

**Comment by hgnamvn** [comment] 2017-12-15 06:10
Hi DominikDitoIvosevic,

I tested on October version (W1 11.0 (18712)).

Now, I test on NAV 2018 (non-docker). It works well.
Because I have a issues about server, so I will tested again on December version (docker version) on next week and give you a result.

**Comment by rslovak** [comment] 2017-12-15 08:02
Hi,
I tested it on December preview (docker-version) and it's still the same.

I have prepared simple list report with RDLC layout based on new table from extension.
Preview and send to PDF - doesn't work
Send to Excel or Word - works

Roman

**Comment by hgnamvn** [comment] 2017-12-18 03:35
Hi,
I think the root cause is found.
It work well for me.
Please reference [this link.](https://github.com/Microsoft/nav-docker/issues/115)

**Comment by DominikDitoIvosevic** [comment] 2017-12-18 06:58
I'm happy to hear this works :)
@rslovak could you please try the same fix from the link?

**Comment by rslovak** [comment] 2017-12-18 08:01
Great. It works now. Thank you to all.

**Comment by DominikDitoIvosevic** [comment] 2017-12-18 08:04
Closing as duplicate of https://github.com/Microsoft/nav-docker/issues/115

**Closed by DominikDitoIvosevic** 2017-12-18 08:04 UTC
Labels: duplicate
