### ISSUE TITLE
Support Function "DownloadFromStream"

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#448] opened 2017-08-02 12:49 UTC
With the help of the function "UploadIntoStream" one can fortunately still send local data to the service. Unfortunately, however, I have found no way to download already existing data. Unfortunately, I can not use the opposite function "DownloadFromStream" to download a file. Furthermore, all functions of the Codeunit "File Management" can not be used. Make i something wrong here, or how to get back to a file that is stored in the database, for example, in a BLOB field.

_**The type or method 'DownloadFromStream' cannot be used for 'Extension' development.**_

**Comment by StanislawStempin** [comment] 2017-08-11 13:34
Duplicate of #343

**Closed by StanislawStempin** 2017-08-11 13:34 UTC
Labels: function-expose, ships-in-future-update

**Comment by viktoreinars** [comment] 2017-09-11 00:34
I am trying to use the DownloadFromStream but I am getting the same error as the original poster. I created my demo sandbox about two days ago. 

How can I update VS Code to recognize that the function is valid?

**Comment by StanislawStempin** [comment] 2017-09-11 09:18
Which method are you referring to?  The File.DownloadFromStream is available in extensions. 
The following code compiles successfully:
```
pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var
    stream : InStream;
    txt : text;
    begin        
        File.DownloadFromStream(stream, 'Title', 'ToFolder', 'Filter', txt);
    end;
}
```

**Comment by viktoreinars** [comment] 2017-09-11 09:21
Hi Stanislaw,

This is how it looks for me:

[cid:image001.jpg@01D32ADF.4D8F8000]

Best regards,
Viktor Einarsson

**Comment by StanislawStempin** [comment] 2017-09-11 09:23
Which AL Language extension version are you using? 
(In VS Code press Ctrl + Shift + X and see the version next to AL Language)

**Comment by viktoreinars** [comment] 2017-09-11 09:24
0.7.12087

**Comment by StanislawStempin** [comment] 2017-09-11 09:28
In that version it was still not enabled. You would need to use version 0.8 or newer  (the latest Dev Preview environments run on 0.9 - September Update, the online Sandboxes and VS Marketplace still run on 0.7 for a few more days)
