### ISSUE TITLE
Compiling App against Next Major shows AL0186 error

### ISSUE THREAD

**Issue by ralf-escher** [microsoft/AL#7650] opened 2024-01-23 05:59 UTC
Since two nights our Next Major pipeline shows AL0186 errors.

For a few of our pages the compiler cannot find the fields from a Table Extension.
```
page/AutBlanketSalesOrder.Page.al(1120,35): error AL0186: Reference '"BET AUT Trans.-/Call Order No."' in application object 'Sales Header' does not exist
page/AutomotiveSalesOrder.Page.al(1936,63): error AL0186: Reference '"BET AUT Our Item No."' in application object 'Sales Header' does not exist
page/AutomotiveSalesOrder.Page.al(1948,35): error AL0186: Reference '"BET EDI Doc. No."' in application object 'Sales Header' does not exist
page/AutomotiveSalesOrderList.Page.al(645,35): error AL0186: Reference '"BET AUT Plant"' in application object 'Sales Header' does not exist
page/AutomotiveSalesOrderList.Page.al(657,63): error AL0186: Reference '"BET AUT Our Item No."' in application object 'Sales Header' does not exist
```

there was no change within these objects and there are plenty of other fields in these pages from the table extension which cause no error.

After the comment of @rdebath (see below) I can confirm that those fields above are used inside a Page Action within a `RunPageLink`

**Comment by NKarolak** [comment] 2024-01-23 07:28
I can confirm the very same like @rdebath described it for `RunPageLink`.

**Comment by NKarolak** [comment] 2024-01-23 07:36
@BazookaMusic Can you please forward? There is some major issue in the latest AL Language build 13.*, it seems.

**Comment by rdebath** [comment] 2024-01-23 09:38
I seem to also have the same issue with a `LinkFields` property on an XMLport

```
##[error]./C:/agents/Agent1/_work/612/s/App/Self/src/XMLport/HSBCNURGCTpain00100103.XmlPort.al(163,38): error AL0186: Reference '"TVT.HSBC Snder Bank Branch No."' in application object 'Payment Export Data' does not exist
```

``` AL
    schema
    {
        tableelement("Gen. Journal Line"; "Gen. Journal Line")
        {
            XmlName = 'Document';
            UseTemporary = true;
            tableelement(companyinformation; "Company Information")
            {
...
                    tableelement(paymentexportdata; "Payment Export Data")
                    {
                        LinkFields = "TVT.HSBC Snder Bank Branch No." = FIELD("TVT.HSBC Snder Bank Branch No."), "SEPA Instruction Priority Text" = FIELD("SEPA Instruction Priority Text"), "Transfer Date" = FIELD("Transfer Date"), "SEPA Batch Booking" = FIELD("SEPA Batch Booking"), "SEPA Charge Bearer Text" = FIELD("SEPA Charge Bearer Text");
                        LinkTable = PaymentExportDataGroup;
                        XmlName = 'CdtTrfTxInf';
                        UseTemporary = true;
...
```

**Comment by TMEKUMA** [comment] 2024-02-01 14:49
I have the same with the SubPageLink.

**Comment by JesperSchulz** [comment] 2024-02-02 12:59
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 24.0.15812.0 and VS Code Extension Version 13.0.934715. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Closed by JesperSchulz** 2024-02-02 12:59 UTC
Labels: ships-in-future-update, accepted

**Comment by rdebath** [comment] 2024-02-04 13:36
Huh, looks like we've only been getting 'core' versions since the 28th Jan.
I can only see Version 24 localised versions for 27th Jan and before.

Oh, and your "Ready2Go" information is out of date (aka.ms/readytogo no longer exists). The `sastoken` provided by that program is no longer needed; you just have to add the `-accept_insiderEula` flag [See here.](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-running-container-development)

Also https://github.com/microsoft/navcontainerhelper/issues/3327 if that's a more appropriate spot.
