### ISSUE TITLE
Error AS0031 thrown if the previous app version has been built with AL Language 6.6

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#6545] opened 2021-03-19 13:46 UTC
**1. Describe the bug**
Apps files compiled with the AL Language version 6.x (including the current from the marketplace) lead to an unexpected behavior when using such files as the previous app version for the AppSourceCop.

The AppSourceCop throws error AS0031 if you try remove an action that was already set on `ObsoleteState = Pending`.

**2. To Reproduce**
Please find the simple repository attached:  [DeleteAction.zip](https://github.com/microsoft/AL/files/6171363/DeleteAction.zip)
Download the symbols from any standard BC database version 17 or 18, and then try to build the package.

Included is the code for **version 2.0** of my app that uses compiler directives to test removing an obsolete page and an obsolete action.

The `.alpackages` folder contains the **version 1.0** of my app, where a codeunit and an action were already set to `ObsoleteState = Pending`. You can verify by unzipping the app file. This app version was compiled with AL Language version 6.6.

The AL language version for testing version 2.0 is **not** relevant.

By updating the app.json (version, preprocessorSymbols) and the AppSourceCop.json (version) you can easily recreate version 1 of my app with other AL language versions to verify.

**3. Expected behavior**
The removal of the codeunit and the action should be allowed.

**4. Actual behavior**
Only the removal of the codeunit is allowed. 
The action throws an error:
> The action with name 'ActionName' defined in Page 'TESTMyPage' was found in the previous version, but is missing in the current extension. This will break dependent extensions.

**5. Versions:**

- AL Language: 6.6.425415
- Visual Studio Code: 1.54.3
- Business Central: not relevant
- List of extensions that you have installed: not relevant

**Comment by dannoe** [comment] 2021-03-19 14:08
The correct way should be to first release a version with ObsoleteState = Removed and then remove it in the next version, right?
So the actual problem is that the codeunit didn't throw that error.

**Comment by NKarolak** [comment] 2021-03-19 14:16
@dannoe There is no Removed state for codeunits and actions. The removed state is for tables and fields only, so that they are still accessible for upgrade codeunits in on-prem when skipping multiple versions.

**Comment by qutreson** [comment] 2021-03-19 15:21
@NKarolak thank you for providing a project with the repro.

 I looked at the extension's baseline and the action is not marked as obsolete, only the containing group is:

![image](https://user-images.githubusercontent.com/31541422/111802952-dd28a100-88ce-11eb-9054-06e2ebf6bf12.png)

We do not propagate the obsolete state to the actions in a group, so the AppSourceCop behavior is correct here

**Comment by NKarolak** [comment] 2021-03-19 15:26
I see, let me check again without any action group.

Since the error does not show up if you compile app version 1 with AL Language 7.x - does it mean there is a bug in that AL Language version?

**Comment by qutreson** [comment] 2021-03-19 15:50
I tried reproducing the issue with an AL extension version 7.* and it reports an error for the missing action:

![image](https://user-images.githubusercontent.com/31541422/111807316-1f53e180-88d3-11eb-80f8-a9dd4252adbc.png)

**Comment by NKarolak** [comment] 2021-03-19 15:55
Just to be sure:
Using AL Language 7, you created app version 1.0 again, moved the new app file to the .alpackages folder, and then you tried to compile version 2.0 again?

**Comment by qutreson** [comment] 2021-03-19 16:02
No, I haven't recompiled the version 1.0, I used the project you provided. Let me try to re-create the baseline project too.

**Comment by qutreson** [comment] 2021-03-19 16:08
I still cannot reproduce the issue. Here are the steps I followed:
1. Change the version to 1.0.0.0 in the app.json and removed the preprocessor symbols from the app.json
2. Build the package 1.0.0.0 and move it to the baseline package cache (.alpackages here)
3. Reverted the changes in the app.json (changing the version to 2.0.0.0 and adding the preprocessor symbols back)
4. Recompiling the project version 2.0.0.0 --> AS0031 is reported

**Comment by NKarolak** [comment] 2021-03-19 16:38
Sounds correct. Weird that you could not reproduce, but probably my 7.x VSIX was too old and buggy and therefore ignorable. Let me verify on Monday.
Have a nice weekend!

**Comment by nicolassaleron** [comment] 2021-03-19 21:22
@qutreson We already get into this issue and it would make sense that ObsoleteState is inherited by child controls.
After all when an object is marked Access=Internal all procedures inherit this scope.

**Comment by NKarolak** [comment] 2021-03-22 08:04
@qutreson 
Using my old  AL Language 7.0.420929 for creating app version 1.0, I can still reproduce it (meaning: deleting the action group + action **without** getting an AS error for the action).
For you reference, here is my faulty version 1.0 app file:
[Test_DeleteAction_1.0.0.0.app.zip](https://github.com/microsoft/AL/files/6180303/Test_DeleteAction_1.0.0.0.app.zip) (zipped because GitHub won't let me upload app files directly)

Testing it again with AL Language 7.0.429144 returned the warning, just like in your test.
So it has been fixed in the meantime.

About "obsoleting action group vs. action": Well, if a group would inherit the obsolete state to its children, it would mean that we could never extract an action from a group. 
So I guess this issue can be closed, unless you have some more input :-)

**Comment by qutreson** [comment] 2021-03-22 09:07
@NKarolak thank you for giving it another try. It is strange that the old version is facing this issue, but good to hear that it doesn't reproduce in the latest version. I'll close this issue then :)

@nicolassaleron this case is slightly different because properties defined on the object itself (like Accessibility, Extensible or ObsoleteState) are considered by the cops. When defining the obsolete state on the page object itself, the AppSourceCop should allow removing the action (as long as the page itself is not obsolete anymore, see #5869 and #5870 for more details) - I just verified and, of course, this specific rule doesn't behave as I just mentioned, so it will be fixed.

Propagating the obsolete state to elements defined in a group looks more like a developer productivity feature request. Changing the current behavior would have to be versioned or based on some kind of opt-in approach in order to not have unintended consequences on existing extensions. Can you report this on bcideas so that it can be prioritized as such?

**Closed by qutreson** 2021-03-22 09:07 UTC
Labels: AppSourceCop, input-needed, static-code-analysis

**Comment by nicolassaleron** [comment] 2021-03-22 09:38
Suggestion reported here: https://experience.dynamics.com/ideas/idea/?ideaid=69e8f64a-f28a-eb11-8ced-0003ff45a07d
