### ISSUE TITLE
Incorrect table name in table relation does not throw an error message during compilation

### ISSUE THREAD

**Issue by JanBoes** [Microsoft/AL#97] opened 2017-02-09 15:26 UTC
![screen shot 2017-02-09 at 12 47 24](https://cloud.githubusercontent.com/assets/22166392/22789743/51c308ea-eee4-11e6-8d7d-81b094f56a1b.png)

Hi,

I made a typo in the table relation property (no space in No. Series"
TableRelation = "No.Series".Code 
It is shown as an error, but when I press [F5] the package is build and published

**Comment by StanislawStempin** [comment] 2017-02-27 10:42
Which version of the AL Language extension are you using? This was an issue in the January Update, that should have been fixed in the February Update. I cannot reproduce it using the latest version.

**Comment by JanBoes** [comment] 2017-02-27 12:55
Hi,

The only thing we are doing is request the offline customer list via PartnerSource Business Center.
They create the csv files for us and we download them.
This process results in different date formats in one line.

I asked our partner care employee to download a new set, I will update you tomorrow on the results.

Kind regards,

Jan Boes

On 27 Feb 2017, at 11:42, Stanislaw Stempin <notifications@github.com<mailto:notifications@github.com>> wrote:


Which version of the AL Language extension are you using? This was an issue in the January Update, that should have been fixed in the February Update. I cannot reproduce it using the latest version.

**Closed** 2017-02-28 09:08 UTC
