### ISSUE TITLE
OnFindRecord in FactBox not executed on record change

### ISSUE THREAD

**Issue by mightyjens** [microsoft/AL#7222] opened 2022-10-21 13:32 UTC
Hi guys,
at the moment we have some problems in our extensions which appear after updating to v21.
We have a FactBox in which we handle the record ourselves using the OnFindRecord trigger. 
The background is, that this way we transfer some more filters into the FactBox.

//I've tested both SaveValueToDatabasePromptly true/false

**Expected Behavior**
The OnFindRecord trigger should be executed everytime the record changes.
E.g. if you click on the next contact in the contact list page.

**Actual Behavior**
It seems that in v21 the OnFindRecord is not executed everytime a record changes. 
It is executed once when opening the Parent List page.
After clicking on the next record, the trigger is not executed/updated again.

**How to Reproduce?** 
I've stripped the problem down to the minimum using a v21 (latest) Docker container.

Create a factbox which should handle the record itself:
```
page 50101 OnFindRecordTestFactBox
{
    Caption = 'OnFindRecordTestFactBox';
    PageType = CardPart;
    SourceTable = Contact;


    trigger OnFindRecord(Which: Text): Boolean;
    begin
        exit(OnFindRecordFilters(Rec)); 
    end;

    procedure OnFindRecordFilters(var pRec: Record Contact): Boolean
    begin
        pRec.FILTERGROUP(4);
        Message(pRec.GETFILTER("No."));
        pRec.FILTERGROUP(0);

        exit(pRec.Findset()); 
    end;
}

```

Create a page extension:
```
pageextension 50101 OnFindRecordTest extends "Contact List"
{
    layout
    {
        addfirst(factboxes)
        {
            part("TestFactbox"; OnFindRecordTestFactBox)
            {
                Editable = false;
                ApplicationArea = All;

                SubPageLink = "No." = field("No.");
                SubPageView = SORTING("No.")
                              ORDER(Ascending);
            }
        }
    }
}
```

The OnFindRecord trigger should execute once after initially opening the contact list. 
Every following record change in the contact list will not execute it again.

I hope I am in the right place with this problem. Otherwise, please give me a tip where else I should report it. 

Thank you
Jens

**Comment by herojo** [comment] 2022-10-25 12:03
> Hi guys, at the moment we have some problems in our extensions which appear after updating to v21. We have a FactBox in which we handle the record ourselves using the OnFindRecord trigger. The background is, that this way we transfer some more filters into the FactBox.
> 
> //I've tested both SaveValueToDatabasePromptly true/false
> 
> **Expected Behavior** The OnFindRecord trigger should be executed everytime the record changes. E.g. if you click on the next contact in the contact list page.
> 
> **Actual Behavior** It seems that in v21 the OnFindRecord is not executed everytime a record changes. It is executed once when opening the Parent List page. After clicking on the next record, the trigger is not executed/updated again.
> 
> **How to Reproduce?** I've stripped the problem down to the minimum using a v21 (latest) Docker container.
> 
> Create a factbox which should handle the record itself:
> 
> ```
> page 50101 OnFindRecordTestFactBox
> {
>     Caption = 'OnFindRecordTestFactBox';
>     PageType = CardPart;
>     SourceTable = Contact;
> 
> 
>     trigger OnFindRecord(Which: Text): Boolean;
>     begin
>         OnFindRecordFilters(Rec);
>     end;
> 
>     procedure OnFindRecordFilters(var pRec: Record Contact): Boolean
>     begin
>         pRec.FILTERGROUP(4);
>         Message(pRec.GETFILTER("No."));
>         pRec.FILTERGROUP(0);
> 
>         exit(true);
>     end;
> }
> ```
> 
> Create a page extension:
> 
> ```
> pageextension 50101 OnFindRecordTest extends "Contact List"
> {
>     layout
>     {
>         addfirst(factboxes)
>         {
>             part("TestFactbox"; OnFindRecordTestFactBox)
>             {
>                 Editable = false;
>                 ApplicationArea = All;
> 
>                 SubPageLink = "No." = field("No.");
>                 SubPageView = SORTING("No.")
>                               ORDER(Ascending);
>             }
>         }
>     }
> }
> ```
> 
> The OnFindRecord trigger should execute once after initially opening the contact list. Every following record change in the contact list will not execute it again.
> 
> I hope I am in the right place with this problem. Otherwise, please give me a tip where else I should report it.
> 
> Thank you Jens

Hi, i detect the same issue. With v21 existing Infobox-Implementations don´t work any longer. 2 Apps (on Appsource) where effected and some PTE-implementations. Someone any idea? Regards Jochen

**Comment by salgiza** [comment] 2022-10-27 12:05
Same thing here, I can confirm that all of our fact boxes that use OnFindRecord have stopped working in BC21, as the trigger is only executed when the fact box is loaded, not when the user navigates through the linked records.

**Comment by NKarolak** [comment] 2022-10-27 12:14
@mightyjens On a sidenote: are you aware that your code above is incomplete?

```
page 50101 OnFindRecordTestFactBox
{
    Caption = 'OnFindRecordTestFactBox';
    PageType = CardPart;
    SourceTable = Contact;


    trigger OnFindRecord(Which: Text): Boolean;
    begin
        exit(OnFindRecordFilters(Rec);) // <------- the return value was missing ----------
    end;

    procedure OnFindRecordFilters(var pRec: Record Contact): Boolean
    begin
        pRec.FILTERGROUP(4);
        Message(pRec.GETFILTER("No."));
        pRec.FILTERGROUP(0);

        exit(pRec.Findset()); // <------ not always true
    end;
}
```

**Comment by mightyjens** [comment] 2022-10-27 12:23
Thank you so much! I had actually just hung on the trigger via debugger and didn't follow up on the rest. Have adjusted it in the initial comment. :)

**Comment by thloke** [comment] 2022-11-01 07:38
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

The reason why this is out of scope is because this is about how triggers work at runtime, and should go to the team that handles the server runtime.

**Closed by thloke** 2022-11-01 07:38 UTC

**Comment by dtacconi** [comment] 2022-11-08 14:24
Thanks to open this request to support.
This behavior has been reproduced and platform changes has been committed into 21.2 December Cumulative Update on-premises. 
The same changes will also be back ported to SaaS worldwide to 21.0 and 21.1 environments. The patching activity might span through this weekend or earlier next week.
