### ISSUE TITLE
Table locking issue 

### ISSUE THREAD

**Issue by shashiBssi** [microsoft/AL#6204] opened 2020-10-08 06:25 UTC
**Describe the bug**
if stop debugger in between , then random table is locked and it did not release lock and not allow to publish again.

Previous versions of Al language didn't have this issue.

**To Reproduce**
debug any code and stop in between, then try to use any related bc feature or publish again.

``` AL Code to reproduce the issue ```

**Expected behavior**
no locking of tables , when i stop debugger in between.

**Screenshots**

**5. Versions:**
al language --- latest on marketplace

bc 16.5

**Comment by GhOnBc** [comment] 2020-10-08 09:21
Can confirm, I am experiencing same issue lately.

**Comment by kalberes** [comment] 2020-10-09 16:11
Can we have a repro please?

**Comment by shashiBssi** [comment] 2020-11-10 06:36
#6233

**Comment by atoader** [comment] 2020-11-10 07:56
@shashiBssi I'll close this as a duplicate of #6233

**Closed by atoader** 2020-11-10 07:56 UTC
Labels: input-needed
