### ISSUE TITLE
[Use of Option Access syntax in formulas] - RunPageLink does not allow change of constant to Database::

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/AL#7281] opened 2022-12-14 08:39 UTC
Using runtime 10.1 changing the const(5407) to const(Database::"Prod. Order Component") fails in a subpage with a property RunPageLink. The IntelliSense suggests "Database" and "Prod. Order Component" but the 10.1 AL compiler refuses the result.

You can test this in the Base app in page 99000818 "Prod. Order Components" in the action "Put-away/Pick Lines/Movement Lines"

page 11223111 "A108 Prod. Order Comp. Subpage"
{
AutoSplitKey = true;
Caption = 'Lines';
DelayedInsert = true;
LinksAllowed = false;
MultipleNewLines = true;
PageType = ListPart;
SourceTable = "Prod. Order Component";

...
            action(PutAwayPickMovementLines)
            {
                ApplicationArea = Warehouse;
                Caption = 'Put-away/Pick Lines/Movement Lines';
                Image = PutawayLines;
                RunObject = Page "Warehouse Activity Lines";
                RunPageLink = "Source Type" = const(5407),
                              "Source Subtype" = const("3"),
                              "Source No." = field("Prod. Order No."),
                              "Source Line No." = field("Prod. Order Line No."),
                              "Source Subline No." = field("Line No.");
                RunPageView = sorting("Source Type", "Source Subtype", "Source No.", "Source Line No.", "Source Subline No.", "Unit of Measure Code", "Action Type", "Breakbulk No.", "Original Breakbulk");
            }

![image_14](https://user-images.githubusercontent.com/30273162/207547346-a0b00d9d-fba0-47ba-9bba-bd10f254847f.png)

**Comment by Duizy1971** [comment] 2022-12-14 09:48
This is a BC21.02W1 database running on latest AL extension with the runtime set to 10.1

![image_15](https://user-images.githubusercontent.com/30273162/207562295-741bc57e-96de-4d9d-8b96-b85ffecfdae0.png)

**Comment by JMA1972** [comment] 2022-12-14 14:39
This is a duplicate of #7205

**Closed** 2022-12-15 18:11 UTC
