### ISSUE TITLE
InitValue for enums no longer working

### ISSUE THREAD

**Issue by RafaelKoch** [microsoft/AL#6106] opened 2020-08-26 18:42 UTC
**Describe the bug**
A table field of type enum cannot have an InitialValue

**To Reproduce**

Given: enum with some members. a table with a field referencing the enum.
Add property InitValue to the table field

``` AL Code to reproduce the issue ```

![image](https://user-images.githubusercontent.com/25029667/91342993-2357cf00-e7dc-11ea-9d5f-c619b75bf169.png)

**Expected behavior**

Works like it did since resolution of #4192

**Screenshots**

**5. Versions:**

 - AL Language:  v6.0.321546

 - Business Central: Platform 17.0.15765.0 + Application 17.0.15854.0

**Comment by NKarolak** [comment] 2020-08-27 06:10
While you are at it, can you please also add intellisense for choosing all available Enum values?
![image](https://user-images.githubusercontent.com/34504100/91398533-942ed380-e83c-11ea-85ef-500ff7d41662.png)
(The screenshot is from AL Language 5.0.320540, where the assignment still works.)

**Comment by thpeder** [comment] 2020-08-27 12:14
Hi @RafaelKoch,
Can you provide a complete simple example since I am not able to reproduce the issue.
Thanks.

However I was able to reproduce the issue @NKarolak highlights and can confirm that is solved in a future release.

**Comment by RafaelKoch** [comment] 2020-08-27 19:06
Hi @thpeder ,

we found the way to make it work, and accidentally maybe also the reason You could not repro: The enum value is called `Warning` and the InitValue was assigned like this: `InitValue = Warning`. This solution used to compile just fine in v15 and v16. 

Now somehow the value has to be set that way `InitValue = "Warning"`

So most likely the word `Warning`is ambiguous now. So forget about this aspect, but check if Intellisense will put it in correctly :-)

**Comment by thpeder** [comment] 2020-08-28 06:41
Thanks @RafaelKoch, You found the issue. 
When the value is a keyword then it can't be used without quotes and unfortunately we have a bug where intellisense doesn't add them.
I'll mark it as a bug

```
enum 50100 MyEnum
{
    value(3; Warning) { }
    value(4; if) { }
}

table 50100 MyTable
{
    fields
    {
        field(2; EnumField; Enum MyEnum)
        {
            InitValue = ^;
        }
    }
}
```

**Comment by BazookaMusic** [comment] 2023-11-28 13:51
This is fixed as of today, so closing it.

**Closed by BazookaMusic** 2023-11-28 13:51 UTC
Labels: bug, intellisense
