### ISSUE TITLE
The request for path /v1.0/sandbox/dev/apps?SchemaUpdateMode=recreate failed with code 422. Reason: There is an error in XML document (1, 1488)

### ISSUE THREAD

**Issue by tfbtrading** [microsoft/AL#4648] opened 2019-02-24 02:45 UTC
**Describe the bug**
The request for path /v1.0/sandbox/dev/apps?SchemaUpdateMode=recreate failed with code 422. Reason: There is an error in XML document (1, 1488)

This is a result when publishing to the Cloud Sandbox.  Does not say which XML file. 

Added two new tables into Tenant Specific Extension after which this error resulted. Compiler shows no errors. 

Looked similar error in GitHub - but it indicated problem was SourceTableView. I checked and had no similar code problem.

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. Publish to Cloud Sandbox 

**Expected behavior**
Expect to publish and run cloud sandbox in the web.

**Screenshots**

**Versions:**

 - AL Langauge: 2.1.79379
 - Business Central: 13.3 (28186)

**Comment by thpeder** [comment] 2019-02-25 15:51
Hi @tfbtrading,
Can you provide some AL that reproduces the problem?

**Comment by tfbtrading** [comment] 2019-02-25 18:38
I actually discerned the problem although the error wasn't informative. It was using a importance=optional rather than additional in a field definition.

It confused because I have other products with the indirect nav table permissions if I'm trying to deploy against a cloud sandbox copies from production. Al deployment only works against the pre-canned sandbox.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by thpeder** [comment] 2019-04-11 09:05
I'm marking this as a bug, because we want to improve the error messages you saw.
Regarding the issue you had with the property importance, starting from spring 2019 it is not allowed to use optional anymore since the system didn't act on it.

**Closed** 2019-06-26 07:16 UTC
Labels: bug, ships-in-future-update
