### ISSUE TITLE
BC17 Translation is not properly applied

### ISSUE THREAD

**Issue by anada1124** [microsoft/AL#6237] opened 2020-10-22 01:18 UTC
**Describe the bug**
Translation by AL extension is not properly applied.
"Entry Type" in "Item Journal" is a field with option captions (4 optional values) but the translation of this field does not work. I am working on the translation app and saw this problem. I have also confirmed it in other languages: French, German, and Italian. This seems to be an issue with the base application.

**To Reproduce**
This can be reproduced with the latest Docker environment. (Japanese is not available with Docker.)

**Expected behavior**
The optional values should be listed in the selected language.

**Screenshots**
Base (English), Japanese, French, German, Italian

![image](https://user-images.githubusercontent.com/61132610/96806520-48209980-144f-11eb-820b-bb8f7566d383.png)
![image](https://user-images.githubusercontent.com/61132610/96806536-51aa0180-144f-11eb-876b-6046fff2dd01.png)
![image](https://user-images.githubusercontent.com/61132610/96806541-55d61f00-144f-11eb-8cca-26c97be79b5e.png)
![image](https://user-images.githubusercontent.com/61132610/96806545-5a9ad300-144f-11eb-8faa-c75c7800a4ad.png)
![image](https://user-images.githubusercontent.com/61132610/96806548-5e2e5a00-144f-11eb-9b94-0fb1f36f152a.png)

**5. Versions:**
- VSC: 1.50.1
- AL Language:  v6.1.352568
- Business Central: 17.0 (Platform 17.0.17020.17774 + Application 17.0.16993.0)

**Comment by dtkb** [comment] 2020-10-22 10:57
may be related to https://github.com/microsoft/AL/issues/5842 for enums

**Comment by anada1124** [comment] 2020-10-22 13:01
Thank you.
I could not find this issue and, yes, it seems to be similar to mine, Enum...

**Comment by PooyaKharamesh** [comment] 2020-10-27 16:37
Thank you for reaching out. It will help us if you can provide us a sample project that reproduces the issue clearly?

/Pooya

**Comment by anada1124** [comment] 2020-10-28 10:25
You do not need any project but you can reproduce this with the latest Docker environment.
Docker environment comes with different language extensions and most of the major languages are there.

**Comment by pri-kise** [comment] 2021-01-22 09:23
I have similar problem with the tooltips on pages.
Caption are displayed correctly but tooltips are wrong and always in english on some BC17 versions.

**Comment by EmilDamsbo** [comment] 2023-10-19 08:23
I am closing this issue because it appears that it has been resolved in more recent versions. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Closed by EmilDamsbo** 2023-10-19 08:23 UTC
Labels: i18n

**Comment by pri-kise** [comment] 2023-10-19 08:28
We solved some issues on BC17 version when we changed wrong spelling of _Tooltip_ to _ToolTip_ . 
In old version this lead to different Translation-Keys in the XLIFF File.
