### ISSUE TITLE
External Document Number disappears after entry from new Sales Invoice

### ISSUE THREAD

**Issue by matthew-rc** [microsoft/AL#7795] opened 2024-07-15 09:25 UTC
Please include the following with each issue:

**1. Describe the bug**
When creating a new Sales Invoice, after filling out the External Document No., the field disappears from the page. The field along with its newly entered value can still be found by clicking 'Show More', but will be gone from the default view.

**2. To Reproduce**
1. Go to Sales Invoices
2. Click New
3. Fill out the External Document No. field and click elsewhere on the screen.
4. The field immediately disappears . Click Show More to reveal it.

base application, page id: 43

``` AL
                field("External Document No."; Rec."External Document No.")
                {
                    ApplicationArea = Basic, Suite;
                    Importance = Additional;
                    ShowMandatory = ExternalDocNoMandatory;
                    ToolTip = 'Specifies a document number that refers to the customer''s or vendor''s numbering system.';
                }
```

**3. Expected behavior**
Field should not disappear
**4. Actual behavior**
![BCbug](https://github.com/user-attachments/assets/85ff633f-40bf-45e3-b6dd-8a92388c194d)

**5. Versions:**

- AL Language: v13.1.1065068
- Business Central: 24.2.20227.20460

**Comment by NKarolak** [comment] 2024-07-16 06:15
This repository handles issues for the AL Language + interaction in VS Code only (hence everything until an app file has been compiled), but not for any later issues that arise when the app file is processed through server and client. Microsoft will close this issue soon.

Btw, I can't reproduce your issue in my German 24.3 database. The External Document No. is hidden by default from beginning. I have to click "Show more" to enter it. 
Ensure that no other extensions or a personalization / profile configuration is doing some tricks here. Or, maybe you can't reproduce it in 24.3 either?

**Comment by kalberes** [comment] 2024-07-21 10:43
![image](https://user-images.githubusercontent.com/12760483/157720687-c507e6aa-8588-4b9f-a7d1-6386db557300.png)

**Closed by kalberes** 2024-07-21 10:43 UTC
