### ISSUE TITLE
BC Latest Release & TESTFIELD

### ISSUE THREAD

**Issue by KaiSwitalla** [Microsoft/AL#3379] opened 2018-08-20 05:55 UTC
Hello,

i am developing against the latest release (NAV 13.0, build 13.0.23802.0. My Question is, do you changed the AL command "TESTFIELD"? It seems, that the Code stopped as expected, but there is still no message in web Client (...also in Windows Client). 

Example:
![testfield](https://user-images.githubusercontent.com/26924867/44322581-82401c00-a43d-11e8-8536-05b99730c853.jpg)

Please tell me what happend to this command and how do you want us to handle that cases when creating our apps.

**Comment by atoader** [comment] 2018-11-02 13:04
Hi @KaiSwitalla ! I am not able to reproduce the issue. The error is showing up as described in the documentation. Are those fields empty?

**Comment by atoader** [comment] 2018-11-12 07:39
I will assume that this problem does not reproduce anymore and close this issue. Feel free to reopen the issue and add steps to reproduce the problem on the latest build.

**Closed by atoader** 2018-11-12 07:39 UTC
Labels: input-needed, investigate

**Comment by rvanbekkum** [comment] 2019-04-08 10:43
I also ran into, what I expect to be, the same issue in our BC Sandbox running at version "NL Dynamics NAV 13.5 (31011)".
When the application calls the `TestField` procedure and fails, then the execution simply stops, but no error message is shown in the client. The application simply doesn't do anything (or so it seems to the user).

To be more specific. We ran into this issue while developing an extension which would call `TestField` on one of our setup table fields. When this call fails (e.g., because the table field is left empty), then the code stops and no error messages are shown.

I also tried to reproduce this with the Spring '19 release (v14), but there I was not able to reproduce this bug (I do get an error message on a failing `TestField` call), so it seems to be resolved in the new release.

**Comment by atoader** [comment] 2019-08-10 20:47
@rvanbekkum we have missed your reply. If the issue still occurs in the latest developer preview https://freddysblog.com/2019/07/31/preview-of-dynamics-365-business-central-2019-release-wave-2/, please open another issue. 
If you are interested in fixing this for a version that is in main-stream support, please open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
