### ISSUE TITLE
(Refered to issue #5671) Technical Upgrade ver 14 to ver 16, C/AL to AL conversion: 'DotNet is missing' errors

### ISSUE THREAD

**Issue by anhquandovu** [microsoft/AL#6076] opened 2020-08-07 10:23 UTC
Hi,

I am running into similar errors as issue #5671 Let me describe as below:

**Task: Technical Upgrade From Version 14 to Version 16**
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-technical-upgrade-v14-v16
   **- Step 2: Code Conversion from C/AL to AL**
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/devenv-code-conversion
    - I have converted the C/AL TXT files to AL
    - I have created and built an AL project for custom base application
    - In the dotnet.al file for the project: I have deleted all instances of Version = '14.0.0.0'; for Microsoft.Dynamics.Nav assembly declarations.
For instance:
![image](https://user-images.githubusercontent.com/52545960/89635640-f46ecd00-d8af-11ea-991b-acb97bcfe806.png)

 When I built and compiled project, I got hundreds of errors, all of them seemed related to deleted DotNet instances of version '14.0.0.0' from the step above

![image](https://user-images.githubusercontent.com/52545960/89635660-fcc70800-d8af-11ea-9a95-634934fd245e.png)

Is there a better way to handle these errors?
I was trying to fix one by one but figured that fixing one would affect to many others and probably would take a lot of time.

**Comment by atoader** [comment] 2020-08-09 18:04
The errors that you have shown above are secondary. The primary errors are the ones in the dotnet.al file. What errors do you get there?

**Comment by anhquandovu** [comment] 2020-08-10 07:14
Hi,

Thanks for the reply.

It was true that I had many errors in dotnet.al, but after I deleted all the instances of Version '14.0.0.0', following C/AL to AL code conversion instruction as below, the dotnet.al showed no more errors. 
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/devenv-code-conversion
- Open the dotnet.al file for the project, and make the following changes:
- Delete all instances of Version = '14.0.0.0'; for Microsoft.Dynamics.Nav assembly declarations.
- For the DocumentFormat.OpenXml assembly declaration, remove the version and culture keys and set PublicKeyToken = '8fb06cb64d019a17'.

This is dotnet.al before being imported:
![image](https://user-images.githubusercontent.com/52545960/89758732-27ec6a00-daf1-11ea-8a4c-47ee934068bd.png)

This is dotnet.al after being imported to AL project and removed '14.0.0.0' version of the instances:
![image](https://user-images.githubusercontent.com/52545960/89758629-eeb3fa00-daf0-11ea-9fc8-307cdeed59b0.png)

What remaining is that other objects are showing errors related to references to those deleted '14.0.0.0' dotnet instances.

**Comment by atoader** [comment] 2020-08-13 10:29
Can you reproduce this in a smaller project and share it? We haven't encountered this issue before.

**Comment by dtkb** [comment] 2020-08-14 10:39
I might be missing something, but to me it looks like simply a case of migrating old (standard or customised) base app code, which used .Net types that are no longer available in the BC16 platform, and would just need to be rewritten not to use them, or converted to extensions and let the standard base objects do whatever they do however they do it now.

**Comment by anhquandovu** [comment] 2020-08-14 12:35
Thanks @dtkb for the reply. 
This is exactly the reason I have thought of.
In this project, I am upgrading v14 to v16.
It seems that v14 using .Net types related to Application Client that are no longer available in BC16, which only has Web Client.
So after being converted to AL, the codes are still referring to v14 .Net types, which no longer available in BC16.

In this project, I am doing upgrade with no customization for testing purpose first. If it goes well, I will do upgrading with the real customization for the customer later.
Therefore, it came bit surprising when resulting in 600 errors even though the solution had no customization. 
The documentation didn't mention this so I posted here to consult instructions to handle these errors.

So rewriting the codes not to use to old v14 .NET types is one way to go, even though it might take lots of time, I guess we could see that as a cost for this upgrading the solution.

> I might be missing something, but to me it looks like simply a case of migrating old (standard or customised) base app code, which used .Net types that are no longer available in the BC16 platform, and would just need to be rewritten not to use them, or converted to extensions and let the standard base objects do whatever they do however they do it now.

I didn't quite get the _**converted to extensions and let the standard base objects do whatever they do however they do it now.**_ 
Which one should be converted to extensions and not touching the standard base objects?

@atoader I hope my elaboration here has described the issue a bit clearer for you to give advice. 
I will reproduce the project and send it to you still if necessary.

**Comment by dtkb** [comment] 2020-08-14 12:39
The preferred way of developing against BC is to extend base objects, not migrate them as-is via a customised base application. So you would get a diff (e.g. a `git diff`) between the original BC14 objects (for whatever CU you used) and your final ones, identify all changes and what they do, and move the code out to event subscribers in an extension codeunit and table/page extensions as appropriate. The [ALAppExtensions repo](https://github.com/microsoft/ALAppExtensions/issues/) can be used to request new events required to migrate your solution from base code to extension.

Doing it that way would mean you don't know or care what changed in the base objects between BCs 14 and 16, just whether they expose the same public interfaces and sufficient extension points to enable you to reimplement your custom functionality.

**Comment by qutreson** [comment] 2020-09-14 07:48
@anhquandovu, based on the additional information provided, can this issue be closed?

**Comment by anhquandovu** [comment] 2020-09-14 15:53
Hi, we haven't gone further with this project yet. Please close for now.
I could open another post referring to this if need support again in the future.

**Comment by qutreson** [comment] 2020-09-14 16:03
Thank you for your reply, closing the issue.

**Closed by qutreson** 2020-09-14 16:03 UTC
Labels: input-needed
