### ISSUE TITLE
Subscribing to page's OnNewRecordEvent event parameter BelowxRec not recognized

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [Microsoft/AL#888] opened 2017-11-02 15:42 UTC
In the old development environment I create a function to subscribe to OnNewRecordEvent event on a page:
[EventSubscriber] Page46_OnNewRecordEvent(VAR Rec : Record "Sales Line";BelowxRec : Boolean;VAR xRec : Record "Sales Line").
Now if I try to do the same in VS Code parameter BelowxRec isn't recognised: The type of the parameter 'BelowxRec' on the event subscriber 'Page46_OnNewRecordEvent' does not match the expected type 'Record'
Also, there is an error in https://msdn.microsoft.com/en-us/dynamics-nav/event-types : instead of OnAfterValidate(VAR Rec : Record, VAR xRec : Record) there should be OnAfterValidateEvent(VAR Rec : Record, VAR xRec : Record).
And it would be also useful if the system could generate procedure code automatically as well once we create event subscriber (I know it's a long shot asking for this, but I had to try)

**Comment by StanislawStempin** [comment] 2017-12-07 09:28
We have seen a similar issue before, we will investigate further.

**Comment by SirBETE** [comment] 2018-02-27 13:26
Still got this in NAV2018CU2 with al language 0.12.16641

**Comment by StanislawStempin** [comment] 2018-02-27 22:39
This is not fixed yet, the issue is still marked as Investigate. Please see here for more details about issue lifecycle: https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#what-do-all-the-labels-assigned-to-issues-mean

**Comment by qutreson** [comment] 2018-03-05 11:47
Hi @SirBETE, I could reproduce your issue and it is now fixed in our code base.

![githubissue888](https://user-images.githubusercontent.com/31541422/36971533-667e1396-206c-11e8-93fb-0daf02948bd8.gif)

**Closed** 2018-05-25 12:13 UTC
Labels: bug, shipped

**Comment by RedFoxUA** [comment] 2018-06-20 16:11
I can't find the right place and decided to add here:
I have released event: SalesEntryOnBefore(VAR TransLine : Record "Trans. Line";VAR TransSalesEntry : Record "Trans. Sales Entry") in the codeunit 9900xxxx.

I want to catch this event in my own codeunit and wrote:
[EventSubscriber(ObjectType::Codeunit, 9900xxxx, 'SalesEntryOnBefore', '', true, true)]
local procedure UpdateCostAmountTransSalesEntry(var POSTransLine : Record "Trans. Line"; var TransSalesEntry: Record "Trans. Sales Entry")

but VS highlights the word "POSTransLine" and shows error AL0282: The member referenced by event subscriber 'UpdateCostAmountTransSalesEntry' parameter 'POSTransLine' is not found.

What I do wrong?
