### ISSUE TITLE
defaultLaunchConfigurationName should not be stored in settings.json

### ISSUE THREAD

**Issue by salgiza** [microsoft/AL#5728] opened 2020-03-16 13:41 UTC
When you have more than one server configured in the launch.json file, and debug the app, VS Code asks which server you want to publish to... and stores its name as "al.defaultLaunchConfigurationName" in the settings.json file.

This is a bad practice: launch.json is a file that will be different depending on the developer but settings.json is defined as the settings for the project (not the user) and it is intended to be shared across all developers.

I'm not sure were this "al.defaultLaunchConfigurationName" should go, but it should be in a user owned file that is outside source control, not in file that is common to all developers.

**Comment by kalberes** [comment] 2020-03-18 16:29
"al.defaultLaunchConfigurationName is set by default on the user settings for the per workspace folder.
"User settings => my settings". I would not put my settings in source control.

**Comment by salgiza** [comment] 2020-03-19 08:04
Interesting, I never had though that someone might use workspace settings for personal settings. I searched around after your comment, and [there is a GitHub ticket for VS Code](https://github.com/microsoft/vscode/issues/40233) asking for a new settings.local.config file to do what you mention.

My previous experience with other languages/IDEs has been that workspace settings are always shared to keep everyone using the same settings that affect how we write code in a project/code generation/etc. (ex. analyzer rules for AL), so I didn't even consider this option, but I can see why someone might want to set some personal settings for a particular workspace.

Regardless, I think that my point stands: VS Code help explicitly states that this file can be shared across developers (and thus included in source control) and a per user workspace looks like its going to be implemented soon (it's mentioned in VS Code March 2020 plan) with a different name.

<img width="790" alt="image" src="https://user-images.githubusercontent.com/6630306/77043701-63f62580-69be-11ea-9356-308a4ae9ded7.png">

That's a cropped screenshot taken from this link: https://code.visualstudio.com/docs/getstarted/settings

**Comment by salmosa1** [comment] 2020-03-20 08:08
I agree with salgiza. In an environment with multiple developers using the same workspace folder, not all developers must name theirs dockers equally. 
Furthermore, it is mandatory to put something, because if not, it is asking for it constantly whenever Ctrl is pressed. When I indicate any environment, it installs the extension there by default, without asking. If I have several dockers to install it, I have to change it in settings. Before I could select where to install.
I think that, at least, it should be optional.

**Comment by MODUSCarstenScholling** [comment] 2020-03-28 08:52
### Explanation

While the launch.json is specific to developers and their respective environments, the workspace Settings are a classic area for project-specific settings and rules that apply to all developers. So the settings.json is not a good place to share developer specific settings.

While there are certainly situations where a developer will temporarily adjust settings.json, these settings are valid for everyone. Classically, the deactivation of rules that are not useful (for us) but must apply to everyone.

To summarize, saving user specific configuration in a workspace configuration file is not a good idea. I would suggest to apply the following changes:

### Suggestions

- Remove the setting from settings.json
- Add a "default": true/false to the/each configuration or apply "defaultLaunchConfigurationName" to the root of launch.json, whatever fits best
- Allow users to configure if the setting of the default launch configuration should be done (Always, Never, Ask, If Not Set)
- And, as the icing on the cake, provide explicit "Publish to..." "Download from..." commands to override default settings on demand :)

Probably this can be aligned to [[Feature] Local Workspace settings](https://github.com/microsoft/vscode/issues/40233).

**Comment by kalberes** [comment] 2020-03-29 15:46
When local workspace settings will be there we are going to move this setting there.
In a multi workspace scenario (I would assume that most implementations do use multi workspace by now) it is a per folder setting. 
Without this setting there is no go to definition. Moving to launch.config is not a viable solution, because the whole system is designed.

**Comment by sonicadv27** [comment] 2020-04-17 12:33
The setting itself is a terrible idea.

Choosing the configuration for downloading symbols and launching was fast and convenient. Now that choice has been taken away from the user and they have to change the settings on the file to change the environment they are working on.

This makes zero sense and created a new problem where there wasn't one.

**Comment by kalberes** [comment] 2020-04-19 14:10
This has been fixed and will be available with the first update of BC 2020 spring release.
It will probably be available sooner in internal builds targeting the next version of BC.
There is no more defaultLaunchConfigurationName. 
gotodefinition will rely on local dependency applications for source symbol resolution for apps with runtime versions >= 5.0.
There is an extra feature that comes with it and that is DAL file symbol source navigation.
aka, gotodefinition within a DAL file defined symbol to its source.

For versions <= 4.0 gotodefinition will work the old way (as before defaultLaunchConfigurationName). No source symbol resolution for gotodefinition if more then one debug configuration is defined.

**Comment by kalberes** [comment] 2020-04-21 11:21
Unfortunately it did not make it to the 16.1 update of BC. Targeting 16.2 for now.

**Comment by qutreson** [comment] 2020-06-30 07:00
This issue should have been fixed as part of 16.2. If you can still reproduce it, please log a new issue with code reproducing the issue.

**Closed by qutreson** 2020-06-30 07:00 UTC
Labels: bug, in-progress, workspaces
