### ISSUE TITLE
Not possible to compile BC14 extensions with version 12 or newer of the compiler

### ISSUE THREAD

**Issue by mfalk118** [microsoft/AL#7579] opened 2023-11-09 10:52 UTC
**1. Describe the bug**

Since version 12 BC14 development with procedures with record parameters is not possible. It will fail on all record parameters to procedures saying:

"Argument 1: cannot convert from 'Record "Company Information" temporary' to '__MissingTypeSymbol__'",

Switching to version 11.7 solves the issue, however we prefer to run at the newest version

**2. To Reproduce**
Download Symbols from BC 14 with AL compiler 12 or newer

Create one extension, lets call it Extension A. Create a codeunit with a procedure that takes a record parameter

Then in another extension create a call like:

trigger OnAction()
                    var
                        TempBlob: Record "Company Information" temporary;
                        FileMgt: Codeunit FileMgtHLPVPE;
                        ImportFileLbl: Label 'Import Xml File';
                    begin
                        **FileMgt.BLOBImportWithFilter(TempBlob, ImportFileLbl, 'Request.xml', 'Xml Files (*.xml)|*.xml');** 
                    end;

It will fail on the bold line with "Argument 1: cannot convert from 'Record "Company Information" temporary' to '__MissingTypeSymbol__'",

If i compile extension A with version 11.7, i can use version 12 or newer in extension B

**3. Expected behavior**
Compiler working and compiling the code

**4. Actual behavior**
Errror as described above

**5. Versions:**

- AL Language: 12.0.875970 + 12.1.887908 + 13.0.887907
- Visual Studio Code: 1.84.1
- Business Central: BC14 CU20
- List of Visual Studio Code extensions that you have installed: Not relevant

**Comment by pborring** [comment] 2023-11-10 11:36
Closing this as duplicate of https://github.com/microsoft/AL/issues/7529

**Comment by pborring** [comment] 2023-11-10 11:36
Closing this as duplicate of https://github.com/microsoft/AL/issues/7529

**Closed by pborring** 2023-11-10 11:36 UTC
