### ISSUE TITLE
Not downloading symbols from ISV app

### ISSUE THREAD

**Issue by dmachanick** [microsoft/AL#7393] opened 2023-05-06 15:43 UTC
When I download symbols, I receive the message "All reference symbols have been downloaded."
However, it only downloads the symbols for the Microsoft base app and not our ISV app.
Have not had this problem previously.
I have tried Docker and the cloud - both give the same problem.
The Govcon app has downloading source = false, but I can still see all the objects in AL Explorer  and look at the source.

I have tried both the current AL language release and the pre-release.

  "id": "7a3f5a17-1da2-49af-80ef-937256380470",
  "name": "DiplomatGroup Customizations",
  "publisher": "XTIVIA",
  "version": "1.5.40.0",
  "brief": "",
  "description": "",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "dependencies": [
    {
      "id": "63ca2fa4-4f03-4f2b-a480-172fef340d3f",
      "publisher": "Microsoft",
      "name": "System Application",
      "version": "16.0.0.0"
    },
    {
      "id": "437dbf0e-84ff-417a-965d-ed2bb9650972",
      "publisher": "Microsoft",
      "name": "Base Application",
      "version": "16.0.0.0"
    },
    {
      "id": "aabf70de-e7af-4252-8727-6beaecbe3f9a",
      "name": "GovCon365",
      "publisher": "XTIVIA",
      "version": "11.0.0.0"
    }
  ],
  "screenshots": [
    
  ],
  "platform": "19.0.0.0",
  "idRanges": [
    {
      "from": 50000,
      "to": 50049
    }
  ],
  "preprocessorSymbols": [ "CLEAN15", "CLEAN16", "CLEAN17", "CLEAN18", "CLEAN19", "CLEAN20" ],
  "contextSensitiveHelpUrl": "https://DiplomatGroup.com/help/",
  "resourceExposurePolicy": {"allowDebugging": true, "allowDownloadingSource": true, "applyToDevExtension": true, "includeSourceInSymbolFile": true},
  "runtime": "10.1"
}

**Comment by dmachanick** [comment] 2023-05-08 13:44
the setting is accessing our github repository -  the same as it always does.
This is also an existing custom app that I have to make BC22 compliant. 
This has the same settings that I have been using for other custom apps.

**Comment by thloke** [comment] 2023-05-09 06:44
This sounds like two separate issues.

**Downloading symbols retrieving wrong symbols.** When you perform a download symbols request, can you check the request that is sent and ensure that it's targeting the right server? It shouldn't be possible to get the Microsoft baseapp symbols from an embed app server, because those symbols don't exist there.

**Source unexpectedly visible.** This is by design. The `allowDownloadingSource` config only prevents the source from being packaged in the .app file when you download it from the extension management page (relevant only for PTEs). If you want the source to also not be visible during debugging, you need to also set `includeSourceInSymbolFiles` to `false`.

https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-security-settings-and-ip-protection#includesourceinsymbolfile

**Comment by dmachanick** [comment] 2023-05-09 20:57
The problem is that it is not downloading the symbols for GovCon even though it downloads the aoo.
The symbols are successfully downloaded for the base app
The download meesage states that all symbols have been downloaded

**Comment by thloke** [comment] 2023-05-10 02:54
Oh, I misunderstood. I thought this was an embed app scenario with a code customized base app. Can you share the output of the console when you download symbols? It should contain exactly what it tried to download and where it saved it.

**Comment by thloke** [comment] 2023-05-11 08:38
Weird, it looks like it is sending the request to download GovCon365 by XTIVIA. I'm also confused by this statement:

> The problem is that it is not downloading the symbols for GovCon even though it downloads the app.

Do you mean that you see the .app file in your packages cache folder but you don't get any symbol information? What is in your package cache folder after doing "download symbols"?

**Comment by dmachanick** [comment] 2023-05-11 09:32
It is in the .alpackages folder, plus I can browse and review all the objects using AL Explorer.
Also, I am not having this problem anywhere else. (We have a lot of customers with add on custom apps.)

**Comment by thloke** [comment] 2023-05-12 02:36
Maybe I'm misunderstanding the problem. If the .app file is in the `.alpackages` folder, what do you mean by the symbols are missing? Does it mean you can't compile against them?

**Comment by dmachanick** [comment] 2023-05-12 14:58
downloading symbols does not update the code, so I cannot compile against them

**Comment by thloke** [comment] 2023-05-15 01:30
What do you mean by "does not update the code"? Maybe it's better with a specific example. For example, do you have a page extension that refers to a page in Govcon, and that page extension doesn't compile?

**Comment by dmachanick** [comment] 2023-05-15 13:43
It is not downloading any GovCon symbols - so all references to GovCon get errors in VS Code

**Comment by JMA1972** [comment] 2023-05-15 14:34
Maybe you have the wrong reference to this GovCon app in your app.json. It seems to download the symbols for a version 11.0.0.0 and such a version no. looks a bit shady for a BC 19 app even. Why you have dependencies to base and system apps with version 16 there is a bit unclear for me also. Runtime 10.1 seems a bit high for BC 19 too.

**Comment by thloke** [comment] 2023-05-16 02:57
> It is not downloading any GovCon symbols - so all references to GovCon get errors in VS Code

Are you sure it's a downloading issue instead of a reference issue? If the .app file is present in your .alpackages folder, that means it has downloaded the symbols.

You can actually open up the .app file using 7zip and check the symbols there as well. There will be a `symbolreference.json` file inside the .app file which contains the symbols that we use for compilation.

**Comment by pborring** [comment] 2023-12-06 11:46
@dmachanick do you still have this issue, or can we close it? Did you verify per thloke comment above?

**Comment by dmachanick** [comment] 2023-12-06 15:16
We can close it.

**Closed** 2023-12-06 16:51 UTC
Labels: input-needed
