### ISSUE TITLE
"UsageCategory = none" in report crashes webclient

### ISSUE THREAD

**Issue by sit-jr** [microsoft/AL#6082] opened 2020-08-14 16:14 UTC
**Describe the bug**
When implementing a report with the property "UsageCategory = **n**one" and executing the report (e.g. calling it via an action from a page), the webclient crashes. Changing the property value to this "UsageCategory = **N**one" does not crash the webclient. (The lowercase/uppercase of the "n" of the property value makes the difference.)

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a report, e.g.
`
report 55999 "XYZ TestUsageCategory"
{
    Caption = 'Test Usage Category';
    Description = 'TestUsageCategory';
    ProcessingOnly = true;
    UsageCategory = none;

    trigger OnPreReport()
    begin
        Message('Hello World!');
    end;
}
`

2. Create an action in a page or page extension 
`
            action(TestUsageCategoryReport)
            {
                Caption = 'Test Usage Category';
                Description = 'TestUsageCategoryReport';
                Image = Action;

                trigger OnAction()
                var
                    TestUsageCategoryReport: Report "XYZ TestUsageCategory";
                begin
                    Clear(TestUsageCategoryReport);
                    TestUsageCategoryReport.RunModal();
                end;
            }
`

3. Publish app, open page (extension) and use the action
Following info message appears:
_Dynamics 365 Business Central
We paused while you were away. Please refresh to continue._

Clicking "refresh" button restarts webclient.

``` AL Code to reproduce the issue ```
--> see above

**Expected behavior**
The webclient should run the report and show the message "Hello World!" as it does, when using "UsageCategory = None".

**Screenshots**
None

**5. Versions:**

 - AL Language: v5.0.312966

 - Business Central: System Application	v. 16.1.12629.12805

**Comment by BartPermentier** [comment] 2020-09-29 11:42
We have the same issue. How is this not fixed yet?

**Comment by dtkb** [comment] 2020-10-20 16:59
I can't be certain, as the environment where I want to deploy the attempted fix is not reachable right now, due to other horrors...

but I think this might also affect reports using `ReportsandAnalysis` instead of `ReportsAndAnalysis`, at least on certain versions of BC. The affected environment seemingly does nothing and/or pauses, whereas my local one runs fine; both are BC15 of some version or another.

Therefore, can anyone who is seeing the bug with `none` on latest BC16/17 check whether it also occurs with the lowercase `a` in `ReportsandAnalysis`? It might affect more/all values.

**Comment by dtkb** [comment] 2020-10-20 17:10
Yes, that was it. `UsageCategory = ReportsandAnalysis` causes the pause/freeze on BC **15.0.41893** - and perhaps other values/versions.

Changing to `UsageCategory = ReportsAndAnalysis` stopped this bug.

In no case does VS Code warn that the runtime will silently die on a value with a case that it does not expect! So if those aren't supported, fix ASAP. This wastes a lot of people's time trying to find other causes for crashing.

Interestingly - or randomly - my local BC **15.0.36510** does NOT care about the case and runs the report fine either way, if that helps find the regression.

**Comment by MaricaPiazzalunga** [comment] 2021-01-14 15:55
We have the same issue on BC17.1.18792.
Report > `ProcessingOnly = true`
If we set the `UsageCategory = none`, the web client crashes if we try to execute it. While, if we set the `UsageCategory = None`, the report is executed without problems.
The same if we set the `UsageCategory = ReportsandAnalysis` instead of `UsageCategory = ReportsAndAnalysis`.

**Comment by qutreson** [comment] 2021-04-09 16:36
Closing this issue as duplicate of #6572

**Closed by qutreson** 2021-04-09 16:36 UTC
Labels: al-core-compiler, bug
