### ISSUE TITLE
IncludeCaption on Report for fields from Table Extension still is not working

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/AL#5669] opened 2020-02-14 13:47 UTC
Although both #3482 and #1616 have been closed is the issue was solved it still exist. I have reported it my self some time ago on yammer (https://www.yammer.com/dynamicsnavdev/threads/70843576008704) and today was confirmed it still exist on BC15 CU2. Apparently this was not fixed. It seems that this keps on lingering. Could you pleas pick this up?

**Comment by lvanvugt** [comment] 2020-02-17 15:30
And, just verified, this is also in the insider build an issue.

Have created a report based on the standard REP101 (Customer - List) for my Lookup Value Case is used in my book https://www.packtpub.com/business/automated-testing-microsoft-dynamics-365-business-central. Find the report and layout attached. I have added only one field, called Lookup Value Code, that was added to the Customer table by a tableextension object (also attached). Using IncudeCaption on the tabkeextension field does not yield a caption as you can see in this screenshot. It yields the name of the parameter itself:

![image](https://user-images.githubusercontent.com/18466198/74666860-8ec44280-51a2-11ea-8486-401ce5b55708.png)

[CustomerList.zip](https://github.com/microsoft/AL/files/4214522/CustomerList.zip)

**Comment by thloke** [comment] 2021-04-27 02:00
Hi, it's been a while since this issue was raised, and I cannot reproduce this anymore. It's very likely that this was fixed in the meantime, quite a few things have changed with reports with the introduction of report extensibility. I'm closing this as a no-repro, but if you can reproduce this on an insider build, please re-open and tag me and I'll have a look at it again.

**Closed by thloke** 2021-04-27 02:00 UTC
Labels: bug, in-progress, input-needed

**Comment by lvanvugt** [comment] 2021-04-27 05:10
True, fixed. I should have closed the issue. Apology for that and thanx for doing so.
