### ISSUE TITLE
Drill Down is not supporting in webclient for october preview

### ISSUE THREAD

**Issue by Rajiniadvaita** [Microsoft/AL#1204] opened 2017-12-15 05:40 UTC
Hi ,

In October preview extension not able to drill down in page for field which has property of flow field, when clicks on drill down in url it is showing default or startup page id i.e 22 which is from App.json.

![image](https://user-images.githubusercontent.com/31922450/34039856-3d603960-e1b7-11e7-8aa8-31ad0d215230.png)

**Comment by qutreson** [comment] 2018-03-20 10:44
Hi @Rajiniadvaita, is using a drill down in a page for a field of type flow field still not working for you?

I just tried with the following snippet code and it seems to work for me:

**Table.al**
```
table 50108 DrillDownTable
{   
    fields
    {
        field(50000; MyFlowField; Integer)
        {
            FieldClass = FlowField;
            TableRelation = Customer."Bill-to No. Of Archived Doc.";
        }

        field(50001;MyField;  Text[50]) { }
    }
}
```

**Page.al**
```
page 50108 DrillDownPage
{
    PageType = Card;
    SourceTable = DrillDownTable;
    
    layout
    {
        area(content)
        {
            group(GroupName)
            {
                field(MyFlowField; MyFlowField)
                {                
                    ApplicationArea = All;
                    DrillDown = true;

                    trigger OnDrillDown()
                    begin 
                        Message('Hello there');
                    end;
                }
            }
        }
    }
}
```

Concerning the PageId appearing in the url: As you pointed out, it is some remaining from publishing using with a startup page id, but it shouldn't have any consequences on the issue here (as this is always appearing when using startup id).

If you are still facing this issue, can you provide us with some repro steps or some code that we could use to figure out if we have a bug here?

**Comment by qutreson** [comment] 2018-04-16 08:44
Hi @Rajiniadvaita, I am closing this issue as we were not able to reproduce the problem you described. If you are still facing this problem, don't hesitate to log a new issue about it with some code to reproduce it and the current version numbers you are using.

**Closed by qutreson** 2018-04-16 08:44 UTC
Labels: input-needed, investigate
