### ISSUE TITLE
Unable to load symbols for Codeunit 131300 after loading Test Library W1

### ISSUE THREAD

**Issue by gunnargestsson** [Microsoft/AL#2366] opened 2018-05-26 22:29 UTC
"dockerImage":  "microsoft/bcsandbox",

[Error - 22:27:16] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/completion' failed with error: 'Object reference not set to an instance of an object.'
StackTrace:
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolDisplayVisitor.VisitParameter(ParameterSymbol symbol) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolDisplay\SymbolDisplayVisitor.cs:line 200
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolDisplayVisitor.AddParametersIfRequired(ImmutableArray`1 parameters) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolDisplay\SymbolDisplayVisitor.cs:line 413
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolDisplayVisitor.VisitMethod(MethodSymbol symbol) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolDisplay\SymbolDisplayVisitor.cs:line 386
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolDisplay.ToDisplayParts(ISymbol symbol, SemanticModel semanticModelOpt, Int32 positionOpt, SymbolDisplayFormat format, Boolean minimal) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolDisplay\SymbolDisplay.cs:line 106
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbol.ToDisplayParts(SymbolDisplayFormat format) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Symbol.cs:line 492
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.SymbolCompletionItem.Create(String displayText, TextSpan span, IReadOnlyList`1 symbols, Int32 contextPosition, Int32 descriptionPosition, String sortText, String insertionText, Nullable`1 glyph, String filterText, Boolean preselect, SupportedPlatformData supportedPlatforms, Boolean isArgumentName, ImmutableDictionary`2 properties, ImmutableArray`1 tags, CompletionItemRules rules, Boolean isSnippet) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\SymbolCompletionItem.cs:line 59
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.CreateItem(String displayText, String insertionText, Int32 position, List`1 symbols, AbstractSyntaxContext context, TextSpan span, Boolean preselect, SupportedPlatformData supportedPlatformData, Boolean isSnippet) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\AbstractSymbolCompletionProvider.cs:line 114
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.CreateItem(String displayText, String insertionText, Int32 position, List`1 symbols, AbstractSyntaxContext context, TextSpan span, Dictionary`2 invalidProjectMap, List`1 totalProjects, Boolean preselect, Boolean isSnippet) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\AbstractSymbolCompletionProvider.cs:line 109
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.<>c__DisplayClass5_0.<CreateItems>b__3(IGrouping`2 g) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\AbstractSymbolCompletionProvider.cs:line 49
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.CreateItems(Int32 position, IEnumerable`1 symbols, TextSpan span, AbstractSyntaxContext context, Dictionary`2 invalidProjectMap, List`1 totalProjects, Boolean preselect) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\AbstractSymbolCompletionProvider.cs:line 46
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.<GetItemsWorkerAsync>d__14.MoveNext() in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\AbstractSymbolCompletionProvider.cs:line 197
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.<ProvideCompletionsAsync>d__13.MoveNext() in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\AbstractSymbolCompletionProvider.cs:line 177
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.<GetContextAsync>d__24.MoveNext() in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 369
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.<GetCompletionsAsync>d__17.MoveNext() in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 186
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CompletionRequestHandler.<HandleAsync>d__4.MoveNext() in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CompletionRequestHandler.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

**Comment by qutreson** [comment] 2018-05-28 13:13
Hi @gunnargestsson, can you provide us with some steps of what you did to get this error? 
This seems to be an IntelliSense related error, did you get this error when triggering IntelliSense? 

As a side note, the stack trace also looks similar the one in #2375.

**Comment by gunnargestsson** [comment] 2018-05-28 13:26
As stated in the first line, current bc sandbox:

"dockerImage":  "microsoft/bcsandbox",
--

**Comment by kalberes** [comment] 2018-05-28 16:02
The question was merely related on whether you can provide some AL code that reproes this stack trace.
Or you mean that if I take the latest bcsandbox and create the simplest Al.Go project I would get this crash?

**Comment by gunnargestsson** [comment] 2018-05-28 16:05
Sure, sorry

https://github.com/gunnargestsson/businesscentral/tree/GLSourceNames/ALTests

**Comment by qutreson** [comment] 2018-06-14 13:34
Hi @gunnargestsson, I tried to reproduce the stack trace based your github project without success until now. Do you remember what you did in order to trigger the stack trace? Did you trigger IntelliSense or did it suggest you something while you were writing? Do you also, by any chance, remember which file you were modifying? Where you were in the file?
From reading the stack trace it seem that IntelliSense is failing when trying to suggest you a method with parameters.

**Comment by gunnargestsson** [comment] 2018-06-14 14:16
Yes.

In the micsoroft\bcsandbox environment I used the NAVContainerHelper function to import the test libraries
Generated new Symbols and downloaded again.
Now having all the test library in my Microsoft…app file
Then from a Test Codeunit object I added Codeunit 131300 as a variable and when intellisense tried to give me details I got this stack trace.

Kind regards,
Gunnar Þór Gestsson

**Comment by gunnargestsson** [comment] 2018-06-14 15:51
The project is in ALTests folder that you can see on GitHub

https://github.com/gunnargestsson/businesscentral/tree/GLSourceNames

in setup.json you can see the docker version I am using.

"dockerImage":  "microsoft/bcsandbox",

Kind regards,
Gunnar Þór Gestsson

**Comment by qutreson** [comment] 2018-06-19 12:40
Hi @gunnargestsson, I was finally able to reproduce the issue `microsoft/bcsandbox', which provided me with the AL extension version: 0.15.18771 and the server version: W1 12.0 (21812).

However this seems to be fixed in our latest master (see below). 

![image](https://user-images.githubusercontent.com/31541422/41597551-11af1a44-73ce-11e8-876d-4ba05e7b5aa7.png)

You should then update to a newer version of the compiler and hopefully this should fix your issue!

**Closed** 2018-08-24 08:50 UTC
Labels: bug, shipped
