### ISSUE TITLE
BC23 NextMajor Pipeline warning AD0001 Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ReferenceFieldSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.FieldGroupSymbol'.

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#7444] opened 2023-06-21 15:04 UTC
Please include the following with each issue:

**1. Describe the bug**

We receive the following in our NextMajor Pipelines.

> warning AD0001: Analyzer 'Microsoft.Dynamics.Nav.AppSourceCop.Upgrade.RuleInvalidObsoleteTagsNotAllowed' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ReferenceFieldSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.FieldGroupSymbol'.
at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceTableExtensionTypeSymbol.GetAddedFieldGroups() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceTableExtensionTypeSymbol.cs:line 181
at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.TableExtensionTypeSymbol.Microsoft.Dynamics.Nav.CodeAnalysis.ITableExtensionTypeSymbol.get_AddedFieldGroups() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\TableExtensionTypeSymbol.cs:line 58
at Microsoft.Dynamics.Nav.AppSourceCop.Upgrade.RuleInvalidObsoleteTagsNotAllowed.AnalyzeTableExtension(SymbolAnalysisContext ctx) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.AppSourceCop\Upgrade\RuleInvalidObsoleteTagsNotAllowed.cs:line 151
at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass49_2.<ExecuteSymbolActionsCore>b__0() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 658
at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1086'

warning AD0001: Analyzer 'Microsoft.Dynamics.Nav.AppSourceCop.Upgrade.RuleInvalidObsoleteTagsNotAllowed' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ReferenceFieldSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.FieldGroupSymbol'.

**Versions:**

- AL Language:  AL Compiler version 12.0.12.31284

**Comment by thpeder** [comment] 2023-06-22 19:18
Hi @pri-kise,
It looks like it is trying to analyze Table Extensions for Obsolete fields. Please have a look if you can narrow down the issue to a AL snippet that reproduces the issue. Maybe you have a Field Group with the same name as some fields.

**Comment by pri-kise** [comment] 2023-06-26 06:16
@thpeder we have no obsolete field in this PTE Customization.
And we only have one piece regarding fieldgroups

```al
tableextension 50000 "PTE Item" extends Item
{
    fieldgroups
    {
        addlast(DropDown; "Description 2") { }
    }
}
```

**Comment by minaskats** [comment] 2023-07-05 06:59
+1 I found the reason of this yesterday.

The reason of this is because  Next Major Pipeline fails due to the use of AL Compiler version 11.0.12.24044 that is using. If you download a version of AL in VS CODE for example v11.0.827766, and you have downloaded symbols of ver 23, the same error appears at the app.json in VS Code . It should be using v12.0.827887 instead, the version of AL that comes with 23.

**Comment by JesperSchulz** [comment] 2023-07-19 07:45
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 23.0.11489.0 and VS Code Extension Version 12.0.834301. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Closed by JesperSchulz** 2023-07-19 07:45 UTC
Labels: ships-in-future-update, static-code-analysis, AppSourceCop, accepted
